### PR TITLE
Ericherman/hv obsolete define

### PR DESCRIPTION
**Pull request by ericherman**

### CODE REVIEW

**Comment by demerphq** [comment]
I think this is meant to be used as part of a guard clause to prevent us growing larger than this number of bits worth of buckets. So I suspect that if its unused we should not remove it but change the logic to use it again. I haven't double checked tho. Hope you are well Eric, Nice to see you pushing change requests!

**Comment by ericherman** [comment]
Hello @demerphq ! I am doing quite well and I hope you are as well.

I tried to sort out what HV_FILL_THRESHOLD is for and originally expected something similar, but I now have the belief that it was only used in hv_fill, which returned buckets *already* in use. Also, I believe hv_fill exists because used hashbucket count is not cached, and this info is useful for debugging, but not actually used in regular execution.

I think a guard like you suggest could make sense, but I'm pretty sure this was not that, thus I think this is a confusing and misleading #define. If we add a bucket growth limit with a constant like that, I think we should name it more clearly/verbosely.

Unless you can shed more light for me, I'm sticking to the thinking it's better to _not_ have this confusing thing in the code.

**Comment by demerphq** [comment]
On Fri, 10 Jul 2020 at 10:06, Eric Herman <notifications@github.com> wrote:

> @demerphq <https://github.com/demerphq> I tried to sort out what that was
> for and originally expected somethign similar, but have now I believe that
> it was only used in hv_fill, which returned buckets *already* in use.
> Also, I believe hv_fill exists because used hashbucket count is not cached,
> and this info is useful for debugging, but not actually used in regular
> execution.
>
> I think a guard like you suggest could make sense, but I'm pretty sure
> this was not that, thus I think this is a confusing and misleading #define.
> If we add a bucket growth limit with a constant like that, I think we
> should name it more clearly/verbosely.
>
> Unless you can shed more light for me, I'm sticking to the thinking it's
> better to *not* have a this confusing thing in the code.
>

The line of code immediately above is probably where the define should be
used.

Let me see.

Yves
-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
On further review I agree you are correct. Thanks, merged!

**Pull request merged**
