### PR TITLE
fix t/win32/signal.t

### PR DESCRIPTION
**Pull request by atoomic**
Make sure Config is loaded before using %Config

### CODE REVIEW

**Comment by Leont** [comment]
This shouldn't matter, as `use` is executed at BEGIN time, but it is less confusing this way

**Comment by Grinnz** [comment]
It matters for strict 'vars' since %Config is imported by this use statement, even though it isn't accessed until runtime.

**Comment by Leont** [comment]
> It matters for strict 'vars' since %Config is imported by this use statement, even though it isn't accessed until runtime.

That sounds like information that should be in the commit message.

**Comment by atoomic** [comment]
I even made it clearer by enforcing `strict` in the test

**Review by toddr — APPROVED** [review]

**Pull request merged**
