### PR TITLE
Fix compiler/pattern warnings

### PR DESCRIPTION
**Pull request by khwilliamson**
These are harmless, but a distraction

### CODE REVIEW

**Comment by jkeenan** [comment]
> These are harmless, but a distraction

When I build blead at HEAD (v5.37.4-90-gf607bd2c83), then apply only the change to `t/op/require_errors.t` and run that file, I get no change in output.  Should I?

**Comment by khwilliamson** [comment]
Did you run it on Windows?

**Comment by jkeenan** [comment]
On 10/8/22 10:08, Karl Williamson wrote:
> Did you run it on Windows?
> 

No, on FreeBSD.

**Comment by khwilliamson** [comment]
The commit message indicates this only occurs on  Windows

**Comment by Leont** [comment]
Personally, I don't particularly like declaring `const` for integer arguments: if it doesn't affect the interface, it shouldn't be part of the interface.

And the compiler is silly for warning about this, I don't see how such a warning would ever be helpful.

**Comment by khwilliamson** [comment]
Declaring a parameter const is an extra bit of information to the reader of the code, and the programmer while writing it that this thing isn't supposed to change.  

And it is pretty much silly for the compiler to complain, except it indicates a potential programmer oversight.  But I learned long ago, when lint was the only checker, that it saved me time in the long run to just give in to its invalid complaints, so I wouldn't have to deal with them again.  But if I didn't, my cognitive load would be increased, for no good reason

**Comment by tonycoz** [comment]
> Declaring a parameter const is an extra bit of information to the reader of the code, and the programmer while writing it that this thing isn't supposed to change.

Which compiler warned here?  I don't see neither the newSVbool() nor the regnode_after() warning with VS2022.

**Comment by khwilliamson** [comment]
At least some of them came from https://m-l.org/~perl/smoke/perl/mswin32-x64-multi-thread-win10/mswin32-win10-smoke-me/Karl%20Williamson/log4fec6e83d97275c709d4b4c49331a79a096b5106.log.gz

**Comment by tonycoz** [comment]
Thanks.

I'd be more inclined to remove the const in these cases rather than add it - the const is an implementation detail of the function and shouldn't really be visible in the declaration (I expect it shows in perlapi too.)

Unfortunately this warning can occur for [useful cases](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4028?view=msvc-170) too, so I don't think we can disable it.

**Comment by khwilliamson** [comment]
@tonycoz,  IIRC the end result of what you are saying is that we need to forbid and remove const declarations to non-pointer variables.  Is that your intent?

**Comment by tonycoz** [comment]
> @tonycoz, IIRC the end result of what you are saying is that we need to forbid and remove const declarations to non-pointer variables. Is that your intent?

Only for the parameters in the function declaration/definition ("formal parameters").

While @Leont mentioned integer parameters, I don't think it's limited to integers, but for any type parameter where the const qualifier is on the parameter itself, eg.

```
void f(int x); /* fine */
void g(const int x); /* causes MSVC problems */
void h(const char *x); /* fine, x points to const, but isn't const itself */
void m(char const *x); /* fine, has exactly the same type as h() */
void j(const char * const x); /* x itself is const, but this only matters inside j() itself, causes MSVC problems */
void k(char const * const x); /* has exactly the same type as j() */
```

**Review by demerphq — APPROVED** [review]

**Comment by demerphq** [comment]
@khwilliamson this is in conflict and stalled. Would you like me to rebase it onto blead so we can decide if we want to apply it? @tonycoz do you have an opinion on what to do with this PR?

**Comment by demerphq** [comment]
I resolved conflicts on this only, I have no opinion on whether it should be applied.

**Comment by jkeenan** [comment]
> I resolved conflicts on this only, I have no opinion on whether it should be applied.

Thanks for the conflict resolution.  There doesn't really seem to be enough consensus on this patch to move forward.  Should we close the ticket?

**Comment by jkeenan** [comment]
> > I resolved conflicts on this only, I have no opinion on whether it should be applied.
> 
> Thanks for the conflict resolution. There doesn't really seem to be enough consensus on this patch to move forward. Should we close the ticket?

There has been no further discussion in this ticket since the end of July.  It still seems that we do not have strong support for the changes proposed in this p.r.  I propose that we close the p.r. in 7 days unless someone makes a good case for it.

**Comment by jkeenan** [comment]
> > > I resolved conflicts on this only, I have no opinion on whether it should be applied.
> > 
> > 
> > Thanks for the conflict resolution. There doesn't really seem to be enough consensus on this patch to move forward. Should we close the ticket?
> 
> There has been no further discussion in this ticket since the end of July. It still seems that we do not have strong support for the changes proposed in this p.r. I propose that we close the p.r. in 7 days unless someone makes a good case for it.

Closing as per plan.  Thanks for all who contributed to the discussion.

**Pull request closed without merging**
