### PR TITLE
Win32: synch with CPAN version 0.59

### PR DESCRIPTION
**Pull request by jkeenan**
As discussed in:
https://www.nntp.perl.org/group/perl.perl5.porters/2022/05/msg263707.html

As explained in the p5p list thread starting at the URL above, since we're in code freeze, this merge request should be completed only once perl-5.37.0 has been released and our next development cycle has begun.  However, I'm assigning this to the production release manager for his consideration.

### CODE REVIEW

**Comment by p-b-o** [comment]
Showing that this failure is the only one left for passing testsuite on Windows on Arm: https://github.com/Perl/perl5/pull/19556#issuecomment-1124586208

**Comment by Leont** [comment]
Should this be a 5.36 blocker? It looks to me like it should be

**Review by Leont — APPROVED** [review]

**Comment by jkeenan** [comment]
On 5/14/22 08:34, Leon Timmermans wrote:
> Should this be a 5.36 blocker? It looks to me like it should be
> 

This is going to be the production release manager's call, but I argue 
that it should *not* be a 5.36.0-release-blocker.

As far as I can tell, until three days ago we (P5P) were completely 
unaware of the existence of the Linaro-Microsoft-Qualcomm team's efforts 
to build applications on the OS/Platform combination of MSWin32 and ARM 
(as mentioned in 
https://www.nntp.perl.org/group/perl.perl5.porters/2022/05/msg263707.html). 
  While perl has been built on that operating system and that platform 
*separately*, I don't think we've ever previously received smoke-test 
reports or bug tickets about building perl on their *combination*.  So 
we're not currently set up to do ongoing QA on this combination.

That being the case, to designate this p.r. as a release blocker would 
mean delaying the release of 5.36 for all other OS/Platform 
combinations.  The benefit is too small to warrant that delay -- 
especially given the fact that for decades the common expectation has 
been that no one will build and install perl on Windows "right out of 
the box," i.e., directly from the P5P source code as opposed to some 
packaging of perl such as ActivePerl or Strawberry Perl.

We (P5P) certainly have been remiss with respect to Perl on Win32. 
AFAICT, right now there is exactly *one* person on the planet generating 
smoke-test reports for Perl 5 blead on Win32.  Just one.  Moreover, one 
of our principal smoke-test aggregators has for some reason simply 
stopped reporting results on Win32 
(https://rt.cpan.org/Ticket/Display.html?id=142752).  With regard to 
Windows we are pretty much flying blind.

We need to correct these problems in our QA apparatus.  Simultaneously 
we need to establish more regular communication with the people 
contributing to https://github.com/perl-libwin32/win32/.  But I don't 
think we should further delay perl-5.36.0 on this account.

**Comment by p-b-o** [comment]
As @jkeenan said, it's not worth blocking the release planned.

Our goal here was simply to contribute for this *new* platform, before investigating more  on this. It's a difficult situation, because there is no public free machine (any CI runner) available now. On our side, we use Azure with Linaro's account (arm64 machines have been available for a few weeks), but of course, it's not free.

It's a problem we have with the different projects we are contributing to, because accepting changes people can't check by themselves is not an ideal situation.

**Pull request merged**
