### PR TITLE
Make t/op/magic.t pass on AlmaLinux 8’s kernel.

### PR DESCRIPTION
**Pull request by FGasper**
Issue #19690

### CODE REVIEW

**Review by rwp0 — COMMENTED** [review]
would be good to explicitly mention kernels/distros that do so in the comment as a short example

**Comment by FGasper** [comment]
> would be good to explicitly mention kernels/distros that do so in the comment as a short example

I don’t disagree, but I don’t know the full spate of systems that have been tested here. I’ll add a couple notes, though.

**Review by rwp0 — APPROVED** [review]
that's better, thanks

**Review by toddr — APPROVED** [review]

**Review by Leont — APPROVED** [review]

**Review by leonerd — APPROVED** [review]
LGTM

**Comment by leonerd** [comment]
This has four approves now, and is a 5.36 release blocker. Can you merge it now please?

**Pull request merged**
