### PR TITLE
Smoke me/jkeenan/replace gh 20435 20221224

### PR DESCRIPTION
**Pull request by jkeenan**
This pull request is a replacement for https://github.com/Perl/perl5/pull/20435/.  That p.r. was prepared by @atoomic and largely reviewed by @tonycoz, but was never merged into blead.  Subsequently some of the files touched in that p.r. were drastically revised, leading to rebase/merge conflicts in 4 of 42 files.  This p.r. applies diffs for the 38 other files unchanged from that p.r., then manually handles the remaining 4 files.

### CODE REVIEW

**Comment by demerphq** [comment]
Fwiw, there is a correction of 'increate' to 'create' that should be
corrected to 'increase'. Other than that LGTM.

**Comment by jkeenan** [comment]
> Fwiw, there is a correction of 'increate' to 'create' that should be corrected to 'increase'. Other than that LGTM.

Thanks; fixed in most recent commit.

**Review by tonycoz — APPROVED** [review]

**Comment by demerphq** [comment]
LGTM as well

**Comment by jkeenan** [comment]
> LGTM as well

Thanks.  I will allow 1 or 2 more days to hear from @atoomic, then merge.

**Pull request merged**
