### PR TITLE
Yves/fix 19168 variable lookbehind

### PR DESCRIPTION
**Pull request by demerphq**
Issue #19168 - Fix variable length lookbehind matches with alternations
    
    We were not validating that when (?<=a|ab) matched that the right hand
    side of the match lined up with the position of the assertion. Similar
    for (?<!a|ab) and related patterns, eg, (*positive_lookbehind:).
    
    Part of the difficulty here was that the SUCCEED node was serving too
    many purposes, necessitating a new regop LOOKBEHIND_END.
    
    Note these problems do NOT affect lookahead. This logic could use more
    tests, especially for nested lookbehind. I added a couple but my brain
    is mush right now and some tests from someone fresher would be helpful.

### CODE REVIEW

**Comment by hvds** [comment]
Thanks, this looks a lot cleaner than I had feared from your earlier caveats.

I'll try to come up with some additional tests over the next day or two, but in principle this already looks good to me.

**Comment by demerphq** [comment]
Are there any objections to me merging this?

**Comment by hvds** [comment]
I don't have an objection; due to a bereavement, though, I haven't managed to spend the time writing extra tests for it that I had hoped to.

**Comment by demerphq** [comment]
On Wed, 23 Feb 2022 at 12:31, Hugo van der Sanden ***@***.***>
wrote:

> I don't have an objection; due to a bereavement,
>
I am very sorry to hear that. My condolences.


> though, I haven't managed to spend the time writing extra tests for it
> that I had hoped to.
>
Not to worry, we can add them later. I will probably add a few more myself
that I have in my command line history.

Since I have removed the patch that removes variable lookbehind from the PR
we are still in experimental mode so this is purely bug-fix territory.

We also have two options for the experimental status of this feature. This
one

  https://github.com/Perl/perl5/pull/19454

removes experimental status entirely, and this one

  https://github.com/Perl/perl5/pull/19455

keeps the experimental status, but reduces the scope of it to only those
cases where positive lookbehind contains a capturing buffer, thus to only
the cases where a possible future change in implementation might result in
a user visible change of behavior.

But all of that can wait, take care of yourself and your family/friends
first.

Cheers,
Yves


-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by khwilliamson** [comment]
I fixed a typo in a commit message, but otherwise pushed these unchanged, the final commit being cbdefcf186788da38bae658c0796f265d10660c2

**Comment by demerphq** [comment]
On Thu, 24 Feb 2022, 01:48 Karl Williamson, ***@***.***>
wrote:

> I fixed a typo in a commit message, but otherwise pushed these unchanged,
> the final commit being cbdefcf
> <https://github.com/Perl/perl5/commit/cbdefcf186788da38bae658c0796f265d10660c2>
>

Thanks! Sorry for the typo, I thought I spell checked all the commits, but
I guess in the rebase process I missed something.

Yves

>

**Comment by demerphq** [comment]
On Wed, 23 Feb 2022 at 12:49, demerphq ***@***.***> wrote:

> We also have two options for the experimental status of this feature. This
> one
>
>   https://github.com/Perl/perl5/pull/19454
>
> removes experimental status entirely, and this one
>
>   https://github.com/Perl/perl5/pull/19455
>
> keeps the experimental status, but reduces the scope of it to only those
> cases where positive lookbehind contains a capturing buffer, thus to only
> the cases where a possible future change in implementation might result in
> a user visible change of behavior.
>

Hi Hugo, Karl,

Gentle reminder we have a decision to make on this subject...

Cheers,
Yves

**Pull request closed without merging**
