### PR TITLE
Exclude RtoL characters from paired regex delimiters

### LINKED ISSUE #22228: feature 'extra_paired_delimiters': Please remove U+0706/U+0707 from the list
**Description**

The feature 'extra_paired_delimiters' allows many pairs, at least one of them is likely to cause confusion: U+0706 and U+0707 (SYRIAC COLON SKEWED LEFT and SYRIAC COLON SKEWED RIGHT).  These characters have the BIDI property "Right-to-Left Arabic [AL]".
Unicode-aware editors and terminals process this property.  The consequence:  If a character _between_ the delimiters has a left-to-right property, then everything looks normal.  However, if the text between the delimiters has only BIDI neutral characters, then this text _including the delimiters_ is displayed as right-to-left.  As a special effect, if one of the characters has a "Mirror" property, then the _mirrored character_ is displayed: a "<" is shown with the glyph ">".

Perl is not confused by this, but humans looking at the code might be.  Can we please remove this (and maybe other) right-to-left delimiters from the list?

```perl
use utf8;
use feature 'extra_paired_delimiters';

my $alphabetic  = q܆a܇; # this is correct
my $punctuation = q܆.܇; # this is also correct but looks backwards

my $weird = q܆<-܇;
print $weird; # prints "<-", because that's actually the value
```

**Perl configuration**

```
# perl -V output goes here
```
Summary of my perl5 (revision 5 version 39 subversion 11) configuration:
  Local Commit: 2fc32c2024a28634f5bb168cc671dcf18056620b
  Ancestor: e3f226d5c6ed541239e77ee339cd04d121da4411
  Platform:
    osname=linux
    osvers=6.5.0-35-generic
    archname=x86_64-linux
    uname='linux hajbuntu 6.5.0-35-generic #35~22.04.1-ubuntu smp preempt_dynamic tue may 7 09:00:52 utc 2 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Dusedevel -Dprefix=/home/haj/localperl/ -Dman1dir=none -Dman3dir=none'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.35'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'

Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
```

### PR DESCRIPTION
**Pull request by khwilliamson**
Fixes #22228

Some scripts in the world are written right-to-left, such as Arabic and Hebrew.  This can result in confusion for regex pattern delimitters that we have chosen based on left-to_right.  Therefore exclude all such. Currently, the only two that fall into this category that we don't exclude for other reasons are SYRIAC COLON SKEWED LEFT/RIGHT.

### CODE REVIEW

**Comment by jkeenan** [comment]
> Fixes #22228
> 
> Some scripts in the world are written right-to-left, such as Arabic and Hebrew. This can result in confusion for regex pattern delimitters that we have chosen based on left-to_right. Therefore exclude all such. Currently, the only two that fall into this category that we don't exclude for other reasons are SYRIAC COLON SKEWED LEFT/RIGHT.

Could we get a unit test to exercise this change?

**Comment by tonycoz** [comment]
The change looks fine to me.

I do think it could use a test.

**Comment by haarg** [comment]
This does seem like a change we should make.

According to policy, a change in behavior like this would require leaving this feature as experimental until v5.42.

**Comment by khwilliamson** [comment]
@haarg, good catch!  Updated PR reverts to experimental, non-stable

**Pull request merged**
