### PR TITLE
keywords.h: Restrict to core

### PR DESCRIPTION
**Pull request by khwilliamson**
These should not be used outside core

### CODE REVIEW

**Comment by khwilliamson** [comment]
@karenetheridge says that these are used on cpan

**Comment by karenetheridge** [comment]
..but maybe they shouldn't be... there were only two matches on grep.metacpan.org

**Comment by Leont** [comment]
> ..but maybe they shouldn't be... there were only two matches on grep.metacpan.org

Devel::Hook can easily be rewritten not to use it, and warnings::unused includes keywords.h but doesn't appear to do anything with it? (unless I'm missing something)

**Comment by karenetheridge** [comment]
Devel::Hook uses the header definitions to check for the availability of UNITCHECK, but it would be more correct to simply do a version (`$]`) check instead: https://metacpan.org/release/Devel-Hook/source/Hook.xs#L22

warnings::used uses KEY_our and KEY_my:

https://metacpan.org/release/warnings-unused/source/unused.xs#L223
https://metacpan.org/release/warnings-unused/source/unused.xs#L248

**Comment by khwilliamson** [comment]
I'm wondering if we could have something like `#define USE_PERL_KEYWORDS` that a module could use to gain access to them.

**Pull request closed without merging**
