### PR TITLE
IPC::Open2 and IPC::Open3 documentation updates

### LINKED ISSUE #16688: IPC::Open2 and IPC::Open3 documentation updates
Migrated from [rt.perl.org#133509](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133509) (status was 'open')

Searchable as RT133509$

### PR DESCRIPTION
**Pull request by Grinnz**
PR to resolve https://github.com/Perl/perl5/issues/16688

* Remove direct usage of bareword filehandles and use lexical filehandles for the first example in each synopsis.
* Add examples using STDIN and STDOUT filehandles, and examples using already open filehandles, with explicit examples of where these handles come from.
* Declare variables with 'my' where appropriate and condense declarations inline.
* Add comments in synopsis describing the purpose of each example.
* Consistency of referencing synopsis variables from the description.
* Replace ambiguous phrase 'null string' with 'empty string or undefined' which is also more correct here.
* Add links to referenced CPAN modules and manpages.
* Better describe the reason for using gensym in IPC::Open3 and how to use it.

### CODE REVIEW

**Review by atoomic — CHANGES_REQUESTED** [review]
some pod issues making pod check failed
```
#   "Apparent broken link"  (6 occurrences, expected 0)
2954
#     to "pipe(2)" near line 47 of ext/IPC-Open3/lib/IPC/Open2.pm
2955
#     to "bc(1)" near line 71 of ext/IPC-Open3/lib/IPC/Open2.pm
2956
#     to "bc(1)" near line 71 of ext/IPC-Open3/lib/IPC/Open2.pm
2957
#     to "sort(1)" near line 71 of ext/IPC-Open3/lib/IPC/Open2.pm
2958
#     to "IO::Pty" near line 83 of ext/IPC-Open3/lib/IPC/Open2.pm
2959
#     to "Expect" near line 83 of ext/IPC-Open3/lib/IPC/Open2.pm
2960
#   "Verbatim line length including indents exceeds 79 by" 
2961
#     +5 (including 0 from =over's) near line 21 of ext/IPC-Open3/lib/IPC/Open2.pm
2962
# See end of this test output for your options on silencing this
2963
#   "Apparent broken link"  (4 occurrences, expected 0)
2964
#     to "pipe(2)" near line 53 of ext/IPC-Open3/lib/IPC/Open3.pm
2965
#     to "bc(1)" near line 94 of ext/IPC-Open3/lib/IPC/Open3.pm
2966
#     to "bc(1)" near line 94 of ext/IPC-Open3/lib/IPC/Open3.pm
2967
#     to "sort(1)" near line 94 of ext/IPC-Open3/lib/IPC/Open3.pm
2968
#   "Verbatim line length including indents exceeds 79 by" 
2969
#     +3 (including 0 from =over's) near line 29 of ext/IPC-Open3/lib/IPC/Open3.pm
2970
# See end of this test output for your options on silencing this
2971
# 
2972
# HOW TO GET porting/podcheck.t TO PASS
```

**Comment by Grinnz** [comment]
Again the lines mentioned where under 79 characters but I wrapped them. I don't understand the link check fails, those are all valid manpage or pod links.

**Comment by Leont** [comment]
> Again the lines mentioned where under 79 characters but I wrapped them.

Verbatims are indented, so it needs to be under 72 I think.

**Comment by Grinnz** [comment]
Link checks updated as in #17373

**Comment by xsawyerx** [comment]
:+1: Nice!

**Comment by atoomic** [comment]
@Grinnz would you mind rebasing on blead so we get a fresh smoker run on this PR?
thanks

**Comment by Grinnz** [comment]
Rebased

**Pull request merged**
