### PR TITLE
Fix Safe clobbering %SIG

### PR DESCRIPTION
**Pull request by ehuelsmann**
Fixes https://rt.cpan.org/Ticket/Display.html?id=112092

I followed pod/perlhack.pod; please let me know if I need to follow additional process: it's my first submission.

### CODE REVIEW

**Comment by tonycoz** [comment]
Could you add a test case please?

**Comment by ehuelsmann** [comment]
Tests added. Is there anything *I* can do about the failing Safe version porters test?

**Comment by jkeenan** [comment]
> Tests added. Is there anything _I_ can do about the failing Safe version porters test?

Increment `$VERSION` in `dist/Safe/Safe.pm`, then confirm results via `make test_porting`.  (Once that's passing, commit, but you can squash commits before repushing pull request.)

**Comment by ehuelsmann** [comment]
Hmm. my local build environment gets stuck building Encode.so.  I did perform the other steps, but since Encode.so isn't building, I can't complete `make test_porting`.

The Encode.so failure is probably unrelated to Safe. Is Encode.so sensitive to particular beginner errors?

**Comment by jkeenan** [comment]
> Hmm. my local build environment gets stuck building Encode.so. I did perform the other steps, but since Encode.so isn't building, I can't complete `make test_porting`.
> 
> The Encode.so failure is probably unrelated to Safe. Is Encode.so sensitive to particular beginner errors?

Please post these failures so that we can take a look.  Thanks.

**Comment by ehuelsmann** [comment]
@jkeenan, actually, it's not showing any errors. It's just showing:

```plain
make[1]: Leaving directory '/home/erik/dev/perl5/cpan/Digest-SHA'
./miniperl -Ilib make_ext.pl lib/auto/Encode/Encode.so  MAKE="make" LIBPERL_A=libperl.a LINKTYPE=dynamic
```

and `top` isn't showing any activity at all. It doesn't matter whether I invoke `make` or `LC_ALL=C make`; both exhibit the same problem. My build machine is:

```
$ uname -a
Linux tuxedo 6.2.0-10018-tuxedo #23 SMP PREEMPT_DYNAMIC Tue Jul 18 21:29:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
$ env | grep LC
LC_ADDRESS=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_MONETARY=nl_NL.UTF-8
LC_PAPER=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
LC_NUMERIC=nl_NL.UTF-8
$ env | grep PERL
PERLBREW_HOME=/home/erik/.perlbrew
PERLBREW_SHELLRC_VERSION=0.92
PERLBREW_ROOT=/home/erik/perl5/perlbrew
```

**Comment by jkeenan** [comment]
> @jkeenan, actually, it's not showing any errors. It's just showing:
> 
> ```
> make[1]: Leaving directory '/home/erik/dev/perl5/cpan/Digest-SHA'
> ./miniperl -Ilib make_ext.pl lib/auto/Encode/Encode.so  MAKE="make" LIBPERL_A=libperl.a LINKTYPE=dynamic
> ```
> 
> and `top` isn't showing any activity at all. It doesn't matter whether I invoke `make` or `LC_ALL=C make`; both exhibit the same problem. My build machine is:
> 

Let's first try to rule out problems related to your branch/p.r.  If you say:
```
$ git clean -dfx
$ git checkout blead
$ sh ./Configure -des -Dusedevel && make test_prep
```
... does your build still stall at `./miniperl -Ilib make_ext.pl lib/auto/Encode/Encode.so`?

I note that your p.r. is, at this moment, doing well in our CI system, and it's also doing well for me on Debian Linux 11.

**Comment by ehuelsmann** [comment]
> ... does your build still stall at `./miniperl -Ilib make_ext.pl lib/auto/Encode/Encode.so`?

yep. fully stalled. even checked out the latest ("now") version of blead from the main repository -- no change.

**Comment by jkeenan** [comment]
> > ... does your build still stall at `./miniperl -Ilib make_ext.pl lib/auto/Encode/Encode.so`?
> 
> yep. fully stalled. even checked out the latest ("now") version of blead from the main repository -- no change.

Okay, I think we can separate your local build failure from the evaluation of your pull request.  I recommend you open a separate ticket (GH issue) about your build failure; we'll keep discussion Safe in this ticket.

**Note to reviewers of this ticket:** Safe has been in `dist/` since 2009 (5a4811be25e2c4fa466997f8fc1ac08c1abddb9e).  The problem which the OP is responding to was reported to Safe's CPAN bug tracker in 2016.  In hindsight, it should have been reported to P5P instead.  Hence, please evaluate this p.r. with respect to https://rt.cpan.org/Ticket/Display.html?id=112092.

**Review by tonycoz — APPROVED** [review]

**Comment by tonycoz** [comment]
If you want to try to debug the Encode issue you could try attaching gdb to the stalled miniperl process, something like:
```
gdb -p PIDOFMINIPERL
```
assuming you have a perl built with debug info:
```
./Configure ... -Doptimize="-O0 -ggdb3"
```
You can use `bt` to dump a C backtrace in the debugger.

To see where in the perl code where this is blocked, assuming an unthreaded perl:
```
p *PL_curcop
call Perl_sv_dump((SV*)PL_curcop->cop_filegv)
```

**Comment by ehuelsmann** [comment]
@tonycoz thanks for the help. No idea what happened, but I've rebooted the system this morning and rebuilt. No problem whatsoever... Totally disappeared. I guess the PR also works on my system now.

**Pull request merged**
