### PR TITLE
Sync Compress-Raw-Zlib-2.105 into blead

### PR DESCRIPTION
**Pull request by toddr**
This commit synchs into blead versions 2.105 for
CPAN distribution Compress-Raw-Zlib

### CODE REVIEW

**Comment by toddr** [comment]
per @pmqs in https://github.com/Perl/perl5/issues/19685#issuecomment-1126660476 , I am submitting this PR for smoke.

**Comment by jkeenan** [comment]
> per @pmqs in [#19685 (comment)](https://github.com/Perl/perl5/issues/19685#issuecomment-1126660476) , I am submitting this PR for smoke.

@toddr, if you would like this branch to be picked up by automatic smokers, its name should start with `smoke-me`, e.g., `smoke-me/toddr/crzlib-2.105` and be pushed to perl5.git.

**Comment by toddr** [comment]
> @toddr, if you would like this branch to be picked up by automatic smokers, its name should start with `smoke-me`, e.g., `smoke-me/toddr/crzlib-2.105` and be pushed to perl5.git.

@jkeenan The github smokers have already smoked this. Just the same, I've also pushed to the alternate branch.

**Review by atoomic — APPROVED** [review]

**Comment by toddr** [comment]
@jkeenan how are the smoker results for this?

**Comment by jkeenan** [comment]
On 5/18/22 11:13, Todd Rinaldo wrote:
> @jkeenan <https://github.com/jkeenan> how are the smoker results for this?
> 

They look good, but you can see them for yourself at:
http://perl.develop-help.com/?b=smoke-me%2Ftoddr%2Fcrzlib-2.105

**Review by Leont — APPROVED** [review]

**Pull request merged**
