### PR TITLE
Minor update to perl -h to display newly added -g option.

### PR DESCRIPTION
**Pull request by manwar**
Hi Team,

Thanks for the ground breaking work. Well done.
I propose a small update so that perl help displays the -g option.

This is my first PR to the core Perl and hopefully not the last.

Best Regards,
Mohammad

### CODE REVIEW

**Comment by briang** [comment]
I think the text should emphasise what the option does, rather than how. eg "enables slurp mode by undefining the input record separator"

**Comment by manwar** [comment]
> I think the text should emphasise what the option does, rather than how. eg "enables slurp mode by undefining the input record separator"

I am happy to add, if everyone agrees to this.

**Comment by Leont** [comment]
> I think the text should emphasise what the option does, rather than how. eg "enables slurp mode by undefining the input record separator"

Agreed. The main point is that it slurps the whole file.

**Comment by manwar** [comment]
> > I think the text should emphasise what the option does, rather than how. eg "enables slurp mode by undefining the input record separator"
> 
> Agreed. The main point is that it slurps the whole file.

Done. Is it good enough?

**Comment by briang** [comment]
> undefines the input record separator ($/) and enables the slurp mode

Now it sounds as if it does two, separate, things. And it still emphasises the "how", and not the "what".

**Comment by neilb** [comment]
"read all input in one go (slurp), rather than line-by-line"?

**Comment by manwar** [comment]
> "read all input in one go (slurp), rather than line-by-line"?

short and precise, applied the changes. thanks @neilb

**Review by Leont — APPROVED** [review]

**Comment by khwilliamson** [comment]
@manwar please rebase this commit.  I have added you to the authors file, so the real tests should now start up

**Comment by khwilliamson** [comment]
... and s uash into a single commit.  The letter between p and r won't display in github text boxes

**Comment by manwar** [comment]
> ... and s uash into a single commit. The letter between p and r won't display in github text boxes

Done.

**Comment by rwp0** [comment]
@manwar Thanks for this.

---

It would be nice if there were **tests** for checking `-h` code/output **adding new command line flags** to the interpreter in core to ensure it's always considered/present/documented.

**Comment by Leont** [comment]
> It would be nice if there were tests for checking -h code/output adding new command line flags to the interpreter in core to ensure it's always considered/present/documented.

Well volunteered!

**Comment by esabol** [comment]
There shouldn't be a period after "line-by-line", I think. None of the other options have periods.

**Pull request merged**
