### PR TITLE
document when backwards-compatibility features are disabled by default

### PR DESCRIPTION
**Pull request by book**

### CODE REVIEW

**Comment by book** [comment]
I had forgotten `feature.pm` was a generated file... :sweat_smile:

**Comment by jkeenan** [comment]
> I had forgotten `feature.pm` was a generated file... 😅

It apparently still needs a version bump; see test failures.  I suspect this bump goes in whatever `*.pl` file generates it.

**Comment by haarg** [comment]
These changes aren't really correct. The features are not disabled by default in Perl 5.36. They are disabled by the 5.36 feature bundle.

**Comment by book** [comment]
> These changes aren't really correct. The features are not disabled by default in Perl 5.36. They are disabled by the 5.36 feature bundle.

Does this sound better (and more correct)?

```
This feature is disabled starting with the C<:5.36> feature bundle.
```

I want to convey clearly that it's going to be disabled in all bundles after `:5.36`.

**Comment by book** [comment]
Actually, I have more changes to this manual page, so I'll bundle them in a single pull request.

**Pull request closed without merging**
