### PR TITLE
Alter documentation to reflect behaviour

### PR DESCRIPTION
**Pull request by benkasminbullock**
The name "wanted" chosen for the documentation was misleading, as the
documentation itself pointed out. I've changed it to "found" except in
the one place where "wanted" has to be used.

I've also addressed several other oddities in the documentation.

### CODE REVIEW

**Comment by Leont** [comment]
When passed as a named argument it's called `wanted`, so IMO the least surprising thing we can do is to use the same name when passing it as a positional argument.

**Comment by jkeenan** [comment]
> The name "wanted" chosen for the documentation was misleading, as the
> documentation itself pointed out. I've changed it to "found" except in
> the one place where "wanted" has to be used.
> 
> I've also addressed several other oddities in the documentation.

You've submitted one pull request for documentation changes which you earlier cited in three separate issues.  As is already evident, some of your suggested changes are controversial.  I think you would be better off submitting a separate pull request for each of the three problems you described in those tickets.  That might improve your chances of getting some of the changes accepted.

Thank you very much.
Jim Keenan

**Comment by benkasminbullock** [comment]
> You've submitted one pull request for documentation changes which you earlier cited in three separate issues. As is already evident, some of your suggested changes are controversial. I think you would be better off submitting a separate pull request for each of the three problems you described in those tickets. That might improve your chances of getting some of the changes accepted.

No thanks, I've done enough work here.

**Comment by Leont** [comment]
> You've submitted one pull request for documentation changes which you earlier cited in three separate issues. As is already evident, some of your suggested changes are controversial. I think you would be better off submitting a separate pull request for each of the three problems you described in those tickets. That might improve your chances of getting some of the changes accepted.

Yeah, or at least split out into three commits

**Comment by benkasminbullock** [comment]
Sorry but as stated above I'm not willing to spend more time on File::Find.

**Pull request closed without merging**
