### PR TITLE
Add POD for AvARRAY.

### PR DESCRIPTION
**Pull request by FGasper**

### CODE REVIEW

**Review by xsawyerx — APPROVED** [review]
:+1: from me.

**Comment by xsawyerx** [comment]
@khwilliamson what work do you see necessary here before we could merge it?

**Comment by xsawyerx** [comment]
@FGasper Can you please rebase this, too? I think it would help get rid of the conflict GitHub is seeing.

**Comment by xenu** [comment]
Note that there was some discussion about this on p5p: https://www.nntp.perl.org/group/perl.perl5.porters/2020/08/msg258173.html

**Comment by FGasper** [comment]
@xsawyerx I rebased; cygwin is failing, but is that a known failure?

**Comment by atoomic** [comment]
the `needs-work` label was added before the auto detection of conflicts, I think we can remove it now that this has been rebased

**Review by atoomic — APPROVED** [review]

**Comment by khwilliamson** [comment]
On 9/29/20 9:01 AM, Felipe Gasper wrote:
> @xsawyerx <https://github.com/xsawyerx> I rebased; cygwin is failing, 
> but is that a known failure?
> 
It is a known failure

**Pull request merged**
