### PR TITLE
Fix do block not running lexical variable instantiation/destruction, when a lexical variable is the only term in the do block

### LINKED ISSUE #16676: Object instantiated/assigned inside of do { } block does not have DESTROY method called if assignment is the only action in the block
Migrated from [rt.perl.org#133489](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133489) (status was 'open')

Searchable as RT133489$

### PR DESCRIPTION
**Pull request by rawleyfowler**
Hi friends,

Do blocks with a single child of an object instantiation ie:

```perl
do { my $obj = Obj->new() };
```

Are not called at all. This patch fixes this by applying the `OPf_PARENS` flag to all `do {...}` blocks, causing all `do {}` blocks to be treated the same.

This is my first every PR against Perl, feedback very welcome :)

fixes #16676 

*Edit*: I originally thought this just affected `DESTROY`, but testing it seems to just not do anything if assigning is all you do in a do block:

```perl
do { my $foo = Obj->new(); }; 
sleep 2;
kill "KILL", $$;
package Obj;

sub new {
  print "FOO"; # not called
  return bless {}, __PACKAGE__;
}

sub DESTROY { print "destroy called\n" } # also not called
```

### CODE REVIEW

**Comment by guest20** [comment]
Does this also need a test that covers it not calling `DESTROY` for `my $thing = do { Foo->new }` ?

**Comment by jkeenan** [comment]
@rawleyfowler, thank you for your pull request.

We have a GH Continuous Integration set up to provide some initial testing of pull requests.  Your p.r. did not PASS and needs some work before it will do so and then be ready for code review.  You can see these failures for yourself if you run:
```
$ make test_porting
```
... in your branch.  It will report something like this:
```
...
Test Summary Report
-------------------
porting/authors.t       (Wstat: 256 (exited 1) Tests: 7 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
porting/regen.t         (Wstat: 0 Tests: 44 Failed: 3)
  Failed tests:  3-5
Files=37, Tests=48051, 12 wallclock secs ( 1.11 usr  0.08 sys + 43.52 cusr  3.42 csys = 48.13 CPU)
Result: FAIL
```
**t/porting/authors.t**

The failure in `t/porting/authors.t` is relatively simple to fix.  To expedite matters, try applying this patch (with, say, `git am`):
```
$ cat 0001-Add-Rawley-Fowler-to-AUTHORS.patch 
From d70100a9c1e94f8c1a7504a4a6b7eda281d8968a Mon Sep 17 00:00:00 2001
From: James E Keenan <jkeenan@cpan.org>
Date: Mon, 2 Sep 2024 08:08:43 -0400
Subject: [PATCH] Add Rawley Fowler to AUTHORS

Add contributor to .mailmap
---
 .mailmap | 1 +
 AUTHORS  | 1 +
 2 files changed, 2 insertions(+)

diff --git a/.mailmap b/.mailmap
index 21a5127126..820f31da34 100644
--- a/.mailmap
+++ b/.mailmap
@@ -717,6 +717,7 @@ Randy J. Ray <rjray@redhat.com> Randy J. Ray <rjray@uswest.com>
 Randy W. Sims <unknown> Randy W. Sims <ml-perl@thepierianspring.org>
 Randy W. Sims <unknown> Randy W. Sims <perlbug@perl.org>
 Raphael Manfredi <raphael.manfredi@pobox.com> Raphael Manfredi <raphael_manfredi@grenoble.hp.com>
+Rawley Fowler <rawleyfowler@proton.me> rawleyfowler <rawleyfowler@proton.me>
 Reini Urban <rurban@cpan.org> Reini Urban <rurban@cpanel.net>
 Reini Urban <rurban@cpan.org> Reini Urban <rurban@x-ray.at>
 Reini Urban <rurban@cpan.org> rurban@cpanel.net <rurban@cpanel.net>
diff --git a/AUTHORS b/AUTHORS
index b2e0bf2043..7a41c0aa4f 100644
--- a/AUTHORS
+++ b/AUTHORS
@@ -1172,6 +1172,7 @@ Randy W. Sims
 Raphael Manfredi               <Raphael.Manfredi@pobox.com>
 Raul Dias                      <raul@dias.com.br>
 Raul E Rangel                  <rrangel@chromium.org>
+Rawley Fowler                  <rawleyfowler@proton.me>
 Raymund Will                   <ray@caldera.de>
 Redvers Davies                 <red@criticalintegration.com>
 Reini Urban                    <rurban@cpan.org>
-- 
2.34.1

```
Once committed, run `make test_prep` and then `$ ./perl -Ilib t/porting/authors.t` to verify.  Output from the latter should be:
```
ok 1 - Is authors_file 'AUTHORS' up to date?
ok 2 - Is mailmap_file '.mailmap' up to date?
ok 3 - Is exclude_file 'Porting/exclude_contrib.txt' up to date?
ok 4 - No dupes in AUTHORS
ok 5 - git status --porcelain should be empty
1..5
```
**t/porting/regen.t**

Relevant output:
```
$ cd t; ./perl harness -v porting/regen.t; cd -

ok 1 - generated keywords.c is up to date
ok 2 - generated keywords.h is up to date
not ok 3 - generated perly.act is up to date
# Failed test 3 - generated perly.act is up to date at porting/regen.t line 120
#      got "perly.y"
# expected ""
# Note: regen_perly.pl must be run manually, because it requires bison
not ok 4 - generated perly.h is up to date
# Failed test 4 - generated perly.h is up to date at porting/regen.t line 120
#      got "perly.y"
# expected ""
not ok 5 - generated perly.tab is up to date
# Failed test 5 - generated perly.tab is up to date at porting/regen.t line 120
#      got "perly.y"
# expected ""
ok 6 - generated regcharclass.h is up to date
...
Failed 3/44 subtests 

Test Summary Report
-------------------
porting/regen.t (Wstat: 0 Tests: 44 Failed: 3)
  Failed tests:  3-5
Files=1, Tests=44,  6 wallclock secs ( 0.01 usr  0.01 sys +  5.88 cusr  0.14 csys =  6.04 CPU)
Result: FAIL
```
I myself do not know how to fix this, as I am not familiar with the `perly.*` files we use.  When I attempted to run `./regen_perly.pl` I was first informed that I did not have `bison` installed.  When I did install `bison` and re-ran that program, I got this output:
```
$ ./perl -Ilib regen_perly.pl 

You have the wrong version of bison in your path; currently versions
2.5-2.7 or 3.0-3.7 are known to work.  Try installing
    http://ftp.gnu.org/gnu/bison/bison-3.3.tar.gz
or similar.  Your bison identifies itself as:

bison (GNU Bison) 3.8.2
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Other readers of this issue queue will have to help you out with that.  Please be sure to run `make test_harness` and getting a PASS before re-pushing this merge request.

**Comment by rawleyfowler** [comment]
So i've added tests, and I've applied the `AUTHORS`, `.mailmap` patches, but when running the `perly.y` generation I get a LOT of changes that seem un-related to my own. Not sure how to address that, or what to do, unless that is intended.

**Comment by rawleyfowler** [comment]
I've pushed the `perly` changes, but in a separate commit just to keep them easily droppable if there is something i've done wrong (as to why I have to a bunch of changes)

**Comment by rawleyfowler** [comment]
I also saw this test (`warnings.t`) fail but seems unrelated?

```
Use of uninitialized value $m1 in substitution (s///) at - line 33.
```

vs.

```
Use of uninitialized value in substitution iterator at - line 33.
```

**Comment by rawleyfowler** [comment]
Ah actually nvm, looks like this in-inadvertently changed `s///ee`.

**Comment by rawleyfowler** [comment]
So from what I can tell, this changes the warning message, but the functionality is the same (or even more consistent, becasue `/ee` will now call destroy if the `eval` is just a object instantiation I believe). I'm not very familiar with the internals of how these warnings are generated but I would be open to learning/fixing this to make it produce the desired warning. For now i've just updated the test.

**Comment by rawleyfowler** [comment]
Closing as I no longer have time to work on this.

**Pull request closed without merging**
