### PR TITLE
Update autodie to 2.31 from CPAN

### PR DESCRIPTION
**Pull request by toddr**
Add additional test excludes for autodie and remove
the CUSTOMIZED section from Porting/Maintainers.pl
now we're in sync with CPAN

### CODE REVIEW

**Comment by bingos** [comment]
I appear to have independently already done this.

**Comment by toddr** [comment]
You were missing some exclusions. I don't follow how ```Porting/sync-with-cpan autodie```  ran for you?

**Comment by toddr** [comment]
> You were missing some exclusions. I don't follow how `Porting/sync-with-cpan autodie` ran for you?

I see you included a qr{xt/}

**Comment by toddr** [comment]
This change has been manually pushed to blead.

**Pull request closed without merging**
