### PR TITLE
Update perlvar.pod to clarify medium name state

### PR DESCRIPTION
**Pull request by jidanni**
Here we clarify if we can use medium names, without needing to check a second man page to see if we need to use "use English" first.

### CODE REVIEW

**Comment by Leont** [comment]
IMHO this is more confusing than clarifying.

**Comment by jkeenan** [comment]
> IMHO this is more confusing than clarifying.

Agreed; closing.

**Comment by mauke** [comment]
I don't see what the commit message has to do with the change.

**Comment by guest20** [comment]
As far as I can see, a "medium" name is just a second "long" name.

How about "Some variables also have an additional awk inspired name"?

**Comment by jidanni** [comment]
All I know is on the perlvar man page,
one sees [$ORS](https://perldoc.perl.org/5.6.0/perlvar#$ORS).

After long study of that page, we can be 100% sure that we will
need `use English` if we want to use `$OUTPUT_RECORD_SEPARATOR`,
and we can also be sure we don't need `use English` if we want to just use `$,`.

However for `$ORS` it is a different story. No matter how many times we read perlvar, we just can't be sure if we will need `use English` if we want to use `$ORS`.

Nope. To find out that detail, we are referred to yet another man page, the English man page, where yes, we finally find the answer.

I'm just saying if one can get the answer about needing `use English` for the long ones, and short ones, right there on perlvar, why not also about the middle ones? Yes, how you phrase is  up to you. Just say something there. Thanks.

**Comment by guest20** [comment]
hmm. The source of long/medium names might be made clearer if we moved all the `English` names to the docs for `English`, so it's clear that they come from `use English`?

**Pull request closed without merging**
