### PR TITLE
ExtUtils::ParseXS: fix OVERLOAD/FALLBACK handling

### PR DESCRIPTION
**Pull request by iamb**
move code generation for xsubs with overloads out of OVERLOAD_HANLDER. they
must come after ->{newXS} et al have been populated. previously, the values of
the preceding xsub (empty if one happened to use OVERLOAD on the first xsub in
the file) were used.

change handling of overloads and fallback from global-per-XS-file to
per-package. previously, if multiple packages existed in a single XS file with
any OVERLOAD, the _nil function and () sub for fetchmethod was created only for
the last package in the file (even if that one didn't have overloads). xsubs in
any packages other than the very last one would not be able to have OVERLOAD
function correctly.

there should be no change in behavior for existing code.

### CODE REVIEW

**Comment by jkeenan** [comment]
> move code generation for xsubs with overloads out of OVERLOAD_HANLDER. they must come after ->{newXS} et al have been populated. previously, the values of the preceding xsub (empty if one happened to use OVERLOAD on the first xsub in the file) were used.
> 
> change handling of overloads and fallback from global-per-XS-file to per-package. previously, if multiple packages existed in a single XS file with any OVERLOAD, the _nil function and () sub for fetchmethod was created only for the last package in the file (even if that one didn't have overloads). xsubs in any packages other than the very last one would not be able to have OVERLOAD function correctly.
> 
> there should be no change in behavior for existing code.

Would you be able to provide a code sample to demonstrate the problem you say currently exists?

Thank you very much.
Jim Keenan

**Comment by Leont** [comment]
> Would you be able to provide a code sample to demonstrate the problem you say currently exists?

Or better yet, a test that shows you've fixed it

**Comment by iamb** [comment]
a test would definitely be best, but that'll be challenging (i'll see if i can figure something out, but i'd be glad for an assist). i'm pretty new to XS, so please bear with me in my demonstration; it's probably a bit silly and way lengthier than need be.

i made a test directory with a simple Makefile.PL:

```
#!/usr/bin/env perl
use ExtUtils::MakeMaker;

WriteMakefile(NAME => "XSDemo");
```

a package lib/XSDemo.pm:

```
package XSDemo;
use XSLoader;
XSLoader::load("XSDemo");
```

and an xs file XSDemo.xs:

```
#define PERL_NO_GET_CONTEXT
#define NO_XS_LOCKS

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "patchlevel.h"

MODULE=XSDemo PACKAGE=XSDemo

void
stringy(...)

  OVERLOAD: \"\"

  CODE:
    XSRETURN_PV("foo");
```

i built the demo with `perl Makefile.PL ; make` and tested the results:

```
$ perl -Ilib -Iblib/arch -E 'use XSDemo; say bless([], "XSDemo")'
Operation """": no method found, argument in overloaded package XSDemo at -e line 1.
```
(with a FALLBACK: TRUE the stringification `XSDemo=ARRAY(0x...)` would be printed instead) this demonstrates the problem with ->{newXS} not being prepared yet by the time OVERLOAD_handler is called. the problem can be seen in the generated XSDemo.c:

```
    /* Making a sub named "XSDemo::()" allows the package */
    /* to be findable via fetchmethod(), and causes */
    /* overload::Overloaded("XSDemo") to return true. */
    (void)newXS_deffile("XSDemo::()", XS_XSDemo_nil);
        (void)("XSDemo::(\"\"", XS_XSDemo_stringy);
        newXS_deffile("XSDemo::stringy", XS_XSDemo_stringy);
```

note the `(void)("XSDemo...` line. the `(""` sub will not exist. if i add a dummy xsub ahead of it, it works as expected:

```
#define PERL_NO_GET_CONTEXT
#define NO_XS_LOCKS

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "patchlevel.h"

MODULE=XSDemo PACKAGE=XSDemo

void
dummy()
  CODE:
    XSRETURN_YES;

void
stringy(...)

  OVERLOAD: \"\"

  CODE:
    XSRETURN_PV("foo");
```

```
$ make
$ perl -Ilib -Iblib/arch -E 'use XSDemo; say bless([], "XSDemo")'
foo
```

however it only "works" because when parsing the stringy xsub, ->{newXS}, ->{file}, ->{proto} are still populated from the parsing of the dummy xsub. this is why i moved the code generation out of OVERLOAD_handler.

the original problem that sent me looking into this was with multiple packages in an XS file. the problem can be seen by adding another package section to the example so far:

```
#define PERL_NO_GET_CONTEXT
#define NO_XS_LOCKS

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "patchlevel.h"

MODULE=XSDemo PACKAGE=XSDemo

void
dummy()
  CODE:
    XSRETURN_YES;

void
stringy(...)

  OVERLOAD: \"\"

  CODE:
    XSRETURN_PV("foo");

MODULE=XSDemo PACKAGE=XSDemo::This::Breaks::It
```

once again, build and test:

```
$ make
$ perl -Ilib -Iblib/arch -E 'use XSDemo; say bless([], "XSDemo")'
XSDemo=ARRAY(0x7f537509d688)
```

this time, it prints the stringification of the object rather than complaining about not finding the overload method because the XSDemo package isn't seen as overloaded at all anymore. this can be seen in the generated c:

```
    /* register the overloading (type 'A') magic */
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    PL_amagic_generation++;
#endif
    /* The magic for overload gets a GV* via gv_fetchmeth as */
    /* mentioned above, and looks in the SV* slot of it for */
    /* the "fallback" status. */
    sv_setsv(
        get_sv( "XSDemo::This::Breaks::It::()", TRUE ),
        &PL_sv_undef
    );
    /* Making a sub named "XSDemo::This::Breaks::It::()" allows the package */
    /* to be findable via fetchmethod(), and causes */
    /* overload::Overloaded("XSDemo::This::Breaks::It") to return true. */
    (void)newXS_deffile("XSDemo::This::Breaks::It::()", XS_XSDemo__This__Breaks__It_nil);
        newXS_deffile("XSDemo::dummy", XS_XSDemo_dummy);
        (void)newXS_deffile("XSDemo::(\"\"", XS_XSDemo_stringy);
        newXS_deffile("XSDemo::stringy", XS_XSDemo_stringy);
```

because overload (and importantly fallback to go with it) are only tracked globally for the whole xs file, if there is any overloading at all it is only the last package to appear which has the special sauce applied for fetchmethod to find overloading. any number of packages can appear in the xs file, and it will always be the case that only the last package can properly have overloading work. that's why i changed to keep track of what packages use overload, and their fallback behavior is meant to be.

**Comment by iamb** [comment]
i had some time to look more into testing, i think i see what i can do to add tests (looking at t/002-more.t). i should be able get something added soon.

**Comment by iamb** [comment]
tests added. running tests without the patch breaks on overload/fallback testing (because multiple packages in the xs file, and the tested overload isn't in the last package) and because the prototype of the previous (dummy) sub is applied to the generated overload method.

**Comment by khwilliamson** [comment]
@iamb sorry for the delay; but I think we're ready to go ahead and test this.  I fixed the failing authors check, but I need you to rebase to blead, change the number of tests in 002-more.t to 33, and change the version in ParseXS.pm to 3.45.  Then the tests should restart, and hopefully pass, at which point I'll make sure this gets merged.

**Comment by iamb** [comment]
A delay is no problem; it's not a high priority if I'm the only one to complain. I appreciate you taking the time! :)

I think I correctly addressed bumping the version (I caught the other modules and added a Changelog entry, too). Hopefully all looks ok now. Let me know if there's anything more I can do.

**Comment by iamb** [comment]
ugh. i think i broke the authors test because i merged blead by pushing github buttons (which used a different email). i can rebase and force push or something to fix it, any other suggestions?

**Comment by khwilliamson** [comment]
On 3/5/22 09:44, Brad Barden wrote:
> ugh. i think i broke the authors test because i merged blead by pushing 
> github buttons (which used a different email). i can rebase and force 
> push or something to fix it, any other suggestions?

I added your extra email.  Just rebase from blead and push

**Comment by iamb** [comment]
apologies for the extra work, thanks for doing that.

**Comment by hvds** [comment]
@iamb note that what you've done is merge blead, not rebase over it.

I don't know whether or how that works with the github interface, but at the command-line that would involve:
```
% git checkout overload_fixes
Switched to branch 'overload_fixes'
Your branch is up to date with 'iamb/overload_fixes'.

# see where we're at
% git log -6 --oneline
052b3e3cc4 (HEAD -> overload_fixes, iamb/overload_fixes) Merge branch 'Perl:blead' into overload_fixes
61cf68d3b8 (origin/blead, origin/HEAD, blead) Add new email for Brad Barden
4c46f86af8 utf8.c: Fix typo in comment
b9b389c232 perl.c: Remove run time docs and redundant support for -DH
a977878db2 hv.c: ALWAYS perform in_collision check
803addad07 ExtUtils-ParseXS: bump version to 3.45

# fix it
% git rebase blead
First, rewinding head to replay your work on top of it...
Applying: ExtUtils::ParseXS: fix OVERLOAD/FALLBACK handling
Applying: ExtUtils::ParseXS: add OVERLOAD regression tests
Applying: ExtUtils-ParseXS: fix 002-more.t plan
Applying: ExtUtils-ParseXS: bump version to 3.45

# verify it
% git log -5 --oneline
fdfb844738 (HEAD -> overload_fixes) ExtUtils-ParseXS: bump version to 3.45
960520959f ExtUtils-ParseXS: fix 002-more.t plan
2a0688d60f ExtUtils::ParseXS: add OVERLOAD regression tests
ffb1d427d5 ExtUtils::ParseXS: fix OVERLOAD/FALLBACK handling
61cf68d3b8 (origin/blead, origin/HEAD, blead) Add new email for Brad Barden
% 
```

Alternatively the merger could do this before merging.

**Comment by iamb** [comment]
thanks for the tips. my failure was in assuming the github buttons would do a fast-forward, but apparently it insists on a merge commit. your suggestions are what i meant about rebasing and force-pushing (and i can still do to clean up the history if desired).

**Comment by iamb** [comment]
thanks for the merge! (and for putting up with my flawed understanding of git merging, i now see where i was wrong)

**Pull request merged**
