### PR TITLE
Eliminate build warnings with gcc 12

### LINKED ISSUE #20410: gcc-12 adds many more build-time warnings
On IRC today @khwilliamson  mentioned that he was seeing a surprising number of build-time warnings when compiling with gcc version 12.  (He stated that he normally compiles with g++.)  Last month, in https://github.com/Perl/perl5/issues/19776#issuecomment-1258084732, I noticed that there were large differences in the number of build-time warnings between different *sub-versions* of `gcc-12`, at least on FreeBSD.

Since I have upgraded my laptop to Ubuntu 22.04 LTS, I have more recent versions available.  I decided to install `gcc-12` and try it out.  On this version of Ubuntu, the *default* C-compiler is `gcc-11`.  Below are the results of building an unthreaded `perl` with these two different versions of `gcc` (as well as an earlier threaded build on FreeBSD).

**gcc-11**

```
$ gcc --version | head -1
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
```
*Linux*
```
$ report-build-warnings 8aca9cadef.linux.unthreaded.gcc-11.maketp.output.txt.gz 
File:  8aca9cadef.linux.unthreaded.gcc-11.maketp.output.txt.gz
[no output]
```

**gcc-12**
```
$ gcc-12 --version | head -1
gcc-12 (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
```
*Linux*
```
$ report-build-warnings 8aca9cadef.linux.unthreaded.gcc-12.maketp.output.txt.gz 
File:  8aca9cadef.linux.unthreaded.gcc-12.maketp.output.txt.gz

  Waddress                                  42
  Warray-bounds                              3
```
*FreeBSD*
```
$ report-build-warnings b93391659d.freebsd.threaded.gcc12.maketp.output.txt.gz
File:  b93391659d.freebsd.threaded.gcc12.maketp.output.txt.gz

  Waddress                                  42
  Warray-bounds                              3
```

Below is the breakdown of the new-on-gcc-12 build-time warnings on Linux:

**-Waddress**
```
File:  8aca9cadef.linux.unthreaded.gcc-12.maketp.output.txt.gz

[
  {
    char   => 9,
    group  => "Waddress",
    line   => 1640,
    source => "gv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 25,
    group  => "Waddress",
    line   => 1846,
    source => "gv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 26,
    group  => "Waddress",
    line   => 1860,
    source => "gv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 19,
    group  => "Waddress",
    line   => 3308,
    source => "gv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 9,
    group  => "Waddress",
    line   => 8112,
    source => "regcomp.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the pointer operand in \xE2\x80\x98old_re->sv_u.svu_pv + (sizetype)Perl_ReANY((const REGEXP *)old_re)->pre_prefix\xE2\x80\x99 must not be NULL",
  },
  {
    char   => 12,
    group  => "Waddress",
    line   => 1703,
    source => "dump.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 12,
    group  => "Waddress",
    line   => 1718,
    source => "dump.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 9,
    group  => "Waddress",
    line   => 5942,
    source => "util.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 23,
    group  => "Waddress",
    line   => 1861,
    source => "mg.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 15,
    group  => "Waddress",
    line   => 1873,
    source => "mg.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 28,
    group  => "Waddress",
    line   => 428,
    source => "mro_core.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 26,
    group  => "Waddress",
    line   => 790,
    source => "mro_core.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 39,
    group  => "Waddress",
    line   => 906,
    source => "mro_core.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 38,
    group  => "Waddress",
    line   => 1166,
    source => "mro_core.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 42,
    group  => "Waddress",
    line   => 1442,
    source => "hv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 18,
    group  => "Waddress",
    line   => 1451,
    source => "hv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 14,
    group  => "Waddress",
    line   => 1540,
    source => "hv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 44,
    group  => "Waddress",
    line   => 2193,
    source => "hv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 31,
    group  => "Waddress",
    line   => 2195,
    source => "hv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 41,
    group  => "Waddress",
    line   => 2246,
    source => "hv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 48,
    group  => "Waddress",
    line   => 3711,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 22,
    group  => "Waddress",
    line   => 3720,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 26,
    group  => "Waddress",
    line   => 3733,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 12,
    group  => "Waddress",
    line   => 3791,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 24,
    group  => "Waddress",
    line   => 3941,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 26,
    group  => "Waddress",
    line   => 3954,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 25,
    group  => "Waddress",
    line   => 4388,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 27,
    group  => "Waddress",
    line   => 6514,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 50,
    group  => "Waddress",
    line   => 6514,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 20,
    group  => "Waddress",
    line   => 6749,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 33,
    group  => "Waddress",
    line   => 10038,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 21,
    group  => "Waddress",
    line   => 10415,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 12,
    group  => "Waddress",
    line   => 10730,
    source => "sv.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 15,
    group  => "Waddress",
    line   => 946,
    source => "pp.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 33,
    group  => "Waddress",
    line   => 971,
    source => "pp.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 19,
    group  => "Waddress",
    line   => 434,
    source => "scope.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 20,
    group  => "Waddress",
    line   => 1201,
    source => "scope.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 41,
    group  => "Waddress",
    line   => 1316,
    source => "scope.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 14,
    group  => "Waddress",
    line   => 1351,
    source => "pp_sys.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 21,
    group  => "Waddress",
    line   => 70,
    source => "module3.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98bufptr\xE2\x80\x99 will never be NULL",
  },
  {
    char   => 9,
    group  => "Waddress",
    line   => 8112,
    source => "re_comp.c",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the pointer operand in \xE2\x80\x98*__builtin_memcpy(&<Uff30>, &({...})) + (sizetype)Perl_ReANY((const REGEXP *)old_re)->pre_prefix\xE2\x80\x99 must not be NULL",
  },
  {
    char   => 17,
    group  => "Waddress",
    line   => 4313,
    source => "APItest.xs",
    text   => "the comparison will always evaluate as \xE2\x80\x98true\xE2\x80\x99 for the address of \xE2\x80\x98hek_key\xE2\x80\x99 will never be NULL",
  },
]

```
**-Warray-bounds**
```
File:  8aca9cadef.linux.unthreaded.gcc-12.maketp.output.txt.gz

[
  {
    char   => 26,
    group  => "Warray-bounds",
    line   => 440,
    source => "hv.h",
    text   => "array subscript [0, 9223372036854775807] is outside array bounds of \xE2\x80\x98char[0]\xE2\x80\x99",
  },
  {
    char   => 26,
    group  => "Warray-bounds",
    line   => 440,
    source => "hv.h",
    text   => "array subscript [0, 9223372036854775807] is outside array bounds of \xE2\x80\x98char[0]\xE2\x80\x99",
  },
  {
    char   => 26,
    group  => "Warray-bounds",
    line   => 440,
    source => "hv.h",
    text   => "array subscript [0, 9223372036854775807] is outside array bounds of \xE2\x80\x98char[0]\xE2\x80\x99",
  },
]
```
So, `gcc-12` is emitting a lot more build-time warnings than `gcc-11` (and, for that matter, many more than `clang-14`).  We should address these warnings -- if only because newer versions are likely to add still more build-time warnings.

### PR DESCRIPTION
**Pull request by tonycoz**
Fixes #20410

### CODE REVIEW

**Review by demerphq — APPROVED** [review]

**Review by Leont — APPROVED** [review]

**Comment by jkeenan** [comment]
I've tested this p.r. on both Linux (Debian 11) and FreeBSD-12 using `gcc` version 12 as the C-compiler in each instance.  I am glad and grateful to report that this patch eliminates all 3 of the remaining `-Warray-bounds` build-time warnings and **all but 1** of the 40 `-Waddress` warnings.

There is **1** remaining `-Waddress` build-time warning:
```
File:  c5c0e9faa2.freebsd.threaded.gcc12.tonyc.maketp.output.txt.gz

[
  {
    char   => 21,
    group  => "Waddress",
    line   => 70,
    source => "module3.c",
    text   => "the comparison will always evaluate as 'true' for the address of 'bufptr' will never be NULL",
  },
]
```
In the output of `make test_prep` it looks like this:
```
./miniperl -Ilib make_ext.pl lib/auto/Devel/PPPort/PPPort.so  MAKE="make" LIBPERL_A=libperl.a LINKTYPE=dynamic
...

gcc-12 -c   -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings -O2   -DVERSION=\"3.69\" -DXS_VERSION=\"3.69\" -fPIC "-I../.."  -W -Wall module3.c
module3.c: In function ‘dummy_parser_warning’:
module3.c:70:21: warning: the comparison will always evaluate as ‘true’ for the address of ‘bufptr’ will never be NULL [-Waddress]
   70 |   return &PL_bufptr != NULL;
      |                     ^~
In file included from ../../perl.h:4464,
                 from module3.c:17:
../../parser.h:83:18: note: ‘bufptr’ declared here
   83 |     char        *bufptr;        /* carries the cursor (current parsing
      |                  ^~~~~~
rm -f ../../lib/auto/Devel/PPPort/PPPort.so
```
Here is what appears to be the relevant part of `dist/Devel-PPPort/module3.c`:
```
 62 int dummy_parser_warning(void)
 63 {
 64   char * volatile my_bufptr;
 65   char * volatile *my_p_bufptr;
 66   my_bufptr = PL_bufptr;
 67   my_p_bufptr = &PL_bufptr;
 68   PL_bufptr = my_bufptr;
 69   PL_bufptr = *my_p_bufptr;
 70   return &PL_bufptr != NULL;
 71 }
```
Would it be possible to eliminate this remaining build-time warning as well within this p.r.?

Thank you very much.
Jim Keenan

**Comment by demerphq** [comment]
On Thu, 17 Nov 2022 at 14:30, James E Keenan ***@***.***>
wrote:

> I've tested this p.r. on both Linux (Debian 11) and FreeBSD-12 using gcc
> version 12 as the C-compiler in each instance. I am glad and grateful to
> report that this patch eliminates all 3 of the remaining -Warray-bounds
> build-time warnings and *all but 1* of the 40 -Waddress warnings.
>
> There is *1* remaining -Waddress build-time warning:
>
> File:  c5c0e9faa2.freebsd.threaded.gcc12.tonyc.maketp.output.txt.gz
>
>
>
> [
>
>   {
>
>     char   => 21,
>
>     group  => "Waddress",
>
>     line   => 70,
>
>     source => "module3.c",
>
>     text   => "the comparison will always evaluate as 'true' for the address of 'bufptr' will never be NULL",
>
>   },
>
> ]
>
>
> In the output of make test_prep it looks like this:
>
> ./miniperl -Ilib make_ext.pl lib/auto/Devel/PPPort/PPPort.so  MAKE="make" LIBPERL_A=libperl.a LINKTYPE=dynamic
>
> ...
>
>
>
> gcc-12 -c   -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings -O2   -DVERSION=\"3.69\" -DXS_VERSION=\"3.69\" -fPIC "-I../.."  -W -Wall module3.c
>
> module3.c: In function ‘dummy_parser_warning’:
>
> module3.c:70:21: warning: the comparison will always evaluate as ‘true’ for the address of ‘bufptr’ will never be NULL [-Waddress]
>
>    70 |   return &PL_bufptr != NULL;
>
>       |                     ^~
>
> In file included from ../../perl.h:4464,
>
>                  from module3.c:17:
>
> ../../parser.h:83:18: note: ‘bufptr’ declared here
>
>    83 |     char        *bufptr;        /* carries the cursor (current parsing
>
>       |                  ^~~~~~
>
> rm -f ../../lib/auto/Devel/PPPort/PPPort.so
>
>
> Here is what appears to be the relevant part of
> dist/Devel-PPPort/module3.c:
>
>  62 int dummy_parser_warning(void)
>
>  63 {
>
>  64   char * volatile my_bufptr;
>
>  65   char * volatile *my_p_bufptr;
>
>  66   my_bufptr = PL_bufptr;
>
>  67   my_p_bufptr = &PL_bufptr;
>
>  68   PL_bufptr = my_bufptr;
>
>  69   PL_bufptr = *my_p_bufptr;
>
>  70   return &PL_bufptr != NULL;
>
>  71 }
>
>
> Would it be possible to eliminate this remaining build-time warning as
> well within this p.r.?
>
It looks to me like this code is deliberately designed to create a warning,
presumably for testing something.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by tonycoz** [comment]
> It looks to me like this code is deliberately designed to create a warning, presumably for testing something.

It's trying to generate a warning at the perl level, not during the build process.

I'll look at it.

**Comment by tonycoz** [comment]
> I'll look at it.

Fixed in the latest commit.

**Comment by jkeenan** [comment]
> > I'll look at it.
> 
> Fixed in the latest commit.

Thanks.  I'm now running with **0** build-time warnings when compiling with gcc version 12 on both Linux (unthreaded) and FreeBSD (threaded).  Let's merge.

**Comment by tonycoz** [comment]
Last push just makes the commit message a little less awful.

**Comment by tonycoz** [comment]
The commit message for the last commit included:
```
Some linter may still complain about it.
```
Coverity provides:
```
*** CID 376999:  Null pointer dereferences  (REVERSE_INULL)
/dist/Devel-PPPort/module3.c: 70 in dummy_parser_warning()
64       char * volatile my_bufptr;
65       char * volatile *my_p_bufptr;
66       my_bufptr = PL_bufptr;
67       my_p_bufptr = &PL_bufptr;
68       PL_bufptr = my_bufptr;
69       PL_bufptr = *my_p_bufptr;
>>>     CID 376999:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "my_p_bufptr" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
70       return my_p_bufptr != NULL;
```
I may split that into separate functions, in another PR.

**Comment by jkeenan** [comment]
> The commit message for the last commit included:
> 
> ```
> Some linter may still complain about it.
> ```
> 
> Coverity provides:
> 
> ```
> *** CID 376999:  Null pointer dereferences  (REVERSE_INULL)
> /dist/Devel-PPPort/module3.c: 70 in dummy_parser_warning()
> 64       char * volatile my_bufptr;
> 65       char * volatile *my_p_bufptr;
> 66       my_bufptr = PL_bufptr;
> 67       my_p_bufptr = &PL_bufptr;
> 68       PL_bufptr = my_bufptr;
> 69       PL_bufptr = *my_p_bufptr;
> >>>     CID 376999:  Null pointer dereferences  (REVERSE_INULL)
> >>>     Null-checking "my_p_bufptr" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
> 70       return my_p_bufptr != NULL;
> ```
> 
> I may split that into separate functions, in another PR.

Yes, I got that Coverity report as well.  A separate PR will be good.

**Pull request merged**
