### PR TITLE
regexp.h  apidoc was misspelled

### PR DESCRIPTION
**Pull request by khwilliamson**

### CODE REVIEW

**Review by jkeenan — APPROVED** [review]

**Comment by khwilliamson** [comment]
The more I look at this, I suspect that the misspelling was intentional, and that this is not intended to be documented at this time. @demerphq please clarify

**Review by demerphq — APPROVED** [review]
Lgtm, I don't think this was deliberate.

**Comment by jkeenan** [comment]
> The more I look at this, I suspect that the misspelling was intentional, and that this is not intended to be documented at this time. @demerphq please clarify

Here's the original commit:
```
ommit 1f6e74eb3536a13f38c1016477cd5b62dfe4e3da
Author:     Karl Williamson <khw@cpan.org>
AuthorDate: Sat Oct 17 07:26:56 2020 -0600
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Wed Dec 30 07:08:52 2020 -0700

    Document regexp, regmatch_info

diff --git a/regexp.h b/regexp.h
index cfb8d443ce..43a5168f74 100644
--- a/regexp.h
+++ b/regexp.h
@@ -97,6 +97,7 @@ struct reg_code_blocks {
 
 
 /*
+= for apidoc AyT||regexp
...
```

**Comment by khwilliamson** [comment]
Well, it looks like it was me who screwed up back then

**Pull request merged**
