### PR TITLE
Fix spelling: progam -> program

### PR DESCRIPTION
**Pull request by FGasper**

### CODE REVIEW

**Review by leonerd — APPROVED** [review]
LGTM

**Comment by leonerd** [comment]
Tests are unhappy though because you've not added yourself to the `AUTHORS` file.:

```
Felipe Gasper  <fgasper@users.noreply.github.com> not found in AUTHORS
```

**Comment by FGasper** [comment]
> Tests are unhappy though because you've not added yourself to the `AUTHORS` file.:
> 
> ```
> Felipe Gasper  <fgasper@users.noreply.github.com> not found in AUTHORS
> ```

Hrm … I’m there, though …
```
Felipe Gasper                  <felipe@felipegasper.com>
```

**Comment by leonerd** [comment]
Apparently the tests are looking for a different address: `<fgasper@users.noreply.github.com>`

**Comment by FGasper** [comment]
Ah. Probably because this PR is from GitHub itself, not my workstation. I’ll see about it.

**Comment by Grinnz** [comment]
You should be able to update .mailmap to recognize the other address

**Comment by FGasper** [comment]
Hrm, still failing despite my having added myself to the .mailmap …

**Comment by leonerd** [comment]
This seems to be an awful lot of work for a single-character typo change in some docs.

Would you like me to just do it and cite you as author in the commit message? ;)

**Comment by FGasper** [comment]
@leonerd Yes, please. :)

**Comment by leonerd** [comment]
Done in 440416fb0a

**Pull request closed without merging**
