### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by gtataranni**
small typo in the docs

### CODE REVIEW

**Comment by karenetheridge** [comment]
This is a file used by a cpan-first dual-life distribution (presumably in its tests), so it should be patched in its respective repository -- **HOWEVER**, it is just a copy of a file that actually does live in core, so could you patch that instead?  It is pod/perlfunc.pod. Thanks!

**Comment by tonycoz** [comment]
The `cpan/Pod-Perldoc/corpus/perlfunc.pod` change isn't really needed (and should be submitted upstream), with that included the PR can't be merged as is.

**Comment by Grinnz** [comment]
That change is undone by the second commit, it just needs to be squashed.

**Comment by tonycoz** [comment]
Thanks, I squashed these and applied it as 54525b93d52a52326368ccf8a330d5b2d1e56089.

**Pull request closed without merging**
