### PR TITLE
⚠️ IGNORE: Remove duplicate [GOTO: PR 21059]

### PR DESCRIPTION
**Pull request by rwp0**
▶️  GO TO: https://github.com/Perl/perl5/pull/21059

⚠️ **And ignore this PR**

### CODE REVIEW

**Comment by jkeenan** [comment]
1. Changes to cpan/Compress-Raw-Zlib/zlib-src/zlib.have to be submitted upstream on CPAN.
2. You have two porting test failures; can you fix and re-push?

**Comment by rwp0** [comment]
> 1. Changes to cpan/Compress-Raw-Zlib/zlib-src/zlib.have to be submitted upstream on CPAN.

Thanks, I've amended my commit to revert the `zlib.h` case.

Created a separate PR for that purpose.

> 2. You have two porting test failures; can you fix and re-push?

Unfortunately no, not alone by myself at least 🙁

**Comment by jkeenan** [comment]
> > 1. Changes to cpan/Compress-Raw-Zlib/zlib-src/zlib.have to be submitted upstream on CPAN.
> 
> Thanks, I've amended my commit to revert the `zlib.h` case.
> 
> Created a separate PR for that purpose:
> 
>     * [[doc] zlib.h: Remove duplicate "the" pmqs/Compress-Raw-Zlib#22](https://github.com/pmqs/Compress-Raw-Zlib/pull/22)
> 

Moving that change out of the pull request magically cleared up one of your porting test failures.  You had omitted incrementing `$VERSION` in a `.pm`file, which caused the failure in `t/porting/cmp_version.t`.

> 
> > 2. You have two porting test failures; can you fix and re-push?
> 
> Unfortunately no, not alone by myself at least 

Well, figuring out how to deal with these failures is a useful skill for a regular committer.  You would do well to run `make test_porting` on your local machine before pushing a pull request.  But let's look at the failure output at https://github.com/Perl/perl5/actions/runs/4840634578/jobs/8626407229?pr=21057.  You have 3 separate failures but all within one single test file, `t/porting/regen.t`.  Two of those failures mention `regen/mk_invlists.pl`, which is also noted to require being run with the `perl` you've just built.  So try running:
```
./perl -Ilib/regen/mk_invlists.pl
```
Examine files which have changed, run `make test_porting` again to see what has been fixed and what hasn't.  Commit as needed.

The remaining test failure also involves generated code.  Note the error output and look through the `regen/` directory to spot a program that might clear that up.  Then, examine files which have changed, etc.

**Comment by jkeenan** [comment]
@rjbs, assuming the content of this p.r. is approved and we get all the porting tests to PASS, is it okay to push this p.r. to blead (given code freeze)?

**Comment by rwp0** [comment]
### Running `./perl -Ilib ./regen/mk_invlist.pl` fixed the two failing tests below

```
porting/regen.t ........... 1/44 # Failed test 6 - generated charclass_invlists.h is up to date at porting/regen.t line 122
#      got "regen/mk_invlists.pl"
# expected ""
# Note: regen/mk_invlists.pl must be run manually, because it needs the Perl you've just built
```

```
# Failed test 7 - generated uni_keywords.h is up to date at porting/regen.t line 122
#      got "regen/mk_invlists.pl"
# expected ""
```

### Output
    Changed: charclass_invlists.h lib/unicore/uni_keywords.pl uni_keywords.h


---

### And running `./perl -Ilib ./regen/uconfig_h.pl` fixed the third failing test in `regen.t`:

```
# Failed test 8 - generated uconfig.h is up to date at porting/regen.t line 122
#      got "config_h.SH"
# expected ""
```

### Output
     Extracting uconfig.h-new (with variable substitutions)
     Changed: uconfig.h

---

### Thanks to GitHub Codespaces all tests PASS now

pass

---

## Next

Will try to amend my commit to include these changes.

**Pull request closed without merging**
