### PR TITLE
Simplify copyright years

### PR DESCRIPTION
**Pull request by rwp0**
PR originally submitted by @Yahasana in #19163

This change seems to be *appropriate* as was stated in the comment below:

https://github.com/Perl/perl5/pull/19163#issuecomment-1065839753

### CODE REVIEW

**Comment by demerphq** [comment]
So I take it you want to supersede #19163 with this?  ON the assumption this is yes, then I have the following question/comment:

@codesections @StuartJMackintosh - i think there is a related question that should be resolved before we change this. We have year based boiler plate in many of our files. Does that boiler plate have to reflect the history of the file itself? Can it be omitted and referenced back to the README? I don't think we should change one of our files without having a clear and common policy across all our files.

**Comment by rwp0** [comment]
> So I take it you want to supersede #19163 with this? ON the assumption this is yes, then I have the following question/comment:
> 
> @codesections @StuartJMackintosh - i think there is a related question that should be resolved before we change this. We have year based boiler plate in many of our files. Does that boiler plate have to reflect the history of the file itself? Can it be omitted and referenced back to the README? I don't think we should change one of our files without having a clear and common policy across all our files.

Yes. The main reason is that the `README` is special, being a main user-facing file that most visitors see first on this GitHub repository, and it looks really ugly with listing each individual year instead of simply using a year range with a dash as is commonly done in many other projects worldwide for good.

**Comment by demerphq** [comment]
@rwp0 this PR has conflicts. Will you resolve them?

**Comment by rwp0** [comment]
Resolved through the GitHub web interface.

It created two commits now, is squeezing them required here?

**Comment by demerphq** [comment]
@rwp0 better to resolve them on a command line and force push them as a single patch please.

**Comment by rwp0** [comment]
> force

Okay, will try.

**Comment by rwp0** [comment]
> error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.

Getting the above error when cloning my `Perl/perl5` fork repository.

Will look at this later then.

BTW the repository always takes a very long time to clone (and many times unsuccessfully, probably due to heavy size), any suggestion to accelerate that with `git clone`?

Tried two times today, one with IDE, one with the CLI, and both failed

---

Anyway, it was a very simple change.

To prevent further delaying on this I'm creating another PR through the interface linking this one to that :-)

**Pull request closed without merging**
