### PR TITLE
Update PSC after 2024 elections

### PR DESCRIPTION
**Pull request by atoomic**

### CODE REVIEW

**Comment by jkeenan** [comment]
@atoomic, could you run Porting/updateAUTHORS.pl to clear the porting test failure?  Thanks.

**Comment by tonycoz** [comment]
Still broken:
```
porting/bincompat.t ....... ok
#   Failed test 'Is mailmap_file '.mailmap' up to date?'
#   at Porting/updateAUTHORS.pl line 126.
#   File '.mailmap' changes:
#     would add: Nicolas R <atoomic@cpan.org> Nicolas R. <atoomic@cpan.org>
# 
# Files need updating! You probably just need to run
# 
#    Porting/updateAUTHORS.pl
# 
# and commit the results.
# Looks like you failed 1 test of 5.
porting/authors.t ......... 
Dubious, test returned 1 (wstat 256, 0x100)
```

The existing entries are
```
Nicolas R <atoomic@cpan.org> Nicolas R <cpan@atoomic.org>
Nicolas R <atoomic@cpan.org> Nicolas R <nicolas@atoomic.org>
Nicolas R <atoomic@cpan.org> Nicolas R. <@atoomic>
Nicolas R <atoomic@cpan.org> ℕicolas ℝ <nicolas@atoomic.org>
Nicolas R <atoomic@cpan.org> ☢ ℕicolas ℝ <nicolas@atoomic.org>
```
none of which quite match.

**Comment by jkeenan** [comment]
> Still broken:
> 
> ```
> porting/bincompat.t ....... ok
> #   Failed test 'Is mailmap_file '.mailmap' up to date?'
> #   at Porting/updateAUTHORS.pl line 126.
> #   File '.mailmap' changes:
> #     would add: Nicolas R <atoomic@cpan.org> Nicolas R. <atoomic@cpan.org>
> # 
> # Files need updating! You probably just need to run
> # 
> #    Porting/updateAUTHORS.pl
> # 
> # and commit the results.
> # Looks like you failed 1 test of 5.
> porting/authors.t ......... 
> Dubious, test returned 1 (wstat 256, 0x100)
> ```
> 
> The existing entries are
> 
> ```
> Nicolas R <atoomic@cpan.org> Nicolas R <cpan@atoomic.org>
> Nicolas R <atoomic@cpan.org> Nicolas R <nicolas@atoomic.org>
> Nicolas R <atoomic@cpan.org> Nicolas R. <@atoomic>
> Nicolas R <atoomic@cpan.org> ℕicolas ℝ <nicolas@atoomic.org>
> Nicolas R <atoomic@cpan.org> ☢ ℕicolas ℝ <nicolas@atoomic.org>
> ```
> 
> none of which quite match.

@tonycoz @atoomic, After an hour of struggling with Porting/updateAUTHORS.pl, I think I've got this.  I'll push.

**Comment by jkeenan** [comment]
Handled manually in c43f2fd16a6517cc5028fffb8e6e474df98faf52.  Will close ticket once CI tests pass.

**Comment by atoomic** [comment]
Thanks @jkeenan

**Pull request closed without merging**
