### PR TITLE
utf8.h: fixup signed/unsigned warning from UTF8_IS_REPLACEMENT

### PR DESCRIPTION
**Pull request by demerphq**
Added a SSize_t cast to the sizeof() call.

### CODE REVIEW

**Comment by jkeenan** [comment]
> Added a SSize_t cast to the sizeof() call.

Can you provide an example of the warning which this p.r. eliminates?

Thank you very much.
Jim Keenan

**Comment by demerphq** [comment]
Sure, it's from APItest.xs:

```
In file included from APItest.xs:10:0:
APItest.xs: In function ‘XS_XS__APItest_test_UTF8_IS_REPLACEMENT’:
../../utf8.h:921:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     UNLIKELY(   ((send) - (s)) >= (sizeof(REPLACEMENT_CHARACTER_UTF8) - 1)  \
                                ^
../../perl.h:3790:62: note: in definition of macro ‘EXPECT’
 #  define EXPECT(expr,val)                  __builtin_expect(expr,val)
                                                              ^~~~
../../perl.h:3811:52: note: in expansion of macro ‘cBOOL’
 #define UNLIKELY(cond)                      EXPECT(cBOOL(cond),FALSE)
                                                    ^~~~~
../../utf8.h:921:5: note: in expansion of macro ‘UNLIKELY’
     UNLIKELY(   ((send) - (s)) >= (sizeof(REPLACEMENT_CHARACTER_UTF8) - 1)  \
     ^~~~~~~~
APItest.xs:6206:18: note: in expansion of macro ‘UTF8_IS_REPLACEMENT’
         RETVAL = UTF8_IS_REPLACEMENT(s, s + len);
```

**Comment by jkeenan** [comment]
On 3/3/22 08:31, Yves Orton wrote:
> Sure, it's from APItest.xs:
> 
> |In file included from APItest.xs:10:0: APItest.xs: In function 
> ‘XS_XS__APItest_test_UTF8_IS_REPLACEMENT’: ../../utf8.h:921:32: warning: 
> comparison between signed and unsigned integer expressions 
> [-Wsign-compare] UNLIKELY( ((send) - (s)) >= 
> (sizeof(REPLACEMENT_CHARACTER_UTF8) - 1) \ ^ ../../perl.h:3790:62: note: 
> in definition of macro ‘EXPECT’ # define EXPECT(expr,val) 
> __builtin_expect(expr,val) ^~~~ ../../perl.h:3811:52: note: in expansion 
> of macro ‘cBOOL’ #define UNLIKELY(cond) EXPECT(cBOOL(cond),FALSE) ^~~~~ 
> ../../utf8.h:921:5: note: in expansion of macro ‘UNLIKELY’ UNLIKELY( 
> ((send) - (s)) >= (sizeof(REPLACEMENT_CHARACTER_UTF8) - 1) \ ^~~~~~~~ 
> APItest.xs:6206:18: note: in expansion of macro ‘UTF8_IS_REPLACEMENT’ 
> RETVAL = UTF8_IS_REPLACEMENT(s, s + len); |
> 

And (I should have asked in previous post), which C-compiler and version 
were you running when this appeared?  (I would like to compare it with 
other open build-time warnings tickets.)

**Comment by demerphq** [comment]
```
$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jkeenan** [comment]
> ```
> $ gcc --version
> gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Thanks.  I see now that this warning only appeared with a commit made two days ago, which is why I had not previously encountered it.  Confirmed the warning's presence with clang10 and confirmed branch eliminates it.  Merged in 3c9bbd85c9.

**Comment by demerphq** [comment]
Er, the ticket says there are unmerged commits?

**Comment by demerphq** [comment]
Did you merge and push this directly to blead without using the github API maybe?

**Comment by jkeenan** [comment]
> Did you merge and push this directly to blead without using the github API maybe?

Yes, I did not use the github API.  For most of the commits I handle, I do verification at the command-line.  Usually, but not always, this entails rebasing a branch on blead, testing the branch at least through `make test_porting`, merging into blead, confirming that the change had the intended effect (in this case, eliminating the build-time warning), running full test suite.  I believe that this affords one greater control than the buttons in the GUI, whose functioning has changed over time.

**Comment by demerphq** [comment]
On Thu, 3 Mar 2022 at 15:59, James E Keenan ***@***.***>
wrote:

> Did you merge and push this directly to blead without using the github API
> maybe?
>
> Yes, I did not use the github API. For most of the commits I handle, I do
> verification at the command-line. Usually, but not always, this entails
> rebasing a branch on blead, testing the branch at least through make
> test_porting, merging into blead, confirming that the change had the
> intended effect (in this case, eliminating the build-time warning), running
> full test suite. I believe that this affords one greater control than the
> buttons in the GUI, whose functioning has changed over time.
>
That is fine. Just push a delete of the branch then afterwards please.
Otherwise github gets confused and says there are unmerged commits. And
then I get confused and have to do extra work to understand what happened.
At least for my branches please. :-)

Yves

**Comment by wollmers** [comment]
> And (I should have asked in previous post), which C-compiler and version were you running when this appeared? (I would like to compare it with other open build-time warnings tickets.)

That's not compiler-specific, it is C-specific. clang also warns [-Wsign-compare] if signed types are used in context with unsigned ones. E.g. in C type `char` is signed and needs casting to unsigned if used as a natural number.

**Comment by demerphq** [comment]
On Fri, 4 Mar 2022, 01:54 Helmut Wollmersdorfer, ***@***.***>
wrote:

> And (I should have asked in previous post), which C-compiler and version
> were you running when this appeared? (I would like to compare it with other
> open build-time warnings tickets.)
>
> That's not compiler-specific, it is C-specific. clang also warns
> [-Wsign-compare] if signed types are used in context with unsigned ones.
> E.g. in C type char is signed and needs casting to unsigned if used as a
> natural number.
>

In this case it was pointer subtraction which produces a signed result. But
same deal, it is defined as a signed result.

I think James was just speaking generally tho, some warnings are compiler
specific. Let's not nitpick him huh, he performs an essential role for our
community.

Cheers,
Yves

>

**Pull request closed without merging**
