### PR TITLE
Update version from CPAN to 0.9929

### PR DESCRIPTION
**Pull request by toddr**
[DELTA]

0.9929
  * Upgrade to ppport 3.62
  * Import fix for core build warning

### CODE REVIEW

**Comment by jkeenan** [comment]
@Toddr, could you rebase and remove merge conflicts?

@Leont and/or @tonycoz and/or anyone else:  Can we get a review of this synch-with-cpan?

Thank you very much.
Jim Keenan

**Comment by toddr** [comment]
rebasing now.

**Comment by toddr** [comment]
@Leont I'd really appreciate your review on this pls.

**Comment by Leont** [comment]
The customizations are no longer necessary:
```patch
leont@leon-desktop:~/Code/perl$ git diff
diff --git Porting/Maintainers.pl Porting/Maintainers.pl
index 3cbaf8cf94..a079697cf1 100755
--- Porting/Maintainers.pl
+++ Porting/Maintainers.pl
@@ -1261,16 +1261,6 @@ use File::Glob qw(:case);
             'vperl/vpp.pm',
         ],
 
-        # When adding the CPAN-distributed files for version.pm, it is necessary
-        # to delete an entire block out of lib/version.pm, since that code is
-        # only necessary with the CPAN release.
-        'CUSTOMIZED'   => [
-            qw( lib/version.pm
-                vutil.c
-                vxs.inc
-                ),
-        ],
-
         'MAP' => {
             'vutil/'         => '',
             ''               => 'cpan/version/',
diff --git t/porting/customized.dat t/porting/customized.dat
index 2b8db23e37..f772abe86b 100644
--- t/porting/customized.dat
+++ t/porting/customized.dat
@@ -21,6 +21,3 @@ Pod::Perldoc cpan/Pod-Perldoc/lib/Pod/Perldoc.pm 582be34c077c9ff44d99914724a0cc2
 Test::Harness cpan/Test-Harness/t/source.t aaa3939591114c0c52ecd44159218336d1f762b9
 Win32API::File cpan/Win32API-File/File.pm 8fd212857f821cb26648878b96e57f13bf21b99e
 Win32API::File cpan/Win32API-File/File.xs beb870fed4490d2faa547b4a8576b8d64d1d27c5
-version cpan/version/lib/version.pm a963b513cf812bd7f4d28b3422efd9904e70a34c
-version vutil.c 1fc71f632e905d65e1b24afbd36f1ebda894ef02
-version vxs.inc d23e4fac6211d3b35b367e80ef23b8ab5fa9d0eb
```

**Comment by toddr** [comment]
ok. reverted these 2 in the amended commit

	modified:   Porting/Maintainers.pl
	modified:   t/porting/customized.dat

**Comment by Leont** [comment]
> ok. reverted these 2 in the amended commit

I think the change to customized.dat didn't make it?

**Review by Leont — APPROVED** [review]

**Pull request merged**
