### PR TITLE
Add missing word in 'if's documentation

### PR DESCRIPTION
**Pull request by skirmess**

### CODE REVIEW

**Comment by Grinnz** [comment]
"one or more modules" would be a more idiomatic phrase

**Comment by Grinnz** [comment]
Also this section really needs to updated with current recommendations, but that's for another PR.

**Comment by skirmess** [comment]
Thanks, updated. I tried to search if "one or multiple" or "one or more" is better but couldn't find an explanation when to use which.

**Comment by Grinnz** [comment]
"one or more" is a phrase which easily represents a count of items. "one or multiple" is presenting two more separate options: one item, or multiple items.

**Pull request merged**
