### PR TITLE
Prepare Module::Corelist for 5.35.7

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
This pull request aims to fix porting tests (`t/porting/corelist.t`)

### CODE REVIEW

**Comment by richardleach** [comment]
Thanks, I hadn't had chance to do this since BinGOs released to cpan.

**Comment by thibaultduponchelle** [comment]
The authors.t tests does not like "Keep my email addresses private" setting from GitHub. Will try to close and reopen this PR

**Comment by richardleach** [comment]
It's okay, I can update Module::Corelist myself. No need to open another PR.

**Comment by thibaultduponchelle** [comment]
OK 😃

**Pull request closed without merging**
