### PR TITLE
S_bool_setlocale_2008_i, S_querylocale_2008_i: Add entry assertions

### PR DESCRIPTION
**Pull request by khwilliamson**

### CODE REVIEW

**Comment by tonycoz** [comment]
Are these necessarily true in an embedded perl? See #21366 for example.

**Comment by jkeenan** [comment]
> Are these necessarily true in an embedded perl? See #21366 for example.

@khwilliamson, can you comment on @tonycoz's concerns here with respect to an embedded perl?

**Comment by khwilliamson** [comment]
I believe they are true in embedded perl.  I need to go through the code and change a bunch of things that say `#ifdef THREADS` to instead be `ifdef MULTIPLICITY`.  Just now I ran a branch with these enabled on OpenBSD, and they caught the bug (in libc I'm pretty sure).

**Comment by jkeenan** [comment]
> I believe they are true in embedded perl. I need to go through the code and change a bunch of things that say `#ifdef THREADS` to instead be `ifdef MULTIPLICITY`. Just now I ran a branch with these enabled on OpenBSD, and they caught the bug (in libc I'm pretty sure).

@khwilliamson there hasn't been any activity on this pull request in 8 months.  Do you intend to move forward with it?  Thanks.

**Comment by khwilliamson** [comment]
I'm confident these assertions are true, and have helped me find bugs in branches I've smoked that included them.  I believe this branch should be merged

**Pull request merged**
