### PR TITLE
autodoc: Fixup signature arglist indentation

### PR DESCRIPTION
**Pull request by khwilliamson**
Somehow this got removed from eabcc813bd321e2c9973f985fa28ab67657e78e2. It affects only a few edge cases.  For example, before this, perlapi had these lines,
```
_void_______sv_vcatpvfn___________(SV_*_const_sv,
_______________________________________const_char_*_const_pat,
_______________________________________const_STRLEN_patlen,
```
 where the first argument to the function  was misaligned with the
 others.  This patch produces instead:
```
_void_______sv_vcatpvfn___________(____SV_*_const_sv,
_______________________________________const_char_*_const_pat,
_______________________________________const_STRLEN_patlen,
```

### CODE REVIEW

**Comment by jkeenan** [comment]
> Somehow this got removed from [eabcc81](https://github.com/Perl/perl5/commit/eabcc813bd321e2c9973f985fa28ab67657e78e2). It affects only a few edge cases. For example, before this, perlapi had these lines,
> 
> void sv_vcatpvfn (SV * const sv, const char * const pat, const STRLEN patlen, ...
> 
> where the first argument to the function was misaligned with the others. This patch produces instead:
> 
> void sv_vcatpvfn ( SV * const sv, const char * const pat, const STRLEN patlen, ...

I don't quite get the point you're making.  Does your code sample above need backticks to render as code in the GH GUI?

**Comment by khwilliamson** [comment]
When I look at it in my browser, it looks properly spaced and has 4 backticks surrounding each example

**Comment by tonycoz** [comment]
The examples look formatted to me, and looking at the source shows the proper sequences of 3 backticks around each example.

**Comment by tonycoz** [comment]
Is this meant to make the argument after `pTHX_` line up generally?

It seems incosistent:
```
void  Perl_sv_vcatpvf_mg         (pTHX_ SV * const sv,
                                         const char * const pat,
                                         va_list * const args)
```
which is fine, but:
```
 void  Perl_sv_vcatpvfn           (pTHX_ SV * const sv,
                                       const char * const pat,
                                       const STRLEN patlen,
                                       va_list * const args,
                                       SV ** const svargs,
                                       const Size_t sv_count,
                                       bool * const maybe_tainted)
```
is mis-aligned.

**Comment by khwilliamson** [comment]
It looked fine on my browser.  What I did now was edit it to replace blanks by underscores.  It still looks fine on mine, but now maybe it will look ok on yours

**Comment by mauke** [comment]
Sorry for the confusion. When you first posted your PR, all whitespace was collapsed (as per the usual Markdown rendering rules). The reason it looks better now is that I edited the PR description shortly after James replied. The source code had retained the spaces, so all I had to do was insert some triple backticks around the code blocks.

I thought my editing would notify the participants of this PR, but apparently not. I didn't mean to gaslight anyone.

**Comment by khwilliamson** [comment]
@mauke, I appreciate your trying to clean up my mess on your own.  It is concerning that github didn't show this had been edited.  I went looking for that when the weirdness was pointed out, but the backticks were there, so I assumed it was me who put them in from the start

**Review by jkeenan — APPROVED** [review]

**Comment by tonycoz** [comment]
```
 void  Perl_sv_vcatpvfn           (pTHX_ SV * const sv,
                                       const char * const pat,
                                       const STRLEN patlen,
                                       va_list * const args,
                                       SV ** const svargs,
                                       const Size_t sv_count,
                                       bool * const maybe_tainted)
```
was still a problem.

**Comment by khwilliamson** [comment]
> was still a problem.

This is working according to how I designed it.  What is happening in this example is that the final line `bool * const maybe_tainted)` would extend too far to the right if it started in the column after the `pTHX_`, so that it could wrap onto the beginning of the next line if the window contains just 80 columns.   What made the most sense to me was to move the entire block of arguments to the left by the minimum amount necessary to ensure that it doesn't wrap in a window that is at least 80 columns wide.  But what to do with the first argument after the `pTHX_`.  The other alternative is to make the whole thing look like

```
void  Perl_sv_vcatpvfn           (pTHX_ 
                                       SV * const sv,
                                       const char * const pat,
                                       const STRLEN patlen,
                                       va_list * const args,
                                       SV ** const svargs,
                                       const Size_t sv_count,
                                       bool * const maybe_tainted)
```
That has the advantage that the block all lines up, but the disadvantage of taking up extra vertical space.  In eyeballing some of the lines in `perlapi` that have this issue, I thought that the way it currently works looked ok.  But it is easy to change it.

**Comment by tonycoz** [comment]
I'm fine with it as it is.

Reformatting to:
```
void  Perl_sv_vcatpvfn(
    pTHX_ 
    SV * const sv,
    const char * const pat,
    const STRLEN patlen,
    va_list * const args,
    SV ** const svargs,
    const Size_t sv_count,
    bool * const maybe_tainted)
```
or similar would avoid the extensive indentation these declarations get.

**Pull request merged**
