### PR TITLE
cpan/Archive-Tar - Update to version 3.02

### PR DESCRIPTION
**Pull request by haarg**
3.02  13/04/2023 (Manfred Stock)
- Test block sizes up to (2**31 - 1) bytes only (fix for 32bit perls)
- Don't match on message from exception in symlink test
- Improve formatting of $Archive::Tar::RESOLVE_SYMLINK documentation

### CODE REVIEW

**Comment by jkeenan** [comment]
Have the problems discussed in https://github.com/Perl/perl5/issues/21402 been addressed?  So far those have discouraged us from synching this version of Archive-Tar into blead.

**Comment by jkeenan** [comment]
> Have the problems discussed in #21402 been addressed? So far those have discouraged us from synching this version of Archive-Tar into blead.

Apparently not.  CI tests on Windows are failing.

**Comment by rwp0** [comment]
This if completed fixes https://github.com/Perl/perl5/issues/21402

May add this wording in the PR description to link those two properly together

**Comment by haarg** [comment]
I'm going to close this for now. Either Archive::Tar needs to be updated, and we'll pull that in, or we'll need to bring Archive::Tar in with a patch. I'm not going to address that right now.

**Pull request closed without merging**
