### PR TITLE
Change various search.cpan.org references to metacpan.org and www.cpan.org

### PR DESCRIPTION
**Pull request by Grinnz**
Updated links in pod and some other references. Link to illguts (https://search.cpan.org/dist/illguts/) not changed because there isn't a good way to link directly to it on metacpan.

### CODE REVIEW

**Comment by jkeenan** [comment]
When I ran this through `make test_porting`, I got this failure:
```
$ cd t;./perl harness porting/customized.t; cd -
porting/customized.t .. 1/? # Failed test 7 - SHA for pod/perlfilter.pod matches stashed SHA at porting/customized.t line 112
#      got "2d98239c4f4a930ad165444c3879629bb91f4cef"
# expected "e9833bf4ebc51087dfee5c553e0f8a5eef67212d"
porting/customized.t .. Failed 1/31 subtests 

Test Summary Report
-------------------
porting/customized.t (Wstat: 0 Tests: 31 Failed: 1)
  Failed test:  7
Files=1, Tests=31,  0 wallclock secs ( 0.01 usr  0.01 sys +  0.04 cusr  0.00 csys =  0.06 CPU)
Result: FAIL
```
Can you investigate?

Thank you very much.
Jim Keenan

**Comment by Grinnz** [comment]
I assume this is because of the change to perlfilter.pod? Is there a way I should fix it, should I just shasum the new file?

**Comment by tonycoz** [comment]
> 
> 
> I assume this is because of the change to perlfilter.pod? Is there a way I should fix it, should I just shasum the new file?

`pod/perlfilter.pod` is maintained upstream in `RURBAN/Filter`, but you're not the first one to modify it without sending the changes upstream.

You can regenerate the hashes with:
````
./perl t/porting/customized.t -regen
````

**Comment by Grinnz** [comment]
I removed the change to perlfilter.pod - I can send it upstream.

**Pull request merged**
