### PR TITLE
win32/Makefiles: don't try to be clever with modification times

### LINKED ISSUE #21680: Can't make on Windows except from scratch
**Description**

When I compile blead with GNUmakefile or plain Makefile on Windows, and then touch a .c file, and try to recompile, it fails.    I have to clean the workspace and compile everything again to get it to work.

**Steps to Reproduce**

````
nmake
touch locale.c
nmake
````
**Expected behavior**

Both nmake's should succeed

**Perl configuration**

```
Summary of my perl5 (revision 5 version 39 subversion 6) configuration:
  Derived from: a7001ebae51d9bdedb2a354e73c96f1ac96e0243
  Ancestor: 2ccb6d6c1681fe8c22580f92efee594927d81430
  Platform:
    osname=MSWin32
    osvers=10.0.22621.2715
    archname=MSWin32-x64-multi-thread
    uname=''
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cl'
    ccflags ='-nologo -GF -W3 -MD -DWIN32 -D_CONSOLE -DNO_STRICT -DDEBUGGING -DWIN64 -D_CRT_SECURE_NO_DEPRECATE  -D_CRT_NONSTDC_NO_DEPRECATE -D_WINSOCK_DEPRECATED_NO_WARNINGS  -DPERL_TEXTMODE_SCRIPTS -DMULTIPLICITY -DPERL_IMPLICIT_SYS'
    optimize='-Od -Zi -fp:precise'
    cppflags='-DWIN32'
    ccversion='19.34.31933'
    gccversion=''
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=undef
    longlongsize=8
    d_longdbl=define
    longdblsize=8
    longdblkind=0
    ivtype='__int64'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='__int64'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='link'
    ldflags ='-nologo -nodefaultlib -debug  -libpath:"c:\perl\lib\CORE"  -machine:AMD64 -subsystem:console,"5.02"'
    libpth="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\\lib\x64"
    libs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib vcruntime.lib ucrt.lib
    perllibs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib vcruntime.lib ucrt.lib
    libc=ucrt.lib
    so=dll
    useshrplib=true
    libperl=perl539.lib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-dll -nologo -nodefaultlib -debug  -libpath:"c:\perl\lib\CORE"  -machine:AMD64 -subsystem:console,"5.02"'


Characteristics of this binary (from libperl):
  Compile-time options:
    DEBUGGING
    HAS_LONG_DOUBLE
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_THREAD_SAFE_LOCALE
  Locally applied patches:
    uncommitted-changes
    585dd37fdbcf7103800de44c664256dc790aa9cc
    99feed1b17d97ca4082a3e005cb46b9de75ae1f5
    df1df930526fb129eff14a02a4bb83903a4de92d
    56d3b7262b38efa4a0f529345583a0fb8fb9817d
    a7001ebae51d9bdedb2a354e73c96f1ac96e0243
  Built under MSWin32
  Compiled at Nov 29 2023 17:28:03
  %ENV:
    PERL5OPT="-w"
    PERL_DIFF_TOOL="wgdiff"
    PERL_POD_PEDANTIC="1"
    PERL_TEST_HARNESS_ASAP="1"
  @INC:
    C:/Users/khw/perl/env_msvc/lib





````

### PR DESCRIPTION
**Pull request by tonycoz**
When I re-worked this I tried to reduce the amount of rebuilding needed in some cases, but this has caused other problems, so simplify.

Fixes #21680

### CODE REVIEW

**Comment by sisyphus** [comment]
> Fixes https://github.com/Perl/perl5/issues/21680

Yes - fixes it for me, too.

**Comment by khwilliamson** [comment]
I probably won't have a chance to check this out, but if it works for @sisyphus , it sounds good to me

**Comment by khwilliamson** [comment]
Actually, I did test this, and found one issue, at least.  It appears that some dependencies aren't getting found.  If I touch perl.h, it rebuilds many objects, as you would expect.  But I happened to just change locale_table.h, and no C files at all were recompiled.  I wonder what other hdrs are somehow not having their dependencies properly built

**Comment by tonycoz** [comment]
> Actually, I did test this, and found one issue, at least. It appears that some dependencies aren't getting found. If I touch perl.h, it rebuilds many objects, as you would expect. But I happened to just change locale_table.h, and no C files at all were recompiled. I wonder what other hdrs are somehow not having their dependencies properly built

There's no dependency scan (`make depend`) on Windows, the dependencies on header files is done by making all objects depend on all headers:
```
# We can't have miniperl.exe depend on git_version.h, as miniperl creates it
$(MINI_OBJ)	: $(MINIDIR)\.exists $(CORE_NOCFG_H)

$(WIN32_OBJ)	: $(CORE_H)

$(CORE_OBJ)	: $(CORE_H)

$(DLL_OBJ)	: $(CORE_H)
```
and `CORE_NOCFG_H` (used in the `CORE_H` definition) doesn't include `locale_table.h`.

**Pull request merged**
