### PR TITLE
Eliminate uninitialized value warnings when running ./TEST -deparse

### PR DESCRIPTION
**Pull request by jkeenan**

### CODE REVIEW

**Comment by jkeenan** [comment]
Running tests through deparsing (`cd t; ./TEST -deparse; cd -`) generates a lot of output on STDERR which we hope will be useful in improving the code base.  Some of this output, however, only refers to B::Deparse itself.  Let's pick some low-hanging fruit.

**Comment by tonycoz** [comment]
Do you have example test filenames that produce these warnings?

I'm worried this will mask undefined value warnings that are caused by a bug in some caller that should be providing a defined value.

**Comment by jkeenan** [comment]
> Do you have example test filenames that produce these warnings?
> 
> I'm worried this will mask undefined value warnings that are caused by a bug in some caller that should be providing a defined value.

I ran `./TEST -deparse` on recent commit 2c387e63ae:
```
commit 2c387e63aed4fdb32777f74fdbac6ec6a8e6683b
Merge: e2b4c63579 e4a5f110e6
Author:     Graham Knop <haarg@haarg.org>
AuthorDate: Thu Aug 8 10:33:57 2024
Commit:     Graham Knop <haarg@haarg.org>
CommitDate: Thu Aug 8 10:33:57 2024
```
Filtering the output:
```
$ zgrep -C2 uninitialized 2c387e63ae.TEST-deparse.output.txt.gz
t/re/opt ......................................................... ok
t/re/overload .................................................... Argument "^" isn't numeric in subroutine entry at ../lib/B.pm line 126.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Argument "$" isn't numeric in subroutine entry at ../lib/B.pm line 126.
Argument "^" isn't numeric in subroutine entry at ../lib/B.pm line 126.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Argument "$" isn't numeric in subroutine entry at ../lib/B.pm line 126.
Undefined subroutine &main::CODE(0x582e50892bd8) called at re/overload.t line 170.
--
t/re/speed_thr ................................................... skipped
t/re/stclass_threads ............................................. skipped
t/re/subst ....................................................... Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Invalid [] range "@-\c_" in regex; marked by <-- HERE in m/[\c\@-\c_ <-- HERE ]/ at re/subst.t line 642.
skipped
t/re/substT ...................................................... ok
t/re/subst_amp ................................................... Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
ok
t/re/subst_wamp .................................................. ok
--
t/op/hash-clear-placeholders ..................................... ok
t/op/hash-rt85026 ................................................ ok
t/op/hash ........................................................ Use of uninitialized value $cx in numeric lt (<) at ../lib/B/Deparse.pm line 1511.
Use of uninitialized value $cx in numeric eq (==) at ../lib/B/Deparse.pm line 1511.
ok
t/op/hashassign .................................................. Use of uninitialized value $cx in numeric lt (<) at ../lib/B/Deparse.pm line 1511.
Use of uninitialized value $cx in numeric eq (==) at ../lib/B/Deparse.pm line 1511.
ok
t/op/hashwarn .................................................... ok
--
t/op/override .................................................... # Failed test 7 - at op/override.t line 46
skipped
t/op/pack ........................................................ Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
# Failed test 38 - at op/pack.t line 217
#      got ''
--
t/op/stat_errors ................................................. ok
t/op/state ....................................................... ok
t/op/study ....................................................... Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in substitution (s///) at ../lib/B/Deparse.pm line 6158.
Use of uninitialized value $first in concatenation (.) or string at ../lib/B/Deparse.pm line 6162.
Warning: Use of "scalar" without parentheses is ambiguous at op/study.t line 27.
Warning: Use of "scalar" without parentheses is ambiguous at op/study.t line 44.
```

**Comment by jkeenan** [comment]
Withdrawn in favor of GH #22505

**Pull request closed without merging**
