### PR TITLE
Apple have started to apply -Werror by default breaking lots of XS modules

### PR DESCRIPTION
**Pull request by DrHyde**
This is the same as https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/commit/a07d951129587be9c6246e967afc754f4b0cbd68, translated for ExtUtils::CBuilder.

In XCode 12, Apple made implicit function declaration a fatal compile-time error by default. This turns that off. Something similar might also be appropriate to go into `hints/darwin.sh`.

### CODE REVIEW

**Comment by haarg** [comment]
Note that they aren't applying `-Werror`, they are specifically applying `-Werror=implicit-function-declaration`.

See [Xcode 12 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes) > Apple Clang Compiler > Resolved

**Comment by toddr** [comment]
@DrHyde You need to bump the $VERSION on `dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/darwin.pm` so the extended CI test suite can run.

```
# not ok 127 - dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/darwin.pm version 0.280234 so 
```

**Comment by Leont** [comment]
> @DrHyde You need to bump the $VERSION on `dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/darwin.pm` so the extended CI test suite can run.

And presumably everything else in `dist/ExtUtils-CBuilder/lib`, as versions within a dist are generally synchronized.

**Comment by DrHyde** [comment]
Fixed the module versions

**Comment by apparluk** [comment]
macOS -Werror=implicit-function-declaration (breaking lots of XS modules)

Xcode 12 Release Notes does not specify the clang version.

```
# Xcode 12.0 (12A7209)
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
```

**Comment by ambs** [comment]
I am releasing ExtUtils-CBuilder-0.280235 today to CPAN. Will give a few days for cpan testers to give it a spin.
If it works, I will update this patch to include other file changes (like CHANGES).

**Comment by ambs** [comment]
https://github.com/Perl-Toolchain-Gang/ExtUtils-CBuilder/commit/067d75adb44691e970bcdb39aaa250b115dd26aa

**Comment by khwilliamson** [comment]
Is this ready to merge?

**Comment by jkeenan** [comment]
In the original post to this Issue, @DrHyde wrote, _"Something similar might also be appropriate to go into `hints/darwin.sh`."_  Since that file is not touched in this pull request, have we determined that it does not need to be modified?

Thank you very much.
Jim Keenan

**Comment by DrHyde** [comment]
That was purely speculation on my part

**Comment by jkeenan** [comment]
> Is this ready to merge?

I think this p.r. is moot and can be closed.  @ambs released ExtUtils-CBuilder-0.280235 to CPAN on Nov 01.  That was somewhat non-standard.  This distro is housed under `dist/` which suggests that it is "blead-upstream" and should have been merged into `blead` before being released to CPAN.

However, @bingos synched blead with CPAN on Nov 14.  So that would mean we no longer mean this p.r. -- correct?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > Is this ready to merge?
> 
> I think this p.r. is moot and can be closed. @ambs released ExtUtils-CBuilder-0.280235 to CPAN on Nov 01. That was somewhat non-standard. This distro is housed under `dist/` which suggests that it is "blead-upstream" and should have been merged into `blead` before being released to CPAN.
> 
> However, @bingos synched blead with CPAN on Nov 14. So that would mean we no longer mean this p.r. -- correct?
> 

I've confirmed that the relevant content of this p.r. is already in blead, so I'm closing it.

**Comment by ambs** [comment]
Hi

Usually I release to CPAN and submit the PR to blead.
This time, however, we wanted to have people running the module before merging with blead.
After a couple weeks I were to submit the PR, but it was already there.

So, sorry for all the confusion.
Thank you
ambs

Alberto Simões

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request closed without merging**
