### PR TITLE
INSTALL: clarify usethreads/useithreads

### PR DESCRIPTION
**Pull request by sevan**
Add a description that they mean the same thing, in case one wondered if there was a difference (perl shipped with system is configured with useithreads, packaging system defines usethreads).

### CODE REVIEW

**Review by tonycoz — APPROVED** [review]
It might be worth adding "currently", but I don't think this is ever going to change realistically.

**Comment by sevan** [comment]
Done.

**Comment by jkeenan** [comment]
@tonycoz, @sevan took your suggestion, but I reworded the doc slightly for better flow.  Pushed as 2a2fbe60b3.

**Comment by matthewpersico** [comment]
Shouldn't "perl" be "Perl" at https://github.com/Perl/perl5/commit/2a2fbe60b3ca61da41a701fa082a961d493bc218#diff-b83b327f0b62e8168163c61f15fb0ac2c14169729e4f4184678337a15cd04decL332 ?

**Pull request closed without merging**
