### PR TITLE
Add a .github/README.md

### PR DESCRIPTION
**Pull request by bram-perl**
This is based on the existing README and is an almost exact copy.
Some minor formatting changes to improve the rendering but the text
remains the same.

t/porting/copyright.t was also adjusted to check the copyright in
.github/README.md

Note: this can be considered a (very) minor first step in adding a more
      informative README for Github. This first step is needed because
      not having a formatted README is blocking some other changes (rendering
      the platform specific READMEs as POD in GitHub).

### CODE REVIEW

**Comment by demerphq** [comment]
I would love to see this done by a script, with a test that when the read README is updated that we know the .md version has too.

**Comment by demerphq** [comment]
Also we have tools to check this stuff in the regen/ tree. It feels to me like that would be a good fit, it already has a mechanism to hash the input files to determine if the output files need to be changed, and if we updated the .md files on make regen it wouldnt be a bad thing.

**Comment by bram-perl** [comment]
> I would love to see this done by a script, with a test that when the read README is updated that we know the .md version has too.

Short answer: No.

Long answer:
The README file isn't really changing; the only thing that changes in it is the copyright year and there is a test to cover that.
Eventually I would also like the .github/README.md to be much more informative and much more relevant for people viewing the repo on GitHub, if you compare the perl5 repo with other repo's then it clear that the current thing is not very user-friendly/doesn't offer a lot of relevant information. (See #18965 for some examples)
So in the long run I expect that README and .github/README.md will differ since they serve a different purpose.
The README file is not suitable for that since that's what included in the releases and that file shouldn't change. For including it in a release the current README is good enough, for showing it on GitHub it - in my opinion - isn't.

**Comment by demerphq** [comment]
On Sat, 3 Sept 2022 at 10:24, Bram ***@***.***> wrote:

> I would love to see this done by a script, with a test that when the read
> README is updated that we know the .md version has too.
>
> Short answer: No.
>
> Long answer:
> The README file isn't really changing; the only thing that changes in it
> is the copyright year and there is a test to cover that.
> Eventually I would also like the .github/README.md to be much more
> informative and much more relevant for people viewing the repo on GitHub,
> if you compare the perl5 repo with other repo's then it clear that the
> current thing is not very user-friendly/doesn't offer a lot of relevant
> information. (See #18965 <https://github.com/Perl/perl5/issues/18965> for
> some examples)
> So in the long run I expect that README and .github/README.md will differ
> since they serve a different purpose.
> The README file is not suitable for that since that's what included in the
> releases and that file shouldn't change. For including it in a release the
> current README is good enough, for showing it on GitHub it - in my opinion
> - isn't.
>

I think if you put this explanation in the commit message it would be
helpful to future people who encounter this should you somehow get diverted
in reaching the conclusion of your plan, which I support.  So if you put a
curated version of this paragraph in the commit and I'd be happy to merge
it for you.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Review by demerphq — APPROVED** [review]

**Comment by rwp0** [comment]
Excellent, it was long awaited, although I'd like the titles (headings) not to be all uppercase.

I had a similar PR: https://github.com/Perl/perl5/pull/19099

Also, having `README.pod` instead would have been better I think (we could do that in the future).

Markdown is good, but we already have POD, so why not using that if GitHub supports rendering POD as good as Markdown?

**Comment by Grinnz** [comment]
I think using pod format would be a good idea particularly so we can add documentation links to it easily in the future. Otherwise I think this is great.

**Pull request merged**
