### PR TITLE
RMG: Add step for deprecation/experimental resolution

### PR DESCRIPTION
**Pull request by khwilliamson**
At the beginning of the development cycle, the project should look ahead at what to do about experimental/deprecated features.  Some are coming due this cycle, so email should be sent to p5p to lower the possibility of their falling through the cracks

### CODE REVIEW

**Review by Mikevin — COMMENTED** [review]
@rjbs
@leonerd
@neilb 
@p5p
Pretty please

**Comment by neilb** [comment]
@khwilliamson you should probably drop me as a reviewer, and add @book

**Comment by jkeenan** [comment]
> At the beginning of the development cycle, the project should look ahead at what to do about experimental/deprecated features. Some are coming due this cycle, so email should be sent to p5p to lower the possibility of their falling through the cracks

Reviewers (esp. PSC members):  this pull request is recommending a change in our development procedures.  Can you review?

Thank you very much.
Jim Keenan

**Review by leonerd — APPROVED** [review]
LGTM

**Review by rjbs — APPROVED** [review]
Looks good, sorry it took so long!

**Pull request merged**
