### PR TITLE
pod: fields.pm corrections

### PR DESCRIPTION
**Pull request by myrrhlin**
correct some confusing word order, clearly was intended to
be 'as ... fast as'

also, 'fewer' elements rather than 'less'

---------------------------------------------------------------------------------
* This set of changes does not require a perldelta entry.

### CODE REVIEW

**Comment by Grinnz** [comment]
LGTM, you will likely need to bump the $VERSION to 2.26 at the top of the file

**Review by jkeenan — APPROVED** [review]

**Comment by myrrhlin** [comment]
I updated the `$VERSION` as suggested.  Thanks @Grinnz

**Comment by jkeenan** [comment]
@myrrhlin, could you run `perl Porting/updateAUTHORS.pl` so as to add your name and email address to our `AUTHORS` file?  Then, run `make test_porting` to get a PASS before re-pushing.  Thanks.

**Comment by myrrhlin** [comment]
done, and thanks for your guidance @jkeenan !

**Pull request merged**
