### PR TITLE
sv.c - add BODYLESS_IV/NV fast code to sv_setXv functions

### PR DESCRIPTION
**Pull request by richardleach**
For "BODYLESS" IVs and NVs, type up/downgrades can be easily done
without having to call `sv_upgrade`. (Which will also not convert a
BODYLESS_NV back down to an IV, even when it is harmless to do so.)

This commit adds "BODYLESS" handling to `sv_setiv` and `sv_setnv`, which
previously lacked it, and "BODYLESS_NV" handling to `sv_setsv_flags`,
which previously only special-cased "BODYLESS_IV"s.

### CODE REVIEW

**Review by demerphq — APPROVED** [review]

**Comment by richardleach** [comment]
Before I merge this, anyone got any thoughts on how doing BODYLESS_NVs in `Perl_sv_setsv_flags` requires preservation of `SVs_TEMP`, but the BODYLESS_IV code doesn't give a hoot? 

Is it just because coincidentally we have a test for a temp SV that gets assigned an NV and not an equivalent for IVs?

And should the new code in `Perl_sv_setiv` & `Perl_sv_setnv` be made to preserve `SVs_TEMP`?

**Comment by richardleach** [comment]
I looked again and think the BODYLESS_IV code in `Perl_sv_setsv_flags` _should_ do `SvOK_off`, rather than clearing **all** the existing flags. I'll modify this PR so that happens.

`Perl_sv_setiv` & `Perl_sv_setnv` are fine as-is.

**Comment by richardleach** [comment]
I've done the above - make `sv_setsv_flags` preserve flags like `SVs_TEMP` in the fast cases. @demerphq  - do you want another look over before I merge?

For posterity, what breaks in the BODYLESS_NV case if `SVs_TEMP` is not preserved:
```
            /* If SVs_TEMP is not preserved, t/lib/warnings/util has a
             * failure because of:
             *    perl: op.c:4915: OP *S_fold_constants(OP *const):
             *        Assertion `SvIMMORTAL(sv)' failed.
```
(I haven't traced through to find out what SV(s) result in that failure.)

**Comment by richardleach** [comment]
@demerphq - do you want a final re-look through this before I merge?

**Comment by demerphq** [comment]
On Sat, 17 Sept 2022, 23:16 Richard Leach, ***@***.***> wrote:

> @demerphq <https://github.com/demerphq> - do you want a final re-look
> through this before I merge?
>

Looks ok to me at the eyeball level, but I can't test till Thursday.  I'm
fine if you merge it without waiting.

Yves

>

**Comment by richardleach** [comment]
Unless anyone has objections, I'd like to merge this before the next dev release in just over a week's time.

**Comment by richardleach** [comment]
No further comments received on this one since Yves said it looked okay, so am merging.

**Comment by demerphq** [comment]
Thanks Richard!

**Pull request merged**
