### PR TITLE
porting/libperl.t: handle nm output on Mac OS Ventura 13.4

### LINKED ISSUE #21117: libperl.t failure on Darwin (macOS Ventura 13.4)
**Description**
libperl.t fails on current macOS with blead.  It appears to have a problem processing the output of nm.

**Steps to Reproduce**
```
$ cd t
$ ./perl -I../lib porting/libperl.t
# $^O = darwin
# $Config{archname} = darwin-2level
# $Config{cc} = cc
# libperl = ../libperl.a
# nm = /usr/bin/nm
# nm_style = darwin
# nm_opt = -m
# command: "/usr/bin/nm -m ../libperl.a 2>libperl17966 |"
porting/libperl.t: undefined current object: op.o: at porting/libperl.t line 254, <$nm_fh> line 2.
```

I have also attached the output of

```
$ /usr/bin/nm -m ../libperl.a > libperl.log 2>&1
```

**Expected behavior**
a passing test

**Perl configuration**

```
$ ./perl -Ilib -V
Summary of my perl5 (revision 5 version 37 subversion 12) config
[libperl.log](https://github.com/Perl/perl5/files/11549616/libperl.log)
uration:
  Commit id: 6a541b132cdeadcf0f93ab599ef5c4600e33c5fe
  Platform:
    osname=darwin
    osvers=22.5.0
    archname=darwin-2level
    uname='darwin triamond.local 22.5.0 darwin kernel version 22.5.0: mon apr 24 20:51:50 pdt 2023; root:xnu-8796.121.2~5release_x86_64 x86_64 '
    config_args='-Dusedevel -des'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=13.4 -DNO_POSIX_2008_LOCALE -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    optimize='-O3'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=13.4 -DNO_POSIX_2008_LOCALE -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='Apple LLVM 14.0.3 (clang-1403.0.22.14.1)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=13.4 -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.3/lib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /usr/lib
    libs=-lgdbm
    perllibs=
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=13.4 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under darwin
  Compiled at May 23 2023 17:39:06
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.37.12/darwin-2level
    /usr/local/lib/perl5/site_perl/5.37.12
    /usr/local/lib/perl5/5.37.12/darwin-2level
    /usr/local/lib/perl5/5.37.12
    /usr/local/lib/perl5/site_perl
```
[libperl.log](https://github.com/Perl/perl5/files/11549625/libperl.log)

### PR DESCRIPTION
**Pull request by tonycoz**
Fixes #21117

### CODE REVIEW

**Review by Leont — APPROVED** [review]

**Comment by craigberry** [comment]
This does get the test passing on Ventura.  However, it creates a lot of extra output that looks like:

```
$ ./perl -I../lib porting/libperl.t
# $^O = darwin
# $Config{archname} = darwin-2level
# $Config{cc} = cc
# libperl = ../libperl.a
# nm = /usr/bin/nm
# nm_style = darwin
# nm_opt = -m
# command: "/usr/bin/nm -m ../libperl.a 2>libperl21428 |"
# Unknown type: 0000000000001df0 (__TEXT,__text) private external _Perl_alloc_LOGOP (op.o)
# Unknown type: 0000000000000aa0 (__TEXT,__text) private external _Perl_allocmy (op.o)
# Unknown type: 0000000000007540 (__TEXT,__text) private external _Perl_bind_match (op.o)
. . .
```

So I think it is not getting into the branch the skips various things.  Not sure if that's new, and not necessarily a reason not to merge this, but I thought I'd pass it along.

**Comment by craigberry** [comment]
I can confirm that on macOS Ventura the second commit clears up the extra chattiness I'd noted earlier.

**Comment by rjbs** [comment]
Thanks.  I'll probably leave v5.38.0 RC as is for now, but we should apply this (or something like it) to v5.39!

Also, maint-5.36…

**Comment by kcaran** [comment]
Hi. I just compiled v5.36.1 on my M2 Ventura 13.4 and got the same test failure. The patch fixed the issue without any noise. Thanks, Tony!

**Comment by tonycoz** [comment]
> Also, maint-5.36…

Added to the voting file.

**Comment by dkechag** [comment]
Was tackling this when I saw there's a patch, it works for my M1 Pro MacOS Ventura, would be nice to add to 5.36.

**Pull request merged**
