### PR TITLE
File::Spec::{Unix,OS2}->path(): Keep trailing empty PATH elements

### LINKED ISSUE #22346: Bug: File::Spec->path() doesn't keep trailing empty elements
Module: File::Spec

**Description**

Tested on Linux, but likely an issue on other platforms as well.
File::Spec->path() accidentally trims trailing empty elements in `$PATH` due to it's use of `split()` without a `LIMIT`.

**Steps to Reproduce**

```shell
> export PATH=/some/path/: # Note trailing colon
> /usr/bin/perl -e 'require File::Spec; print join(":", File::Spec->path());'
/some/path

> export PATH=:::/some/path/:::: # Leading colons are kept
> /usr/bin/perl -e 'require File::Spec; print join(":", File::Spec->path());'
.:.:.:/usr/bin/

> export PATH=: # This should be the same as '.'
> /usr/bin/perl -e 'require File::Spec; print join(":", File::Spec->path());'

> export PATH=:::::: # Technically all trailing
> /usr/bin/perl -e 'require File::Spec; print join(":", File::Spec->path());'

```

**Expected behavior**

File::Spec->path() should include trailing empty elements.

<details>
<summary>Perl configuration</summary>

```
Summary of my perl5 (revision 5 version 38 subversion 2) configuration:
   
  Platform:
    osname=linux
    osvers=5.12.15-arch1-1
    archname=x86_64-linux-thread-multi
    uname='archlinux'
    config_args='-des -Dusethreads -Duseshrplib -Doptimize=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/perl/src=/usr/src/debug/perl -flto=auto -Dprefix=/usr -Dvendorprefix=/usr -Dprivlib=/usr/share/perl5/core_perl -Darchlib=/usr/lib/perl5/5.38/core_perl -Dsitelib=/usr/share/perl5/site_perl -Dsitearch=/usr/lib/perl5/5.38/site_perl -Dvendorlib=/usr/share/perl5/vendor_perl -Dvendorarch=/usr/lib/perl5/5.38/vendor_perl -Dscriptdir=/usr/bin/core_perl -Dsitescript=/usr/bin/site_perl -Dvendorscript=/usr/bin/vendor_perl -Dinc_version_list=none -Dman1ext=1perl -Dman3ext=3perl -Dlddlflags=-shared -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -flto=auto -Dldflags=-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -flto=auto -Dloclibpth=/usr/lib/db5.3 -Dlocincpth=/usr/include/db5.3'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/include/db5.3 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/perl/src=/usr/src/debug/perl -flto=auto'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/include/db5.3'
    ccversion=''
    gccversion='13.2.1 20230801'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags ='-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs -flto=auto -fstack-protector-strong -L/usr/lib/db5.3'
    libpth=/usr/local/lib /usr/lib /usr/lib/db5.3
    libs=-lpthread -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib/libc.so.6
    so=so
    useshrplib=true
    libperl=libperl.so
    gnulibc_version='2.39'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib/perl5/5.38/core_perl/CORE'
    cccdlflags='-fPIC'
    lddlflags='-shared -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs -flto=auto -L/usr/lib/db5.3 -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Feb 11 2024 19:15:41
  @INC:
    /usr/lib/perl5/5.38/site_perl
    /usr/share/perl5/site_perl
    /usr/lib/perl5/5.38/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib/perl5/5.38/core_perl
    /usr/share/perl5/core_perl
```

</details>

### PR DESCRIPTION
**Pull request by aarondill**
Fixes #22346 by ensuring that trailing PATH elements are maintained *on
Unix and OS2*

### CODE REVIEW

**Comment by aarondill** [comment]
I've amended the commits to ensure all `$VERSION` values match (https://github.com/Perl/perl5/issues/22346#issuecomment-2227173799)

**Comment by jkeenan** [comment]
> I've amended the commits to ensure all `$VERSION` values match ([#22346 (comment)](https://github.com/Perl/perl5/issues/22346#issuecomment-2227173799))

This looks good to me, but I'd like to see https://github.com/Perl/perl5/pull/22404 merged in first.

**Comment by jkeenan** [comment]
> > I've amended the commits to ensure all `$VERSION` values match ([#22346 (comment)](https://github.com/Perl/perl5/issues/22346#issuecomment-2227173799))
> 
> This looks good to me, but I'd like to see #22404 merged in first.

GH #22404 has been merged in to blead.  That caused GitHub to append a `hasConflicts` label to this p.r.  I attempted to resolve it via the web editor, only for GH now to tell me "This branch cannot be rebased due to conflicts."

I think I'll let the GH CI testing proceed before taking further action.  In the meantime, if there is anyone else who wants to look over this pull request, please do so. Thanks.

**Comment by jkeenan** [comment]
> > > I've amended the commits to ensure all `$VERSION` values match ([#22346 (comment)](https://github.com/Perl/perl5/issues/22346#issuecomment-2227173799))
> > 
> > 
> > This looks good to me, but I'd like to see #22404 merged in first.
> 
> GH #22404 has been merged in to blead. That caused GitHub to append a `hasConflicts` label to this p.r. I attempted to resolve it via the web editor, only for GH now to tell me "This branch cannot be rebased due to conflicts."
> 
> I think I'll let the GH CI testing proceed before taking further action. In the meantime, if there is anyone else who wants to look over this pull request, please do so. Thanks.

@tonycoz or @book, can either of you look at the code changes being requested here and approve?  At that point, I'll deal with the merge problems.  Thanks.

**Comment by aarondill** [comment]
I'll rebase onto `bleed` and force push. that should be the simplest way to resolve the conflicts.

**Comment by aarondill** [comment]
@jkeenan I've rebased onto `bleed` and resolved the conflicts. This should keep the commit history and diff cleaner :smile:

**Review by jkeenan — APPROVED** [review]

**Comment by jkeenan** [comment]
> @jkeenan I've rebased onto `bleed` and resolved the conflicts. This should keep the commit history and diff cleaner 😄

Thanks for that legwork.  I've approved this commit and self-assigned.  I'll allow for 2 or 3 days for other committers to approve, and then proceed to merge unless there's an objection.

**Review by tonycoz — APPROVED** [review]

**Pull request merged**
