### PR TITLE
Make more use of the various RETURN macros

### PR DESCRIPTION
**Pull request by JRaspass**
We have them to reduce boilerplate, may as well use them.

### CODE REVIEW

**Comment by demerphq** [comment]
@iabyn what would you prefer with patches like this? Would you prefer we hold off until the stack refcounting stuff is merged or does this kind of thing help you?

@JRaspass in theory LGTM but I want to make sure it's not going to cause unnecessary extra work for @iabyn .

**Review by rwp0 — APPROVED** [review]

**Comment by iabyn** [comment]
On Wed, Feb 22, 2023 at 02:56:18PM -0800, Yves Orton wrote:
> @iabyn what would you prefer with patches like this? Would you prefer we hold off until the stack refcounting stuff is merged or does this kind of thing help you?
> 
> @JRaspass in theory LGTM but I want to make sure it's not going to cause unnecessary extra work for @iabyn .

I very much do not want this patch to be applied, sorry!

Eventually core PP code will not be using PUSH/RETURN macros of any
variety, and this patch is likely to conflict with any work I've done so
far on my RC branch.  (But it may be helpful as a guide to me to spot
things that can be converted to the new reference-counted regime more
efficiently.)

-- 
Technology is dominated by two types of people: those who understand what
they do not manage, and those who manage what they do not understand.

**Comment by demerphq** [comment]
@JRaspass sorry mate, I'm going to close this.

**Comment by JRaspass** [comment]
No worries, makes sense.

**Pull request closed without merging**
