### PR TITLE
File-Find: Replace bareword filehandle with a lexical scalar

### PR DESCRIPTION
**Pull request by xsawyerx**
Bareword filehandles are bad and this module should really remove this one.

### CODE REVIEW

**Review by jkeenan — APPROVED** [review]

**Review by Leont — APPROVED** [review]

**Comment by shlomif** [comment]
@xsawyerx : I suggest moving `my $dh;` closer to the opendir calls: [predeclarations](https://perl-begin.org/tutorials/bad-elements/#declaring_all_vars_at_top)

**Comment by xsawyerx** [comment]
[Edited: Removed a crappy part of my response because I was annoyed. Sorry.]

> @xsawyerx : I suggest moving `my $dh;` closer to the opendir calls: [predeclarations](https://perl-begin.org/tutorials/bad-elements/#declaring_all_vars_at_top)

That's what I did originally. I decided to then stick with the pattern in which this code was written, which included all variable declarations at the top of the function.

**Comment by xsawyerx** [comment]
I've force-pushed a commit that includes the `$dh` variable defined below, prior to being used.

Considering the comment and 2 thumbs up (last I checked), I am complying by making this change. I still think the violation of the coding style of the existing code (where all lexicals are defined together at the beginning of the functions) is the wrong thing to do.

**Comment by Grinnz** [comment]
Not that I have a strong opinion but for the sake of explaining my reaction: I think improving the code style is more important than being consistent with the bad code style in this particular case.

**Comment by khwilliamson** [comment]
On 12/28/21 11:28, Dan Book wrote:
> Not that I have a strong opinion but for the sake of explaining my 
> reaction: I think improving the code style is more important than being 
> consistent with the bad code style in this particular case.
> 
I am mixed about this.  Making a change shouldn't open a can of worms 
about modernizing tangential things.  And by moving it would confuse 
newbies with an inconsistency.

Another option is to leave it where it was, but add a comment that this 
style is no longer recommended

**Comment by xsawyerx** [comment]
> Not that I have a strong opinion but for the sake of explaining my reaction: I think improving the code style is more important than being consistent with the bad code style in this particular case.

Thank you for explaining. I understand and I do think there's logic to this, certainly.

I believe another commit that cleans up some of the code could be useful, but as it stands, this single change creates a situation in which almost all lexicals are defined in one location except *one*. Since that is far less consistent with either direction (one being lexicals defined where used and the other being all defined at once), I think it creates greater cognitive effort this way.

This is why I think a single change for this one particular case is not an improvement on the style, but instead splinters a consistent style (even if I think it's worse) for a single variable.

Of course, I yield to the thumbs up since this is not a hill worth any lives. :) I also appreciate the quick responses and didn't want to then drop the ball on my side.

**Comment by xsawyerx** [comment]
> On 12/28/21 11:28, Dan Book wrote: Not that I have a strong opinion but for the sake of explaining my reaction: I think improving the code style is more important than being consistent with the bad code style in this particular case.
> I am mixed about this. Making a change shouldn't open a can of worms about modernizing tangential things. And by moving it would confuse newbies with an inconsistency.

Agreed on both accounts.

> Another option is to leave it where it was, but add a comment that this style is no longer recommended

Do you mean a comment in the code itself saying "please don't use the style of this code when writing other code"? I don't follow.

**Comment by khwilliamson** [comment]
On 12/28/21 12:08, Sawyer X wrote:
>     On 12/28/21 11:28, Dan Book wrote: Not that I have a strong opinion
>     but for the sake of explaining my reaction: I think improving the
>     code style is more important than being consistent with the bad code
>     style in this particular case.
>     I am mixed about this. Making a change shouldn't open a can of worms
>     about modernizing tangential things. And by moving it would confuse
>     newbies with an inconsistency.
> 
> Agreed on both accounts.
> 
>     Another option is to leave it where it was, but add a comment that
>     this style is no longer recommended
> 
> Do you mean a comment in the code itself saying "please don't use the 
> style of this code when writing other code"? I don't follow.

I indeed meant "please don't use the style of this code when writing 
other code"

And I thre this out as an option; not a recommendation

**Comment by jkeenan** [comment]
Pushed to blead in commit b838a0e335.  Further discussion of best ways to present code samples in documentation can be conducted on list or in a separate pull request.

Thank you very much.
Jim Keenan

**Pull request closed without merging**
