### PR TITLE
Minor optype neatenings

### PR DESCRIPTION
**Pull request by leonerd**
A few miscellaneous fixings of small details, ahead of some larger work that I intend to do to tidy up the way some of these op types work.

### CODE REVIEW

**Comment by leonerd** [comment]
I have some larger things to work on that are depending on this to be merged first.
If there are no objections I shall merge it on Wednesday.

**Comment by jkeenan** [comment]
> I have some larger things to work on that are depending on this to be merged first. If there are no objections I shall merge it on Wednesday.

Do you know/suspect if there are any important CPAN distros that might be affected by these changes?

**Review by bram-perl — APPROVED** [review]
For commit 'Define the remaining convenience cMETHOP* macros' :  one thing *I* would do is include the list of the added methods in the commit message (and with what they match, basically the list of added `#define` but a bit more readable)

**Comment by leonerd** [comment]
> Do you know/suspect if there are any important CPAN distros that might be affected by these changes?

None of this should be visible to CPAN modules at all. It's minor adjustments of deep internals; no interface-visible changes.

**Pull request merged**
