### PR TITLE
perldelta - change pod markup for non-core modules

### PR DESCRIPTION
**Pull request by richardleach**

### CODE REVIEW

**Comment by haarg** [comment]
This seems wrong. I don't see a problem with including links outside core. And when viewed on a site like metacpan, these links are definitely valuable.

**Comment by jkeenan** [comment]
> _ No description provided. _

@richardleach, this is the second time recently that you have issued a pull request and then merged it into blead without getting a single comment or review.

Can you explain why you think you have the right to do this?

I believe you are abusing your commit but.  Please revert this commit ASAP.

Thank you very much.
Jim Keenan

**Comment by hvds** [comment]
> > _ No description provided. _
> 
> @richardleach, this is the second time recently that you have issued a pull request and then merged it into blead without getting a single comment or review.
> 
> Can you explain why you think you have the right to do this?
> 
> I believe you are abusing your commit but. Please revert this commit ASAP.

I think that's putting it a bit strongly: this was intended as a correction to his own perldelta entry committed a few hours earlier, and a request had gone out to update perldelta as soon as possible.

(I don't know what the other recent pull request was - was it the original perldelta entry?)

In this case at least there's no harm done beyond a bit of churn in the commit history.

**Comment by demerphq** [comment]
On Tue, 20 Sept 2022, 05:25 Hugo van der Sanden, ***@***.***>
wrote:

> _ No description provided. _
>
> @richardleach <https://github.com/richardleach>, this is the second time
> recently that you have issued a pull request and then merged it into blead
> without getting a single comment or review.
>
> Can you explain why you think you have the right to do this?
>
> I believe you are abusing your commit but. Please revert this commit ASAP.
>
> I think that's putting it a bit strongly: this was intended as a
> correction to his own perldelta entry committed a few hours earlier, and a
> request had gone out to update perldelta as soon as possible.
>
> (I don't know what the other recent pull request was - was it the original
> perldelta entry?)
>
> In this case at least there's no harm done beyond a bit of churn in the
> commit history.
>

Fwiw, agreed.

Yves

>

**Comment by jkeenan** [comment]
On 9/20/22 00:25, Hugo van der Sanden wrote:
>         _ No description provided. _
> 
>     @richardleach <https://github.com/richardleach>, this is the second
>     time recently that you have issued a pull request and then merged it
>     into blead without getting a single comment or review.
> 
>     Can you explain why you think you have the right to do this?
> 
>     I believe you are abusing your commit but. Please revert this commit
>     ASAP.
> 
> I think that's putting it a bit strongly: this was intended as a 
> correction to his own perldelta entry committed a few hours earlier, and 
> a request had gone out to update perldelta as soon as possible.
> 

Thank you for correcting me on that.  FWIW, I don't think that every 
commit has to come in the form of a pull request.  If someone makes a 
small mistake in a commit, it would suffice for the correction to appear 
in the commit message.  Similarly, is someone is merely correcting a 
typo, I think a committer should have the leeway to simply make the 
commit and mention that in the commit message.  (After all, we survived 
for 25+ years without pull requests.)

I do however, think that something is significant enough to warrant a 
code review, then a pull request should be made and the requestor should 
refrain from merging the p.r. until at least one review has appeared.

**Comment by khwilliamson** [comment]
On 9/20/22 05:36, James E Keenan wrote:
> On 9/20/22 00:25, Hugo van der Sanden wrote:
>  > _ No description provided. _
>  >
>  > @richardleach <https://github.com/richardleach>, this is the second
>  > time recently that you have issued a pull request and then merged it
>  > into blead without getting a single comment or review.
>  >
>  > Can you explain why you think you have the right to do this?
>  >
>  > I believe you are abusing your commit but. Please revert this commit
>  > ASAP.
>  >
>  > I think that's putting it a bit strongly: this was intended as a
>  > correction to his own perldelta entry committed a few hours earlier, and
>  > a request had gone out to update perldelta as soon as possible.
>  >
> 
> Thank you for correcting me on that. FWIW, I don't think that every
> commit has to come in the form of a pull request. If someone makes a
> small mistake in a commit, it would suffice for the correction to appear
> in the commit message. Similarly, is someone is merely correcting a
> typo, I think a committer should have the leeway to simply make the
> commit and mention that in the commit message. (After all, we survived
> for 25+ years without pull requests.)
> 
> I do however, think that something is significant enough to warrant a
> code review, then a pull request should be made and the requestor should
> refrain from merging the p.r. until at least one review has appeared.
> 

I thought we had language somewhere that already gives permission to 
avoid a PR for likely uncontroversial changes, but I can't find it off-hand

Many of my PRs get warnocked.  My personal rule for handling those is to 
give it at least a week of zero response before pushing to blead.  If it 
is a side issue, I can let it sit for far longer.  If it is blocking 
something, I might cut it to 5-6 days.

We just don't have the staffing and expertise to demand a review of 
every PR.

It is demoralizing to have your PRs have no responses.  And it takes 
discipline to continue to issue them when all previous ones on the topic 
have been warnocked.  Earlier this cycle, I let a PR languish for a 
month with no reviews.  After I pushed it, I noticed the code could be 
simplified by a bit of refactoring, but which showed a large-ish 
difference listing.  I just pushed that directly.  If no one cared or 
knew enough about the first request, no one is likely to care or know 
enough about its revision.

**Comment by Grinnz** [comment]
Those are all reasonable considerations. The disconnect here is that the PR process was used but no time was given for review so it served only to run automated tests before committing. I would suggest writing in the description if that's the only reason a PR was made instead of committing a simple uncontroversial change directly.

**Comment by richardleach** [comment]
I hold my hands up to making a dog's breakfast of updating _perldelta.pod_ in haste and apologize for peoples' time wasted. Points made above duly noted.

**Pull request merged**
