### PR TITLE
Unify grok_bin, grok_oct, and grok_hex

### PR DESCRIPTION
**Pull request by khwilliamson**
These functions were almost the same, but making changes was a pain because the same thing had to be applied separately to each.  I have been thinking about a way to unify them without slowing them down.  The problem is you don't want to add a conditional to each loop iteration to apply this function's semantics as opposed to the other functions' semantics.  I finally figured out a way to compute the value of an arbitrary hex digit without using conditionals and array lookups.  This speeds up grok_hex, and the same code can be used in the other two functions without introducing extra branching.  There is a penalty for those two, an extra array lookup per loop iteration.  I think that is worth it.   I don't believe these are as critical as grok_hex, which this branch speeds up.

And 3 100-ish line functions are collapsed into a single 100-ish line function, and changes only have to be made in one place.

I thought I should make this a PR, in case I'm overlooking something, to give people a chance to object or coment, or embellish.

### CODE REVIEW

**Comment by tonycoz** [comment]
This looks reasonable.

Did you benchmark the changes to see if there's any improvement? (possibly using Porting/bench.pl)

**Comment by dur-randir** [comment]
At least grok_hex is a bit slower now. Those are stats for perl build with './Configure -de -Dusedevel' and run with 'taskset 0x2 perf stat -e cycles:u,instructions:u,branches:u,branch-misses:u ./perl -e '$z="0x666666"; hex($z) for 1..200_000_000'':

blead
```
 Performance counter stats for './perl -e $z="0x666666"; hex($z) for 1..200_000_000':

    27,981,396,632      cycles:u
    86,801,326,182      instructions:u            #    3.10  insn per cycle
    17,400,270,987      branches:u
            23,212      branch-misses:u           #    0.00% of all branches

       9.574013631 seconds time elapsed

       9.564293000 seconds user
       0.004006000 seconds sys
```
origin/grok
```
 Performance counter stats for './perl -e $z="0x666666"; hex($z) for 1..200_000_000':

    30,924,499,607      cycles:u
    96,201,316,071      instructions:u            #    3.11  insn per cycle
    18,000,269,371      branches:u
            24,108      branch-misses:u           #    0.00% of all branches

      10.571267105 seconds time elapsed

      10.562079000 seconds user
       0.004003000 seconds sys
```

**Comment by dur-randir** [comment]
Pure slowdown looks like 21%, for the following C program
```
int
main(int argc, char **argv, char **env)
{
    char* foo = "0x666666";
    int len = strlen(foo);
    int flags = 0;
    NV res;
    long int i;

    for (i = 0; i < 100000000; ++i) {
        grok_hex(foo, &len, &flags, &res);
    }

    exit(0);
}
```
blead
```
     6,403,105,849      cycles:u
    23,900,392,055      instructions:u            #    3.73  insn per cycle
     4,600,081,844      branches:u
             5,877      branch-misses:u           #    0.00% of all branches

       2.243903185 seconds time elapsed

       2.231829000 seconds user
       0.012164000 seconds sys
```
origin/grok
```
     7,804,500,822      cycles:u
    28,800,389,126      instructions:u            #    3.69  insn per cycle
     4,900,081,493      branches:u
             6,155      branch-misses:u           #    0.00% of all branches

       2.708099849 seconds time elapsed

       2.699235000 seconds user
       0.008043000 seconds sys
```

**Comment by khwilliamson** [comment]
On 1/9/20 1:36 PM, Sergey Aleynikov wrote:
> Pure slowdown looks like 21%, for the following C program
> 
> |int main(int argc, char **argv, char **env) { char* foo = "0x666666"; 
> int len = strlen(foo); int flags = 0; NV res; long int i; for (i = 0; i 
> < 100000000; ++i) { grok_hex(foo, &len, &flags, &res); } exit(0); } |
> 
> blead
> 
> |6,403,105,849 cycles:u 23,900,392,055 instructions:u # 3.73 insn per 
> cycle 4,600,081,844 branches:u 5,877 branch-misses:u # 0.00% of all 
> branches 2.243903185 seconds time elapsed 2.231829000 seconds user 
> 0.012164000 seconds sys |
> 
> origin/grok
> 
> |7,804,500,822 cycles:u 28,800,389,126 instructions:u # 3.69 insn per 
> cycle 4,900,081,493 branches:u 6,155 branch-misses:u # 0.00% of all 
> branches 2.708099849 seconds time elapsed 2.699235000 seconds user 
> 0.008043000 seconds sys |
> 

By continuing to tweak the implementation, I was able to speed things 
up.  I prefer to use @iabyn benchmarking tool in /Porting, which uses 
cachegrind.  After the tweaks, I get this:

Key:
     Ir   Instruction read
     Dr   Data read
     Dw   Data write
     COND conditional branches
     IND  indirect branches
     _m   branch predict miss
     _m1  level 1 cache miss
     _mm  last cache (e.g. L3) miss
     -    indeterminate percentage (e.g. 1/0)

The numbers represent raw instruction counts per function call
        blead fixup Ratio %
        ----- ----- -------
     Ir 326.0 298.0   109.4
     Dr  72.0  73.0    98.6
     Dw  31.0  38.0    81.6
   COND  50.0  36.0   138.9
    IND   2.0   2.0   100.0

COND_m   1.0   0.0     Inf
  IND_m   3.0   3.0   100.0

  Ir_m1   0.0   0.0   100.0
  Dr_m1   0.0   0.0   100.0
  Dw_m1   0.0   0.0   100.0

  Ir_mm   0.0   0.0   100.0
  Dr_mm   0.0   0.0   100.0
  Dw_mm   0.0   0.0   100.0

@iabyn has told me that the most important number in this is the final 
column in the COND row.  It says that there are nearly 40% fewer 
branches in the newest version compared to blead

I believe the second most important number is the COND_m ratio cell.  It 
says there were no missed branch predictions, as opposed to a single one 
in blead.

The slowdown under Dw doesn't really matter from what @iabyn has said.

It turns out that the XDIGIT_VALUE() macro that I changed to be 
branchless was already being optimized  by gcc to remove the branching 
in the instance it is called in the main loop.  The other occurrence of 
this macro in this function did not get the branching removed, but it is 
executed only when there is an underscore in the input.

A reason the changes slowed things down is that the loop doesn't get 
executed all that many times (things overflow pretty quickly), so the 
setup overhead was more significant than I had realized.  The first 
tweaking I tried was to move some of the setup calculations out of the 
function, and hardcode their values in the calling macros.  The 
grok_hex() macro knows for example that the leading characters are 0x; 
grok_bin() that they are instead 0b.  So the macros can pass these to 
the called function instead of it having to test and set them.

WHen I did that, the number of conditionals already went down from what 
is in blead.

I then unrolled the loop for the first 7 iterations.  This is enough so 
that the next iteration could overflow on a 32-bit word.  That improved 
things quite a bit.

One could argue that we could unroll the loop without combining the bin, 
oct, and hex functions.  And that is true.  But that is a big part of my 
point.  Doing it after combining them causes the speed-up to happen in 
all three.  It becomes much more of a bother to do it in three different 
places, and if we say we don't care so much about speed in the bin and 
octal cases, then the functions start to diverge, and that leads to, 
well you know the story.

I also cleaned up the tail of this function.  Again it becomes less 
attractive to spend the time to do that when it has to be done multiple 
times.

And, I improved the accuracy of the NV approximation to the intended 
code point when there is overflow.  That fixes a long-standing XXX in 
the source code.  Again, I might not have bothered if I had to do it 
three times.

This code is optimized for hex.  I doubt that large octal and binary 
numbers are converted that often in real life.  If we wanted to get 
everything optimized to the fullest extent possible, the alternative 
would be to write a perl script that takes a template and writes out the 
three functions, customized for their purpose, to a new file, say 
grok_bin_oct_hex.c.  There is a disadvantage of that in that it is 
easier to write code for C in an editor that is expecting it to be a C 
file, and does the highlighting, indentation, and error detection for 
you.  It would be harder to maintain if all that were in a heredoc in a 
perl file.

I ran the benchmarks on the same input value for both octal and binary 
inputs.  (That is, I took the hex number and took its oct and bin 
equivalents.)  Below are the results of these.  They show that the 
number of CONDS goes down, and the number of pipe-lined instructions 
goes up.  I think it is acceptable as-is.

oct

        blead fixup Ratio %
        ----- ----- -------
     Ir 338.0 389.0    86.9
     Dr  70.0  82.0    85.4
     Dw  30.0  42.0    71.4
   COND  60.0  47.0   127.7
    IND   2.0   2.0   100.0

COND_m   1.0   0.0     Inf
  IND_m   3.0   3.0   100.0

  Ir_m1   0.0  -0.1    -0.0
  Dr_m1   0.0   0.0   100.0
  Dw_m1   0.0   0.0   100.0

  Ir_mm   0.0   0.0   100.0
  Dr_mm   0.0   0.0   100.0
  Dw_mm   0.0   0.0   100.0


binary

        blead fixup Ratio %
        ----- ----- -------
     Ir 631.0 916.0    68.9
     Dr  76.0 145.0    52.4
     Dw  28.0  57.0    49.1
   COND 138.0 107.0   129.0
    IND   2.0   2.0   100.0

COND_m   1.0   1.0   100.0
  IND_m   3.0   3.0   100.0

  Ir_m1   0.0  -0.1    -0.0
  Dr_m1   0.0   0.0   100.0
  Dw_m1   0.0   0.0   100.0

  Ir_mm   0.0   0.0   100.0
  Dr_mm   0.0   0.0   100.0
  Dw_mm   0.0   0.0   100.0

I have replaced the smoke-me/khw-grok branch with the newest version for 
any testing.

**Comment by dur-randir** [comment]
They're almost indistinguishable now, testing 100kk grok_hex iterations:

blead
```     6,402,308,652      cycles:u
    23,900,392,053      instructions:u            #    3.73  insn per cycle
     4,600,081,842      branches:u
             5,359      branch-misses:u           #    0.00% of all branches

       2.244296230 seconds time elapsed
```
origin/smoke-me/khw-grok
```
     6,468,860,281      cycles:u
    21,800,389,010      instructions:u            #    3.37  insn per cycle
     3,100,081,377      branches:u
             5,072      branch-misses:u           #    0.00% of all branches

       2.249467724 seconds time elapsed
```
Of the other interesting counters, new version performs ~11% more cache writes than blead (though I can't profile write misses on this machine).

I much prefer perf over cachegrind. Cachegrind performs simulation of some imaginary hardware, corresponding to ~ pentium 4 generation. Perf, on the other hand, works with the actual hardware and provides direct insight into what's happening during program execution. And intel has changed a lot since pentium 4 times - there're at least two major changes (core2 and then radically changing cache layout in server skylake) and each generation varies a little. So, while the numbers you get with perf, are exact only on a single generation, they're much closer to the real world.

And you can see this with a branch predictor - it actually fails over 5k times, and this number goes down on a new vs old branch together with the number of total branches, but with a 1:1000 ratio.

**Comment by dur-randir** [comment]
Missed counter for blead
```
     6,402,308,652      cycles:u
```

**Comment by khwilliamson** [comment]
On 1/11/20 7:23 AM, Sergey Aleynikov wrote:
> They're almost indistinguishable now, testing 100kk grok_hex iterations:
> 
> blead
> 
> |23,900,392,053 instructions:u # 3.73 insn per cycle 4,600,081,842 
> branches:u 5,359 branch-misses:u # 0.00% of all branches 2.244296230 
> seconds time elapsed |
> 
> origin/smoke-me/khw-grok
> 
> |6,468,860,281 cycles:u 21,800,389,010 instructions:u # 3.37 insn per 
> cycle 3,100,081,377 branches:u 5,072 branch-misses:u # 0.00% of all 
> branches 2.249467724 seconds time elapsed |
> 
> Of the other interesting counters, new version performs ~11% more cache 
> writes than blead (though I can't profile write misses on this machine).
> 
> I much prefer perf over cachegrind. Cachegrind performs simulation of 
> some imaginary hardware, corresponding to ~ pentium 4 generation. Perf, 
> on the other hand, works with the actual hardware and provides direct 
> insight into what's happening during program execution. And intel has 
> changed a lot since pentium 4 times - there're at least two major 
> changes (core2 and then radically changing cache layout in server 
> skylake) and each generation varies a little. So, while the numbers you 
> get with perf, are exact only on a single generation, they're much 
> closer to the real world.
> 
> And you can see this with a branch predictor - it actually fails over 5k 
> times, and this number goes down on a new vs old branch together with 
> the number of total branches, but with a 1:1000 ratio.
> 
> —

I did some more work, and have pushed a new version to the same branch 
for you to try.

I now use a switch statement so that in the common case, 'len' doesn't 
have to be adjusted, and a bunch of branches are removed, replaced by 
whatever the compiler generates for a switch.

I also use strnlen() at the beginning to avoid having to test that we 
haven't reached a terminating NUL, which, undocumented, the functions 
check for.  That behavior seems odd, that we have a length parameter, 
but don't trus it.  I was surprised to see that strnlen is only in POSIX 
2008 and up, and that we have our own implementation for platforms that 
don't have it, and which loops byte by byte.  That implementation could 
be replaced by the following 3 lines inline:

const char * end = (char *) memchr((const void *) s, '\0', len);
if (end == NULL) return len;
return end - s;

(I may not have all the casts right.)  memchr is C89.  I have noticed on 
glibc that it is extremely fast.

The branch also fixes the bug in which it doesn't test that there isn't 
a NUL before the end of the 0x prefix.

This latest revision gives a further 20% fewer conditionals according to 
cachegrind

I also thought of another way to have all three functions based on a 
single template.  And that is to have grok_hex as a function in 
numeric.c, and then have a perl script that reads it, and substitutes 
the few changes needed for each of grok_oct and grok_bin, writing them 
to a new .c file.  I don't know how hard that would be to put the 
correct dependencies in the Makefile for regenerating them.

grok_hex would be specially formatted so that it would be easy to search 
and replace the few items that need doing.

**Comment by dur-randir** [comment]
Results from the latest branch are
```
     6,303,241,264      cycles:u
    22,300,390,560      instructions:u            #    3.54  insn per cycle
     2,800,081,649      branches:u
            19,552      branch-misses:u           #    0.00% of all branches

       2.187571263 seconds time elapsed
```

This is faster than blead. But even if they were equal, i'd still go on with the merger - without configure-time code generation, just plain and understandable single C function. It's much easier to support and the gains from separating it and creating custom build step won't be that much to vastly increase complexity here.

PS: interestingly, this has a higher misses count.

**Comment by tonycoz** [comment]
>I have replaced the smoke-me/khw-grok branch with the newest version for any testing.

Update the `grok` branch too, otherwise if someone tries to merge this they'll be merging the old code.

You can make the PR from the smoke-me to save yourself time.

The changes in the smoke-me look fine to me.

**Comment by iabyn** [comment]
On Sat, Jan 11, 2020 at 06:23:28AM -0800, Sergey Aleynikov wrote:
> I much prefer perf over cachegrind. Cachegrind performs simulation of
> some imaginary hardware, corresponding to ~ pentium 4 generation. Perf,
> on the other hand, works with the actual hardware and provides direct
> insight into what's happening during program execution. And intel has
> changed a lot since pentium 4 times - there're at least two major
> changes (core2 and then radically changing cache layout in server
> skylake) and each generation varies a little. So, while the numbers you
> get with perf, are exact only on a single generation, they're much
> closer to the real world.

Cachegrind fairly accurately indicates the number of reads, writes,
branches etc; I tend to discount its reporting of numbers of cache/branch
misses, since as you say, it's making old assumptions (unless its been
updated recently).

But Porting/bench.pl has some important advantages over 'perf stat'.

1) it's more or less completely reproducible - you get the same results
for every run, and it can be used to bisect where a small performance
issue was introduced into blead. perf stat gives noise, not just timing
noise, but even in terms of the CPU counters. For example this simple
10x run gives a 34% variation in branch misses:

    $ perf stat -r 10 perl5300o -e'$x++ for 1..100_000_000'
    ...
        81,379  branch-misses:u  # 0.00% of all branches ( +- 34.34% )


2) It factors out the startup and loop overhead. This means you can
measure very small changes, such as an optimisation in a small, hot op
like pp_padsv, and also immediately spot where you've made mistakes, e.g.
the number of instructions or branches goes up by 3 say when you expect
them to go down, because you forgot to use the _NN version of a macro.

3) Small changes to bits of code in the executable that aren't even
executed can cause significant changes to execution performance, since the
the alignment of instructions affects caches misses. For example before
now I've added a line of code to dump.c then run a small benchmark (that
doesn't call anything in dump.o) which caused a 10% slowdown.

4) bench.pl allows you to add a number of small benchmarks in a test file,
and allows you to run all those against a number of perl binaries. For
example during development of an optimisation, I'll first add some
benchmarks, which also includes things I *don't* expect to get faster, but
which I don't want to inadvertently slow down. Then as development
processes I might have several perl binaries which represent various
stages of development, including trying alternative strategies; In a
single run with bench.pl I can compare all perls against all benchmarks,
and study what gets better and what gets worse.

5) It's fast. You can run it in parallel if you have multiple CPUs and a
"full spectrum" run like the described in (4) might take just a couple of
minutes. Running the benchmark across all CPUs doesn't affect the results
(you don't get any noise from context switching, cache contention etc).

-- 
Never work with children, animals, or actors.

**Comment by dur-randir** [comment]
I don't observe that much discrepancy between runs. Without binding to a single core, I get 
```
            52,558      branch-misses             #    0.00% of all branches          ( +-  6.57% )
```
with taskset, deviation is improved even further
```
            49,638      branch-misses             #    0.00% of all branches          ( +-  1.82% )
```
I'm not sure what can attribute for such differences between systems. I run tests on a v3 xeon with scaling_governor = performance and x86_energy_perf_policy = performance to minimize time before a core is sped up to a maximum multiplier. Maybe it also affects other computational units' parts?

And I don't think that the number of mispredictions is irrelevant - having 3kk branches and 0.01% misses is much better than having 1kk branches and 50% misses. Probably cachegrind can detect some of those pathological cases, but all of them? I'm not sure, that's why I always check with perf, and than why not start with it in the first place?

Furthermore, perf really shines when you need not only to compare performance of two code versions, but when you want to understand why the code isn't running with expected speed - cache misses/front stalls/unit starvation. Though not that frequently required and is more interesting for streaming processing that for general computing, this data can't be simulated, and here perf is invaluable.

As for the other points - they're not about cachegrind vs perf, but about infrastructure on top of cachegrind vs pure perf. It'd be good to have all of those perks with perf too, as they're handy, but the tool that drives them is less accurate.

**Comment by khwilliamson** [comment]
A version of this was merged.

**Comment by dur-randir** [comment]
It's even better now
```
     5,302,731,293      cycles:u
    20,000,388,909      instructions:u            #    3.77  insn per cycle
     2,300,081,276      branches:u
             4,887      branch-misses:u           #    0.00% of all branches

       1.861104574 seconds time elapsed
```

**Pull request closed without merging**
