### PR TITLE
Terminology slave 20211112

### PR DESCRIPTION
**Pull request by jkeenan**

### CODE REVIEW

**Comment by Grinnz** [comment]
Just to verify, is this change to a variable API not a backcompat concern?

**Comment by Grinnz** [comment]
I see this was previously discussed in https://github.com/Perl/perl5/pull/18854.

**Comment by khwilliamson** [comment]
Is this ready to be squashed and merged, since @rbjs comments have been incorporated

**Comment by khwilliamson** [comment]
@jkeenan is this ready to be squashed and merged?

**Comment by jkeenan** [comment]
> @jkeenan is this ready to be squashed and merged?

Squashed, then merged into blead in 3a99f1de4609feb952ca294cc4b3479d615c8d94.

**Pull request closed without merging**
