### PR TITLE
PathTools: update bug tracker location, update maintainer

### PR DESCRIPTION
**Pull request by mbeijen**
See for discussion https://rt.cpan.org/Public/Bug/Display.html?id=116342

### CODE REVIEW

**Comment by jkeenan** [comment]
@mbeijen, changes to `*.pm` files require us to increment the `$VERSION` in such files.  This requirement is enforced by `t/porting/cmp_version.t`, which is failing in your branch.  Can you increment `$VERSION` in all the `*.pm` files underneath `dist/PathTools/`, re-build and run `make test_porting`, then squash commits and re-submit?

Thank you very much.
Jim Keenan

**Comment by mbeijen** [comment]
I've updated the $VERSION in PathTools. Doing so I noticed a couple of issues:

- Cwd.pm and File/Spec/Unix.pm had already been updated to 3.82, the other files are still at 3.81
- The Changes file is missing some lines, and maybe I should also add my change to this file?
- The CPAN release is 3.75 and is thus lagging behind perls 3.81+ state. How do releases happen, typically?

I've updated the VERSION now to 3.83 in all files, and can add (back) the missing changes at least back to 3.75, just let me know.

**Comment by jkeenan** [comment]
I locally squashed all your commits, rebased on blead, merged to blead, then pushed blead in commit ad06173e13ddbddbf53a4f776f5c03f061acb68f.

> I've updated the $VERSION in PathTools. Doing so I noticed a couple of issues:
> 
>     * Cwd.pm and File/Spec/Unix.pm had already been updated to 3.82, the other files are still at 3.81
> 

Yes, but I would consider the non-bump of $VERSION in all those other `*.pm` files to be an oversight -- albeit an oversight that we don't have a porting test for.

>     * The Changes file is missing some lines, and maybe I should also add my change to this file?
> 

The PathTools distribution was, IIRC, long maintained upstream, so it once was shipped under the `cpan/` directory rather than `dist/`.  A `Changes` file is a best practice for CPAN releases, but it's not quite as relevant, IMO, for "blead-upstream" distributions.  (Why not *quite* as relevant?  Because we have a lot of history between the Perl 5 commit log, GH issue queue, etc.)  However, the `Changes` file definitely should be updated when we get around to doing a fresh CPAN release -- which brings us to ...

>     * The CPAN release is 3.75 and is thus lagging behind perls 3.81+ state. How do releases happen, typically?
> 

You've asked the $64,000 question!  I won't claim to know specifics about how to do a CPAN release of PathTools.  I will state that this is a messy area in our process.  To do a CPAN release you need to have the PAUSE permissions to do so, which means you either need to be the pumpking or be able to release as the 'P5P' user.  So, in the recent past, dual-life distributions under `dist/` have gotten CPAN releases mainly by the pumpking.  We have a Perl Steering Council now -- but do we have a pumpking?  I don't actually know what we "typically" do about this nowadays.  This is something that we should sort out on the mailing list, as it's well beyond the scope of this ticket.

Thanks again for your contribution.  Closing ticket.

**Comment by xsawyerx** [comment]
Even though this is already closed, I want to comment on the release discussion. This week I intended to release a new `PathTools` to CPAN and as I was working on it today, I realized that a recent change in `Cwd` makes it impossible to compile `Cwd` on Perl 5.34 and below.

Commit 12a8085aee9a1a5ac613205b43ea06406736ac6b introduced the usage of `PerlIO_lstat` and `PerlLIO_readlink` which were introduced in 680b2c5ee3b53c627074192b3cf14416a24da6ea. Releasing `PathTools` separately to CPAN renders its release unable because unless you installed blead, you won't be able to install it.

Maybe a change to `Devel::PPPort` can help.

**Comment by jkeenan** [comment]
> Even though this is already closed, I want to comment on the release discussion. This week I intended to release a new `PathTools` to CPAN and as I was working on it today, I realized that a recent change in `Cwd` makes it impossible to compile `Cwd` on Perl 5.34 and below.
> 
> Commit [12a8085](https://github.com/Perl/perl5/commit/12a8085aee9a1a5ac613205b43ea06406736ac6b) introduced the usage of `PerlIO_lstat` and `PerlLIO_readlink` which were introduced in [680b2c5](https://github.com/Perl/perl5/commit/680b2c5ee3b53c627074192b3cf14416a24da6ea). Releasing `PathTools` separately to CPAN renders its release unable because unless you installed blead, you won't be able to install it.
> 
> Maybe a change to `Devel::PPPort` can help.

@xsawyerx, the two commits you've cited were both committed to blead in the *last* development cycle and are therefore present in perl-5.34.0.
```
commit 680b2c5ee3b53c627074192b3cf14416a24da6ea
Author:     Tony Cook <tony@develop-help.com>
AuthorDate: Wed Oct 7 16:31:22 2020 +1100
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Tue Dec 1 15:29:33 2020 +1100

    Win32: implement symlink() and readlink()


commit 12a8085aee9a1a5ac613205b43ea06406736ac6b
Author:     Tony Cook <tony@develop-help.com>
AuthorDate: Wed Oct 7 11:50:55 2020 +1100
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Tue Dec 1 15:29:33 2020 +1100

    PathTools: use PerlLIO_*() functions and chdir() on a symlink differences
```
Can you open a new GH issue that describes this problem so that @tonycoz and others can take a look at it?

Thank you very much.
Jim Keenan

**Comment by xsawyerx** [comment]
> > Even though this is already closed, I want to comment on the release discussion. This week I intended to release a new `PathTools` to CPAN and as I was working on it today, I realized that a recent change in `Cwd` makes it impossible to compile `Cwd` on Perl 5.34 and below.
> > Commit [12a8085](https://github.com/Perl/perl5/commit/12a8085aee9a1a5ac613205b43ea06406736ac6b) introduced the usage of `PerlIO_lstat` and `PerlLIO_readlink` which were introduced in [680b2c5](https://github.com/Perl/perl5/commit/680b2c5ee3b53c627074192b3cf14416a24da6ea). Releasing `PathTools` separately to CPAN renders its release unable because unless you installed blead, you won't be able to install it.
> > Maybe a change to `Devel::PPPort` can help.
> 
> @xsawyerx, the two commits you've cited were both committed to blead in the _last_ development cycle and are therefore present in perl-5.34.0.

Ah! I should've taken a closer look at the history. :)

> ```
> commit 680b2c5ee3b53c627074192b3cf14416a24da6ea
> Author:     Tony Cook <tony@develop-help.com>
> AuthorDate: Wed Oct 7 16:31:22 2020 +1100
> Commit:     Tony Cook <tony@develop-help.com>
> CommitDate: Tue Dec 1 15:29:33 2020 +1100
> 
>     Win32: implement symlink() and readlink()
> 
> 
> commit 12a8085aee9a1a5ac613205b43ea06406736ac6b
> Author:     Tony Cook <tony@develop-help.com>
> AuthorDate: Wed Oct 7 11:50:55 2020 +1100
> Commit:     Tony Cook <tony@develop-help.com>
> CommitDate: Tue Dec 1 15:29:33 2020 +1100
> 
>     PathTools: use PerlLIO_*() functions and chdir() on a symlink differences
> ```
> 
> Can you open a new GH issue that describes this problem so that @tonycoz and others can take a look at it?

Will do.

**Pull request closed without merging**
