### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by vchaves123**
just an typo

### CODE REVIEW

**Comment by Grinnz** [comment]
This is not a typo, it's just slang.

**Comment by mauke** [comment]
> an typo

**Comment by mauke** [comment]
More seriously:

- "typo" is not a good commit title/summary.
- Your commit message contains a typo ("an" should be "a").
- As Grinnz said, this is not a typo.

In summary, I think this PR should be rejected.

**Comment by khwilliamson** [comment]
I dispute this outcome.

Perl source code should not be designed to be intelligible to only extremely fluent English speakers.  There are a lot of contributors to this project whose native language is not English, and who have varying degrees of facility in it.

When someone cares enough to submit a pull request like this, I consider it to be prima facie evidence that the existing terminology is deficient, and their efforts should not be dismissed out-of-hand.  So let's look at the particulars of this request.

The commit takes this line

```echo "Also extracting names from /lib/syscalls.exp for good ole AIX..." >&4```

and changes `ole` to `old`

What does keeping it `ole` gain us?  I don't see that it gains us anything.  My guess is that the original text was attempting to denigrate in passing the AIX operating system versions in use at the time.  I suspect they were expressing an opinion, not very forthrightly, and that opinion was really only aimed at those in the "know".  If I'm a member of that club, maybe that will bring a slight smile or smirk to my face.  But nothing of real value.

Then what is the cost of keeping it?  Well, not that many people are in the know, and the sly reference will be lost on them.  They may not be proficient enough in English to even understand what is meant here.  This can lead to confusion, wasting their time unnecessarily.

I say that `old` is better than `ole` here, and the existence of even one person for whom the current situation is problematic enough that they bothered to try to fix it means the word should be changed.

Yes the title and message of the request need to be improved.  If someone over time often makes these kinds of mistakes, it would be ok with me to reject their request so that they can fix it up and resubmit.

But with a first time or few-time contributor, they should be gently guided towards meeting our reasonable standards.

@vchaves123 whatever the outcome of this, I thank you for caring enough to take the time to submit this proposed change.

In this message, I have deliberately used terms that might not be familiar to all potential readers.  If you had no problem with understanding any of it, then you are pretty proficient in English.  If you did have problems, how did you feel?

**Comment by mauke** [comment]
@khwilliamson OK, you're making some good points.

Still, the commit message needs to be fixed and this change would need to be upstreamed to metaconfig. Is the protocol still to patch Configure in place and notify tux to backport the changes?

**Comment by Grinnz** [comment]
PRs like this are commonly low effort trolls (in the fishing sense) to get one's name in as a committer; I would not consider the effort spent here to indicate any level of caring. This is an obscure message in the configure script for Perl, and "ole" is defined in merriam-webster: https://www.merriam-webster.com/dictionary/ole

**Comment by Grinnz** [comment]
If the submitter wishes to further support their point or rationale, I would of course change my view on this situation. The points raised by @khwilliamson are quite salient in the general case, but I don't believe are warranted here.

**Comment by Tux** [comment]
Interesting insights. I'll backport whatever decision is made. I understand both views and have no personal preference other than that "typo" is no correct description for a change like this

**Comment by ap** [comment]
> My guess is that the original text was attempting to denigrate in passing the AIX operating system versions in use at the time. I suspect they were expressing an opinion, not very forthrightly, and that opinion was really only aimed at those in the "know".

It comes from 2304df62caa7d9be70e8b8bcdb454e139c9c103d, which is one of the retconned Git commits that document early perl history, which is to say their name is almost certainly Larry Wall, and one could ask them…

**Comment by Tux** [comment]
> > My guess is that the original text was attempting to denigrate in passing the AIX operating system versions in use at the time. I suspect they were expressing an opinion, not very forthrightly, and that opinion was really only aimed at those in the "know".
> 
> It comes from [2304df6](https://github.com/Perl/perl5/commit/2304df62caa7d9be70e8b8bcdb454e139c9c103d), which is one of the retconned Git commits that document early perl history, which is to say their name is almost certainly Larry Wall, and one could ask them…

No, it comes from meta-unit `mcon/U/libc.U` and already exists in the first initial commit from their git version from `2006-08-24 14:32:52`. Before that, it was SVN, for which I do not have their history

**Comment by ap** [comment]
Ah. I found it in Perl/metaconfig@959f3c4c3cb71471e6fa1ba0ee4c8fba7f157582 which is backdated to 1999 and credited to @jhi (which probably doesn’t mean anything real). But metaconfig was written by Larry and initially another one-man project of his, right? Would you say it’s a good chance that a line that old came from him, or would you say were there enough contributors even back then that it’s hard to say?

(Admittedly this is going off into the weeds now… but my curiosity is piqued.)

**Comment by khwilliamson** [comment]
regardless, does this wording serve us now?  It's commentary from 25 years ago.  I would propose `s/good ole //`

**Comment by Tux** [comment]
> Ah. I found it in [Perl/metaconfig@959f3c4](https://github.com/Perl/metaconfig/commit/959f3c4c3cb71471e6fa1ba0ee4c8fba7f157582) which is backdated to 1999 and credited to @jhi (which probably doesn’t mean anything real). But metaconfig was written by Larry and initially another one-man project of his, right? Would you say it’s a good chance that a line that old came from him, or would you say were there enough contributors even back then that it’s hard to say?
> 
> (Admittedly this is going off into the weeds now… but my curiosity is piqued.)

@jhi just merged from meta/dist

**Pull request closed without merging**
