### PR TITLE
Fix some build issues with clang in Mingw-w64

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by jkeenan** [comment]
Thank you for this pull request.  I suspect that this p.r. may be attempting to do too much and that p.r.s addressing separate problems may be better.

Specifically, until we can see the build-time warnings you are getting when compiling with clang on Mingw-w64, we can't evaluate your proposed changes to `perl.h`.  Because `perl.h` is very fundamental to compilation, we have to be very careful before changing it.

We keep track of build-time warnings with a GitHub "label" by that name.  Can you please open a separate Issue for the build-time warnings, pasting in the relevant parts of the `make` (or Windows equivalent) output and the relevant configuration options?

Thank you very much.
Jim Keenan

**Comment by Biswa96** [comment]
I think you've already opened the issue here https://github.com/Perl/perl5/issues/18780

**Comment by jkeenan** [comment]
> I think you've already opened the issue here #18780

As noted in https://github.com/Perl/perl5/issues/18780#issuecomment-878634611 today, I tried out your pull request and found that it eliminated the vast majority of build-time warnings discussed in #18780.  The warnings it does not eliminate appear to come from files under `dist/` rather than from `perl.h`.

I'm not in a position to evaluate the mingw-related parts of this pull request.  Nor can I say whether this is the *best* way to eliminate approximately 28,000 build-time warnings; only that is *a* way to eliminate such warnings.  I don't have access to more recent versions of `clang` (clang13, I think, is relevant).

So a qualified +1 to this p.r.

**Comment by jkeenan** [comment]
@Biswa96, can you confirm that the changes in [this commit](https://github.com/Perl/perl5/commit/88e366d42b36d12b0fed022ac5209f0151150740) are consistent with your proposed changes to `perl.h` and help to eliminate build-time warnings when compiling with clang12?

Reference: https://github.com/Perl/perl5/issues/18780

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > I think you've already opened the issue here #18780
> 
> As noted in [#18780 (comment)](https://github.com/Perl/perl5/issues/18780#issuecomment-878634611) today, I tried out your pull request and found that it eliminated the vast majority of build-time warnings discussed in #18780. The warnings it does not eliminate appear to come from files under `dist/` rather than from `perl.h`.
> 
> I'm not in a position to evaluate the mingw-related parts of this pull request. Nor can I say whether this is the _best_ way to eliminate approximately 28,000 build-time warnings; only that is _a_ way to eliminate such warnings. I don't have access to more recent versions of `clang` (clang13, I think, is relevant).
> 
> So a qualified +1 to this p.r.

@xenu, are you in a position to review the mingw-related parts of this p.r.?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
@Biswa96,

Thank you for providing this pull request, which helped focus discussion of the problem of build-time warnings with clang12.

In https://github.com/Perl/perl5/pull/18984, @tonycoz has provided a more focused version of your patch, which we have applied to blead.

That leaves the 3 mingw-focused commits which were part of your p.r.  If you would like to pursue those further, please open a new p.r. with just mingw-focused commits.

Closing this pull request.  Thank you very much.

**Comment by Biswa96** [comment]
Thank you for the fix. It will take time to test perl in mingw with blead branch because it needs [some patches][1] to adapt mingw style path. Also, if compiled with mingw clang perl crashes after compiling miniperl.exe.

[1]: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-perl

**Pull request closed without merging**
