### PR TITLE
perlfunc.pod - when sleep() is called with a negative int

### PR DESCRIPTION
**Pull request by richardleach**
Intended to address #18010

### CODE REVIEW

**Comment by Grinnz** [comment]
Can someone confirm that this behavior is also present on other platforms?

**Comment by richardleach** [comment]
The text is basically paraphrasing pp_sleep:

```
        if (duration < 0) {
          /* diag_listed_as: %s() with negative argument */
          Perl_ck_warner_d(aTHX_ packWARN(WARN_MISC),
                           "sleep() with negative argument");
          SETERRNO(EINVAL, LIB_INVARG);
          XPUSHs(&PL_sv_zero);
          RETURN;
        } else {
          PerlProc_sleep((unsigned int)duration);
        }
```

**Comment by khwilliamson** [comment]
Shouldn't we explicitly also say what happens when called with zero.  The text mentions positive and negative, which leads me to wonder about when its neither.

**Comment by richardleach** [comment]
Zero seconds is fine by pp_sleep, which will call _PerlProc_sleep( 0 )_ and subsequently return zero. 

The detail of actually happens looks to be platform dependent. e.g. on Windows via Win32::sleep: "`...the thread will relinquish the remainder of its time slice but remain ready. Note that a ready thread is not guaranteed to run immediately. Consequently, the thread may not run until some time after the sleep interval elapses.`" So that's not quite the same as not sleeping at all, though the difference may not be observable as far as most users are concerned.

I'll try to come up with a short sentence to cover the nuance later today.

**Comment by richardleach** [comment]
Pushed an update to cover `sleep 0` without going into too much unnecessary detail.

**Review by khwilliamson — APPROVED** [review]
LGTM

**Comment by khwilliamson** [comment]
@richardleach You added a Do not merge label to this.  Is that still your position?

**Comment by richardleach** [comment]
Nope, not since you ok'd the `sleep 0` words. Just hadn't had the opportunity before now to remove the label.

**Pull request merged**
