### PR TITLE
Fix defined PERL_CORE

### PR DESCRIPTION
**Pull request by Jamaika1**

### CODE REVIEW

**Comment by tonycoz** [comment]
As it says at the top of the file, this file is generated and shouldn't be manually edited.

**Comment by Jamaika1** [comment]
In perl.h is default define MULTIPLICITY for USE_ITHREADS. My question is how to use USE_ITHREADS?

**Comment by Leont** [comment]
I'm not sure what this change is trying to fix, but I'm pretty sure it's the wrong fix anyway.

**Comment by jkeenan** [comment]
> I'm not sure what this change is trying to fix, but I'm pretty sure it's the wrong fix anyway.

What @LeonT said.

**Pull request closed without merging**
