### PR TITLE
Bisection example calling a debugging program

### PR DESCRIPTION
**Pull request by jkeenan**
Based on Tony Cook's example in
https://github.com/Perl/perl5/issues/21564#issuecomment-1767311741.

### CODE REVIEW

**Comment by jkeenan** [comment]
This merge request should not be applied until https://github.com/Perl/perl5/pull/21566 is accepted and merged.

**Comment by tonycoz** [comment]
I realized later I didn't need the Devel::* module, I could just use PERL5DB:
```
PERL5DB='sub DB::DB {}' perl ../bisect.pl --start=v5.35.5 --end=v5.35.6 -- ./perl -Ilib -d ../21564b.pl
```

which significantly simplifies the setup for this bisect.

**Comment by jkeenan** [comment]
> I realized later I didn't need the Devel::* module, I could just use PERL5DB:
> 
> ```
> PERL5DB='sub DB::DB {}' perl ../bisect.pl --start=v5.35.5 --end=v5.35.6 -- ./perl -Ilib -d ../21564b.pl
> ```
> 
> which significantly simplifies the setup for this bisect.

I'll try that out tomorrow and revise as needed.

**Comment by jkeenan** [comment]
> > I realized later I didn't need the Devel::* module, I could just use PERL5DB:
> > ```
> > PERL5DB='sub DB::DB {}' perl ../bisect.pl --start=v5.35.5 --end=v5.35.6 -- ./perl -Ilib -d ../21564b.pl
> > ```
> > 
> > 
> > which significantly simplifies the setup for this bisect.
> 
> I'll try that out tomorrow and revise as needed.

p.r. updated; please re-review. Thanks.

**Review by tonycoz — APPROVED** [review]

**Pull request merged**
