### PR TITLE
Create .github/CONTRIBUTING.pod

### PR DESCRIPTION
**Pull request by rwp0**
Adding a standard GitHub file as a symlink to [`pod/perlhack`](https://github.com/Perl/perl5/blob/blead/pod/perlhack.pod)

See https://github.com/Perl/perl5/community

---

Initially just clicked the `Propose` button to pass a checklist item

### CODE REVIEW

**Comment by demerphq** [comment]
This should contain instructions on how to add yourself to the authors file and related steps required to contribute a patch that wont fail the author tests.

Otherwise good idea.

**Comment by Leont** [comment]
Good idea, but I'm not sure this implementation of it is really helpful.

**Review by demerphq — CHANGES_REQUESTED** [review]
Please add some verbiage about how to add yourself to AUTHORS. (Configure git properly, and run Porting/updateAUTHORS.pl) Other than that I like it.

**Comment by demerphq** [comment]
@leont while I agree as regards to its present state, I think we can provide some guidance so that it gets merged in an acceptable condition for its initial release. Do you have any recommendations for @rwp0 that are a bit more actionable?

**Comment by jkeenan** [comment]
On 9/2/22 14:00, Elvin Aslanov wrote:
> Adding a standard GitHub file
> 
> See https://github.com/Perl/perl5/community 
> <https://github.com/Perl/perl5/community>
> 

We don't need this.  We have pod/perlhack.pod, accessible through 
`perldoc perlhack`.

Let's bear in mind:  We existed long before git, and long before 
github.com.  We don't have to do anything simply because it's become the 
latest feature on github.

Thank you very much.
Jim Keenan

**Comment by rwp0** [comment]
> AUTHORS



> Please add some verbiage about how to add yourself to AUTHORS. (Configure git properly, and run Porting/updateAUTHORS.pl) Other than that I like it.

I plan to add the following steps:

- Include your name in [AUTHORS](https://github.com/Perl/perl5/blob/blead/AUTHORS) (in the alphabetical order)
- Run `make test_porting` (after doing `./Configure -des -Dusedevel`) before submitting PR's (as was frequently requested from my own experience)

I'm not familiar with `updateAuthors.pl`, could you please provide some guidance on it?

**Comment by rwp0** [comment]
> On 9/2/22 14:00, Elvin Aslanov wrote: Adding a standard GitHub file See https://github.com/Perl/perl5/community <https://github.com/Perl/perl5/community>
> We don't need this. We have pod/perlhack.pod, accessible through `perldoc perlhack`. Let's bear in mind: We existed long before git, and long before github.com. We don't have to do anything simply because it's become the latest feature on github. Thank you very much. Jim Keenan

We're on GitHub so following its guidelines is fathomable I think.

We can link [perlhack](https://perldoc.perl.org/perlhack) here as well.

Not having such things (the other being `.github/README.md`) makes Perl somewhat **invisible** to new users.

**Comment by demerphq** [comment]
On Fri, 2 Sept 2022 at 20:09, Elvin Aslanov ***@***.***> wrote:
>
> AUTHORS
>
> Please add some verbiage about how to add yourself to AUTHORS. (Configure git properly, and run Porting/updateAUTHORS.pl) Other than that I like it.
>
> I plan to add the following steps:
>
> Include your name in AUTHORS
> Run make test_porting (after doing ./Configure -des -Dusedevel) before submitting PR's (as was frequently requested from my own experience)
>
> I'm not familiar with updateAuthors.pl, could you please provide some guidance on it?

It is the tool that test_porting will run to tell you to run itself to
update AUTHORS if you haven't done so before. :-) [Used to be called
Porting/checkAUTHORS.pl]

Remove yourself from the AUTHORS file. Run test_porting. Let me know
what you see. Or just do:

$ Porting/updateAUTHORS.pl --help
$ Porting/updateAUTHORS.pl --man

Or you could temporarily do something like

   GIT_AUTHOR_NAME="Fozzy Bear" git commit -a -m'testing'

and then run test_porting. There are a variety of ways to learn about
the tool. :-)

cheers,
Yves


-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
On Fri, 2 Sept 2022 at 20:14, Elvin Aslanov ***@***.***>
wrote:

> On 9/2/22 14:00, Elvin Aslanov wrote: Adding a standard GitHub file See
> https://github.com/Perl/perl5/community
> https://github.com/Perl/perl5/community
> We don't need this. We have pod/perlhack.pod, accessible through perldoc
> perlhack. Let's bear in mind: We existed long before git, and long before
> github.com. We don't have to do anything simply because it's become the
> latest feature on github. Thank you very much. Jim Keenan
>
> We're on GitHub so following its guidelines is fathomable.
>
> We can link perlhack <https://perldoc.perl.org/perlhack> here as well.
>

Maybe just convert perlhack to markdown using
https://metacpan.org/pod/Pod::Markdown.

> Not having such things (the other being .github/README.md) make Perl
> invisible to users.
>

Agreed.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by Grinnz** [comment]
> Maybe just convert perlhack to markdown using https://metacpan.org/pod/Pod::Markdown.

No need; you can simply include a copy as CONTRIBUTING.pod.

**Comment by Grinnz** [comment]
Though a symlink would be much better if github accepts that, so it doesn't become out of date.

**Comment by Grinnz** [comment]
My recommendation would be to create a symlink from .github/CONTRIBUTING.pod to pod/perlhack.pod. Github will recognize it from this folder and then it will not interfere with the build process or end up on CPAN.

**Comment by demerphq** [comment]
On Fri, 2 Sept 2022 at 20:27, Dan Book ***@***.***> wrote:

> My recommendation would be to create a symlink from
> .github/CONTRIBUTING.pod to pod/perlhack.pod. Github will recognize it from
> this folder and then it will not interfere with the build process or end up
> on CPAN.
>
A fine idea. Good recommendation. +1.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by rwp0** [comment]
> My recommendation would be to create a symlink from .github/CONTRIBUTING.pod to pod/perlhack.pod. Github will recognize it from this folder and then it will not interfere with the build process or end up on CPAN.

Let's do that then if it works for GitHub.

I also like the idea of collecting GitHub files in the `.github` directory, and using POD instead of Markdown for documentation files.

I'm not sure if the following files could also be candidates to go into that directory:

- [`CODE_OF_CONDUCT.md`](https://github.com/Perl/perl5/blob/blead/CODE_OF_CONDUCT.md)
- [`SECURITY.md`](https://github.com/Perl/perl5/blob/blead/SECURITY.md)

**Comment by rwp0** [comment]
I did rebase doing:

```
 ln -s pod/perlhack.pod .github/CONTRIBUTING.pod
```

Please tell if there's anything else left to do from my side.

**Review by demerphq — APPROVED** [review]

**Comment by demerphq** [comment]
if it passes test ill merge it.

**Comment by Grinnz** [comment]
Seems github isn't showing symlinked docs at all anymore? This definitely used to work https://github.com/Perl/perl5/blob/blead/.github/CONTRIBUTING.pod

**Comment by Grinnz** [comment]
Oh the problem is the symlink is not created correctly. It's relative but needs to be to ../pod/perlhack.pod

**Comment by demerphq** [comment]
On Fri, 2 Sept 2022 at 21:04, Dan Book ***@***.***> wrote:
>
> Oh the problem is the symlink is not created correctly. It's relative but needs to be to ../pod/perlhack.pod

fix pushed, but it didnt make a difference.

Yves


-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by rwp0** [comment]
Yes, seems like GitHub doesn't follow such symlinks:

https://github.com/isaacs/github/issues/348

https://github.com/lxc/lxd/issues/6764

Though its being recognized correctly (as POD):

image

So filling it with the entire content for `perlhack`?

**Comment by demerphq** [comment]
On Fri, 2 Sept 2022 at 20:08, James E Keenan ***@***.***>
wrote:

> On 9/2/22 14:00, Elvin Aslanov wrote:
> > Adding a standard GitHub file
> >
> > See https://github.com/Perl/perl5/community
> > <https://github.com/Perl/perl5/community>
> >
>
> We don't need this. We have pod/perlhack.pod, accessible through
> `perldoc perlhack`.
>
> Let's bear in mind: We existed long before git, and long before
> github.com. We don't have to do anything simply because it's become the
> latest feature on github.


If that is a suggestion to pipe perldoc perlhack into some kind of "convert
to md formatter", then that is a fine idea. If it is that we should just
not do something that would improve our integration with github because we
are the old man on the block and have something else then I disagree.  That
just impedes our community growth for no real good reason.

Its fine to say "this should mostly point at perlhack" for instance, but to
say we shouldnt have one at all seems unreasonably hostile to newer
innovations that we should take advantage of. Especially considering they
are free to us as a project.

cheers,
Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Pull request merged**
