### PR TITLE
remove recursion from yyl_try/yyl_fake_eof

### LINKED ISSUE #17268: Bleadperl v5.31.5-48-g760fdf2808 breaks KRYDE/Filter-gunzip-7.tar.gz
Breaking commit: https://github.com/Perl/perl5/commit/760fdf2808b7158c548dcb6208804ff8d4c97b30

Sample fail report: http://www.cpantesters.org/cpan/report/2bbf525a-f690-11e9-b861-b2173384a6e2

XRef: https://rt.cpan.org/Ticket/Display.html?id=130914

### PR DESCRIPTION
**Pull request by tonycoz**
fixes #17268

### CODE REVIEW

**Comment by xsawyerx** [comment]
@demerphq You're the listed approver. Any chance you could take a look? I would like this merged in the next few days.

**Comment by hvds** [comment]
I'm not familiar with this area of the code, but I'll do my best. I have no problems with the first 3 commits.

For the final one:
- I can believe that (-1) is a safe (unique) value to use for YYL_RETRY, but I haven't checked.
- It isn't obvious to me why PL_bufptr now needs to be set in the affected codepaths. Assuming it does need to be, it makes me wonder if there are other variables derived from PL_bufptr that need to be kept in sync.
- I've no idea why the other two calls to `yyl_keylookup` did not need changing. Even if there is some logical reason those ones cannot return YYL_RETRY, it feels fragile not to cater for that.

I'd have preferred to make the whole thing into a `while (tok != YYL_RETRY)` loop, and let all the paths go through that; but I appreciate it might feel like too large a change at this point. Failing that, it feels too subtle to allow only for specific functions returning YYL_RETRY (or obversely, to allow only for specific groups of functions reaching yyl_fake_eof in their calls). More warnings in the comments clarifying invariants relied on would help.

**Comment by tonycoz** [comment]
> I'm not familiar with this area of the code, but I'll do my best. I have no problems with the first 3 commits.

Thanks.

>     * I can believe that (-1) is a safe (unique) value to use for YYL_RETRY, but I haven't checked.

I've added a comment that addresses this.

>     * It isn't obvious to me why PL_bufptr now needs to be set in the affected codepaths. Assuming it does need to be, it makes me wonder if there are other variables derived from PL_bufptr that need to be kept in sync.

yyl_fake_eof() already modifies PL_bufptr and doesn't restore it to its previous value.

The modification is needed to pass a possibly modified `s` back up to yyl_try(), both because the calls yyl_fake_eof() does can move PL_linestr and because yyl_fake_eof() might advance through the input buffer (eg. when skipping pod) so the updated value needs to be returned to yyl_try() so it can continue parsing.

I considered making the involved functions accept a pointer to s and replacing all the references to `s` to `*pointer`, but that would be invasive, and also slow down all of that code, not just the code trying to invoke the retry.

>     * I've no idea why the other two calls to `yyl_keylookup` did not need changing. Even if there is some logical reason those ones cannot return YYL_RETRY, it feels fragile not to cater for that.

That was a mistake, which the updated push fixes.  I don't know how I missed it, I haven't been 100% over the last few weeks, unfortunately.

> I'd have preferred to make the whole thing into a `while (tok != YYL_RETRY)` loop, and let all the paths go through that; but I appreciate it might feel like too large a change at this point. Failing that, it feels too subtle to allow only for specific functions returning YYL_RETRY (or obversely, to allow only for specific groups of functions reaching yyl_fake_eof in their calls). More warnings in the comments clarifying invariants relied on would help.

Yeah, I was trying to keep the change minimal.

**Comment by hvds** [comment]
Within the limits of my knowledge, looks good to me.

**Comment by tonycoz** [comment]
@xsawyerx is it ok to merge this?  It fixes a regression from 5.30.

**Comment by xsawyerx** [comment]
:+1: to merge.

**Pull request merged**
