### PR TITLE
Smoke me/jkeenan/fix clangpp build gh 19515 20220310

### PR DESCRIPTION
**Pull request by jkeenan**
For: https://github.com/Perl/perl5/issues/19515

### CODE REVIEW

**Review by Leont — APPROVED** [review]

**Comment by jkeenan** [comment]
No smoke test failures attributable to these changes.  Squash two commits, rebase and merge.

**Comment by demerphq** [comment]
Andreas can you confirm the status of the autobundle feature in cpan for us?

Thanks,
Yves

**Comment by andk** [comment]
@demerphq , I do not understand your question, the context of these issues #19515 and #19516 do not seem to lead to CPAN.pm and the autobundle feature;

**Comment by demerphq** [comment]
Umm, sorry, I meant to ask you about a different PR, my bad. Sorry about
that.

Yves

**Pull request merged**
