### PR TITLE
Update CoreList for 5.41.4

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
# Changes
- Update CoreList to list module versions shipped with 5.41.4

Notes:
- The version of CoreList is already set to `5.20240920`
- No new "utilities" shipped with 5.41.4

---------------------------------------------------------------------------------
* [ ] This set of changes requires a perldelta entry, and it is included.
* [ ] This set of changes requires a perldelta entry, and I need help writing it.
* [ ] This set of changes does not require a perldelta entry.

*perldelta entry will be generated at release time

### CODE REVIEW

**Comment by jkeenan** [comment]
This looks good ... but since the presumptive release date (Sep 20) is still four days away, can we be certain that there will be no further changes needed before then?

**Comment by thibaultduponchelle** [comment]
No we are definitely not certain :sweat_smile: 
If some versions are modified, it will require to update CoreList again.
Can we proceed anyway? What do you think?

**Comment by jkeenan** [comment]
> No we are definitely not certain 😅 If some versions are modified, it will require to update CoreList again. Can we proceed anyway? What do you think?

Well, you're the release manager, so ultimately it's your call.  You have to choose between (a) having a committer merge this ticket now and running the risk that a module which we *need* to synch has a version change -- which means a new p.r. -- and (b) waiting until, say, a day before release date to have someone commit this p.r.

With great power comes ... blah, blah, blah ;-)

**Comment by thibaultduponchelle** [comment]
I suggest to just keep this pull request open

**Comment by thibaultduponchelle** [comment]
It's was worth the wait (Storable 3.35)

@jkeenan Now can you please consider merging 🙏🏼

**Pull request merged**
