### PR TITLE
Smoke me/jkeenan/sawyerx/findbin duallife

### PR DESCRIPTION
**Pull request by jkeenan**
Alternative to https://github.com/Perl/perl5/pull/17267.  Forked from sawyer's branch.  Adjusts search for ```@INC``` in ```BEGIN``` block to reflect new position of test file within the core distribution.

But note ...

The ```else``` block within the ```BEGIN``` block will probably need further revision if and when we attempt to release FindBin to CPAN.

When we release to CPAN we should probably run all the code under ```use strict; use warnings;```.

Thank you very much.
Jim Keenan

### CODE REVIEW

**Comment by tonycoz** [comment]
Simply removing the BEGIN block also works.

**Comment by jkeenan** [comment]
> Simply removing the BEGIN block also works.

Which leads me to ask:  If we're moving this to ```dist/``` with an eye toward eventually dual-life-ing it on CPAN, couldn't we simply convert the test to use Test::More?

Thank you very much.
Jim Keenan

**Comment by tonycoz** [comment]
Sure it could use Test::More, though the tests aren't really complex enough to need it.

**Comment by tonycoz** [comment]
This has been applied to blead, but with a simpler fix for the test script.

**Pull request closed without merging**
