### PR TITLE
Update Test::Harness to 3.44

### PR DESCRIPTION
**Pull request by Leont**
This includes changes to support taint-free perl and removes ASCII-isms to better work on EBCDIC

### CODE REVIEW

**Comment by neilb** [comment]
LGTM

**Review by neilb — COMMENTED** [review]
LGTM

**Review by khwilliamson — APPROVED** [review]

**Comment by Leont** [comment]
@jkeenan This probably should not have been merged, given that ASAN builds apparently break.

The quick fix is to skip that one test, I think I'll do that for now.

**Comment by jkeenan** [comment]
On 4/18/22 15:00, Leon Timmermans wrote:
> @jkeenan <https://github.com/jkeenan> This probably should not have been 
> merged, given that ASAN builds apparently break.
> 

Sorry about that.  I checked matrix.cpantesters.org before hitting the 
button.  Test-Harness is about the last place I would have expected ASAN 
complications.
> The quick fix is to skip that one test, I think I'll do that for now.
> 

Good enough.  Thanks.

**Pull request merged**
