### PR TITLE
Update perlcheat.pod removing inconsistency

### PR DESCRIPTION
**Pull request by jidanni**
P.S., "p" and "t" are never explained.

### CODE REVIEW

**Comment by jkeenan** [comment]
> P.S., "p" and "t" are never explained.

I'm not in favor of this change.  The document's DESCRIPTION explains why:
```
This 'cheat sheet' is a handy reference, meant for beginning Perl
programmers. Not everything is mentioned, but 195 features may already
be overwhelming.
```

**Comment by rwp0** [comment]
Looking at the diff, I guess `p` is **pattern**, and `t` is **text** here right?

**Comment by khwilliamson** [comment]
I'm trying to understand the objection.  This just adds the single character `p` to the pod.  How is that creating extra cognitive load?  And I think it would be good to have a sentence explaining what `p` and `t` mean

**Review by tonycoz — APPROVED** [review]
Whoever merges might need to be careful of the added merge commit.

**Comment by khwilliamson** [comment]
I would like @jidanni to repush after rebasing to get rid of that.  Can't we change github so that a rebase is the default instead of the merge?

**Comment by tonycoz** [comment]
WRT the p vs t, as far as I can tell `t` is only used in the comment example, perhaps that could be:
`(?#some comment)` or something similar instead, *without* the following "comment" label.

I think the p is obvious enough in context.

**Comment by jidanni** [comment]
> rebase

I'm using the GitHub web interface and am like grandma with a cellphone.

**Comment by khwilliamson** [comment]
Merged via 

> commit 1c8b66f3dcebedb963116eabf0b583223fe8ee70
 Author: Dan Jacobson <jidanni@jidanni.org>
 Date:   Fri May 24 17:53:09 2024 +0800

**Pull request closed without merging**
