### PR TITLE
Provide code example for 'my' declared in initialization of 'for' loop

### PR DESCRIPTION
**Pull request by jkeenan**
For: https://github.com/Perl/perl5/issues/18260

### CODE REVIEW

**Review by Grinnz — APPROVED** [review]
Seems illustrative. I feel like it would be better to show a strict 'vars' error outside the scope than shadowing, but that is harder to show in a concise example.

**Comment by jkeenan** [comment]
> Seems illustrative. I feel like it would be better to show a strict 'vars' error outside the scope than shadowing, but that is harder to show in a concise example.

I thought about that possibility and concluded that if I showed that error, I'd first have to prepend the code with a comment to the effect that `$i` had not already been declared before the `for` loop.  That verbiage seemed excessive.

**Comment by jkeenan** [comment]
> > Seems illustrative. I feel like it would be better to show a strict 'vars' error outside the scope than shadowing, but that is harder to show in a concise example.
> 
> I thought about that possibility and concluded that if I showed that error, I'd first have to prepend the code with a comment to the effect that `$i` had not already been declared before the `for` loop. That verbiage seemed excessive.

No one has objected to this p.r. since early November, so I intend to merge it to blead within 3 days.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Handled manually in commit dba7cf2eab.

**Pull request closed without merging**
