### PR TITLE
fix a collection of other I32 bugs

### PR DESCRIPTION
**Pull request by tonycoz**
These commits fix a few of the other I32 bugs I suspected when I was reviewing the code for the #20990 work.

I have a few more I haven't investigated yet.

### CODE REVIEW

**Review by demerphq — APPROVED** [review]

**Review by khwilliamson — APPROVED** [review]

**Comment by tonycoz** [comment]
squashed the "squash me" commit and rebased

**Comment by jkeenan** [comment]
@tonycoz, to properly test this pull request, should we be building a perl with any particular configuration arguments in order to get meaningful results?

(This p.r. has 2 approvals, but probably has not yet been tested other than GH actions.)

**Comment by tonycoz** [comment]
To test this properly you need to set PERL_TEST_MEMORY set in the environment to 8 or more, and have that amount of available memory (in GB).

They only make sense for 64-bit platforms, ie. where ptrsize is 8 (or more if that exists.)

**Comment by demerphq** [comment]
IN the perlreapi.pod commit you say "though I suspect it could use some, some members mentioned no longer exist,", which might be the case as this is  a copy of the actual structure. Ill take a look, but i guess your patch will need to be applied first.

Actually, even better maybe would be to drop the perlreapi.pod patch and let me take care of it.

**Comment by tonycoz** [comment]
> Actually, even better maybe would be to drop the perlreapi.pod patch and let me take care of it.

I've removed it.

I also added another fix for a bug that came up while I was testing the rebased code.  Unfortunately I expect we have a number of similar bugs, I think it means we need to add `-Wconversion` to our warnings and follow-up on them, since it caught this one:
```
op.c: In function ‘Perl_check_hash_fields_and_hekify’:
op.c:2745:64: warning: conversion from ‘ssize_t’ {aka ‘long int’} to ‘I32’ {aka ‘int’} may change value [-Wconversion]
 2745 |             SV *nsv = newSVpvn_share(key, SvUTF8(sv) ? -keylen : keylen, 0);
```

This is a big job:
```
$ make opmini.o 2>&1 | grep 'warning:' | wc -l
247
```
and it takes more than just adding a bunch of casts.

**Comment by demerphq** [comment]
> I've removed it.

Ok, I have just pushed https://github.com/Perl/perl5/pull/21241 as promised.

**Comment by tonycoz** [comment]
Pushed as merge commit 03f6a7924c84dfae6ebc442d73072b6e26ae3896

**Pull request closed without merging**
