### PR TITLE
Clarify when qx/STRING/ returns undef

### LINKED ISSUE #16572: When does qx/STRING/ return undef?
Migrated from [rt.perl.org#133235](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133235) (status was 'open')

Searchable as RT133235$

### PR DESCRIPTION
**Pull request by mavit**
Fixes #16572.

### CODE REVIEW

**Comment by tonycoz** [comment]
It can also return undef if the pipe() or fork() fails.  Also complicated by whether a shell is used.

**Comment by khwilliamson** [comment]
@mavit, could you revise resubmit in light of @tonycoz comments?

**Comment by mavit** [comment]
How's this?

**Comment by atoomic** [comment]
@tonycoz could you please do a final review on this PR?
thanks

**Review by khwilliamson — APPROVED** [review]

**Pull request merged**
