### PR TITLE
Move PerlIO::scalar into core

### PR DESCRIPTION
**Pull request by Leont**
This moves PerlIO::scalar into core. This prevents unpredictable behavior when the module can't be loaded (e.g. #21275), and also allows miniperl to run tests that need :scalar handles.

### CODE REVIEW

**Comment by demerphq** [comment]
Nice. The commit message could be cleaned up tho. "prevents" is duplicated and "make run tests" doesn't make sense.

**Review by demerphq — APPROVED** [review]

**Review by demerphq — APPROVED** [review]

**Comment by haarg** [comment]
There are a number of CPAN modules that explicitly load PerlIO::scalar. It may be good to leave a stub module.

**Comment by Leont** [comment]
> There are a number of CPAN modules that explicitly load PerlIO::scalar. It may be good to leave a stub module.

Fair, I've reintroduced a stub.

**Comment by Grinnz** [comment]
I can't tell from the tests, but does `open my $fh, '<:scalar', \$x` still work with this change? Not that I think it was commonly used explicitly

**Comment by Leont** [comment]
> I can't tell from the tests, but does open my $fh, '<:scalar', \$x still work with this change? Not that I think it was commonly used explicitly

Yes it does. The only difference is that :scalar is now already included in the main binary, same way `:unix`/`:perlio`/`:crlf`/`:raw`/etc… have always been.

**Pull request merged**
