### PR TITLE
IO::Socket::UNIX: synchronize behavior with module documentation

### PR DESCRIPTION
**Pull request by vividsnow**
IO::Socket docs states that passing Blocking => 0 will be set socket to non-blocking mode

### CODE REVIEW

**Comment by jkeenan** [comment]
> IO::Socket docs states that passing Blocking => 0 will be set socket to non-blocking mode

We have to be careful about modifying the behavior of a module which has shipped with the Perl core distribution since 1998 and upon which a tremendous amount of production code is likely to depend.  We have to consider the possibility that the code is correct and that it is the documentation which is wrong.

I don't know enough about sockets to evaluate this further, so others should study this.

Thank you very much.
Jim Keenan

**Comment by Leont** [comment]
This looks logical to me.

**Comment by toddr** [comment]
t/porting/authors.t - vividsnow  <vividsnow@gmail.com> not found in AUTHORS

**Comment by toddr** [comment]
2020-05-18T11:43:31.2651094Z # not ok 4 - dist/IO/lib/IO/Socket/UNIX.pm version 1.41
2020-05-18T11:43:31.2825000Z t/porting/cmp_version .......................................... FAILED at test 4

**Comment by toddr** [comment]
It looks like the only remaining change required is to bump $VERSION.

**Comment by toddr** [comment]
Thank you for this submission @vividsnow. We are currently stabilizing for Perl 5.32.0. I think our current protocol requires we hold this pull request until that is released in about a month!

**Comment by vividsnow** [comment]
ok, thank you

**Pull request merged**
