### PR TITLE
Consistent Compilation Error Behavior.

### PR DESCRIPTION
**Pull request by demerphq**
This is a set of patches to make our rules for errors during compilation consistent. Currently they are a bit random. 

When the stop on first error change was introduced I didnt understand about yyquit() so I did some hacky logic to handle syntax errors properly and it means that the way eval errors were reported wasnt consistent, this makes it more consistent.

This also ensures that `$SIG{__DIE__}` is called whenever the eval fails to compile without actually generating a croak(), and ensures that any errors produced by the eval are passed into the handler as they would be for other errors. 

See issue https://github.com/Perl/perl5/issues/20296

### CODE REVIEW

**Comment by jkeenan** [comment]
On FreeBSD-12, using `clang10` as the compiler, I built my customary threaded `perl` from this branch.  I then tried to install all the CPAN modules which have been cited in the 2 BBC tickets: https://github.com/Perl/perl5/issues/20291 and https://github.com/Perl/perl5/issues/20346.
```
./bin/cpanm HTML::Mason Quote::Code BenchmarkAnything::Schema Mojolicious::Plugin::RenderCGI Quote::Ref Sub::Documentation
```
I should note that I wasn't really expecting this p.r. to clear up all those failures, as this is a situation where we know that some of the CPAN code is sub-optimal.  None of the above modules succeeded, but there was one new result: a test in Mojolicious itself failed, thereby preventing us from getting to its reverse dependencies.  That failure looks like this:
```
t/mojo/template.t .......................... 1/? 
#   Failed test 'exception in nested template'
#   at t/mojo/template.t line 778.
#                   'Bareword "bar" not allowed while "strict subs" in use at template line 1.
# Context:
#   143:   # Use a local stack trace for compile exceptions
#   144:   my $compiled = $self->compiled;
#   145:   unless ($compiled) {
#   146:     my $code = $self->_compile->code;
#   147:     monkey_patch $self->namespace, '_escape', $self->escape;
#   148:     return Mojo::Exception->new($@)->inspect($self->unparsed, $code)->trace->verbose(1)
#   149:       unless $compiled = eval $self->_wrap($code, @_);
#   150:     $self->compiled($compiled);
#   151:   }
#   152: 
#   153:   # Use a real stack trace for normal exceptions
# Traceback (most recent call first):
#   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 148, in "Mojo::Template::__ANON__"
#   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 163, in "Mojo::Template::process"
#   File "template", line 3, in "Mojo::Template::render"
#   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 160, in "Mojo::Template::Sandbox::__ANON__"
#   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 160, in "(eval)"
#   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 163, in "Mojo::Template::process"
#   File "t/mojo/template.t", line 769, in "Mojo::Template::render"
# '
#     doesn't match '(?^u:test\n\nBareword "bar".+in use at template line 1\.)'
# Looks like you failed 1 test of 226.
t/mojo/template.t .......................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/226 subtests 
```
At least as of two days ago, this test is passing in blead.  A test failure in Mojolicious is certainly as much of a blocker as a test failure in HTML::Mason.  Needs more investigation.

**Comment by bram-perl** [comment]
Relevant issue: https://github.com/Perl/perl5/issues/20296

**Comment by demerphq** [comment]
@jkeenan the underlying nature of this problem is that what happens in a given string eval is only incidentally deterministic, and from the point of view of a single error is non-deterministic. Thus whether a given eval error will trigger someones `$SIG{__DIE__}` depends on the larger context of the code being evaled and the presence of *other* errors. 

This patch makes the behavior "strongly" deterministic, in that the `$SIG{__DIE__}` will fire for ALL eval STRING errors. 

This will very likely surface existing bugs in `$SIG{__DIE__}` related code, bugs that could be triggered by supplying just the right different test case than the ones they were using. It is an expected outcome of fixing indeterminate behavior. The best we can do is help people fix their code to deal with it and make things strongly deterministic in the future. I guess we could introduce a round of warnings, and then fix it in a following cycle.

Anyway, ill check out the issue that @bram-perl referenced.

**Comment by demerphq** [comment]
@jkeenan fwiw:

```
t/mojo/template.t .......................... 1/? 
#   Failed test 'exception in nested template'
#   at t/mojo/template.t line 778.
#                   'Bareword "bar" not allowed while "strict subs" in use at template line 1.
# Context:
#   143:   # Use a local stack trace for compile exceptions
#   144:   my $compiled = $self->compiled;
#   145:   unless ($compiled) {
#   146:     my $code = $self->_compile->code;
#   147:     monkey_patch $self->namespace, '_escape', $self->escape;
#   148:     return Mojo::Exception->new($@)->inspect($self->unparsed, $code)->trace->verbose(1)
#   149:       unless $compiled = eval $self->_wrap($code, @_);
#   150:     $self->compiled($compiled);
#   151:   }
#   152: 
#   153:   # Use a real stack trace for normal exceptions
# Traceback (most recent call first):
#   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 148, in "Mojo::Template::__ANON__"
#   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 163, in "Mojo::Template::process"
#   File "template", line 3, in "Mojo::Template::render"
#   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 160, in "Mojo::Template::Sandbox::__ANON__"
#   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 160, in "(eval)"
#   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 163, in "Mojo::Template::process"
#   File "t/mojo/template.t", line 769, in "Mojo::Template::render"
# '
#     doesn't match '(?^u:test\n\nBareword "bar".+in use at template line 1\.)'
```

seems to suggest their test pattern is to restrictive. If they remove the "test\n\n" prefix they would get a test that pases in both cases.

**Comment by jkeenan** [comment]
> @jkeenan fwiw:
> 
> ```
> t/mojo/template.t .......................... 1/? 
> #   Failed test 'exception in nested template'
> #   at t/mojo/template.t line 778.
> #                   'Bareword "bar" not allowed while "strict subs" in use at template line 1.
> # Context:
> #   143:   # Use a local stack trace for compile exceptions
> #   144:   my $compiled = $self->compiled;
> #   145:   unless ($compiled) {
> #   146:     my $code = $self->_compile->code;
> #   147:     monkey_patch $self->namespace, '_escape', $self->escape;
> #   148:     return Mojo::Exception->new($@)->inspect($self->unparsed, $code)->trace->verbose(1)
> #   149:       unless $compiled = eval $self->_wrap($code, @_);
> #   150:     $self->compiled($compiled);
> #   151:   }
> #   152: 
> #   153:   # Use a real stack trace for normal exceptions
> # Traceback (most recent call first):
> #   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 148, in "Mojo::Template::__ANON__"
> #   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 163, in "Mojo::Template::process"
> #   File "template", line 3, in "Mojo::Template::render"
> #   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 160, in "Mojo::Template::Sandbox::__ANON__"
> #   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 160, in "(eval)"
> #   File "/usr/home/jkeenan/.cpanm/work/1664387589.71629/Mojolicious-9.27/blib/lib/Mojo/Template.pm", line 163, in "Mojo::Template::process"
> #   File "t/mojo/template.t", line 769, in "Mojo::Template::render"
> # '
> #     doesn't match '(?^u:test\n\nBareword "bar".+in use at template line 1\.)'
> ```
> 
> seems to suggest their test pattern is to restrictive. If they remove the "test\n\n" prefix they would get a test that pases in both cases.

Okay, I have prepared a pull request for Mojolicious which I will submit once this p.r. is merged into blead.

**Comment by haarg** [comment]
I believe the test failure in Mojo is pointing to a real bug in this PR. Test case:
```
perl -e'use strict; use warnings; $SIG{__DIE__} = sub { die $@ }; eval { eval "bar"; warn "after strict error in eval [$@]"; }; if ($@) { print "outer eval failed [$@]\n" }'
```
The inner eval will fail during compilation due to strict. We should expect that the "after strict error" message will be printed. That is what happens on stable and blead. With this PR, we instead get the "outer eval failed" message. If you remove the `__DIE__` handler, it produces the "after strict error" message as expected.

**Comment by haarg** [comment]
Also, the behavior is not consistent for all compile time errors:
```
perl -e'use strict; use warnings; $SIG{__DIE__} = sub { die $@ }; eval { eval "]"; warn "after compile error in eval [$@]"; }; if ($@) { print "outer eval failed [$@]\n" }'
```
This is a syntax error rather than a strict error. It consistently produces the "after compile error" message, with or without this PR.

**Comment by bram-perl** [comment]
> Anyway, ill check out the issue that @bram-perl referenced.

I didn't mean it as something to check out, I **assumed** this PR was fixing #20296 but I might have been mistaken..
(I have not yet looked at the changes in the PR)

**Comment by demerphq** [comment]
@haarg i will check into your test case. I am focusing on getting https://github.com/Perl/perl5/pull/20398 sorted out first tho. I will follow up on this one once that has been pushed. (I suspect they might be related subtly)

**Comment by demerphq** [comment]
@bram-perl I got confused, i didnt realize that was my original bug report.

**Comment by demerphq** [comment]
@haarg: as regards to your also, yes, indeed the whole point of this patch is to make this consistent. I am now testing a fix for the test case you showed, thanks for that!

**Comment by demerphq** [comment]
@haarg i added your test case to my patch, and reordered when the sig die handler is called so it is handled in the right scope. Thanks for the pointer.

**Comment by haarg** [comment]
I can confirm that this now handles my test cases and the Mojo test correctly.

**Comment by demerphq** [comment]
@haarg @jkeenan am I correct in thinking this is good to go now?

**Comment by demerphq** [comment]
I am going to merge this so it can be part of  5.37.9 and so we can shake out all the bugs related to early compilation halts in one release (5.38). We already have multiple such patches in this sequence. So I am merging this now.

**Pull request merged**
