### PR TITLE
perlxs changes from @apparluk

### PR DESCRIPTION
**Pull request by khwilliamson**
This replaces PR #18247

### CODE REVIEW

**Review by xsawyerx — APPROVED** [review]

**Comment by ghost** [comment]
Run rpctest.pl and verify the correctness of the output before merging.

**Comment by tonycoz** [comment]
This is a Linux specific change, non-glibc systems still have the headers visible as `rpc/rpc.h` etc (I checked FreeBSD 13 and OpenIndiana).

**Comment by khwilliamson** [comment]
So does Linux still work with the old scheme, or do we need a Configure probe?

**Comment by Grinnz** [comment]
This is just documentation, no functionality needs to change.

**Comment by khwilliamson** [comment]
Note that this commit is now updated

**Pull request merged**
