### PR TITLE
typos: fixing usally and patern

### PR DESCRIPTION
**Pull request by stensonb**

### CODE REVIEW

**Comment by stensonb** [comment]
not sure how to fix this: https://github.com/Perl/perl5/commit/567cde8c92b98a1aaf1cbbe7c80b42803e23dc37/checks?check_suite_id=367424092

any pointers?

**Comment by jkeenan** [comment]
On 12/19/19 3:53 PM, Bryan Stenson wrote:
> not sure how to fix this: 
> https://github.com/Perl/perl5/commit/567cde8c92b98a1aaf1cbbe7c80b42803e23dc37/checks?check_suite_id=367424092
> 
> any pointers?
> 

Don't worry about those github actions.  As committer, I'll take care of it.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Handled via commit 4357af6ce6bbf62e83c554355bd8063b6fd0880a.  Thank you very much.

**Comment by stensonb** [comment]
happy to help

**Pull request closed without merging**
