### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by vaitkus**
This PR fixes multiple typos and minor grammatical issues in the pod files.

### CODE REVIEW

**Comment by jkeenan** [comment]
I strongly advise that this pull request be rejected in its current form.

1. The author has failed to run `make test_porting` and the consequent porting test failures mean that the p.r. doesn't make it through our CI testing.  Moreover, the failure to run 'make test_porting` suggests that `make test` wasn't run, either.
2. It's one thing to correct spelling or grammar errors in files that are pure documentation.  But this pull request also makes changes to 4 C/guts-level files.
```
$ git diff -w blead..HEAD | ack '^diff ' | sort
diff --git a/embed.fnc b/embed.fnc
diff --git a/embed.h b/embed.h
diff --git a/pod/perl5101delta.pod b/pod/perl5101delta.pod
diff --git a/pod/perl5122delta.pod b/pod/perl5122delta.pod
...
diff --git a/pod/perlvar.pod b/pod/perlvar.pod
diff --git a/pod/perlvms.pod b/pod/perlvms.pod
diff --git a/proto.h b/proto.h
diff --git a/sv.c b/sv.c
```

**Comment by leonerd** [comment]
> 2\. It's one thing to correct spelling or grammar errors in files that are pure documentation.  But this pull request also makes changes to 4 C/guts-level files.

Interesting... I'm not seeing that in the github view. Just 50 Pod files.

**Comment by mauke** [comment]
At minimum, this PR needs some serious disentanglement. For example, one of the commits only exists to fix a misspelling introduced by another commit in this same PR, and there is a merge commit in here for some reason.

> But this pull request also makes changes to 4 C/guts-level files.

No, those are commits that exist in blead, but not in this branch, so the diff from blead to here shows them as "removed". See 3a769e864b479894fcc1245b38738679bc1a6935.

**Comment by vaitkus** [comment]
Sorry for a messy PR, a clear skill issue. I would be happy to fix it or create a new one instead with some guidance.

1. I indeed failed to run the test locally. I have run them now and will fix the problems accordingly. This would also require updating comments in `regcomp.sym` since `pod/perldebguts.pod` is generated from it. Is that OK, or it would be better to leave both of these files alone?
2. I made the merge commit to sync my branch with the bleed. What would have been a better way to go about this?
3. I did not (at least definitely not on purpose) modify the 4 C/guts-level files that @jkeenan mentioned.

@mauke could you provide a bit more information on how I could present this PR in a suitable form?

**Comment by mauke** [comment]
Not sure what the optimal form of this PR would look like.

For commits that just fix earlier commits, combining them via interactive rebase is a good idea (`git rebase -i`, particularly the `fixup` and `squash` commands).

Re 2: Rebase your branch on top of blead (`git rebase blead`). If there are any conflicts, run `git status` and it should tell you what to do next (it generally involves editing the files with the conflicts, marking them as resolved with `git add`, and then `git rebase --continue`). If you're doing this after you've already created a PR from your branch, the `git push` to github will fail. Use `git push --force-with-lease` to update the PR with your rebased version of the branch.

**Comment by vaitkus** [comment]
@mauke Thank you for the explanation, that was extremely useful!

I removed the merge commit and squashed some of the related commits together. Hopefully it is more manageable now.

**Comment by iabyn** [comment]
As a general comment, I don't like the commit messages. Each message should stand alone, and if seen randomly 10 years later, should give an idea of what part of the code or what functionality is being affected. For example,

_Fix a few issues related to ordinal numbers._ 

that sounds at first glance as if the commit changes the behaviour of perl integer handling. A better commit message might be:

_perlbook.pod: fix a few issues related to ordinal numbers._

**Comment by vaitkus** [comment]
@iabyn I can definitively rewrite the messages as recommended. For commits that affect more than one pod file, would referring to the pod/ directory be sufficient? E.g.:

_pod/: correct usage of plural vs singular._

**Comment by iabyn** [comment]
On Fri, Sep 06, 2024 at 04:32:27AM -0700, Antanas Vaitkus wrote:
> @iabyn I can definitively rewrite the messages as recommended. For commits that affect more than one pod file, would referring to the pod/ directory be sufficient? E.g.:
> 
> _pod/: correct usage of plural vs singular._

Anything that gives a clue is fine, e.g.

    "fix spelling errors in various doc files"
    "pod: fix assorted spelling errors"

-- 
31 Dec 1661: "I have newly taken a solemne oath about abstaining from plays".
 1 Jan 1662: "And after ... we went by coach to the play".
    -- The Diary of Samuel Pepys

**Comment by vaitkus** [comment]
@iabyn, I have updated the log messages.

**Pull request merged**
