### PR TITLE
Remove docs of broken SAVELONG

### PR DESCRIPTION
**Pull request by khwilliamson**
This macro can't work, because it calls a non-existent function: save_long().

### CODE REVIEW

**Comment by tonycoz** [comment]
It was removed in 7008caa915ad99e650acf2aea40612b5e48b7ba2 after being marked deprecated in 57f51a64ab975e4a9036295a6bc803071e86de43, presumably because it was in mathoms.c.

It was moved to mathoms.c in 2053acbf3eca3963d3a31404e10d54b0900f80ed though no reason is given.

There's still some support code in regen/scope_types.pl, scope_types.h, scope.c and sv.c for it: the definition and handling of SAVEt_LONG.

**Comment by jkeenan** [comment]
> It was removed in [7008caa](https://github.com/Perl/perl5/commit/7008caa915ad99e650acf2aea40612b5e48b7ba2) after being marked deprecated in [57f51a6](https://github.com/Perl/perl5/commit/57f51a64ab975e4a9036295a6bc803071e86de43), presumably because it was in mathoms.c.
> 
> It was moved to mathoms.c in [2053acb](https://github.com/Perl/perl5/commit/2053acbf3eca3963d3a31404e10d54b0900f80ed) though no reason is given.
> 
> There's still some support code in regen/scope_types.pl, scope_types.h, scope.c and sv.c for it: the definition and handling of SAVEt_LONG.

@tonycoz, is your comment meant as an objection to this pull request -- or just as a comment on it?  thanks.

**Comment by tonycoz** [comment]
> or just as a comment on it?

Some bits of the long saving code persists: the `SAVEt_`, and code in scope.c, sv.c, I think those could be cleaned up.

Mostly as a comment.  I saw the commit message:
```
This macro can't work, because it calls a non-existent function:
save_long().
```
and wondered how the orphan macro came about.  I thought others might also wonder, the commit message could refer back to when save_long() was removed rather than leaving it as a mystery.

**Comment by khwilliamson** [comment]
Should the extant support code be removed?

**Comment by tonycoz** [comment]
> Should the extant support code be removed?

I think so.

**Comment by jkeenan** [comment]
> > Should the extant support code be removed?
> 
> I think so.

@khwilliamson, could you update this p.r. as suggested by @tonycoz ? Thanks.

**Review by tonycoz — APPROVED** [review]

**Pull request merged**
