### PR TITLE
Document suggestion to use libffi for simple library bindings

### LINKED ISSUE #16671: Document suggestion to use libffi for simple library bindings
Migrated from [rt.perl.org#133474](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133474) (status was 'open')

Searchable as RT133474$

### PR DESCRIPTION
**Pull request by Grinnz**
PR to resolve https://github.com/Perl/perl5/issues/16671

### CODE REVIEW

**Review by atoomic — CHANGES_REQUESTED** [review]
porting/podcheck.t is also failing there as shown by the smokers
please fix and resubmit
```
#     to "FFI::Platypus" near line 82 of dist/ExtUtils-ParseXS/lib/perlxs.pod
#     to "FFI::Raw" near line 82 of dist/ExtUtils-ParseXS/lib/perlxs.pod
```

**Comment by Grinnz** [comment]
These are also valid pod links.

**Comment by atoomic** [comment]
I see you want to use the `--add-link` option for them
`  ./perl -I../lib porting/podcheck.t --add_link MODULE ...`

**Comment by Grinnz** [comment]
I've run this to add the modules

**Comment by xsawyerx** [comment]
:+1: Thank you!

**Pull request merged**
