### PR TITLE
Remove customizations for Compress::Raw::* in core

### PR DESCRIPTION
**Pull request by jkeenan**
Compress::Raw::Bzip2: https://github.com/Perl/perl5/issues/21262

Compress::Raw::Zlib:  https://github.com/Perl/perl5/issues/21263

### CODE REVIEW

**Comment by jkeenan** [comment]
@pmqs or @tonycoz: Does this look okay?

**Comment by tonycoz** [comment]
You can remove the entries from `t/porting/customized.dat` too.

**Comment by pmqs** [comment]
> @pmqs or @tonycoz: Does this look okay?

Yes, looks fine

**Comment by jkeenan** [comment]
> You can remove the entries from `t/porting/customized.dat` too.

Done; thanks.   Once the test suite has run, I'll merge into blead and then synch the two distros with upstream.

**Pull request merged**
