### PR TITLE
Add strict and warnings to some .PL files

### PR DESCRIPTION
**Pull request by atoomic**

### CODE REVIEW

**Comment by Grinnz** [comment]
FTR this will prevent installation of these dual life modules (Module-CoreList and XSLoader) on perls older than 5.6, but I don't think anyone cares about that.

**Comment by khwilliamson** [comment]
Could that be avoided with 'use if' ?

**Comment by Grinnz** [comment]
if.pm also did not exist before 5.6 so sadly not :)

**Comment by Leont** [comment]
> FTR this will prevent installation of these dual life modules (Module-CoreList and XSLoader) on perls older than 5.6, but I don't think anyone cares about that.

Even MakeMaker and Test::More dropped <5.6 support in 2007. This is a non-issue.

**Comment by atoomic** [comment]
this would work with 5.6 and later, but do we really want this boilerplate?
```perl
BEGIN {
  if ( $] >= 5.008 ) {
    require strict;
    strict->import;
    require warnings;
    warnings->import;
  }
}
```

**Comment by atoomic** [comment]
@Leont  / @Grinnz let me know if you like that BEGIN block or would prefer a straight `use strict; use warnings`

**Comment by Grinnz** [comment]
No that does not help anything. 5.6 has strict and warnings.

**Comment by khwilliamson** [comment]
@pali does this impact Devel::PPPort?

**Comment by atoomic** [comment]
@Grinnz ok switched back to `use strict; use warnings` I removed the `our` 
@khwilliamson it should not impact D:PP

**Comment by pali** [comment]
@khwilliamson seems that in this PR there are no changed to Devel::PPPort, so I guess it cannot affect Devel::PPPort.

**Pull request merged**
