### PR TITLE
report an error when making an object of an incomplete class

### LINKED ISSUE #22159: feature class: attempting to create an object of an incomplete class asserts
Module:

**Description**

Perl crashes with an assertion (debugging builds) or an unhelpful message (non-debugging) if you attempt to create an object of an incomplete class.

**Steps to Reproduce**

```
$ ~/perl/blead/bin/perl5.39.9 -Mfeature=class -e 'eval "class Foo {"; Foo->new'
class is experimental at (eval 1) line 1.
perl5.39.9: class.c:170: injected_constructor: Assertion `aux->xhv_class_initfields_cv' failed.
Aborted
```

**Expected behavior**

A helpful error message.

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 39 subversion 9) configuration:
  Commit id: bc2427acad39d9b52d84a987047ca10c3c2f7b77
  Platform:
    osname=linux
    osvers=6.1.0-17-amd64
    archname=x86_64-linux
    uname='linux venus 6.1.0-17-amd64 #1 smp preempt_dynamic debian 6.1.69-1 (2023-12-30) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dprefix=/home/tony/perl/blead'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2 -g'
    cppflags='-fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='12.2.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lgdbm -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.36'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Mar  4 2024 11:01:24
  %ENV:
    PERLBREW_BASHRC_VERSION="0.43"
    PERLBREW_HOME="/home/tony/.perlbrew"
    PERLBREW_MANPATH=""
    PERLBREW_PATH="/home/tony/perl5/perlbrew/bin"
    PERLBREW_ROOT="/home/tony/perl5/perlbrew"
    PERLBREW_VERSION="0.67"
  @INC:
    /home/tony/perl/blead/lib/site_perl/5.39.9/x86_64-linux
    /home/tony/perl/blead/lib/site_perl/5.39.9
    /home/tony/perl/blead/lib/5.39.9/x86_64-linux
    /home/tony/perl/blead/lib/5.39.9

```

### PR DESCRIPTION
**Pull request by tonycoz**
instead of asserting or crashing

Fixes #22159

### CODE REVIEW

**Comment by xenu** [comment]
Why are incomplete classes even a thing? Shouldn't the creation of the class be aborted on syntax error?

**Comment by tonycoz** [comment]
Force push moved the message tests from `lib/warnings.t` where I originally had them to `t/lib/croak.t` since they are fatal.

> Why are incomplete classes even a thing? Shouldn't the creation of the class be aborted on syntax error?

That's a more complex change than I would want at this point in the dev cycle.

I'll have a look at it this afternoon, though I found a less painful class issue to work on first.  We'd still need the croak for the BEGIN{} test case.

**Comment by jkeenan** [comment]
In the course of working on https://github.com/Perl/perl5/issues/22159, I had occasion to update my CPAN module Devel::Git::MultiBisect.  For that purpose I needed to transform the one-liner provided in that ticket by @tonycoz into a test file.
```
$ cat /tmp/gh-22159-class.t
#!./perl

BEGIN {
    chdir 't' if -d 't';
    require './test.pl';
    set_up_inc('../lib');
    require Config;
}

use v5.36;
use feature 'class';
no warnings 'experimental::class';


# https://github.com/Perl/perl5/issues/22159
{
    #'eval "class Foo {"; Foo->new'
    local $@;
    eval {
        eval "class Foo {"; Foo->new;
    };
    ok( ! $@, "No exception" ) or diag($@);
}

done_testing;
```
I then ran this through Tony's branch, first on a plain build, then on a debugging build.
```
$ git checkout gh-22166-tonycoz-22159-incomplete-class-20240422
$ regular_configure && make minitest_prep
$ ./miniperl -Ilib /tmp/gh-22159-class.t 
not ok 1 - No exception
# Failed test 1 - No exception at /tmp/gh-22159-class.t line 22
# Cannot create an object of incomplete class "Foo" at /tmp/gh-22159-class.t line 20.
1..1

$ git clean -dfxq

$ sh ./Configure -des -Dusedevel -DDEBUGGING && make minitest_prep

$ ./miniperl -Ilib /tmp/gh-22159-class.t 
not ok 1 - No exception
# Failed test 1 - No exception at /tmp/gh-22159-class.t line 22
# Cannot create an object of incomplete class "Foo" at /tmp/gh-22159-class.t line 20.
1..1
```
LGTM; I also did a debugging build on FreeBSD-13 and ran the full test suite: PASS.

**Review by jkeenan — APPROVED** [review]

**Comment by leonerd** [comment]
> Why are incomplete classes even a thing? Shouldn't the creation of the class be aborted on syntax error?

@xenu Possibly, but detecting that and rolling it back is really difficult. The class-enabled package gets created at the point of the `class NAME` keyword, but it isn't until the end of the block that it gets finished off to the point that a constructor can be invoked. These failures are what happens if you try to invoke a constructor after the former but before the latter.

**Review by leonerd — APPROVED** [review]
Yup, exactly what I would have done.

And you found the other `BEGIN { Thing->new }` case as well.

LGTM; ship it!

**Comment by tonycoz** [comment]
> > Why are incomplete classes even a thing? Shouldn't the creation of the class be aborted on syntax error?
> 
> @xenu Possibly, but detecting that and rolling it back is really difficult. The class-enabled package gets created at the point of the `class NAME` keyword, but it isn't until the end of the block that it gets finished off to the point that a constructor can be invoked. These failures are what happens if you try to invoke a constructor after the former but before the latter.

The rollback is pretty painful, but I do think it's necessary.

This one of the few cases where if you do see such a compilation error you can't recover and supply a new correct definition.

For legacy classes you can simply supply the new class definition and you will have successfully defined the class, with `class` keyword classes, you cannot do that.  You might see some redefinition warnings, but you can do the replacement.

Of course, this isn't only a problem for redefinition after error, it's also a problem with redefinition after success, which perl also generally allows.

**Pull request merged**
