### PR TITLE
Add ceil & floor to builtin

### PR DESCRIPTION
**Pull request by JRaspass**
I figured I would try my hand at adding a couple of ops to `builtin`. Like most people I resent having to load the heavy `POSIX` to do simple operations like `ceil` and `floor`.

@leonerd Feel free to close this if it doesn't fit in with your grand vision for `builtin`.

Marking it as a draft for now as I still need to add logic to `B::Deparse` but feel free to let me know what else I've missed.

### CODE REVIEW

**Comment by leonerd** [comment]
> I figured I would try my hand at adding a couple of ops to `builtin`. Like most people I resent having to load the heavy `POSIX` to do simple operations like `ceil` and `floor`.
> 
> @leonerd Feel free to close this if it doesn't fit in with your grand vision for `builtin`.

In fact these two were probably next on my list to add, I just hadn't got around to doing it yet. They're a great fit - exactly for the reason you say. So thanks for this :)

> Marking it as a draft for now as I still need to add logic to `B::Deparse` but feel free to let me know what else I've missed.

Deparse should be almost a one-liner; the main logic for most of the builtins is already there so it just needs a couple more cases adding like these ones:

https://github.com/Perl/perl5/blob/blead/lib/B/Deparse.pm#L6640

Looking at your test results, I see two failures:

```
 porting/cmp_version.t                                              (Wstat: 0 Tests: 3 Failed: 2)
  Failed tests:  1, 3
perf/opcount.t                                                     (Wstat: 0 Tests: 2596 Failed: 2)
  Failed tests:  2595-2596
```

Of those, `cmp_version` is a simple one, to remember to bump the `$VERSION` in some edited files. It helpfully tells you which:

```
 # not ok 1 - ext/Opcode/Opcode.pm version 1.55
# not ok 3 - lib/builtin.pm version 0.001
porting/cmp_version.t ................................................ 
Failed 2/3 subtests 
```

Don't forget to bump B/Deparse.pm too when you add that logic.

The opcount one is more fun:

```
# Failed test 2595 - builtin::ceil is replaced with direct opcode at perf/opcount.t line 67
# expected 1, got 0: ceil
# Failed test 2596 - builtin::floor is replaced with direct opcode at perf/opcount.t line 67
# expected 1, got 0: floor
perf/opcount.t ....................................................... 
Failed 2/2596 subtests 
```

That suggests that the callchecker didn't successfully rewrite the optree. You'd have to dig more into that one and see where it went wrong. I'd suggest peering at the output of:

```
$ ./perl -Ilib -MO=Concise -E 'say builtin::ceil(1.23)'
```

**Comment by leonerd** [comment]
Random guess: did const-folding happen first? Maybe try testing on

```perl
my $one_point_five = 1.5;

test_opcount ... sub { builtin::floor($one_point_five) }
```

**Comment by JRaspass** [comment]
@leonerd Thanks for your help, looks like all the checks are passing now :tada:

**Comment by JRaspass** [comment]
Found a nice easy win for a builtin ceil too in https://github.com/Perl/perl5/pull/19360/commits/843b573.

**Comment by leonerd** [comment]
The builtin stuff looks good now.

Can you take out the change to `Tie::SubstrHash` though, and we'll move that to a separate commit. That will need to account for the `experimental::builtin` warnings I'm about to add in https://github.com/Perl/perl5/pull/19359 - but I'll merge this one first.

**Comment by JRaspass** [comment]
It is a separate commit, but I presume you mean a separate PR. Technically it would be unaffected since `Tie::SubstrHash` doesn't use warnings (or strict :see_no_evil:), still want it in a different PR?

**Comment by leonerd** [comment]
Separate PR I meant, yes.
But yes, it's useful to split the "create a mechanism" from the "use mechanism in existing code" changes, in case of needing to revert one of them.

**Review by leonerd — APPROVED** [review]

**Comment by leonerd** [comment]
Looking good. I'll hit the merge button once it's been CI'ed

**Pull request merged**
