### PR TITLE
README: make the GitHub and root directory match

### PR DESCRIPTION
**Pull request by rjbs**
…by using a symlink!

### CODE REVIEW

**Review by leonerd — APPROVED** [review]
LGTM

**Review by book — APPROVED** [review]

**Review by rwp0 — APPROVED** [review]

**Comment by Grinnz** [comment]
The symlink is not necessary - github will use the root README.md, the only reason to also have one in .github is so it doesn't need to be in root.

**Comment by Grinnz** [comment]
Oh I missed that the root README is not being renamed to README.md. I'm not sure this will work with the symlink.

**Comment by Grinnz** [comment]
It seems like it is working at https://github.com/Perl/perl5/tree/42557cf44325545afd1c1455ebfeecbc2d23157c but I'm not sure if that is indicative (I've been fooled before)

**Pull request merged**
