### PR TITLE
Use dNOOP for otherwise empty declarations

### LINKED ISSUE #17725: Building with -DNO_LOCALE_NUMERIC has an error in numeric.c
Module:

**Description**

There is a problem building perl with `NO_LOCALE_NUMERIC` defined.  This is similar to #16771, but apparently I was mistaken that it was fixed in v5.30.0 as I have the problem on that tag as well.

This could be a gcc vs clang issue as OpenBSD switched the system compiler to clang since I reported #16771 as fixed.

```
$ ./Configure -de -Accflags='-DNO_LOCALE_NUMERIC' -Dusedevel && make
...
cc -c -DPERL_CORE -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_FORTIFY_SOURCE=2 -DNO_LOCALE_NUMERIC -std=c89 -O2 -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement numeric.c
numeric.c:38:8: error: ISO C90 forbids mixing declarations and code [-Werror,-Wdeclaration-after-statement]
    NV result;
       ^
1 error generated.
*** Error 1 in /home/afresh1/perl (makefile:246 'numeric.o': @`sh  cflags "optimize='-O2'" numeric.o`  numeric.c)
```

**Steps to Reproduce**

./Configure -de -Accflags='-DNO_LOCALE_NUMERIC' -Dusedevel && make

**Expected behavior**

I expect perl to build successfully and be able to run `make test`

**Perl configuration**

I don't get a working perl from this,  but it is blead@182d7c4db2d316d74a275009ee5e30226cb0121d, but I also see the issue on the v5.30.0 and v5.30.2 tags.

### PR DESCRIPTION
**Pull request by khwilliamson**
Otherwise, the semi-colon the code has afterwards can be interpreted by
some compilers as ending the block of declarations, and treat any later
declarations in the same block as erors in C89.

For an example, see the ticket this fixes #17725

@afresh1 please see if this fixes your bug

### CODE REVIEW

**Comment by afresh1** [comment]
> @afresh1 please see if this fixes your bug

I am able to build this branch with `-Accflags='-DNO_LOCALE_NUMERIC'`, which wasn't working.  Many thanks for looking a this.

**Comment by jkeenan** [comment]
> Otherwise, the semi-colon the code has afterwards can be interpreted by
> some compilers as ending the block of declarations, and treat any later
> declarations in the same block as erors in C89.
> 
> For an example, see the ticket this fixes #17725
> 
> @afresh1 please see if this fixes your bug

I created a smoke-me branch from this p.r. and tested it on OpenBSD 6.6 thus:
```
[openbsd66: perl] $ uname -mrs
OpenBSD 6.6 amd64

[openbsd66: perl] $ git describe
v5.31.10-69-g3df86c373f

[openbsd66: perl] $ gitcurr
smoke-me/jkeenan/khw/ghpr-17750

[openbsd66: perl] $ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Accflags=-DNO_LOCALE_NUMERIC -DNO_LOCALE_COLLATE';

[openbsd66: perl] $ cc --version
OpenBSD clang version 8.0.1 (tags/RELEASE_801/final) (based on LLVM 8.0.1)
Target: amd64-unknown-openbsd6.6
Thread model: posix
InstalledDir: /usr/bin
```
All tests PASSed.  I also built successfully with `'-Dccflags...'`, but I didn't run `make test` on that build.  Branch is available here:
https://github.com/Perl/perl5/tree/smoke-me/jkeenan/khw/ghpr-17750

**Comment by afresh1** [comment]
I did run tests, only one failure that seems unrelated.
```
t/porting/podcheck ............................................. Wide character in subroutine entry at porting/podcheck.t line 1808.
# Looks like you planned 1499 tests but ran 0.
FAILED--expected 1499 tests, saw 0
```

**Comment by xsawyerx** [comment]
:+1: Good to merge then.

**Pull request merged**
