### PR TITLE
Fix spaces

### PR DESCRIPTION
**Pull request by jidanni**
Say either
- integer / floating / string, or
- integer/floating/string

not
- integer/floating/ string

### CODE REVIEW

**Comment by karenetheridge** [comment]
No, this is not correct.

**Comment by karenetheridge** [comment]
Neither of those cases exist. There is a line break in the middle, but that is not the same as introducing a regular 0x20 space.

**Comment by Grinnz** [comment]
Line breaks do get collapsed to a space character by POD parsers, unfortunately. So this change might improve rendering.

**Comment by jidanni** [comment]
Yes. It looks like doo doo on Debian. That's why I'm here.

**Comment by khwilliamson** [comment]
I agree that something should be done.  I think that this would be best, so that formatters would be clear as to what is meant
`of four different ways: they may force it to one of the
integerE<sol>floatingE<sol>string formats, or they may behave differently
`

**Comment by Grinnz** [comment]
Would that not also need a line break and thus introduce whitespace?

**Comment by khwilliamson** [comment]
I don't understand your point.  I actually think that the three items are most clearly displayed as an unbroken sequence on a single line.  

> and/or
for example is best understood unseparated

**Comment by Grinnz** [comment]
Yes, I mean it would need a line break in the POD because otherwise the line would be too long for pod tests. A line break in the POD gets rendered as a space character.

But it could just be split into more lines so that no line break is needed within this term.

**Comment by oodler577** [comment]
Or you can learn how to use commas properly with a helpful semi-colon: 

```
of four different ways: they may force it to one of the integer, floating,
or string formats; or they may behave differently depending on the format of
the operand.
```

**Comment by jidanni** [comment]
Yes, please use @oodler577 's version. Thanks.

**Comment by jkeenan** [comment]
> Yes, please use @oodler577 's version. Thanks.

@oodler577's version implemented in https://github.com/Perl/perl5/pull/18806.  Please review.

**Comment by jkeenan** [comment]
This issued should be resolved as of ffa5817eaa.  Closing ticket.

**Pull request closed without merging**
