### PR TITLE
Fix several undefined behaviour issues detected by -fsanitize=undefined

### PR DESCRIPTION
**Pull request by tonycoz**
Fixes both issues mentioned in #19874.

Fixes all but the unaligned access issues described in #19851.

Draft for now, hoping for an update from @hvds on the FIXME patch.

### CODE REVIEW

**Comment by hvds** [comment]
> Draft for now, hoping for an update from @hvds on the FIXME patch.

I'm hoping for a comment from @demerphq on that patch (originally [here](https://github.com/Perl/perl5/issues/19874#issuecomment-1159011222)), but I think it's probably good.

**Comment by khwilliamson** [comment]
I would have thought the casts would need to include 'const' to avoid assignments

**Comment by tonycoz** [comment]
> I would have thought the casts would need to include 'const' to avoid assignments

No, code like:

  (type)(lvalue) = somevalue;

is ill-formed.  Old versions of gcc allowed it as an extension.
```
tony@venus:.../perl/git$ gcc -c castlvalue.c
castlvalue.c: In function ‘f’:
castlvalue.c:5:14: error: lvalue required as left operand of assignment
    5 |     (int *)x = y;
      |              ^
castlvalue.c: In function ‘g’:
castlvalue.c:9:12: error: lvalue required as left operand of assignment
    9 |     (int)z = a;
      |            ^
tony@venus:.../perl/git$ clang-14 -c castlvalue.c
castlvalue.c:5:5: error: assignment to cast is illegal, lvalue casts are not supported
    (int *)x = y;
    ^~~~~~~~ ~
castlvalue.c:9:5: error: assignment to cast is illegal, lvalue casts are not supported
    (int)z = a;
    ^~~~~~ ~
2 errors generated.
tony@venus:.../perl/git$ cat castlvalue.c
int *x;
int z;

void f(int *y) {
    (int *)x = y;
}

void g(int a) {
    (int)z = a;
}
```

**Review by khwilliamson — APPROVED** [review]

**Comment by hvds** [comment]
Commit message for the "FIXME" can be something like `study_chunk: avoid integer overflow in calculation of delta`.

**Comment by hvds** [comment]
@tonycoz - @demerphq has now commented on the `study_chunk` patch in #19874, so please remove it from this PR; he is working up a new fix.

**Comment by demerphq** [comment]
I created https://github.com/Perl/perl5/pull/19947 related to the regex engine parts of this.

**Comment by tonycoz** [comment]
> @tonycoz - @demerphq has now commented on the `study_chunk` patch in #19874, so please remove it from this PR; he is working up a new fix.

Done.

**Review by Leont — APPROVED** [review]

**Pull request merged**
