### PR TITLE
locale.c: Don't compile unused function

### PR DESCRIPTION
**Pull request by khwilliamson**
Since 60e050beb2e45ebd7ead7f1bf93f845b23c474b5, this function is no longer called if -DNO_LOCALE has been specified.  Don't compile it when not called.

### CODE REVIEW

**Comment by jkeenan** [comment]
> Since [60e050b](https://github.com/Perl/perl5/commit/60e050beb2e45ebd7ead7f1bf93f845b23c474b5), this function is no longer called if -DNO_LOCALE has been specified. Don't compile it when not called.

Can you describe how I would see that "this function" is not currently being called?

I configured and built blead in two ways:
```
$ sh ./Configure -des -Dusedevel -DNO_LOCALE && make test_prep
```
and 
```
$ sh ./Configure -des -Dusedevel && make test_prep
```
I logged the output of `make test_prep` in both cases.  The outputs were identical.

**Comment by khwilliamson** [comment]
Sorry. I shortcutted when I specified `-DNO_LOCALE`  It's really `-Accflags=-DNO_LOCALE`

**Comment by jkeenan** [comment]
> Sorry. I shortcutted when I specified `-DNO_LOCALE` It's really `-Accflags=-DNO_LOCALE`

But when I tried that, I failed to build.
```
$ gitcurr
blead
$ git describe
v5.39.7-32-gaf9733f1e2

$ sh ./Configure -des -Dusedevel -Accflags=-DNO_LOCALE && make test_prep
...
cc -fstack-protector-strong -L/usr/local/lib -o miniperl \
    opmini.o perlmini.o universalmini.o av.o builtin.o caretx.o class.o deb.o doio.o doop.o dquote.o dump.o globals.o gv.o hv.o keywords.o locale.o mathoms.o mg.o mro_core.o numeric.o pad.o peep.o perlio.o perly.o pp.o pp_ctl.o pp_hot.o pp_pack.o pp_sort.o pp_sys.o reentr.o regcomp.o regcomp_debug.o regcomp_invlist.o regcomp_study.o regcomp_trie.o regexec.o run.o scope.o sv.o taint.o time64.o toke.o utf8.o util.o   miniperlmain.o  -lpthread -ldl -lm -lcrypt -lutil -lc 
/usr/bin/ld: locale.o: in function `Perl_sv_langinfo':
locale.c:(.text+0x85a): undefined reference to `emulate_langinfo'
/usr/bin/ld: locale.o: in function `Perl_langinfo':
locale.c:(.text+0x8cb): undefined reference to `emulate_langinfo'
/usr/bin/ld: locale.o: in function `Perl_langinfo8':
locale.c:(.text+0x92c): undefined reference to `emulate_langinfo'
collect2: error: ld returned 1 exit status
make: *** [makefile:390: lib/buildcustomize.pl] Error 1
```

**Comment by khwilliamson** [comment]
It turns out there is a bug on non-Linux builds that needs to be fixed before this PR will work on those boxes.  Am now smoking a fix

**Comment by jkeenan** [comment]
> It turns out there is a bug on non-Linux builds that needs to be fixed before this PR will work on those boxes. Am now smoking a fix

But I tested on Linux.
```
$ uname -mrs
Linux 6.5.0-14-generic x86_64
```

**Comment by khwilliamson** [comment]
Sorry.  I don't know why this was working for me and CI and not you.  I believe that with #21903 applied, this should work.

**Comment by jkeenan** [comment]
Still unable to compile the base case on Linux.  See [here](https://github.com/Perl/perl5/pull/21892#issuecomment-1915301558).

**Pull request merged**
