### PR TITLE
Make map and grep preserve their args lists.

### PR DESCRIPTION
**Pull request by FGasper**
Issue #19340: This prevents an obscure segfault.

### CODE REVIEW

**Comment by Leont** [comment]
I don't think leaking really is the best solution we can offer here.

**Comment by FGasper** [comment]
@Leont Given how small ARGV usually is I didn’t think it unreasonable, though obviously preserving the cleanup would be best for all. Do you have any suggestions of where to start? Some way to prevent the SAVEFREESV from nextargv from conflicting with the leave-time free of the saved $_?

**Comment by Leont** [comment]
This should have been a new PR, now my first comment doesn't make sense anymore.

I don't think this is going to fly either. This is one of the more difficult problems that we have, please don't try to quick-fix it.

**Comment by FGasper** [comment]
@Leont I don't mean to oversimplify, certainly. But can you give a bit more detail as to what else needs to happen? This approach doesn't incur leakage and does solve both of the reproductions in the issue thread.

I don't doubt that there are bigger problems in play; I'd just like to have a better sense of those. Thank you for your time.

**Comment by xenu** [comment]
This is a good starting point: https://github.com/Perl/perl5/issues/12315#issuecomment-544033274

**Comment by xenu** [comment]
Also see [this](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=77706) meta ticket for an incomplete list of related tickets (the dependsOn section).

**Comment by FGasper** [comment]
@xenu: Thank you for the clarification and broader context.

I would still think that fixing 30% of the cases (i.e., map and grep) is better than solving none of them. To @demerphq’s point, though, this really is a “stop hitting yourself” thing; there seems to be no reason why normal development would result in such code being written, let alone being put into production.

Anyhow, I‘ll close this.

**Pull request closed without merging**
