### PR TITLE
Use bison's named references

### PR DESCRIPTION
**Pull request by happy-barney**
Usage of bison's named references makes actions little bit easier
to read and maintain.

### CODE REVIEW

**Comment by atoomic** [comment]
FYI this is going to conflict with #18000 which should go in first

**Comment by ilmari** [comment]
@happy-barney What is the oldest version of Bison that supports named references? We currently (as of #18000, which I just merged) support down to version 2.4.

**Comment by happy-barney** [comment]
@ilmari oldest documentation mentioning named references I found so far (via google) is 2.5

**Comment by happy-barney** [comment]
@atoomic conflicts resolved

@ilmari named references are supported since bison 2.5. I think increased readability of actions advocates min supported Bison version increase.

**Comment by atoomic** [comment]
This looks good to me, I'm not sure about the impact of increasing bison to 2.5, what are we going to leave behind?
Going to wait for @ilmari feedback on it.

**Comment by Leont** [comment]
> I'm not sure about the impact of increasing bison to 2.5, what are we going to leave behind

RHEL6, as far as I can tell. I think old dromedary ran that, but that has been decommissioned a few months ago.

**Comment by atoomic** [comment]
@ilmari any final opinion on this? I think this is good to have?

**Comment by ilmari** [comment]
There are still nearly 200 numeric references left in `perly.y`:
```
~/src/perl (happy-barney-hpb-perly $)$ ag -c '\$\d+' perly.y 
183
```

Also, do we want to change `$$` to be `$rulename`, or are we fine with leaving that as is?

**Comment by happy-barney** [comment]
numeric references I left on purpose are literals like `'{'`
later I'd like to change them into named tokens (`BRACE_OPEN` token and `$BRACE_OPEN` reference)

ad result I'm not sure, `$$` is only one and cannot change position

**Comment by ilmari** [comment]
Some of them are, yes, but there's things like:

```
	|	UNLESS '(' remember mexpr ')' mblock else
			{
			  $$ = block_end($remember,
                              newCONDOP(0, $mexpr, $else, op_scope($mblock)));
			  parser->copline = (line_t)$1;
			}
```
where the last line could be `parser->copline = (line_t)$UNLESS;`

and productions like this under `sideff`, and lots more
```
	|	expr IF expr
			{ $$ = newLOGOP(OP_AND, 0, $3, $1); }
```

**Comment by happy-barney** [comment]
@ilmari rebased, squashed

Two kind of numeric references left:
- those addressing character literals
- those addressing recursive statement (`term`, `sideff`)
-- I have to study these rules deeper

**Comment by Leont** [comment]
This looks like an improvement to me :-)

**Comment by happy-barney** [comment]
@Leont  clarification request: is improvement good word or swear word ? :-)

**Comment by happy-barney** [comment]
@ilmari , any chance to continue with this?

**Review by smpeters — COMMENTED** [review]
I really like this change.  Using named references really improves the readability of perly.y.

**Comment by xenu** [comment]
As far as I can tell, no one is opposed to this PR. So why this wasn't merged yet?

I understand that people are afraid of the parser, it is indeed big and scary, but the only real way to find out if this change breaks anything is to merge it and wait for BBC tickets. Just like we did with the tokenizer refactor. The sooner it's merged, the more feedback it will get.

**Comment by khwilliamson** [comment]
I merged this not having knowledge of it, but going by the positive feedback

**Pull request merged**
