### PR TITLE
hints/linux.sh: use GNUmakefile on case-insensitive file systems (e.g. WSL)

### PR DESCRIPTION
**Pull request by mauke**
... because the Windows file system is case insensitive.

See the discussion in #22715.

---------------------------------------------------------------------------------
* This set of changes does not require a perldelta entry.

### CODE REVIEW

**Review by Leont — APPROVED** [review]

**Comment by tonycoz** [comment]
Wouldn't it be better to just check if the filesystem is case sensitive or not?

There are other case-insensitive file systems on Linux, and WSL isn't necessarily case-insensitive.

In my WSL 2:
```
tony@GANYMEDE:~$ stat -f .
  File: "."
    ID: 985c804e36bc4a52 Namelen: 255     Type: ext2/ext3
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 263940717  Free: 254354045  Available: 240928177
Inodes: Total: 67108864   Free: 66845622
tony@GANYMEDE:~$ touch Makefile makefile
tony@GANYMEDE:~$ ls *akefile
makefile  Makefile
tony@GANYMEDE:~$ uname -a
Linux GANYMEDE 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux
```

**Comment by Leont** [comment]
> Wouldn't it be better to just check if the filesystem is case sensitive or not?

Probably. We're already setting it on 4 other platforms (5 if the msys2 branch gets merged) so we might as well come up with a more generic solution.

**Comment by Leont** [comment]
That said, unless you're planning to write that patch in the near future I suspect it's best to have this in now. It's crude but effective.

**Comment by mauke** [comment]
> Wouldn't it be better to just check if the filesystem is case sensitive or not?

I've pushed a patch to that effect.

**Review by tonycoz — APPROVED** [review]
Needs to be squashed before it's applied.

**Pull request merged**
