### PR TITLE
Remove Pod::Functions::Functions from CoreList

### PR DESCRIPTION
**Pull request by choroba**
There's no such module and there never has been.

### CODE REVIEW

**Comment by choroba** [comment]
Fixes #19991.

**Comment by choroba** [comment]
Please see the linked issue for a discussion.

**Comment by jkeenan** [comment]
@bingos, will you be able to review this merge request?

**Comment by jkeenan** [comment]
> @bingos, will you be able to review this merge request?

@bingos, will you be able to review this merge request?  Thanks.

**Pull request merged**
