### PR TITLE
perlpodspec: Note that "=item *" has nothing else

### PR DESCRIPTION
**Pull request by khwilliamson**
`=item * foo bar`

is not supposed to be a bullet list; it is a text (definition) list whose first character is an asterisk.  This commit makes it explicit that a bullet list contains only asterisk characters on the =item lines

This is implied later on in the existing documentation where it says that

>  The "=item [text]" paragraph should not match
 C<m/\A=item\s+\d+\.?\s*\z/> or C<m/\A=item\s+\*\s*\z/>, nor should it
 match just C<m/\A=item\s*\z/>.

The text already says numbered lists must match
`<m/\A=item\s+\d+\.?\s*\z/`.  This commit adapts that text to the bullet list case.

* This set of changes does not require a perldelta entry.

### CODE REVIEW

**Comment by Grinnz** [comment]
I'm not sure this is true. Bulleted lists in this form are used all over core and CPAN docs and are rendered as such.

**Comment by khwilliamson** [comment]
You're right.  SHould the text then say this is legal?

**Comment by Grinnz** [comment]
Perhaps, it may be worth verifying how different renderers currently handle it. It seems to be a useful feature.

**Comment by khwilliamson** [comment]
Hmm. I just pushed the wrong thing here; given that it was already wrong, I'll just close it and start over

**Pull request closed without merging**
