### PR TITLE
delete metaphoric quotations

### PR DESCRIPTION
**Pull request by ghost**
Seems like this nonsense is finally obsolete.

### CODE REVIEW

**Comment by karenetheridge** [comment]
Could you please include more explanation in your your pull request comments?

**Comment by wchristian** [comment]
This arbitrarily removes perl history and character for (at best) marginal gains, and as the emoji reactions above indicate, several people feel there is no clear reason to do this.

As such, at the very least a reason should be argued, in a clear manner.

**Comment by tonycoz** [comment]
> Seems like this nonsense is finally obsolete.
> 
> pod/perlhack.pod
> 
> "..."

That justifies adding quotes to new `*.c` files, not for removing them from existing files.

**Comment by jkeenan** [comment]
Rejected.

**Comment by apparluk** [comment]
People used to sit around in parks on the grass in the 1960s reading those volumes.

Is that really the mindset of the developers of the language or the current contributors?

**Pull request closed without merging**
