### PR TITLE
Rename README to README.md

### PR DESCRIPTION
**Pull request by quick007**
There is literally no reason not to do this, it cleans up the readme, makes it look more presentable, and fixed the parts where they intended formatting but (seemingly?) forgot to use the correct file type

### CODE REVIEW

**Comment by rwp0** [comment]
See #19099 

---

the base README is *not* Markdown

**Comment by jkeenan** [comment]
> There is literally no reason not to do this, it cleans up the readme, makes it look more presentable, and fixed the parts where they intended formatting but (seemingly?) forgot to use the correct file type

I strongly oppose this and all attempts to reformat `README` as anything other than plain text.

**Comment by rwp0** [comment]
> > There is literally no reason not to do this, it cleans up the readme, makes it look more presentable, and fixed the parts where they intended formatting but (seemingly?) forgot to use the correct file type
> 
> I strongly oppose this and all attempts to reformat `README` as anything other than plain text.

Right, and therefore I think an additional `README.md` file should be set for GitHub (repository home)

**Comment by Grinnz** [comment]
As stated, this README is not in markdown format, and its filename must not change.

**Comment by ilmari** [comment]
GitHub supports POD too, so if anything we could rewrite (and rename) it to POD, like INSTALL is (which could also be renamed, so GitHub renders it nicely, or maybe we could add `linguist-language=Pod` to `.gitattributes`?)

**Comment by haarg** [comment]
linguist-language is used by GitHub for language stats, but not for deciding how to render a README type file. Adjusting the current README to be markdown without renaming it would be possible if that worked.

**Comment by rwp0** [comment]
> GitHub supports POD too, so if anything we could rewrite (and rename) it to POD, like INSTALL is (which could also be renamed, so GitHub renders it nicely, or maybe we could add `linguist-language=Pod` to `.gitattributes`?)

I initially thought so as well, but the newer Code of Conduct and Security files in the repository, which are in Markdown, and not in Pod is making Markdown the new standard for Github-oriented files.

**Comment by Grinnz** [comment]
There is no standard. POD and markdown are equally viable for Github-oriented files. Markdown is more easily read as a plaintext file and so may be more suited to this particular case. POD is capable of section linking and module linking and so is more suitable for other cases.

**Pull request closed without merging**
