### PR TITLE
GH #18047: Initial phrasing for =head5 and =head6

### LINKED ISSUE #18047: [feature] Add head5 and head6 to perl pod
Please add `head5` and `head6` to the available commands in Plain Old Documentation (POD). Most other markup languages have 6 heading levels.

### PR DESCRIPTION
**Pull request by xsawyerx**
This is an initial phrasing. Please suggest any improvements on it.

### CODE REVIEW

**Comment by Grinnz** [comment]
FYI if you mention the issue in your issue comment it will link them better on github: #18047

**Comment by tonycoz** [comment]
That looks reasonable, but perlpod should mention it too, I think.

**Comment by neilb** [comment]
You can now change this:

    L<Pod::Simple> 3.41 was released in XX

to

    L<Pod::Simple> 3.41 was released in October 2020

**Comment by xsawyerx** [comment]
I force-pushed a cleanup commit and rebase. It resolves the `XX` in the release time based on Neil's helpful suggestion.

I will address Tony's comment and push an update.

**Comment by xsawyerx** [comment]
Revised the commit to include the changes to `perlpod` as well, as Tony suggested. This is ready to be merged, as far as I'm concerned.

**Comment by shlomif** [comment]
On Sat, 03 Jul 2021 11:58:08 -0700
Sawyer X ***@***.***> wrote:

> Revised the commit to include the changes to `perlpod` as well, as Tony
> suggested. This is ready to be merged, as far as I'm concerned.
> 

Thanks, Sawyer! ♥️

-- 

Shlomi Fish       https://www.shlomifish.org/
https://is.gd/MQHVF3 - The Atom Text Editor edits a 2,000,001B file

Shlomi: if you read my stories, I’ll give you 1,000,000 virtual dollars.
Sjors: causing me to have a lot of extra virtual time!

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Pull request merged**
