### PR TITLE
GNU/Hurd doesn't support SO_PROTOCOL

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by ntyni** [comment]
Just noting that the test failure fixed by this is a 5.32 regression on Hurd.

**Comment by ntyni** [comment]
@sthibaul did you test this? The build log at https://buildd.debian.org/status/fetch.php?pkg=perl&arch=hurd-i386&ver=5.32.0%7Erc1-1&stamp=1592442236&raw=0 has two failures, so I assume the system list on line 108 needs updating too.

**Comment by sthibaul** [comment]
Ah, no I hadn't tested it, because the issue was so obvious, and  pointed to me by https://lists.debian.org/debian-hurd/2020/06/msg00028.html

**Review by khwilliamson — COMMENTED** [review]
Looks fine to me, though I don't know if 'gnu' is the precise correct string; but if it weren't @jmdh  would have said something

**Comment by sthibaul** [comment]
'gnu' can be seen already used in various places:

```
dist/Time-HiRes/t/itimer.t:            && $^O ne 'gnu' # GNU/Hurd: has the API but no implementation
ext/POSIX/t/sigaction.t:            ($^O eq 'gnu')
t/io/socket.t:		    if $^O eq "gnu";
```

**Comment by jmdh** [comment]
Yep, I think "gnu" is correct.

**Comment by Leont** [comment]
LGTM

**Pull request merged**
