### PR TITLE
cpan/IO-Socket-IP - Update to version 0.43

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
0.43    2024-11-25
        [CHANGES]
         * Swapped unit tests from `Test::More` to `Test2::V0`
         * Fixed some documentation typoes
           (thanks Igor Sobrado Delgado) (RT157201)

### CODE REVIEW

**Comment by thibaultduponchelle** [comment]
@leonerd @Corion

**Comment by leonerd** [comment]
This sort of thing is usually done automatically with `Porting/sync-with-cpan` rather than manual PRs.

**Comment by jkeenan** [comment]
This appears to have been run with `Porting/sync-with-cpan`.  (I ran that locally and got similar results.)  So looks good to merge.

**Comment by thibaultduponchelle** [comment]
Thank you both for the review 😃 I pushed the change to blead

**Pull request closed without merging**
