### PR TITLE
Test::More::note() needs version 0.82

### PR DESCRIPTION
**Pull request by jkeenan**
For: https://github.com/Perl/perl5/issues/19569, as reported by
kbulgrien.

### CODE REVIEW

**Comment by Grinnz** [comment]
My only concern with this is Test::More also depends on Storable, so I would want to make sure this would not create a dependency cycle on ancient Perls when trying to upgrade these modules.

**Review by Grinnz — APPROVED** [review]
I've checked and Test::More's dependency on Storable is versionless, so there should be no upgrade cycle.

**Comment by jkeenan** [comment]
> My only concern with this is Test::More also depends on Storable, so I would want to make sure this would not create a dependency cycle on ancient Perls when trying to upgrade these modules.

I would never have guessed it!  However, it seems that that dependency is on the `Test-Simple` *distribution*, not on the `Test::More` *module*.
```
$ cd cpan/Test-Simple/

[perlmonger: Test-Simple] $ ack Storable .
t/Test2/modules/IPC/Driver/Files.t
243:    Storable::store({}, $fn);
251:    Storable::store(bless({}, 'Test2::Event::FakeEvent'), $fn);
259:    Storable::store(bless({}, 'Test2::API'), $fn);
267:    Storable::store(bless({}, 'Foo'), $fn);

lib/Test2/IPC/Driver/Files.pm
13:use Storable();
185:        Storable::store($e, $file);
349:    my $obj = Storable::retrieve($file);

lib/Test2/API/InterceptResult.pm
9:use Storable     qw/dclone/;
287:structure is duplicated. This uses C<dclone> from L<Storable> to achieve the

lib/Test2/API/InterceptResult/Event.pm
11:use Storable qw/dclone/;
```
I think we can live with that.

**Review by khwilliamson — COMMENTED** [review]
My review was requested, but I have no insight or knowledge into its correctness

**Comment by Grinnz** [comment]
> > My only concern with this is Test::More also depends on Storable, so I would want to make sure this would not create a dependency cycle on ancient Perls when trying to upgrade these modules.
> 
> I would never have guessed it! However, it seems that that dependency is on the `Test-Simple` _distribution_, not on the `Test::More` _module_.

There is no distinction - dependencies are always on modules, and satisfied by a distribution.

**Comment by Grinnz** [comment]
The issue I mentioned would occur if both Test::More and Storable had dependencies on each others' distribution, on versions of module which are not present in core in a particular version of Perl (i.e. 5.8.9 does not ship with Test::More 0.82). But since the dependency on Storable is versionless, it is satisfied by default on any Perl that ships with Storable.

**Comment by jkeenan** [comment]
Addressed by https://github.com/Perl/perl5/pull/19570; closing ticket.  Thanks.

**Pull request merged**
