### PR TITLE
 Add feature to get extra paired string delimiters

### PR DESCRIPTION
**Pull request by khwilliamson**
This is based on `http://nntp.perl.org/group/perl.perl5.porters/262686](https://github.com/Perl/perl5/pull/19420)`

### CODE REVIEW

**Comment by khwilliamson** [comment]
Force pushed after resolving all comments and adding tests

**Comment by khwilliamson** [comment]
This branch looks through all Punctuation and Symbol characters in the Unicode data base and finds many that are suitable for use as paired string delimiters in Perl.  The first portion adds a feature to allow accessing the ones that got chosen.  The later commits do the choosing.  I made the choices as close to the maximum ones that seemed reasonable to me; things could be added or subtracted.  Below is a list of all the possible ones that were potential pairs that didn't get chosen.  git hub doesn't allow me a larger list
`
Mirrored says Unicode, but not currently used as paired string delimiters
 ∕  ⧵    U+2215, U+29F5   DIVISION SLASH,  REVERSE SOLIDUS OPERATOR
 ∟  ⯾    U+221F, U+2BFE   RIGHT ANGLE,  REVERSED RIGHT ANGLE
 ∠  ⦣    U+2220, U+29A3   ANGLE,  REVERSED ANGLE
 ∡  ⦛    U+2221, U+299B   MEASURED ANGLE,  MEASURED ANGLE OPENING LEFT
 ∢  ⦠    U+2222, U+29A0   SPHERICAL ANGLE,  SPHERICAL ANGLE OPENING LEFT
 ∤  ⫮    U+2224, U+2AEE   DOES NOT DIVIDE,  DOES NOT DIVIDE WITH REVERSED
                          NEGATION SLASH
 ∼  ∽    U+223C, U+223D   TILDE OPERATOR,  REVERSED TILDE
 ≃  ⋍    U+2243, U+22CD   ASYMPTOTICALLY EQUAL TO,  REVERSED TILDE EQUALS
 ≅  ≌    U+2245, U+224C   APPROXIMATELY EQUAL TO,  ALL EQUAL TO
 ≒  ≓    U+2252, U+2253   APPROXIMATELY EQUAL TO OR THE IMAGE OF,  IMAGE
                          OF OR APPROXIMATELY EQUAL TO
 ≔  ≕    U+2254, U+2255   COLON EQUALS,  EQUALS COLON
 ⊏  ⊐    U+228F, U+2290   SQUARE IMAGE OF,  SQUARE ORIGINAL OF
 ⊑  ⊒    U+2291, U+2292   SQUARE IMAGE OF OR EQUAL TO,  SQUARE ORIGINAL
                          OF OR EQUAL TO
 ⊘  ⦸    U+2298, U+29B8   CIRCLED DIVISION SLASH,  CIRCLED REVERSE SOLIDUS
 ⊲  ⊳    U+22B2, U+22B3   NORMAL SUBGROUP OF,  CONTAINS AS NORMAL SUBGROUP
 ⊴  ⊵    U+22B4, U+22B5   NORMAL SUBGROUP OF OR EQUAL TO,  CONTAINS AS
                          NORMAL SUBGROUP OR EQUAL TO
 ⊶  ⊷    U+22B6, U+22B7   ORIGINAL OF,  IMAGE OF
 ⊸  ⟜    U+22B8, U+27DC   MULTIMAP,  LEFT MULTIMAP
 ⋉  ⋊    U+22C9, U+22CA   LEFT/RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT
 ⋋  ⋌    U+22CB, U+22CC   LEFT/RIGHT SEMIDIRECT PRODUCT
 ⋢  ⋣    U+22E2, U+22E3   NOT SQUARE IMAGE OF OR EQUAL TO,  NOT SQUARE
                          ORIGINAL OF OR EQUAL TO
 ⋤  ⋥    U+22E4, U+22E5   SQUARE IMAGE OF OR NOT EQUAL TO,  SQUARE
                          ORIGINAL OF OR NOT EQUAL TO
 ⋪  ⋫    U+22EA, U+22EB   NOT NORMAL SUBGROUP OF,  DOES NOT CONTAIN AS
                          NORMAL SUBGROUP
 ⋬  ⋭    U+22EC, U+22ED   NOT NORMAL SUBGROUP OF OR EQUAL TO,  DOES NOT
                          CONTAIN AS NORMAL SUBGROUP OR EQUAL
 ⋰  ⋱    U+22F0, U+22F1   UP RIGHT DIAGONAL ELLIPSIS,  DOWN RIGHT
                          DIAGONAL ELLIPSIS
 ⟋  ⟍    U+27CB, U+27CD   MATHEMATICAL RISING DIAGONAL,  MATHEMATICAL
                          FALLING DIAGONAL
 ⟕  ⟖    U+27D5, U+27D6   LEFT/RIGHT OUTER JOIN
 ⟣  ⟢    U+27E3, U+27E2   WHITE CONCAVE-SIDED DIAMOND WITH RIGHT/
                          LEFTWARDS TICK
 ⦤  ⦥    U+29A4, U+29A5   ANGLE WITH UNDERBAR,  REVERSED ANGLE WITH
                          UNDERBAR
 ⧄  ⧅    U+29C4, U+29C5   SQUARED RISING DIAGONAL SLASH,  SQUARED FALLING
                          DIAGONAL SLASH
 ⧏  ⧐    U+29CF, U+29D0   LEFT TRIANGLE BESIDE VERTICAL BAR,  VERTICAL
                          BAR BESIDE RIGHT TRIANGLE
 ⨫  ⨬    U+2A2B, U+2A2C   MINUS SIGN WITH FALLING DOTS,  MINUS SIGN WITH
                          RISING DOTS
 ⨭  ⨮    U+2A2D, U+2A2E   PLUS SIGN IN LEFT/RIGHT HALF CIRCLE
 ⨴  ⨵    U+2A34, U+2A35   MULTIPLICATION SIGN IN LEFT/RIGHT HALF CIRCLE
 ⨼  ⨽    U+2A3C, U+2A3D   INTERIOR PRODUCT,  RIGHTHAND INTERIOR PRODUCT
 ⩤  ⩥    U+2A64, U+2A65   Z NOTATION DOMAIN ANTIRESTRICTION,  Z NOTATION
                          RANGE ANTIRESTRICTION
 ⫍  ⫎    U+2ACD, U+2ACE   SQUARE LEFT/RIGHT OPEN BOX OPERATOR
 ⫬  ⫭    U+2AEC, U+2AED   DOUBLE STROKE NOT SIGN,  REVERSED DOUBLE STROKE
                          NOT SIGN

Mirror found by name, but not currently used as paired string delimiters
 ϵ  ϶    U+03F5, U+03F6   GREEK LUNATE EPSILON SYMBOL,  GREEK REVERSED
                          LUNATE EPSILON SYMBOL
 ֍  ֎    U+058D, U+058E   RIGHT/LEFT-FACING ARMENIAN ETERNITY SIGN
 ࿕  ࿖    U+0FD5, U+0FD6   RIGHT/LEFT-FACING SVASTI SIGN
 ࿗  ࿘    U+0FD7, U+0FD8   RIGHT/LEFT-FACING SVASTI SIGN WITH DOTS
 ↗  ↖    U+2197, U+2196   NORTH EAST/WEST ARROW
 ↘  ↙    U+2198, U+2199   SOUTH EAST/WEST ARROW
 ⇗  ⇖    U+21D7, U+21D6   NORTH EAST/WEST DOUBLE ARROW
 ⇘  ⇙    U+21D8, U+21D9   SOUTH EAST/WEST DOUBLE ARROW
 ∅  ⦰    U+2205, U+29B0   EMPTY SET,  REVERSED EMPTY SET
 ⌍  ⌌    U+230D, U+230C   BOTTOM LEFT/RIGHT CROP
 ⌏  ⌎    U+230F, U+230E   TOP LEFT/RIGHT CROP
 ⌜  ⌝    U+231C, U+231D   TOP LEFT/RIGHT CORNER
 ⌞  ⌟    U+231E, U+231F   BOTTOM LEFT/RIGHT CORNER
 ⍃  ⍄    U+2343, U+2344   APL FUNCTIONAL SYMBOL QUAD LESS-THAN/GREATER-
                          THAN
 ⍆  ⍅    U+2346, U+2345   APL FUNCTIONAL SYMBOL RIGHT/LEFTWARDS VANE
 ⎣  ⎦    U+23A3, U+23A6   LEFT/RIGHT SQUARE BRACKET LOWER CORNER
 ⎨  ⎬    U+23A8, U+23AC   LEFT/RIGHT CURLY BRACKET MIDDLE PIECE
 ⎸  ⎹    U+23B8, U+23B9   LEFT/RIGHT VERTICAL BOX LINE
 ⏋  ⎾    U+23CB, U+23BE   DENTISTRY SYMBOL LIGHT VERTICAL AND TOP LEFT/
                          RIGHT
 ⏌  ⎿    U+23CC, U+23BF   DENTISTRY SYMBOL LIGHT VERTICAL AND BOTTOM LEFT/
                          RIGHT
 ⏵  ⏴    U+23F5, U+23F4   BLACK MEDIUM RIGHT/LEFT-POINTING TRIANGLE
 ▶  ◀    U+25B6, U+25C0   BLACK RIGHT/LEFT-POINTING TRIANGLE
 ▷  ◁    U+25B7, U+25C1   WHITE RIGHT/LEFT-POINTING TRIANGLE
 ▸  ◂    U+25B8, U+25C2   BLACK RIGHT/LEFT-POINTING SMALL TRIANGLE
 ▹  ◃    U+25B9, U+25C3   WHITE RIGHT/LEFT-POINTING SMALL TRIANGLE
 ►  ◄    U+25BA, U+25C4   BLACK RIGHT/LEFT-POINTING POINTER
 ▻  ◅    U+25BB, U+25C5   WHITE RIGHT/LEFT-POINTING POINTER
 ◖  ◗    U+25D6, U+25D7   LEFT/RIGHT HALF BLACK CIRCLE
 ◣  ◢    U+25E3, U+25E2   BLACK LOWER LEFT/RIGHT TRIANGLE
 ◤  ◥    U+25E4, U+25E5   BLACK UPPER LEFT/RIGHT TRIANGLE
 ◸  ◹    U+25F8, U+25F9   UPPER LEFT/RIGHT TRIANGLE
 ◺  ◿    U+25FA, U+25FF   LOWER LEFT/RIGHT TRIANGLE
 ♱  ♰    U+2671, U+2670   EAST/WEST SYRIAC CROSS
 ⛦  ⛥    U+26E6, U+26E5   LEFT/RIGHT-HANDED INTERLACED PENTAGRAM
 ✌  🖔    U+270C, U+1F594  VICTORY HAND,  REVERSED VICTORY HAND
 ✎  🖉    U+270E, U+1F589  LOWER RIGHT/LEFT PENCIL
 ❧  ☙    U+2767, U+2619   ROTATED FLORAL HEART BULLET,  REVERSED ROTATED
                          FLORAL HEART BULLET
 ⤤  ⤣    U+2924, U+2923   NORTH EAST/WEST ARROW WITH HOOK
 ⤥  ⤦    U+2925, U+2926   SOUTH EAST/WEST ARROW WITH HOOK
 ⥼  ⥽    U+297C, U+297D   LEFT/RIGHT FISH TAIL
 ⬀  ⬁    U+2B00, U+2B01   NORTH EAST/WEST WHITE ARROW
 ⬂  ⬃    U+2B02, U+2B03   SOUTH EAST/WEST WHITE ARROW
 ⬈  ⬉    U+2B08, U+2B09   NORTH EAST/WEST BLACK ARROW
 ⬊  ⬋    U+2B0A, U+2B0B   SOUTH EAST/WEST BLACK ARROW
 ⭧  ⭦    U+2B67, U+2B66   NORTH EAST/WEST TRIANGLE-HEADED ARROW
 ⭨  ⭩    U+2B68, U+2B69   SOUTH EAST/WEST TRIANGLE-HEADED ARROW
 ⭷  ⭶    U+2B77, U+2B76   NORTH EAST/WEST TRIANGLE-HEADED ARROW TO BAR
 ⭸  ⭹    U+2B78, U+2B79   SOUTH EAST/WEST TRIANGLE-HEADED ARROW TO BAR
 ⮎  ⮌    U+2B8E, U+2B8C   ANTICLOCKWISE TRIANGLE-HEADED LEFT/RIGHT U-
                          SHAPED ARROW
 ⮐  ⮑    U+2B90, U+2B91   RETURN LEFT/RIGHT
 ⮒  ⮓    U+2B92, U+2B93   NEWLINE LEFT/RIGHT
 ⯈  ⯇    U+2BC8, U+2BC7   BLACK MEDIUM RIGHT/LEFT-POINTING TRIANGLE
                          CENTRED
 ⯨  ⯩    U+2BE8, U+2BE9   LEFT/RIGHT HALF BLACK STAR
 ⹑  ⹐    U+2E51, U+2E50   CROSS PATTY WITH LEFT/RIGHT CROSSBAR
 ⼐ ⼕   U+2F10, U+2F15   KANGXI RADICAL OPEN BOX,  KANGXI RADICAL RIGHT
                          OPEN BOX
 ⿸ ⿹   U+2FF8, U+2FF9   IDEOGRAPHIC DESCRIPTION CHARACTER SURROUND FROM
                          UPPER LEFT/RIGHT
 ㊧ ㊨   U+32A7, U+32A8   CIRCLED IDEOGRAPH LEFT/RIGHT
 𐡸  𐡷    U+10878, U+10877 PALMYRENE RIGHT/LEFT-POINTING FLEURON
 𜽛  𜽬    U+1CF5B, U+1CF6C ZNAMENNY NEUME CHELYUSTKA,  ZNAMENNY NEUME
                          REVERSED CHELYUSTKA
 𝅊  𝅌    U+1D14A, U+1D14C MUSICAL SYMBOL TRIANGLE NOTEHEAD LEFT/RIGHT
                          WHITE
 𝅋  𝅍    U+1D14B, U+1D14D MUSICAL SYMBOL TRIANGLE NOTEHEAD LEFT/RIGHT
                          BLACK
 𝅐  𝅈    U+1D150, U+1D148 MUSICAL SYMBOL TRIANGLE NOTEHEAD UP RIGHT
                          WHITE,  MUSICAL SYMBOL TRIANGLE NOTEHEAD UP
                          WHITE
 𝅑  𝅉    U+1D151, U+1D149 MUSICAL SYMBOL TRIANGLE NOTEHEAD UP RIGHT
                          BLACK,  MUSICAL SYMBOL TRIANGLE NOTEHEAD UP
                          BLACK
 🀂  🀀    U+1F002, U+1F000 MAHJONG TILE WEST/EAST WIND
 🔎 🔍   U+1F50E, U+1F50D RIGHT/LEFT-POINTING MAGNIFYING GLASS
 🕃  🕄    U+1F543, U+1F544 NOTCHED LEFT/RIGHT SEMICIRCLE WITH THREE DOTS
 🖎  ✍    U+1F58E, U+270D  LEFT WRITING HAND,  WRITING HAND
 🖐  🖑    U+1F590, U+1F591 RAISED HAND WITH FINGERS SPLAYED,  REVERSED
                          RAISED HAND WITH FINGERS SPLAYED
 🗨  🗩    U+1F5E8, U+1F5E9 LEFT/RIGHT SPEECH BUBBLE
 🗬  🗭    U+1F5EC, U+1F5ED LEFT/RIGHT THOUGHT BUBBLE
 🗮  🗯    U+1F5EE, U+1F5EF LEFT/RIGHT ANGER BUBBLE
 🙒  🙐    U+1F652, U+1F650 NORTH EAST/WEST POINTING LEAF
 🙓  🙑    U+1F653, U+1F651 SOUTH EAST/WEST POINTING LEAF
 🙖  🙔    U+1F656, U+1F654 TURNED NORTH EAST/WEST POINTING LEAF
 🙗  🙕    U+1F657, U+1F655 TURNED SOUTH EAST/WEST POINTING LEAF
 🙚  🙘    U+1F65A, U+1F658 NORTH EAST/WEST POINTING VINE LEAF
 🙛  🙙    U+1F65B, U+1F659 SOUTH EAST/WEST POINTING VINE LEAF
 🙞  🙜    U+1F65E, U+1F65C HEAVY NORTH EAST/WEST POINTING VINE LEAF
 🙟  🙝    U+1F65F, U+1F65D HEAVY SOUTH EAST/WEST POINTING VINE LEAF
 🙢  🙠    U+1F662, U+1F660 NORTH EAST/WEST POINTING BUD
 🙣  🙡    U+1F663, U+1F661 SOUTH EAST/WEST POINTING BUD
 🙦  🙤    U+1F666, U+1F664 HEAVY NORTH EAST/WEST POINTING BUD
 🙧  🙥    U+1F667, U+1F665 HEAVY SOUTH EAST/WEST POINTING BUD
 🙮  🙬    U+1F66E, U+1F66C RIGHT/LEFTWARDS ROCKET
 🙾  🙿    U+1F67E, U+1F67F CHECKER BOARD,  REVERSE CHECKER BOARD
 🞂  🞀    U+1F782, U+1F780 BLACK RIGHT/LEFT-POINTING ISOSCELES RIGHT
                          TRIANGLE
 🡕  🡔    U+1F855, U+1F854 NORTH EAST/WEST SANS-SERIF ARROW
 🡖  🡗    U+1F856, U+1F857 SOUTH EAST/WEST SANS-SERIF ARROW
 🡥  🡤    U+1F865, U+1F864 WIDE-HEADED NORTH EAST/WEST LIGHT BARB ARROW
 🡦  🡧    U+1F866, U+1F867 WIDE-HEADED SOUTH EAST/WEST LIGHT BARB ARROW
 🡭  🡬    U+1F86D, U+1F86C WIDE-HEADED NORTH EAST/WEST BARB ARROW
 🡮  🡯    U+1F86E, U+1F86F WIDE-HEADED SOUTH EAST/WEST BARB ARROW
 🡵  🡴    U+1F875, U+1F874 WIDE-HEADED NORTH EAST/WEST MEDIUM BARB ARROW
 🡶  🡷    U+1F876, U+1F877 WIDE-HEADED SOUTH EAST/WEST MEDIUM BARB ARROW
 🡽  🡼    U+1F87D, U+1F87C WIDE-HEADED NORTH EAST/WEST HEAVY BARB ARROW
 🡾  🡿    U+1F87E, U+1F87F WIDE-HEADED SOUTH EAST/WEST HEAVY BARB ARROW
 🢅  🢄    U+1F885, U+1F884 WIDE-HEADED NORTH EAST/WEST VERY HEAVY BARB
                          ARROW
 🢆  🢇    U+1F886, U+1F887 WIDE-HEADED SOUTH EAST/WEST VERY HEAVY BARB
                          ARROW
 🤜 🤛   U+1F91C, U+1F91B RIGHT/LEFT-FACING FIST
 🫱 🫲   U+1FAF1, U+1FAF2 RIGHT/LEFTWARDS HAND
 🮲  🮳    U+1FBB2, U+1FBB3 LEFT/RIGHT HALF RUNNING MAN
 🮹  🮺    U+1FBB9, U+1FBBA LEFT/RIGHT HALF FOLDER
 🯇  🯈    U+1FBC7, U+1FBC8 STICK FIGURE LEANING LEFT/RIGHT

**Comment by rjbs** [comment]
I think that we want to revise the rules by which we pick pairs.  I could mean that in either sense of the word "revise"!

1. study them so we are confident they're right
2. change them [to make them easier to reason about or less surprising]

That said, those changes fit nicely in "adjust experiment."  I don't see a reason to _not_ merge this for further experimentation across v5.36+.

Are there objections?

**Comment by jkeenan** [comment]
> I think that we want to revise the rules by which we pick pairs. I could mean that in either sense of the word "revise"!
> 
>     1. study them so we are confident they're right
> 
>     2. change them [to make them easier to reason about or less surprising]
> 
> 
> That said, those changes fit nicely in "adjust experiment." I don't see a reason to _not_ merge this for further experimentation across v5.36+.
> 

Could you explain what you mean by "adjust experiment"?  I don't see that terminology in either this issue or our documentation?

**Comment by rjbs** [comment]
By "adjust experiment", I mean that if we create an experimental feature, and then find ways in which it's not quite ready yet, we can adjust it while it remains experimental.

**Pull request merged**
