### PR TITLE
Suggestions from GW Haywood

### PR DESCRIPTION
**Pull request by davorg**
See https://www.nntp.perl.org/group/perl.perl5.porters/2022/01/msg262533.html

### CODE REVIEW

**Comment by Grinnz** [comment]
This is going to require incrementing `$VERSION`. Please also change it to be declared as a string so the trailing zero doesn't get lost.

**Comment by davorg** [comment]
@Grinnz  Thanks for the advice. Done :-)

**Comment by Grinnz** [comment]
Failure is just `Dave Cross  <dave@perlhacks.com> not found in AUTHORS` - you may correct this or the merger can. LGTM

**Comment by Grinnz** [comment]
You are listed in AUTHORS already so Porting/checkAUTHORS.pl needs to be updated with the alternate email used for the commits.

**Review by Grinnz — APPROVED** [review]

**Comment by jkeenan** [comment]
Squashed, rebased on blead, merged in cc4fcefcb9.  Closing ticket.  Thank you very much.

**Pull request closed without merging**
