### PR TITLE
av.c - av_store() do the refcount dance around magic av's

### LINKED ISSUE #20675: Set magic in av_store called in such a way that if the magic dies we may leak a scalar
**Description**
av_store() calls mg_set(av), (and other magic), *after* storing the item in the array, but without calling refcount inc first, there is even a comment about it in aassign. If the magic dies and the scalar was mortalized prior to store we then end up freeing the scalar when we clear the mortals, even though it is still referenced by the array.  This then results in an attempt to free unreferenced scalar in global destruction error. We have to store the item in the AV before we call the magic because in mg_set(av) the magic needs to be able to see the newly stored value. This seems somewhat at odds with the comment in aassign which says and does this:

https://github.com/Perl/perl5/blob/blead/pp_hot.c#L2527
```
            if (SvMAGICAL(ary) || SvREADONLY(ary) || !AvREAL(ary)) {
                /* for arrays we can't cheat with, use the official API */
                av_extend(ary, nelems - 1);
                for (i = 0; i < nelems; i++) {
                    SV **svp = &(PL_tmps_stack[tmps_base + i]);
                    SV *rsv = *svp;
                    /* A tied store won't take ownership of rsv, so keep
                     * the 1 refcnt on the tmps stack; otherwise disarm
                     * the tmps stack entry */
                    if (av_store(ary, i, rsv))
                        *svp = &PL_sv_undef;
                    /* av_store() may have added set magic to rsv */;
                    SvSETMAGIC(rsv);
                }
                /* disarm ary refcount: see comments below about leak */
                PL_tmps_stack[tmps_base - 1] = &PL_sv_undef;
            }
            else {
                /* directly access/set the guts of the AV */
                SSize_t fill = nelems - 1;
                if (fill > AvMAX(ary))
                    av_extend_guts(ary, fill, &AvMAX(ary), &AvALLOC(ary),
                                    &AvARRAY(ary));
                AvFILLp(ary) = fill;
                Copy(&(PL_tmps_stack[tmps_base]), AvARRAY(ary), nelems, SV*);
                /* Quietly remove all the SVs from the tmps stack slots,
                 * since ary has now taken ownership of the refcnt.
                 * Also remove ary: which will now leak if we die before
                 * the SvREFCNT_dec_NN(ary) below */
                if (UNLIKELY(PL_tmps_ix >= tmps_base + nelems))
                    Move(&PL_tmps_stack[tmps_base + nelems],
                         &PL_tmps_stack[tmps_base - 1],
                         PL_tmps_ix - (tmps_base + nelems) + 1,
                         SV*);
                PL_tmps_ix -= (nelems + 1);
            }
```

I dont understand the code in the first block that looks like this:

```
/* disarm ary refcount: see comments below about leak */
                PL_tmps_stack[tmps_base - 1] = &PL_sv_undef;
```

It seems to do its thing too late. And it doesnt seem to deal with the many items on the stack. So I dont get it.

Bisect says this was broken in 80c1439ffbd799a82c109d650c32e9ecc7a3eb26  @iabyn can you take a look at this and the patch in #20676?

**Steps to Reproduce**

This is visible using Variable::Magic with the following script:

```
use Variable::Magic qw(wizard cast);
use Devel::Peek;
my $wizard = wizard(set => sub { 
        warn "In set\n";
        Dump($_[0]);
        study(); die "@_"; 
});
cast my @x, $wizard;
eval { @x = (1,2,3) };
warn "Final\n";
Dump(\@x);
```
On my system '@x' ends up storing a reference to itself, and you can see the refcount doesn't make sense, it then complains about an unreferenced scalar:

```
Final
SV = IV(0x564b8b660508) at 0x564b8b660518
  REFCNT = 1
  FLAGS = (TEMP,ROK)
  RV = 0x564b8b746ea8
  SV = PVAV(0x564b8b703df8) at 0x564b8b746ea8
    REFCNT = 2
    FLAGS = (SMG)
    MAGIC = 0x564b8b69eb50
      MG_VIRTUAL = 0x564b8b6a2d60
      MG_TYPE = PERL_MAGIC_ext(~)
      MG_LEN = -2
      MG_PTR = 0x564b8b747a18 => HEf_SVKEY
      SV = PVMG(0x564b8b747f20) at 0x564b8b747a18
        REFCNT = 2
        FLAGS = (RMG,READONLY)
        IV = 0
        NV = 0
        PV = 0
        MAGIC = 0x564b8b69ea70
          MG_VIRTUAL = 0x7fdf052a32c0
          MG_TYPE = PERL_MAGIC_ext(~)
          MG_FLAGS = 0x10
            DUP
          MG_PTR = 0x564b8b681280 ""
    ARRAY = 0x564b8b683780
    FILL = 0
    MAX = 3
    FLAGS = (REAL)
    Elt No. 0
    SV = IV(0x564b8b660508) at 0x564b8b660518
      REFCNT = 1
      FLAGS = (TEMP,ROK)
      RV = 0x564b8b746ea8
      SV = PVAV(0x564b8b703df8) at 0x564b8b746ea8
        REFCNT = 2
        FLAGS = (SMG)
        MAGIC = 0x564b8b69eb50
          MG_VIRTUAL = 0x564b8b6a2d60
          MG_TYPE = PERL_MAGIC_ext(~)
          MG_LEN = -2
          MG_PTR = 0x564b8b747a18 => HEf_SVKEY
          SV = PVMG(0x564b8b747f20) at 0x564b8b747a18
            REFCNT = 2
            FLAGS = (RMG,READONLY)
            IV = 0
            NV = 0
            PV = 0
            MAGIC = 0x564b8b69ea70
              MG_VIRTUAL = 0x7fdf052a32c0
              MG_TYPE = PERL_MAGIC_ext(~)
              MG_FLAGS = 0x10
                DUP
              MG_PTR = 0x564b8b681280 ""
        ARRAY = 0x564b8b683780
        FILL = 0
        MAX = 3
        FLAGS = (REAL)
        Elt No. 0
        SV = IV(0x564b8b660508) at 0x564b8b660518
          REFCNT = 1
          FLAGS = (TEMP,ROK)
          RV = 0x564b8b746ea8
Attempt to free unreferenced scalar: SV 0x564b8b660518, Perl interpreter: 0x564b8b65d2a0.
```

This was original reported by @ovid on perl5porters in message id `<CA+M4CHsKYZz9ob4TLZEod+1t6V6kZJj6sgxnjauGo4s+5Ucuvg@mail.gmail.com>`

And has also been reported to Variable::Magic at https://rt.cpan.org/Public/Bug/Display.html?id=145680 where Vincent (IMO rightly) rejected the bug and pointed back at core. I concur with his analysis.

**Expected behavior**
The set should die, and nothing should get freed twice.  I have a provisional fix which I will push once this is filed.

**Perl configuration**
```
perl -V
Summary of my perl5 (revision 5 version 37 subversion 8) configuration:
  Derived from: 25a36e71fc493a6139ad72fbee25617b129969f1
  Platform:
    osname=linux
    osvers=5.14.0-1054-oem
    archname=x86_64-linux-thread-multi
    uname='linux oncidium 5.14.0-1054-oem #61-ubuntu smp fri oct 14 13:05:50 utc 2022 x86_64 x86_64 x86_64 gnulinux '
    config_args='-de -Dcc=ccache gcc -Dld=gcc -Dprefix=/home/yorton/perl5/perlbrew/perls/latest_blead -Dman1dir=none -Dman3dir=none -Dusemultiplicity -Dusethreads -DDEBUGGING -Dusedevel -Aeval:scriptdir=/home/yorton/perl5/perlbrew/perls/latest_blead/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='9.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.31.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.31'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Locally applied patches:
    uncommitted-changes
  Built under linux
  Compiled at Jan  4 2023 21:18:46
  %ENV:
    PERLBREW_CONFIGURE_FLAGS="-de -Dcc=ccache\ gcc -Dld=gcc"
    PERLBREW_HOME="/home/yorton/.perlbrew"
    PERLBREW_MANPATH="/home/yorton/perl5/perlbrew/perls/latest_blead/man"
    PERLBREW_PATH="/home/yorton/perl5/perlbrew/bin:/home/yorton/perl5/perlbrew/perls/latest_blead/bin"
    PERLBREW_PERL="latest_blead"
    PERLBREW_ROOT="/home/yorton/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.88"
    PERLBREW_VERSION="0.88"
  @INC:
    /home/yorton/perl5/perlbrew/perls/latest_blead/lib/site_perl/5.37.8/x86_64-linux-thread-multi
    /home/yorton/perl5/perlbrew/perls/latest_blead/lib/site_perl/5.37.8
    /home/yorton/perl5/perlbrew/perls/latest_blead/lib/5.37.8/x86_64-linux-thread-multi
    /home/yorton/perl5/perlbrew/perls/latest_blead/lib/5.37.8
```

### PR DESCRIPTION
**Pull request by demerphq**
The api for av_store() says it is the callers responsibility to call SvREFCNT_inc() on the stored item after the store is successful.

However inside of av_store() we store the item in the C level array before we trigger magic. To a certain extent this is required because mg_set(av) needs to be able to see the newly stored item.

But if the mg_set() or other magic associated with the av_store() operation fails, we would end up with a double free situation, as we will long jump up the stack above and out of the call to av_store(), freeing the mortal as we go (via Perl_croak()), but leaving the reference to the now freed pointer in the array. When the next SV is allocated the reference will be reused, and then we are in a double free scenario.

I see comments in pp_aassign talking about defusing the temps stack for the parameters it is passing in, and things like this, which at first looked related. But that commentary doesn't seem that relevant to me, as this bug could happen any time a scalar owned by one data structure was copied into an array with set magic which could die. Eg, I can easily imagine XS code that expected code like this (assume it handles magic properly) to work:

    SV **svp = av_fetch(av1,0,1);
    if (av_store(av2,0,*svp))
        SvREFCNT_inc(*svp);

but if av2 has set magic and it dies the end result will be that both av1 and av2 contain a visible reference to *svp, but its refcount will be 1. So I think this is a bug regardless of what pp_aassign does.

This fixes https://github.com/Perl/perl5/issues/20675

### CODE REVIEW

**Comment by tonycoz** [comment]
I think it's safe, but would like another opinion.

**Comment by jkeenan** [comment]
> 
> This fixes #20675

In https://github.com/Perl/perl5/issues/20675, it was stated that the "Expected behavior" would be: "The set should die, and nothing should get freed twice."

Can we get a unit test demonstrating this?

**Comment by demerphq** [comment]
> Can we get a unit test demonstrating this?

Maybe yes. I saw that @iabyn added some code to XS-APItest in the commit where this bug was introduced that could probably be cargo-culted to test what we need to test I think. But it is bedtime here now. Maybe you want to make a stab at it yourself? See https://github.com/Perl/perl5/commit/80c1439ffbd799a82c109d650c32e9ecc7a3eb26

**Comment by demerphq** [comment]
@jkeenan test added.

**Comment by jkeenan** [comment]
On 1/5/23 04:31, Yves Orton wrote:
> @jkeenan <https://github.com/jkeenan> test added.
> 

Thanks.  I recommend adding the GH p.r. URL to the inline comments.

**Comment by demerphq** [comment]
@jkeenan I already added a link to the issue, which is more informative than this PR. 

https://github.com/Perl/perl5/pull/20676/files#diff-7dba2c9b471d66f1d1650b3f1653fe42307cba352ccaebebbd1740592573ee71R409

**Comment by demerphq** [comment]
@iabyn approved this in the issue related to it so I will merge

**Pull request merged**
