### PR TITLE
Give SV information in default typemap

### PR DESCRIPTION
**Pull request by FGasper**
Issue #18461

### CODE REVIEW

**Comment by Leont** [comment]
I'm not sure this error message is really more useful than the previous one. Could you explain to me how it would be helpful?

**Comment by FGasper** [comment]
> I'm not sure this error message is really more useful than the previous one. Could you explain to me how it would be helpful?

@Leont By showing what the wrong thing is—not merely that it’s the wrong type of thing—it’ll be easier to determine how we got there in the first place.

Apparently there’s a case where DNS::Unbound has the wrong type of internal object and is sending it to the destructor, leading to this:
```
(in cleanup) DNS::Unbound::_destroy_context: ctx is not of type struct ub_ctxPtr
```
There’s already a filter in place to ensure that global-destruct doesn’t send undef into that _destroy_context() function; it looks like there’s somehow some other non-falsy value that’s being stored.

I’m altering DNS::Unbound to tell me what this value is; I thought it would be useful upstream as well.

**Comment by Leont** [comment]
> By showing what the wrong thing is—not merely that it’s the wrong type of thing—it’ll be easier to determine how we got there in the first place.

I get your intention, but `scalar: 123123` isn't the clearest way of showing what is wrong. If something should have been a reference but isn't, why don't we just say that? And likewise if something is blessed into the wrong class.

**Comment by FGasper** [comment]
@Leont If I take your meaning, you’re looking for different wording?

Maybe:

> Expected `ctx` to be a `struct ub_ctxPtr` reference; received `ARRAY` reference instead.

> Expected `ctx` to be a `struct ub_ctxPtr` reference; received scalar (123123) instead.

> Expected `ctx` to be a `struct ub_ctxPtr` reference; received undef instead.

**Comment by FGasper** [comment]
Feedback from @Leont @tonycoz incorporated. Further thoughts?

Thank you!

**Comment by jkeenan** [comment]
> Issue #18461

Are there any places in the test suite where we exercise the *existing* error messages?

If so, then we may need to modify those tests?

If not, then perhaps we should write tests to exercise them.

Thank you very much.
Jim Keenan

**Comment by tonycoz** [comment]
`ext/XS-Typemap/t/Typemap.t` tests that error messages are produced in a limited set of cases, but not their content

**Pull request merged**
