### PR TITLE
build: add configurations to compile perl for windows/arm64

### PR DESCRIPTION
**Pull request by niyas-sait**
This change is adding a few missing configurations to compile `Perl` for windows/arm64 targets.

All tests are not passing yet on windows/arm64 but this could be a starting point.

```
Test Summary Report
-------------------
porting/customized.t                                               (Wstat: 0 Tests: 22 Failed: 22)
  Failed tests:  1-22
porting/pending-author.t                                           (Wstat: 0 Tests: 1 Failed: 1)
  Failed test:  1
porting/pod_rules.t                                                (Wstat: 0 Tests: 5 Failed: 4)
  Failed tests:  2-5
  Parse errors: Bad plan.  You planned 7 tests but ran 5.
porting/regen.t                                                    (Wstat: 65280 Tests: 12 Failed: 1)
  Failed test:  12
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 42 tests but ran 12.
../cpan/CPAN-Meta-YAML/t/30_yaml_spec_tml.t                        (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
../cpan/CPAN-Meta-YAML/t/31_local_tml.t                            (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
../cpan/CPAN-Meta-YAML/t/32_world_tml.t                            (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
../cpan/Term-Cap/test.pl                                           (Wstat: 512 Tests: 45 Failed: 2)
  Failed tests:  16, 22
  Non-zero exit status: 2
../cpan/Win32/t/Names.t                                            (Wstat: 256 Tests: 16 Failed: 1)
  Failed test:  6
  Non-zero exit status: 1
../ext/IPC-Open3/t/IPC-Open3.t                                     (Wstat: 0 Tests: 45 Failed: 0)
  TODO passed:   25
Files=2745, Tests=1152241, 1996 wallclock secs (81.53 usr + 10.36 sys = 91.89 CPU)
```

### CODE REVIEW

**Comment by niyas-sait** [comment]
Update:

`cpan/Win32/t/Names.t` failure will be fixed by [Add support for ARM/ARM64 architecture by pbo-linaro · Pull Request #34 · perl-libwin32/win32](https://github.com/perl-libwin32/win32/pull/34)

**Comment by niyas-sait** [comment]
@khwilliamson Apologies to ping you directly. I have been waiting for a review for this for a few days. Just wondering if someone can help with the review. Thanks

**Comment by Leont** [comment]
> @khwilliamson Apologies to ping you directly. I have been waiting for a review for this for a few days. Just wondering if someone can help with the review. Thanks

I suspect this needs a Windows person like @xenu or @sisyphus

**Comment by khwilliamson** [comment]
This looks reasonable to me, but I would defer to  @xenu or @sisyphus or @steve-m-hay

**Comment by xenu** [comment]
LGTM

**Comment by p-b-o** [comment]
For completeness, after investigation, only one test failure was reproducible:

```
Test Summary Report
-------------------
../cpan/Win32/t/Names.t                                            (Wstat: 256 (exited 1) Tests: 16 Failed: 1)
  Failed test:  6
  Non-zero exit status: 1
../ext/IPC-Open3/t/IPC-Open3.t                                     (Wstat: 0 Tests: 45 Failed: 0)
  TODO passed:   25
Files=2766, Tests=1153792, 1224 wallclock secs (32.30 usr + 14.34 sys = 46.64 CPU)
Result: FAIL
```

tested natively on arm64 windows machine with:
```
$ cd win32
$ nmake CCTYPE=MSVC142 test-prep
$ cd ../t
$ file perl.exe
perl.exe: PE32+ executable (console) Aarch64, for MS Windows
$ ./perl.exe harness
```

See tests log on our CI (ran today):
- [run-script](https://gitlab.com/Linaro/windowsonarm/packages/perl5-testing/-/blob/master/recipe.sh) - version is ce90e44439
- [pipeline](https://gitlab.com/Linaro/windowsonarm/packages/perl5-testing/-/jobs/2445961965) - [raw log](https://gitlab.com/Linaro/windowsonarm/packages/perl5-testing/-/jobs/2445961965/raw) - grep "Failed"
  op/stat.t failure is related to CI env (no stdin), does not happen when running interactively.

**Pull request merged**
