### PR TITLE
Update Data::Dumper synopsis

### PR DESCRIPTION
**Pull request by rwp0**
Add `my` to synopsis.

### CODE REVIEW

**Comment by rwp0** [comment]
Any feedback on this PR?
Looks like all is good, the two test failures are on macOS and seem unrelated.

**Comment by rwp0** [comment]
Is Dumper developed separately from Perl core?

**Comment by jkeenan** [comment]
On 9/24/22 21:07, Elvin Aslanov wrote:
> Is Dumper developed separately from Perl core?
> 

In the Perl core distribution, you find Data-Dumper under dist/.  That 
means it's "dual life, but blead upstream."  That is, the core 
distribution's blead (main) branch is the place development should occur 
first.  Then, periodically (or perhaps intermittently), releases are 
made to CPAN so that older perls can obtain the benefit of improvements 
in core.

**Comment by jkeenan** [comment]
I updated $VERSION in the POD, then locally merged and pushed in a0a15662a9.  Closing ticket.

**Pull request closed without merging**
