### PR TITLE
leonerd's svtrue branch as a PR

### LINKED ISSUE #17225: The non-GCC SvTRUEx() macro is unsafe
Module: none

**Description**

The non-GCC SvTRUEx() macro expands like:

```C
#  define SvTRUEx(sv)      ((PL_Sv = (sv)), SvTRUE(PL_Sv))
#define SvTRUE(sv)         (LIKELY(sv) && SvTRUE_NN(sv))
#define SvTRUE_NN(sv)      (SvGETMAGIC(sv), SvTRUE_nomg_NN(sv))
#define SvTRUE_nomg_NN(sv) (SvTRUE_common(sv, sv_2bool_nomg(sv)))
```

While this prevents the argument sv to SvTRUEx() from being evaluated multiple times, if the sv has any magic the SvGETMAGIC() call may call code that uses any of the other SvFOOx() macros that also modify PL_Sv, which is interpreter global, so the following call to SvTRUE_nomg_NN() will end up testing the wrong sv.

**Expected behavior**

Similar to the other SvFOOx() macros, SvTRUEx() should leave magic to a helper function.

**Perl configuration**
```
Summary of my perl5 (revision 5 version 31 subversion 6) configuration:
  Commit id: 0927980403a8984cd4df39ccb644eb53b1e6a3b2
  Platform:
    osname=linux
    osvers=4.9.0-9-amd64
    archname=x86_64-linux-thread-multi
    uname='linux mars 4.9.0-9-amd64 #1 smp debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 gnulinux '
    config_args='-des -Dusedevel -Dusethreads -Doptimize=-O0 -g'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='6.3.0 20170516'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib /lib64 /usr/lib64
    libs=-lpthread -lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Oct 25 2019 05:31:00
  %ENV:
    PERLBREW_BASHRC_VERSION="0.43"
    PERLBREW_HOME="/home/tony/.perlbrew"
    PERLBREW_MANPATH=""
    PERLBREW_PATH="/home/tony/perl5/perlbrew/bin"
    PERLBREW_ROOT="/home/tony/perl5/perlbrew"
    PERLBREW_VERSION="0.67"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.31.6/x86_64-linux-thread-multi
    /usr/local/lib/perl5/site_perl/5.31.6
    /usr/local/lib/perl5/5.31.6/x86_64-linux-thread-multi
    /usr/local/lib/perl5/5.31.6

```

### PR DESCRIPTION
**Pull request by tonycoz**
see what the CI makes of it, expect to merge it pretty quickly

fixes #17225

### CODE REVIEW

**Comment by dur-randir** [comment]
Checking with gcc 8.3.0 and -O2, it hasn't been inlined in 2 calls sites in Perl_parse_uniprop_string. It looks fine in modules.

**Comment by tonycoz** [comment]
I saw the same, one is from this conditional:
````
            if (TAINT_get || SvTRUE(error)) {
````

which seemed strange, could gcc consider `TAINT_get` to be likely?  I added UNLIKELY() around it in perl.h and SvTRUE() was inlined.

I wonder if we should make TAINT_get and TAINTING_get unlikely?

**Comment by khwilliamson** [comment]
What about the other place it didn't get inlined?

**Comment by atoomic** [comment]
Should we block this Pull Request for the two locations not inlined?

My recommendation would be to merge it as it, and come back with some follow up if needed for the two extra locations that need to be inlined?

Any feedbacks?

**Comment by dur-randir** [comment]
I feel that unless this is resolved now or a new blocker ticket is created, the same symptoms can spread unnoticed over the codebase, which couldn't have happened with macros.

**Comment by iabyn** [comment]
On Thu, Jan 02, 2020 at 04:27:53PM -0800, Sergey Aleynikov wrote:
> I feel that unless this is resolved now or a new blocker ticket is
> created, the same symptoms can spread unnoticed over the codebase, which
> couldn't have happened with macros.

So, we get the extra overhead of a function call in occasional places
where the compiler has decided it doesn't really matter? I'm ok with that.

-- 
Decaffeinated coffee is like dehydrated water

**Comment by hvds** [comment]
> On Thu, Jan 02, 2020 at 04:27:53PM -0800, Sergey Aleynikov wrote: I feel that unless this is resolved now or a new blocker ticket is created, the same symptoms can spread unnoticed over the codebase, which couldn't have happened with macros.
> So, we get the extra overhead of a function call in occasional places where the compiler has decided it doesn't really matter? I'm ok with that.

More than that: the compiler has decided it's preferable; eg by saving the bytes it may make some branch destinations nearer allowing a more efficient type of branch. One of the points of inline is that the compiler is allowed to know better.

I haven't seen the other uninlined location mentioned, and I'm not sure offhand how to look for these short of grepping a disassembly. There's some value in looking at that one too, to get a better understanding of what's triggering the compiler's decisions.

Hugo

**Comment by xenu** [comment]
> I'm not sure offhand how to look for these short of grepping a disassembly. 

`-Winline`

>So, we get the extra overhead of a function call in occasional places
where the compiler has decided it doesn't really matter? I'm ok with that.

Inlining and autovectorization are the two areas where compilers are wrong more often than not. Even with the `inline` specifier they don't do the right thing due to a tiny default inlining budget and dumb function size growth heuristics.

**Comment by khwilliamson** [comment]
On 1/3/20 7:18 AM, xenu wrote:
>     I'm not sure offhand how to look for these short of grepping a
>     disassembly.
> 
> |-Winline|
> 
>     So, we get the extra overhead of a function call in occasional places
>     where the compiler has decided it doesn't really matter? I'm ok with
>     that.
> 
> Inlining and autovectorization are the two areas where compilers are 
> wrong more often than not. Even with the |inline| specifier they don't 
> do the right thing due to a tiny default inlining budget and dumb 
> function size growth heuristics.
> 

Would your in-progress work of inline-all overcome this for cases like 
SvTRUE?

**Comment by dur-randir** [comment]
> So, we get the extra overhead of a function call in occasional places
where the compiler has decided it doesn't really matter? I'm ok with that.


I can easily see the currently known pattern of TAINT_get + SvTRUE appearing in some hot path. While this is not the end of the world, i don't think that even modern compilers always make correct predictions about what is more likely to get called and thus correctly choosing such microoptimisations.

**Comment by iabyn** [comment]
On Fri, Jan 03, 2020 at 12:37:32PM -0800, Sergey Aleynikov wrote:
> > So, we get the extra overhead of a function call in occasional places
> where the compiler has decided it doesn't really matter? I'm ok with that.
> 
> 
> I can easily see the currently known pattern of TAINT_get + SvTRUE
> appearing in some hot path. While this is not the end of the world, i
> don't think that even modern compilers always make correct predictions
> about what is more likely to get called and thus correctly choosing such
> microoptimisations.

Currently SvTRUE() is a large macro, and inlining it may not necessarily
always be a good thing. And TAINT_get() being true is (relatively)
unlikely. Personally I think the compiler failing to inline SvTRUE
following a TAINT_get here is actually a *good* thing.

-- 
Fire extinguisher (n) a device for holding open fire doors.

**Comment by khwilliamson** [comment]
Here's the current list of functions in blead on my linux box that don't get inlined:
dquote_inline.h:39:1: warning: inlining failed in call to ‘S_form_short_octal_warning’: call is unlikely and code size would grow [-Winline]
gv.c:707:1: warning: inlining failed in call to ‘S_gv_fetchmeth_internal’: --param max-inline-insns-single limit reached [-Winline]
hv_func.h:104:5: warning: inlining failed in call to ‘S_perl_hash_with_seed’: --param large-stack-frame-growth limit reached [-Winline]
inline.h:1589:1: warning: inlining failed in call to ‘Perl_utf8_hop_back.constprop’: call is unlikely and code size would grow [-Winline]
inline.h:1847:1: warning: inlining failed in call to ‘Perl_utf8_to_uvchr_buf_helper.constprop’: call is unlikely and code size would grow [-Winline]
inline.h:292:1: warning: inlining failed in call to ‘Perl_croak_memory_wrap’: call is unlikely and code size would grow [-Winline]
inline.h:64:1: warning: inlining failed in call to ‘Perl_CvDEPTH’: call is unlikely and code size would grow [-Winline]
invlist_inline.h:135:1: warning: inlining failed in call to ‘S_invlist_highest’: call is unlikely and code size would grow [-Winline]
invlist_inline.h:181:1: warning: inlining failed in call to ‘S_invlist_iterinit’: call is unlikely and code size would grow [-Winline]
invlist_inline.h:48:1: warning: inlining failed in call to ‘S__invlist_len’: call is unlikely and code size would grow [-Winline]
invlist_inline.h:63:1: warning: inlining failed in call to ‘S__invlist_contains_cp’: call is unlikely and code size would grow [-Winline]
invlist_inline.h:75:1: warning: inlining failed in call to ‘S_invlist_array’: call is unlikely and code size would grow [-Winline]
op.c:5861:1: warning: inlining failed in call to ‘S_fold_constants_eval’: function not inlinable [-Winline]
re_comp.c:2006:1: warning: inlining failed in call to ‘S_ssc_union’: call is unlikely and code size would grow [-Winline]
re_comp.c:2019:1: warning: inlining failed in call to ‘S_ssc_intersection’: call is unlikely and code size would grow [-Winline]
re_comp.c:2034:1: warning: inlining failed in call to ‘S_ssc_add_range’: call is unlikely and code size would grow [-Winline]
sbox32_hash.h:1493:26: warning: inlining failed in call to ‘sbox32_hash_with_state.constprop’: --param max-inline-insns-single limit reached [-Winline]
zaphod32_hash.h:176:5: warning: inlining failed in call to ‘zaphod32_hash_with_state’: call is unlikely and code size would grow [-Winline]

I note that there are some non-inlined in re_comp.c., but those apparently did get inlined in regcomp.c

**Comment by hvds** [comment]
> What about the other place it didn't get inlined?

Looks like it's a similar case, suppressed by this change:
```
--- a/regcomp.c
+++ b/regcomp.c
@@ -23927,7 +23927,7 @@ Perl_parse_uniprop_string(pTHX_
                     sv_catsv(msg, error);
                     sv_catpvs(msg, "\"");
                 }
-                if (TAINT_get) {
+                if (UNLIKELY(TAINT_get)) {
                     if (SvTRUE(error)) sv_catpvs(msg, "; ");
                     sv_catpvn(msg, insecure, sizeof(insecure) - 1);
                 }
```

.. so should already have been fixed by marking TAINT_get implicitly unlikely.

**Comment by khwilliamson** [comment]
On 1/6/20 4:54 AM, Hugo van der Sanden wrote:
>     What about the other place it didn't get inlined?
> 
> Looks like it's a similar case, suppressed by this change:
> 
> |--- a/regcomp.c +++ b/regcomp.c @@ -23927,7 +23927,7 @@ 
> Perl_parse_uniprop_string(pTHX_ sv_catsv(msg, error); sv_catpvs(msg, 
> "\""); } - if (TAINT_get) { + if (UNLIKELY(TAINT_get)) { if 
> (SvTRUE(error)) sv_catpvs(msg, "; "); sv_catpvn(msg, insecure, 
> sizeof(insecure) - 1); } |
> 
> .. so should already have been fixed by marking TAINT_get implicitly 
> unlikely.
> 

We have two different situations here in regcomp.c

Here the UNLIKELY would mean it's better for the compiler to NOT inline 
SvTRUE, as the code is not likely to get executed.

The other situation was

if (TAINT_get || SvTRUE(error)) {

There, the SvTRUE is relatively likely to get executed, so it would be 
fine to inline it.  But, in looking at the context these statements 
occur in, we don't actually care if these two calls get inlined, as they 
are both used in constructing an error message: program is about to die 
anyway.

**Pull request merged**
