### PR TITLE
dist/IO: move binmode from IO::File to IO::Handle

### LINKED ISSUE #17457: PATCH: move binmode method to IO::Handle from IO::File [rt.cpan.org #65107]
Migrated from [rt.cpan.org#65107](https://rt.cpan.org/Ticket/Display.html?id=65107) (status was 'new')

Requestors:
* ambrus@math.bme.hu

From ambrus@math.bme.hu on 2011-01-25 16:06:08:

This is a bug report for perl from ambrus@math.bme.hu,
generated with the help of perlbug 1.39 running under perl 5.12.3.

-----------------------------------------------------------------
[Please describe your issue here]

The binmode method belongs to the IO::Handle class, because PerlIO
layers can be applied to any kind of file descriptor, not the IO::File
subclass where it currently is.  The patch below (based on perl 5.13.9)
moves the method to the IO::Handle class.

<details><summary>Perl Info</summary>

```
-----------------------------------------------------------------
---
Flags:
    category=library
    severity=low
    module=IO::Handle
---
Site configuration information for perl 5.12.3:

Configured by ambrus at Tue Jan 25 14:12:12 CET 2011.

Summary of my perl5 (revision 5 version 12 subversion 3) configuration:

  Platform:
    osname=linux, osvers=2.6.34.1, archname=x86_64-linux
    uname='linux king 2.6.34.1 Perl/IO#1 smp sat jul 10 18:21:56 cest 2010
x86_64 gnulinux '
    config_args='-Dinc_version_list=5.12.2/x86_64-linux 5.12.2
5.12.1/x86_64-linux 5.12.1 5.12.0/x86_64-linux 5.12.0 -d'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.5.1', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t',
lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64 /usr/local/lib64
    libs=-lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.7.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.7'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -L/usr/local/lib
-fstack-protector'

Locally applied patches:


---
@INC for perl 5.12.3:
    /usr/local/lib/perl5/site_perl/5.12.3/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.12.3
    /usr/local/lib/perl5/5.12.3/x86_64-linux
    /usr/local/lib/perl5/5.12.3
    /usr/local/lib/perl5/site_perl/5.12.2/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.12.2
    /usr/local/lib/perl5/site_perl/5.12.1/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.12.1
    /usr/local/lib/perl5/site_perl/5.12.0/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.12.0
    /usr/local/lib/perl5/site_perl
    .

---
Environment for perl 5.12.3:
    HOME=/home/ambrus
    LANG (unset)
    LANGUAGE (unset)
    LC_CTYPE=hu_HU
    LD_LIBRARY_PATH=/home/ambrus/local/lib/
    LOGDIR (unset)
    PATH=/home/ambrus/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/bash
```
</details>

### PR DESCRIPTION
**Pull request by tonycoz**
since you can binmode() any handle.

Fixes #17457 which is most of this change, I only added tests, such as they are.

### CODE REVIEW

**Comment by jkeenan** [comment]
The change looks okay to me.  **However,** since these modules are housed under `dist/`, they are independently releasable on CPAN for installation against older versions of `perl`.  Indeed, https://metacpan.org/pod/IO::Handle shows that @toddr performed such a release earlier this year.  Do we have any way of testing these changes against older versions of `perl` before we apply them to blead?

**Comment by tonycoz** [comment]
> Do we have any way of testing these changes against older versions of `perl` before we apply them to blead?

CI tests (and tested this change) dist/ modules against 5.8, 5.10, 5.24, latest maint (5.38.2 in this case).

**Comment by toddr** [comment]
> The change looks okay to me. **However,** since these modules are housed under `dist/`, they are independently releasable on CPAN for installation against older versions of `perl`. Indeed, https://metacpan.org/pod/IO::Handle shows that @toddr performed such a release earlier this year. Do we have any way of testing these changes against older versions of `perl` before we apply them to blead?

That's what the github actions for cpan/io does. https://github.com/Dual-Life/IO/actions/runs/3983577079

**Comment by xenu** [comment]
> since you can binmode() any handle.

I was going to say that you can't binmode directory handles, but apparently `IO::Dir` doesn't inherit from `IO::Handle`, so it's all good.

**Review by mauke — APPROVED** [review]

**Pull request merged**
