### PR TITLE
[Win32] On mingw-w64 builds, set $Config{libc} to the default runtime.

### PR DESCRIPTION
**Pull request by sisyphus**

### CODE REVIEW

**Comment by sisyphus** [comment]
See https://github.com/Perl/perl5/pull/21612 for context.
Basically, by setting <code>$Config{libc}</code> to the default runtime (which will be either <code>-lucrt</code> or <code>-lmsvcrt</code>) we enable perl scripts to determine the identity of the default runtime.

**Comment by khwilliamson** [comment]
LGTM, @xenu @tonycoz  comments?

**Comment by tonycoz** [comment]
This should be a single commit, no individual commit works without the others.

Other than that and the `.mailmap` thing below I think it's good.

Also,:
```
#   Failed test 'Is mailmap_file '.mailmap' up to date?'
#   at Porting/updateAUTHORS.pl line 127.
#   File '.mailmap' changes:
#     would add: Sisyphus <sisyphus@cpan.org> sisyphus <sisyphus359@gmail.com>
# 
# Files need updating! You probably just need to run
# 
#    Porting/updateAUTHORS.pl

```

**Comment by sisyphus** [comment]
> This should be a single commit, no individual commit works without the others.

So ... instead of running 3 separate commits perhaps I should have run something like <code>git commit --all --file=msg.txt</code> (where msg.txt is the file containing the commit message).
Would that have had the desired effect ? 

Later on today, I'll try to squash the commits into 1.
Then I'll try running Porting/updateAUTHORS.pl and see what happens from that....
If it all goes to shit, I'll just close this PR and try again from scratch.

**Comment by sisyphus** [comment]
Sorry for wasting your time, @khw.
You'd be better off just creating the PR, yourself - and I apologize for not having suggested that in the first place. (No accreditation required or warranted.)

This git stuff is just way too time-consuming, confusing and frustrating for me to deal with.

**Comment by demerphq** [comment]
> This git stuff is just way too time-consuming, confusing and frustrating for me to deal with.

I'd be happy to help you with that if you mail me. Squashing those commits using `git rebase --interactive` should have been trivial. What went wrong?

**Comment by sisyphus** [comment]
Ok @demerphq, I'll reopen - with apologies again to @khw for dragging this out.
Following an earlier mantra you had given me, I ran:
```
$ git checkout locale_configure
$ git fetch
$ git rebase origin/blead
$ git reset origin/blead
$ git commit -a -m'appropriate message'
```
That all seemed to work ok - but, IIRC, the "Unstaged changes after reset" specified by the second last command mentioned only MANIFEST and win32/config_sh.PL, making no mention of win32/configure/rt.c.
And <code>$ git push</code> did not take and reported a bunch of hints that I didn't really understand, and that I can no longer recall.

Anyway, I've since deleted my local copy of my fork - so the first thing I need to do is regain a copy of my perl5 fork from github.
I ran <code>git clone https://github.com/sisyphus/perl5 sis-fork</code>, but then my <code>sis-fork</code> clone does not have a <code>locale_configure</code> branch.

What's the best way of retrieving a local copy of that github clone (including the <code>locale_configure</code> branch) ?

Also, do I need to address the <code>.mailmap</code> issue before squashing commits ?

As regards "interactive" commands, I'm not sure if this Cygwin system I'm using has a text editor.
If it does, then I've never used it. (I have no experience with text editors.)

See what you're up against ?
(@khw, you're still welcome to go ahead with doing your own PR, rather than waiting for this PR to complete.)

**Comment by khwilliamson** [comment]
rather than @sisyphus having to learn something very unfamiliar, I'll squash the commits.

BTW to get the branch onto your local box, on the line that says "Rebase and merge", there is a link to "command line instructions"  If you do Step 1 (and no further), you get your branch locally

**Comment by khwilliamson** [comment]
I did the squashing and fixed mailmap through the automated tool, and this PR has now been merged into blead via f276fe5ce5cea2b3d1f6b72d42b95bee2bbdb3e7.  (If I were better at git and/or github), I could have figured out a way to do it via this pull request, I suspect)

**Pull request closed without merging**
