### PR TITLE
perl5db.pl - remove redundant share($rl)

### PR DESCRIPTION
**Pull request by richardleach**
As pointed out in #18214, the second instance seems unnecessary.

(Caveat: I am unfamiliar with the debugger internals.)

### CODE REVIEW

**Comment by richardleach** [comment]
Tests failing under _porting/cmp_version.t_. I haven't ventured here before, may have just missed some routine step. Haven't time tonight to dig, will circle back to this later in the week.

For info, the duplicate `share($rl)` goes right back to the introduction of debugger support for threads:
2cbb2ee1d6d1dc9f375107de4b70573ece8a4e13

**Comment by Grinnz** [comment]
That just means `$VERSION` in perl5db.pl needs to be bumped to 1.59 due to the changes.

**Comment by richardleach** [comment]
Thanks @Grinnz. I hoped that was all it needed.

**Comment by Grinnz** [comment]
This has to be rebased on blead and another version bump isn't needed.

**Comment by richardleach** [comment]
FML. I don't have time to git today. Just going to do a fresh PR.

**Pull request closed without merging**
