### PR TITLE
regen/regcomp.pl - Apparently this extra const breaks g++

### PR DESCRIPTION
**Pull request by demerphq**

### CODE REVIEW

**Comment by Leont** [comment]
I think (but I haven't checked) that the better fix would be to remove the `EXTCONST` instead of the `const` (but only from that line and not from the declaration two lines above)

**Comment by demerphq** [comment]
On Sat, 6 Aug 2022, 20:36 Leon Timmermans, ***@***.***> wrote:

> I think (but I haven't checked) that the better fix would be to remove the
> EXTCONST instead of the const
>

I've stepped out, but I can test that when I return.

Yves

>

**Comment by jkeenan** [comment]
> I think (but I haven't checked) that the better fix would be to remove the `EXTCONST` instead of the `const` (but only from that line and not from the declaration two lines above)

@LeonT, when I tried out your suggestion on `regen/regcomp.pl`, then ran `perl regen/regcomp.pl` to get the following `diff`:
```
$ git diff |cat
diff --git a/regen/regcomp.pl b/regen/regcomp.pl
index 17f2cc03e0..828f21ed61 100644
--- a/regen/regcomp.pl
+++ b/regen/regcomp.pl
@@ -501,7 +501,7 @@ sub print_regnode_info {
 #ifndef DOINIT
 EXTCONST struct regnode_meta PL_regnode_info[];
 #else
-EXTCONST struct regnode_meta const PL_regnode_info[] = {
+struct regnode_meta const PL_regnode_info[] = {
 EOP
     my @fields= qw(type arg_len arg_len_varies off_by_arg);
     foreach my $node_idx (0..$#all) {
diff --git a/regnodes.h b/regnodes.h
index 22ebce23bd..292b650cc2 100644
--- a/regnodes.h
+++ b/regnodes.h
@@ -1741,7 +1741,7 @@ EXTCONST char * const PL_regnode_name[] = {
 #ifndef DOINIT
 EXTCONST struct regnode_meta PL_regnode_info[];
 #else
-EXTCONST struct regnode_meta const PL_regnode_info[] = {
+struct regnode_meta const PL_regnode_info[] = {
     {
         /* #0 op END */
         .type = END,

```
... and I then configured and compiled with:
```
sh ./Configure -des -Dusedevel -Duseithreads -Dcc=g++ && make test_prep
```
... my compilation terminated prematurely with this:
```
g++ -pthread -Wl,-E  -fstack-protector-strong -L/usr/local/lib -o miniperl  opmini.o perlmini.o universalmini.o  gv.o toke.o perly.o pad.o regcomp.o dump.o util.o mg.o reentr.o mro_core.o keywords.o builtin.o hv.o av.o run.o pp_hot.o sv.o pp.o scope.o pp_ctl.o pp_sys.o peep.o doop.o doio.o regexec.o utf8.o taint.o deb.o globals.o perlio.o numeric.o mathoms.o locale.o pp_pack.o pp_sort.o caretx.o dquote.o time64.o  miniperlmain.o  -lpthread -ldl -lm -lcrypt -lutil
/usr/local/bin/ld: regcomp.o: in function `Perl_regnode_after':
regcomp.c:(.text+0xb): undefined reference to `PL_regnode_info'
/usr/local/bin/ld: regcomp.c:(.text+0x1f): undefined reference to `PL_regnode_info'
/usr/local/bin/ld: regcomp.o: in function `Perl_regnext':
regcomp.c:(.text+0x364): undefined reference to `PL_regnode_info'
/usr/local/bin/ld: regcomp.o: in function `S_reginsert.constprop.0':
regcomp.c:(.text+0x1422): undefined reference to `PL_regnode_info'
/usr/local/bin/ld: regcomp.o: in function `S_reg_node':
regcomp.c:(.text+0x1eca): undefined reference to `PL_regnode_info'
/usr/local/bin/ld: regcomp.o:regcomp.c:(.text+0x1f47): more undefined references to `PL_regnode_info' follow
collect2: error: ld returned 1 exit status
*** Error code 1
```
When I configured/compiled with `gcc` instead (in both cases, version 10 on FreeBSD-12), `make` completed and all tests passed.  So, assuming I've followed correct build procedures, it looks as if @demerphq's approach is better.

**Comment by demerphq** [comment]
On Sat, 6 Aug 2022 at 22:35, James E Keenan ***@***.***>
wrote:

> I think (but I haven't checked) that the better fix would be to remove the
> EXTCONST instead of the const (but only from that line and not from the
> declaration two lines above)
>
> @Leont <https://github.com/Leont>, when I tried out your suggestion on
> regen/regcomp.pl, then ran perl regen/regcomp.pl to get the following diff
> :
>
> $ git diff |cat
> diff --git a/regen/regcomp.pl b/regen/regcomp.pl
> index 17f2cc03e0..828f21ed61 100644
> --- a/regen/regcomp.pl
> +++ b/regen/regcomp.pl
> @@ -501,7 +501,7 @@ sub print_regnode_info {
>  #ifndef DOINIT
>  EXTCONST struct regnode_meta PL_regnode_info[];
>  #else
> -EXTCONST struct regnode_meta const PL_regnode_info[] = {
> +struct regnode_meta const PL_regnode_info[] = {
>  EOP
>      my @fields= qw(type arg_len arg_len_varies off_by_arg);
>      foreach my $node_idx (0..$#all) {
> diff --git a/regnodes.h b/regnodes.h
> index 22ebce23bd..292b650cc2 100644
> --- a/regnodes.h
> +++ b/regnodes.h
> @@ -1741,7 +1741,7 @@ EXTCONST char * const PL_regnode_name[] = {
>  #ifndef DOINIT
>  EXTCONST struct regnode_meta PL_regnode_info[];
>  #else
> -EXTCONST struct regnode_meta const PL_regnode_info[] = {
> +struct regnode_meta const PL_regnode_info[] = {
>      {
>          /* #0 op END */
>          .type = END,
>
>
> ... and I then configured and compiled with:
>
> sh ./Configure -des -Dusedevel -Duseithreads -Dcc=g++ && make test_prep
>
> ... my compilation terminated prematurely with this:
>
> g++ -pthread -Wl,-E  -fstack-protector-strong -L/usr/local/lib -o miniperl  opmini.o perlmini.o universalmini.o  gv.o toke.o perly.o pad.o regcomp.o dump.o util.o mg.o reentr.o mro_core.o keywords.o builtin.o hv.o av.o run.o pp_hot.o sv.o pp.o scope.o pp_ctl.o pp_sys.o peep.o doop.o doio.o regexec.o utf8.o taint.o deb.o globals.o perlio.o numeric.o mathoms.o locale.o pp_pack.o pp_sort.o caretx.o dquote.o time64.o  miniperlmain.o  -lpthread -ldl -lm -lcrypt -lutil
> /usr/local/bin/ld: regcomp.o: in function `Perl_regnode_after':
> regcomp.c:(.text+0xb): undefined reference to `PL_regnode_info'
> /usr/local/bin/ld: regcomp.c:(.text+0x1f): undefined reference to `PL_regnode_info'
> /usr/local/bin/ld: regcomp.o: in function `Perl_regnext':
> regcomp.c:(.text+0x364): undefined reference to `PL_regnode_info'
> /usr/local/bin/ld: regcomp.o: in function `S_reginsert.constprop.0':
> regcomp.c:(.text+0x1422): undefined reference to `PL_regnode_info'
> /usr/local/bin/ld: regcomp.o: in function `S_reg_node':
> regcomp.c:(.text+0x1eca): undefined reference to `PL_regnode_info'
> /usr/local/bin/ld: regcomp.o:regcomp.c:(.text+0x1f47): more undefined references to `PL_regnode_info' follow
> collect2: error: ld returned 1 exit status
> *** Error code 1
>
> When I configured/compiled with gcc instead (in both cases, version 10 on
> FreeBSD-12), make completed and all tests passed. So, assuming I've
> followed correct build procedures, it looks as if @demerphq
> <https://github.com/demerphq>'s approach is better.
>

Yeah, when I tried it I couldnt make it work either.

It is not clear to me what the correct way to say that "PL_regnode_info is
an externally accessible constant pointer to an array of constant struct
regnode_meta" using the [] notation. It seems like you can do it with the *
notation, but that causes other problems. I hate the way const has been
done in C. :-(

With the current code, anything I do to set PL_regnode_info to something
like NULL results in a compile time error.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Pull request merged**
