### PR TITLE
Fix whitespace noise in Locale::MakeText

### PR DESCRIPTION
**Pull request by toddr**
Bump to 1.31 for release to CPAN.

### CODE REVIEW

**Review by atoomic — APPROVED** [review]

**Comment by atoomic** [comment]
need a version bump view: `porting/cmp_version.t `

**Review by atoomic — CHANGES_REQUESTED** [review]
please bump version

**Comment by jkeenan** [comment]
@toddr, I am very grateful that you have taken on the task of preparing Locale-Maketext for an updated release on CPAN -- but I think you're going about this backwards.

As is indicated by its positioning under `dist/` in the core distribution, Locale-Maketext is **blead-first**, not CPAN-first.  Changes should be made in the core distribution first, tested and verified there, then propagated out to CPAN.  If one follows this procedure, and if the changes entail modification of a `*.pm` or `*.xs` file, then `$VERSION` needs to be bumped in blead.  It can then be released on CPAN without further modification of `$VERSION`.

What you have done is to take Locale-Maketext version 1.30 from blead and then made more changes in the CPAN version -- changes which include changes in a `*.pm` file.  As @atoomic has pointed out, this means that if you try to import CPAN back into blead (as per this pull request), you need a version bump.  But I really hate to see unnecessary "devel version" numbers like 1.30_01 in the core distribution, particularly as we get close to our annual production release.  It just seems sloppy.

So why not simply make your whitespace changes in blead, bump `$VERSION` in `dist/Locale-Maketext/lib/Locale/Maketext.pm` to `1.31`, then release *that* to CPAN with no further modification of `$VERSION`.  That way, blead and CPAN end up with the same `$VERSION`.

**Comment by toddr** [comment]
@jkeenan Bumped to 1.31 and changed the commit message.

**Review by atoomic — APPROVED** [review]
This LGTM and seems to have fixed concerns raised by @jkeenan 
thanks for the update

**Comment by jkeenan** [comment]
toddr:lmt-130 branch rebased on blead, merged into blead, pushed to repo in commit f5469426bb.  Closing this ticket.  Thank you very much.

**Pull request closed without merging**
