### PR TITLE
Remove DOS/DJGPP and AT&T UWIN support

### PR DESCRIPTION
**Pull request by ilmari**
These are both long obsolete.

### CODE REVIEW

**Comment by jkeenan** [comment]
1. I see that this pull request consists of two commits, one for DOS/DJGPP and one for AT&T UWIN.  For review purposes, might it be better to do these in two separate pull requests?
2. With this p.r. applied, is there any flavor or variant of DOS left in the Perl 5 core distribution?
3. It might be good to provide a brief, one-paragraph description of what these OSes once were in the commit messages.

**Comment by ilmari** [comment]
>  1. I see that this pull request consists of two commits, one for DOS/DJGPP and one for AT&T UWIN.  For review purposes, might it be better to do these in two separate pull requests?

Github makes it easy to review PRs commit by commit, so I don't see the point in the extra make-work for this.

>  2. With this p.r. applied, is there any flavor or variant of DOS left in the Perl 5 core distribution?

Win32 and OS/2 are the remaining `DOSISH` OSes that we support. The in-tree OS/2 port doesn't seem to have had any updates other than typo fixes and keeping up with tree-wide changes since 2006, but there is an [out-of-tree port of 5.32.0](https://www.os2world.com/cms/index.php/past-news/80-news/software/22838-perl-5-35-0) (the version in the title/URL is wrong) whose author we might want to get in touch with.

> 3. It might be good to provide a brief, one-paragraph description of what these OSes once were in the commit messages.

Will do, and add perldelta entries too.

**Comment by bingos** [comment]
The last DOS/DJGPP build I attempted was against v5.20.0 and it only managed to build miniperl 
image

Happy to see it go.

**Comment by xenu** [comment]
Once this is merged, these tickets can be closed: https://github.com/Perl/perl5/issues?q=is%3Aissue+is%3Aopen+label%3Adistro-dos

**Pull request merged**
