### PR TITLE
Time-HiRes: Add MANIFEST and META files

### PR DESCRIPTION
**Pull request by atoomic**

### CODE REVIEW

**Comment by Grinnz** [comment]
Why? These should be generated in the CPAN release process.

**Comment by atoomic** [comment]
Indeed these files are generated before a release in the https://github.com/Dual-Life/Time-HiRes repo

I noticed that some other distributions in `dist/ ` also provides these files (view for example 6d37ab4efc1fb099593fb29406193ae79c3be543)

I think it has the advantage of avoiding surprises on a release.
Otherwise outdated/incorrect MANIFEST/META files have a very poor visibility.

Having these files in blead, make sure that more than a few pair of eyes can look at them IMO.

If we are saying we do not want these files, then we should consider removing all similar files from `dist/`.

I'm fine with both options.

**Comment by Grinnz** [comment]
They are actually more likely to be outdated if you include copies of them in blead, because they will be generated on CPAN release regardless, these files will be ignored. (edit: not quite true for MANIFEST, but assuming the author runs make manifest before releasing as they should)

**Comment by Grinnz** [comment]
I can't speak to why other similar dists may have these files, they may have a different authoring workflow or it may be a mistake.

**Comment by atoomic** [comment]
I'm closing this PR, as having a discussion in first place makes much more sense.

@Grinnz you are right having there file in place will increase the risk of having them outdated, and will be a burden over time.

The main advantage I see of having these meta file in place is having the `MANIFEST.SKIP` which guarantee that no cruft will be added to a release. I wonder if some of these files are in place here in blead, as the release was performed from blead itself. 

If we come to the conclusion that this a bad idea to have these files versioned, we should consider removing all meta files from `dist/*`.

@xsawyerx could you indicate (if you remember) why you pushed such a change via 6d37ab4efc1fb099593fb29406193ae79c3be543 ?

thanks

**Comment by xsawyerx** [comment]
I think it makes sense to avoid having these files. Our problem is different: How do we make sure that we have a clean flow for all of these dual-life modules?

In commit 402defd695e9a9bf33a68c8738cc08e5533fded4, I try to document my porcess when releasing `Data::Dumper`. Essentially, this is:

* Build perl
* Copy `Data::Dumper` to other directory
* Grab `MANIFEST.SKIP` and `Makefile.PL` from previous release
* Add the `DEFINE` we need to fix this:

        # In WriteMakefile(...)
        DEFINE        => '-DUSE_PPPORT_H',

* `perl Makefile.PL && make && make test && make dist`
* Retest the tarball
* Release to CPAN

As you can see, in this particular case, the `MANIFEST.SKIP` and even `Makefile.PL` are not available. Because `Makefile.PL`, I cannot even generate the `MANIFEST`. I don't even remember why we need to add the `DEFINE` to it.

This shows the problem we have in making these dual-life releases. Each author can have their own style and each distribution can have a different file structure. Perhaps it's time to fix it.

**Comment by Grinnz** [comment]
`Makefile.PL` and `MANIFEST.SKIP` are certainly a different case and part of the release toolset required, at least in EUMM-managed distributions.

**Pull request closed without merging**
