### PR TITLE
Adjust Win32/t/Unicode.t for Cygwin

### PR DESCRIPTION
**Pull request by atoomic**
Attempt to fix the Cygwin issue

We need to postpone the function call 

Error reported upstream:
https://github.com/perl-libwin32/win32/pull/33/files

### CODE REVIEW

**Comment by xenu** [comment]
This test does **not** fail in blead. In fact, it was recently fixed by this commit: 3fe11e08ed12031c30123faa114fa48661ea6226

**Comment by atoomic** [comment]
@xenu view all CI run from pending PRs they are failing in blead due to the lack of wrapper around the function to skip
```
skip($^O eq "cygwin", Win32::GetLongPathName($subdir), $long);
```
should be
```
skip($^O eq "cygwin", sub { Win32::GetLongPathName($subdir) }, $long);
```

The current CI run confirm that this is fixing the issue

**Comment by atoomic** [comment]
Mmm you are right the failure is now fixed, but the test skip should not even try to call the function IMO

**Comment by atoomic** [comment]
Closing this case.

We do not need this fix with 0.58, the smoker are not failing anymore.
Considering using an anonymous sub to avoid running the code to test, should be considered but this is an upstream issue.

**Pull request closed without merging**
