### PR TITLE
Remove smartmatch, given, when, default and non-loop continue

### PR DESCRIPTION
**Pull request by tonycoz**
This removes the switch feature, which covers smartmatch, and the given/when structure.

This is scheduled for removal in 5.42

### CODE REVIEW

**Comment by jkeenan** [comment]
> This removes the switch feature, which covers smartmatch, and the given/when structure.
> 
> This is scheduled for removal in 5.42

**Committers:** We need to develop a plan for the review of this pull request, as it is likely to be the largest single commit we perform in this development cycle.  I've skimmed the pure perl and documentation parts of the p.r. They look satisfactory but I notice that I get weary quickly looking at such large diffs -- and most of the patch is not pure perl.  Suggestions?

**Comment by Leont** [comment]
> Committers: We need to develop a plan for the review of this pull request, as it is likely to be the largest single commit we perform in this development cycle. I've skimmed the pure perl and documentation parts of the p.r. They look satisfactory but I notice that I get weary quickly looking at such large diffs -- and most of the patch is not pure perl. Suggestions?

Yeah I would have preferred this as a series of patches that each remove a piece of the two features, but I'm not sure it's worth it to recreate that after the fact.

**Comment by tonycoz** [comment]
> Yeah I would have preferred this as a series of patches that each remove a piece of the two features, but I'm not sure it's worth it to recreate that after the fact.

I'll do that.

**Comment by tonycoz** [comment]
Split it into 3.

I considered removing default and break separately, but it would require making minor changes to many tests and updating their results for tests I would be removing anyway.

**Comment by mauke** [comment]
| File                    | Notes                                                                     |
| :---------------------- | :------------------------------------------------------------------------ |
| pod/perldeprecation.pod | smartmatch "will be removed" - maybe change to past tense?                |
| pod/perlexperiment.pod  | move to "Removed features" section                                        |
| dist/Safe/t/safeops.t   | still uses `~~`                                                           |
| t/op/cmpchain.t         | still uses `~~` (also, bug: `~~` has been removed, but tests don't fail)  |
| t/comp/parser.t         | still uses `~~`                                                           |

**Comment by jkeenan** [comment]
Each of the 3 commits in this pull request, when tested individually, configures, builds and tests satisfactorily.  That's a good sign, but I haven't yet examined the code in each commit.  I hope to get to that soon.

**Comment by khwilliamson** [comment]
I think `DEBUG_M` should be removed.  perlrun describes it as   `M  trace smart match resolution`

**Comment by tonycoz** [comment]
Thanks for the reviews

**Review by khwilliamson — COMMENTED** [review]
I didn't look at this in excruciating detail, but lgtm

**Comment by jkeenan** [comment]
@tonycoz, merge conflicts.  (I'd fix, but I screwed up last time I tried the "web editor." ;-) )

**Comment by mauke** [comment]
The conflict was in pp_ctl.c. Commit 352ca4bc5 touched some of the smartmatch functions that this PR wants to remove. I resolved it by rebasing on top of blead and re-deleting the smartmatch functions in pp_ctl.c (now in their latest version).

**Comment by haarg** [comment]
Something to note is that we previously weren't issuing any deprecation notices for adding a `~~` overload. This PR removes the support for them, which results in warnings if you try to add them. We could decide to continue allowing `~~` overloads to be added, but just never using them for anything. I'd say that isn't needed though, and what is currently in the PR is fine.

**Review by mauke — APPROVED** [review]

**Comment by jkeenan** [comment]
Each of the now 8 commits in this pull request, when tested individually, configures, builds and tests satisfactorily.

**Comment by tonycoz** [comment]
Applied manually.

**Pull request closed without merging**
