### PR TITLE
cygwin: workaround DLL load address conflict

### LINKED ISSUE #22695: cygwin DLL address conflict with version 5.41.6
Module:

**Description**
Similar to #22104 we're seeing address conflicts loading LangInfo.dll in CI:
```
      0 [main] perl 13868 child_info_fork::abort: address space needed by 'Langinfo.dll' (0x190000) is already occupied
Can't fork, trying again in 5 seconds at lib/MakeMaker/Test/Utils.pm line 325.
      0 [main] perl 13870 child_info_fork::abort: address space needed by 'Langinfo.dll' (0x190000) is already occupied
Can't fork, trying again in 5 seconds at lib/MakeMaker/Test/Utils.pm line 325.
      0 [main] perl 13872 child_info_fork::abort: address space needed by 'Langinfo.dll' (0x190000) is already occupied
Can't fork, trying again in 5 seconds at lib/MakeMaker/Test/Utils.pm line 325.
      0 [main] perl 13983 child_info_fork::abort: address space needed by 'Langinfo.dll' (0x190000) is already occupied
Can't fork, trying again in 5 seconds at lib/MakeMaker/Test/Utils.pm line 325.
```

And rebase shows the conflict:
```
$ rebase -i `find . -name '*.dll'` ./perl.exe | grep -F '*'
/home/tony/dev/perl/git/perl/cygperl5_41_6.dll                          base 0x00059f6d0000 size 0x010d8000 *
/home/tony/dev/perl/git/perl/lib/auto/I18N/Langinfo/Langinfo.dll        base 0x00059fe80000 size 0x00025000 *
```

And can be similarly reproduced:
```
$ ./perl -Ilib -MI18N::Langinfo -efork
      0 [main] perl 16510 child_info_fork::abort: address space needed by 'Langinfo.dll' (0x400000) is already occupied
```

I plan to prepare a fix and perldelta note PR.

**Steps to Reproduce**
1. build perl, I've only tested with `-DDEBUGGING`, there may or may not be a conflict without it
2. run `./perl -Ilib -MI18N::LangInfo -efork`

**Expected behavior**
No error on fork.

**Perl configuration**

```
Summary of my perl5 (revision 5 version 41 subversion 6) configuration:
  Commit id: 161ff7336a85931cf738fbfbffcf68de4d2f1c81
  Platform:
    osname=cygwin
    osvers=3.5.4-1.x86_64
    archname=cygwin-thread-multi
    uname='cygwin_nt-10.0-19045 ganymede 3.5.4-1.x86_64 2024-08-25 16:52 utc x86_64 cygwin '
    config_args='-des -Dusedevel -DDEBUGGING'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags ='-D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2'
    optimize='-O3 -g'
    cppflags='-D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='12.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags =' -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib /usr/lib/w32api /usr/local/lib /lib
    libs=-lpthread -ldl
    perllibs=-lpthread -ldl
    libc=/usr/lib/libcygwin.a
    so=dll
    useshrplib=true
    libperl=cygperl5_41_6.dll
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' --shared  -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    DEBUGGING
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
  Built under cygwin
  Compiled at Oct 23 2024 12:47:36
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.41.6/cygwin-thread-multi
    /usr/local/lib/perl5/site_perl/5.41.6
    /usr/local/lib/perl5/5.41.6/cygwin-thread-multi
    /usr/local/lib/perl5/5.41.6
```

### PR DESCRIPTION
**Pull request by tonycoz**
The DLL load addresses are generated by the linker based on the DLL names, and 5.39.10 we're getting a conflict between cygperl5_41_6.dll and Langinfo.dll.

As a workaround, statically link Langinfo into cygperl for CI and mention the problem in perldelta for anyone else who might build perl on cygwin

Fixes but should not close #22695

TODO: fill description here

---------------------------------------------------------------------------------
* This set of changes requires a perldelta entry, and it is included.
* This set of changes requires a perldelta entry, and I need help writing it.
* This set of changes does not require a perldelta entry.

### CODE REVIEW

**Comment by sisyphus** [comment]
For me, the failure occurs only with <code>-DDEBUGGING</code> builds.
Should the proposed perldelta entry mention that non-debugging builds are not affected ?

**Comment by bulk88** [comment]
https://github.com/Perl/perl5/blob/a6f05e6c69b1b871ac6c89a44d9f2aeb84979a1c/cpan/ExtUtils-MakeMaker/lib/ExtUtils/MM_Cygwin.pm#L134

isnt a global rebase of libperl and all XS DLLs supposed to run in Cygwin?

**Comment by tonycoz** [comment]
> For me, the failure occurs only with `-DDEBUGGING` builds. Should the proposed perldelta entry mention that non-debugging builds are not affected ?

It would be anything that makes the binaries larger, I reproduced it with `./Configure -des -Dusedevel -Doptimize=-O0\ -g` and with `./Configure -des -Dusedevel -Doptimize=-O2\ -g\ -march=x86-64-v2`

**Comment by tonycoz** [comment]
> https://github.com/Perl/perl5/blob/a6f05e6c69b1b871ac6c89a44d9f2aeb84979a1c/cpan/ExtUtils-MakeMaker/lib/ExtUtils/MM_Cygwin.pm#L134
> 
> isnt a global rebase of libperl and all XS DLLs supposed to run in Cygwin?

That isn't what that says, and isn't what it does.

`cygperl_5_41_6.dll` isn't an archdir dll, though perhaps that code should include `cygperl*.dll` too.

Also, it only runs for 32-bit builds, which cygwin no longer support, which I can understand, since DLL conflicts like this were many times more common there.

**Comment by tonycoz** [comment]
> For me, the failure occurs only with `-DDEBUGGING` builds. Should the proposed perldelta entry mention that non-debugging builds are not affected ?

I've added a note on this.

**Comment by jkeenan** [comment]
> > For me, the failure occurs only with `-DDEBUGGING` builds. Should the proposed perldelta entry mention that non-debugging builds are not affected ?
> 
> I've added a note on this.

Can someone familiar with Cygwin review this p.r.?  (I'd like to quiet our CI failures on that platform.) Thanks.

**Comment by jkeenan** [comment]
> The DLL load addresses are generated by the linker based on the DLL names, and 5.39.10 we're getting a conflict between cygperl5_41_6.dll and Langinfo.dll.
> 
> As a workaround, statically link Langinfo into cygperl for CI and mention the problem in perldelta for anyone else who might build perl on cygwin
> 
> Fixes but should not close #22695
> 

@tonycoz,  this *did* close #22695; should you re-open it?  (My impression is that our Cygwin CI builds are still failing.)

**Comment by tonycoz** [comment]
> @tonycoz, this _did_ close #22695; should you re-open it?

Thanks github, reopened.

> (My impression is that our Cygwin CI builds are still failing.)

blead is passing, see the green tick at the top of https://github.com/Perl/perl5 and you can see green ticks for the CI runs done since this was merged at https://github.com/Perl/perl5/commits/blead/

Any PRs will need to be rebased on blead to pass.

**Pull request merged**
