### PR TITLE
Moved unused variable into debug scope

### PR DESCRIPTION
**Pull request by AnFunctionArray**
Moved declaration of object p.

[#20485](https://github.com/Perl/perl5/issues/20485)

### CODE REVIEW

**Review by demerphq — APPROVED** [review]

**Comment by khwilliamson** [comment]
This is failing.  Try moving the declaration to the for loop line

**Comment by AnFunctionArray** [comment]
@khwilliamson Can you link the issue - I've rebased multiple times.

**Comment by AnFunctionArray** [comment]
@khwilliamson I think currently all tests have passed plus I don't see warning on builds.

**Comment by jkeenan** [comment]
Built locally to inspect for elimination of `-Wunused-variable` warning.  Rebased on, merged into blead, locally pushed to origin.  Thanks.

**Pull request closed without merging**
