### PR TITLE
add POD for PL_phase

### PR DESCRIPTION
**Pull request by FGasper**

### CODE REVIEW

**Comment by xsawyerx** [comment]
Can you add an example value? I think that would help readers.

**Comment by FGasper** [comment]
> Can you add an example value? I think that would help readers.

Done.

**Comment by xsawyerx** [comment]
Thank you for adding those. This is much more helpful now!

Can I request one last change?

Use `C<>` for the possible values there.

**Comment by jkeenan** [comment]
Commits squashed and applied to blead in commit 5e18b295a0.

Closing P.R.  Thank you very much.

**Comment by xsawyerx** [comment]
@FGasper thank you for this!

**Pull request closed without merging**
