### PR TITLE
Smoke me/jkeenan/alyssais/gh 18726 toke c warnings

### PR DESCRIPTION
**Pull request by jkeenan**

### CODE REVIEW

**Comment by jkeenan** [comment]
@alyssais, this was my attempt to improve upon your earlier patch in https://github.com/Perl/perl5/pull/18726.

Thank you very much.
Jim Keenan

**Comment by Leont** [comment]
Both additions look sensible to me

**Comment by jkeenan** [comment]
> Both additions look sensible to me

Thanks for taking a look.  Assuming this addresses the OP's problem and does well in smoke tests, we can apply this after 5.35.0 is out.

**Review by tonycoz — APPROVED** [review]

**Comment by alyssais** [comment]
This fixes my build. :)

**Review by Leont — APPROVED** [review]

**Pull request merged**
