### PR TITLE
locale.c: Slightly change wording of DEBUG messages

### PR DESCRIPTION
**Pull request by khwilliamson**
This makes them more consistent with the other messages in this file.

### CODE REVIEW

**Comment by jkeenan** [comment]
> This makes them more consistent with the other messages in this file.

Can you provide an example of how (assuming I've built perl with `-DDEBUGGING`) I would do some work that would show me before/after contrasts for the debugging messages?

**Comment by khwilliamson** [comment]
You could do 
'./perl -Ilib -T -DLv lib/locale.t`
with and without the patch, and compare the outputs

**Comment by jkeenan** [comment]
> You could do './perl -Ilib -T -DLv lib/locale.t` with and without the patch, and compare the outputs

Be careful what you asked for, Jim; you get a million-plus-line diff!

**Review by jkeenan — APPROVED** [review]

**Comment by khwilliamson** [comment]
Sorry I did not think about the size of the output.  What you could do is look at the beginning of the post-commit file until you get to one with the word "toggle", note the line number, and then look in the other file near that line number.

**Pull request merged**
