### PR TITLE
Fix building with gdbm 1.20

### PR DESCRIPTION
**Pull request by graygnuorg**
Since gdbm commit d3e27957, error codes are enumeration constants, rather than defines.  Fix the ITEM_NOT_FOUND macro to comply.  This fixes building with version 1.20 while maintaining backward compatibility with earlier versions.

### CODE REVIEW

**Comment by jkeenan** [comment]
> Since gdbm commit d3e27957, error codes are enumeration constants, rather than defines. Fix the ITEM_NOT_FOUND macro to comply. This fixes building with version 1.20 while maintaining backward compatibility with earlier versions.

@graygnuorg, you filed this p.r. just a few minutes ago, but some commits were made six months ago.  That seems confusing.  Also, GH is indicating that the branch cannot be rebased on blead.

Could you please double-check that you are forking a branch from HEAD, and then commit code and generate a fresh pull request?

It so happens that I was trying to diagnose https://github.com/Perl/perl5/issues/18915 just as this p.r. comes in.  If you can provide a clean pull request, I'd like to make this into a smoke-me branch.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > Since gdbm commit d3e27957, error codes are enumeration constants, rather than defines. Fix the ITEM_NOT_FOUND macro to comply. This fixes building with version 1.20 while maintaining backward compatibility with earlier versions.
> 
> @graygnuorg, you filed this p.r. just a few minutes ago, but some commits were made six months ago. That seems confusing. Also, GH is indicating that the branch cannot be rebased on blead.
> 
> Could you please double-check that you are forking a branch from HEAD, and then commit code and generate a fresh pull request?
> 
> It so happens that I was trying to diagnose #18915 just as this p.r. comes in. If you can provide a clean pull request, I'd like to make this into a smoke-me branch.
> 
> Thank you very much.
> Jim Keenan

@graygnuorg I believe we only need the last of the 4 commits in this p.r., https://github.com/Perl/perl5/pull/18919/commits/c029d660f2fe60699cf64bbb3fa9f671a1a370d5.

I have locally created a branch that cherry-picks that commit.  The test file PASSes whether I'm using gdbm 1.19 or 1.20.  I have pushed that branch for smoke-testing:

https://github.com/Perl/perl5/tree/smoke-me/jkeenan/graygnuorg/GDBM_File-20210622

Please review.  Thank you very much.

**Comment by jkeenan** [comment]
> @graygnuorg I believe we only need the last of the 4 commits in this p.r., [c029d66](https://github.com/Perl/perl5/commit/c029d660f2fe60699cf64bbb3fa9f671a1a370d5).
> 
> I have locally created a branch that cherry-picks that commit. The test file PASSes whether I'm using gdbm 1.19 or 1.20. I have pushed that branch for smoke-testing:
> 
> https://github.com/Perl/perl5/tree/smoke-me/jkeenan/graygnuorg/GDBM_File-20210622
> 
> Please review. Thank you very much.

In the smoke-me/jkeenan/graygnuorg/GDBM_File-20210622 branch I've been getting good results on the *BSDs, but got this failure on Linux:
```
$ uname -mrs
Linux 5.10.13-x86_64-linode141 x86_64

$ git describe
v5.35.1-26-g50f2f79

$ gitcurr
smoke-me/jkeenan/graygnuorg/GDBM_File-20210622

$ cd t;TEST_JOBS=1 ./perl harness ../ext/GDBM_File/t/gdbm.t; cd -
../ext/GDBM_File/t/gdbm.t .. 1/? 
#   Failed test at ../../t/lib/dbmt_common.pl line 489.
#     Structures begin differing at:
#          $got->[0] = Does not exist
#     $expected->[0] = undef

#   Failed test at ../../t/lib/dbmt_common.pl line 490.
#          got: 'gdbm_fetch: Item not found at ../../t/lib/dbmt_common.pl line 489.
# '
#     expected: ''

#   Failed test at ../../t/lib/dbmt_common.pl line 505.
#     Structures begin differing at:
#          $got->[0] = Does not exist
#     $expected->[0] = undef

#   Failed test at ../../t/lib/dbmt_common.pl line 506.
#          got: 'gdbm_fetch: Item not found at ../../t/lib/dbmt_common.pl line 505.
# '
#     expected: ''
# Looks like you failed 4 tests of 134.
../ext/GDBM_File/t/gdbm.t .. Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/134 subtests 

Test Summary Report
-------------------
../ext/GDBM_File/t/gdbm.t (Wstat: 1024 Tests: 134 Failed: 4)
  Failed tests:  129-130, 133-134
  Non-zero exit status: 4
Files=1, Tests=134,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.12 cusr  0.01 csys =  0.16 CPU)
Result: FAIL
```
Needs more investigation.

**Comment by graygnuorg** [comment]
@jkeenan I created a new PR: https://github.com/Perl/perl5/pull/18924.  It should apply cleanly.
Regarding the reported failure: I wasn't able to reproduce it. Any hints?
I propose to drop this PR and switch to 18924 to be sure we're on the same page.

**Comment by jkeenan** [comment]
Closed; superseded by https://github.com/Perl/perl5/pull/18924.

**Pull request closed without merging**
