### PR TITLE
GH #17826: Remove entire section, thanks @richardleach

### PR DESCRIPTION
**Pull request by xsawyerx**

### CODE REVIEW

**Comment by richardleach** [comment]
Sawyer, Grinnz & I noticed that Pod::Parser was removed in this cycle, so this section can't go after all. I'll do a fresh PR now.

**Comment by Grinnz** [comment]
This section is under the Deprecations heading, so it's not necessary to mention Pod::Parser's removal here.

**Comment by richardleach** [comment]
D'oh, sorry for the noise.

**Comment by Grinnz** [comment]
The two "removed modules" sections were confusing to me as well until I looked at the broader organization

**Comment by xsawyerx** [comment]
I think it might be beneficial to keep it for `Pod::Parser` anyway. I'll review this today.

**Pull request merged**
