### PR TITLE
Document octal literals

### PR DESCRIPTION
**Pull request by briandfoy**
If this is officially supported (#18664), here's a patch for the docs.

### CODE REVIEW

**Comment by tonycoz** [comment]
Did you want to cover binary floating point too?

**Comment by briandfoy** [comment]
Yeah, binary would be fine. I'm waiting for a ruling from somebody that commits Perl to supporting these.

**Comment by briandfoy** [comment]
There's no ruling on this or #18664, so I'll close this rather than let it languish.

**Comment by khwilliamson** [comment]
I think it's premature to close this.  

There are higher priority items on the plates of quite a few people at the moment.  Leaving it open will cause it not to fall through the cracks.

The yearly code freeze is nearly upon us.  This is an item that can be deferred until after that deadline.

**Comment by toddr** [comment]
Actually, aren't doc fixes allowed during this window @khwilliamson ?

**Comment by briandfoy** [comment]
The issue is still open. It's just this PR is closed. I'm not going to keep rebasing it and so on.

**Comment by khwilliamson** [comment]
Yes, which is a reason to keep this in mind

**Pull request closed without merging**
