### PR TITLE
io/sem.t:  Initialize value to numeric

### PR DESCRIPTION
**Pull request by jkeenan**
Per Tony Cook review.

For:  https://github.com/Perl/perl5/issues/17926

### CODE REVIEW

**Review by tonycoz — APPROVED** [review]
This looks fine, but should probably be squashed before merging.

**Comment by jkeenan** [comment]
> This looks fine, but should probably be squashed before merging.

Thanks for your review.  I will squash and merge once perl-5.33.0 has been released and blead has been explicitly unfrozen.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
@tonycoz, in the branch for this p.r., I squashed 3 commits, after which the diff from `blead` looked like this:
```
$ git diff blead..HEAD -- t/io/sem.t |cat
diff --git a/t/io/sem.t b/t/io/sem.t
index 7a911fccdb..e5413f5e38 100644
--- a/t/io/sem.t
+++ b/t/io/sem.t
@@ -47,7 +47,9 @@ else {
 }
 
 { # [perl #120635] 64 bit big-endian semctl SETVAL bug
-    ok(semctl($id, "ignore", SETALL, pack("s!*",(0)x$nsem)),
+  # [GH #17926]
+    my $ignored = 0;
+    ok(semctl($id, $ignored, SETALL, pack("s!*",(0)x$nsem)),
        "Initialize all $nsem semaphores to zero");
 
     my $sem2set = 3;
@@ -56,7 +58,7 @@ else {
        "Set semaphore $sem2set to $semval");
 
     my $semvals;
-    ok(semctl($id, "ignore", GETALL, $semvals),
+    ok(semctl($id, $ignored, GETALL, $semvals),
        'Get current semaphore values');
 
     my @semvals = unpack("s!*", $semvals);
@@ -66,7 +68,7 @@ else {
     is($semvals[$sem2set], $semval, 
        "Checking value of semaphore $sem2set");
 
-    is(semctl($id, $sem2set, GETVAL, "ignored"), $semval,
+    is(semctl($id, $sem2set, GETVAL, 'ignore'), $semval,
        "Check value via GETVAL");
 }
 
```
If I then run this file as is, I get:
```
$ cd t;./perl harness -v io/sem.t; cd -

ok 1 - acquired semaphore
ok 2 - Initialize all 10 semaphores to zero
ok 3 - Set semaphore 3 to 17
ok 4 - Get current semaphore values
ok 5 - Make sure we get back statuses for all 10 semaphores
ok 6 - Checking value of semaphore 3
ok 7 - Check value via GETVAL
ok
All tests successful.
Files=1, Tests=7,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.01 cusr  0.00 csys =  0.02 CPU)
Result: PASS
```
But now, suppose I modify it to `use warnings;` right after the point where the file currently does `use strict;`.
```
$ diff t/io/sem.t t/io/sem-with-warnings.t 
19a20
> use warnings;
```
I now run the modified file:
```
$ cd t;./perl -w harness -v io/sem-with-warnings.t; cd -

ok 1 - acquired semaphore
ok 2 - Initialize all 10 semaphores to zero
ok 3 - Set semaphore 3 to 17
ok 4 - Get current semaphore values
ok 5 - Make sure we get back statuses for all 10 semaphores
ok 6 - Checking value of semaphore 3
ok 7 - Check value via GETVAL
Use of uninitialized value $semvals in semctl at io/sem-with-warnings.t line 62.
Argument "ignore" isn't numeric in semctl at io/sem-with-warnings.t line 72.
ok
All tests successful.
Files=1, Tests=7,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.01 cusr  0.00 csys =  0.02 CPU)
Result: PASS
```
I'm being told that the 4th argument to `semctl` must be numeric -- which contradicts what you said earlier in code review.

Relevant code:
```
 61     my $semvals;
 62     ok(semctl($id, $ignored, GETALL, $semvals),
 63        'Get current semaphore values');
 64 
 65     my @semvals = unpack("s!*", $semvals);
 66     is(scalar(@semvals), $nsem,
 67        "Make sure we get back statuses for all $nsem semaphores");
 68 
 69     is($semvals[$sem2set], $semval,
 70        "Checking value of semaphore $sem2set");
 71 
 72     is(semctl($id, $sem2set, GETVAL, 'ignore'), $semval,
 73        "Check value via GETVAL");
```

Can you clarify?

Thank you very much.
Jim Keenan
```

**Comment by Leont** [comment]
> I'm being told that the 4th argument to semctl must be numeric -- which contradicts what you said earlier in code review.

In general the meaning of the 4th argument to `semctl` depends on the 3rd argument of `semctl`.

But in this case, that warning feels like a bug to me. `GETVAL` doesn't require any argument, so we shouldn't require anything of it either.

Quite frankly this corner of our code is rather crufty.

**Comment by jkeenan** [comment]
Closing this p.r.  See https://github.com/Perl/perl5/issues/17926#issuecomment-660329026 for discussion.

**Pull request closed without merging**
