### PR TITLE
Beautify

### PR DESCRIPTION
**Pull request by jidanni**
Hope I didn't break anything.

### CODE REVIEW

**Comment by jkeenan** [comment]
The commit message does not sufficiently describe the objective of the commit.

**Comment by jidanni** [comment]
1. Saygluedtothenextwordlooksbad.
2. Paragraphs should start with a capital letter.

**Comment by Grinnz** [comment]
This information should be in the commit message so it's recorded in git. You can edit the message with git commit --amend.

Otherwise looks good to me.

**Comment by jidanni** [comment]
Erg... I am just using github.com.
But I fully authorize you folks to edit it for me!

**Comment by jidanni** [comment]
I confirm there is no way I can edit it from github.com.

**Comment by khwilliamson** [comment]
This was merged via 2dd0054b59ca4f0922ec3c2f2d43cec09d713784

**Pull request closed without merging**
