### PR TITLE
Make clear Fatal is still not OK

### PR DESCRIPTION
**Pull request by jidanni**
Otherwise people will think we are publishing the final OK accepted way!
Perhaps also note there is still no OK accepted way.

### CODE REVIEW

**Comment by jidanni** [comment]
> Not that we still don't recommend it

s/Not/Note/

**Comment by Grinnz** [comment]
This already seems clear in context to me, since this follows all of the caveats in the text.

**Comment by jidanni** [comment]
> This already seems clear in context to me, since this follows all of the caveats in the text.

No. Compare perlvar:
```
       In Perl 5.20.0 a new copy-on-write system was enabled by default, which
       finally fixes all performance issues with these three variables, and
       makes them safe to use anywhere.
```
So you still need to remind the user that this (new way to write FATAL) doesn't fix anything.
But do please rephrase it. I am a bad writer.

**Comment by jkeenan** [comment]
Addressed in commit 01900a5f23.  Closing ticket.

**Pull request closed without merging**
