### PR TITLE
toke.c: remove PERL_CR_FILTER

### PR DESCRIPTION
**Pull request by mauke**
When enabled (e.g. with `./Configure -A ccflags=-DPERL_CR_FILTER`), this would define an implicit source filter that turns \r\n pairs into \n whenever the parser reads a line of Perl source code.

As far as I can tell, perl already does the equivalent of this (without a source filter) on all platforms and has done so since 5.005.

(Also, the code could read out-of-bounds if the last character of the line read was a \r.)

---------------------------------------------------------------------------------
* This set of changes requires a perldelta entry, and ~~I need help writing it~~ it is included.

### CODE REVIEW

**Review by leonerd — COMMENTED** [review]
Changes LGTM; probably could do with a note in `perldelta` though

**Comment by mauke** [comment]
> probably could do with a note in `perldelta` though

Yeah, that's what I was sort of implying with

> > - This set of changes requires a perldelta entry, and I need help writing it.

:-P

**Comment by leonerd** [comment]
As to perldelta content, I don't think a huge amount needs adding here. This is a little-known, probably entirely forgotten-about feature, that is being removed.

Maybe possible to combine it with the text about the removal of `PERL_STRICT_CR`.

**Comment by mauke** [comment]
perldelta entry added.

**Review by leonerd — APPROVED** [review]
LGTM

**Pull request merged**
