### PR TITLE
Pod-Html: have tests run in individual tempdirs

### PR DESCRIPTION
**Pull request by jkeenan**
This is the first of five pull requests to be submitted in support of https://github.com/Perl/perl5/issues/18894.

Until now, the tests for this library ran inside the `ext/Pod-Html`
directory in the core distribution. Since the tests necessarily create
files while the harness runs, there was a possibility for race
conditions, which meant that we had to have a workaround in t/harness to
have the tests in this directory not run in parallel.

This commit restructures the testing process so that each test program
gets its own tempdir in which to create files and directories.

The test architecture is now found in `t/lib/Testing.pm`.
This module will export two functions on demand that are used in the
individual test files. They guarantee that all files created when
running a test program will be created in a temporary directory rather
than underneath the core distribution.

`t/pod2html-lib.pl` is now superseded by `t/lib/Testing.pm` and can be
removed. The workaround has been removed from `t/harness`.

This should help in the resolution of https://github.com/Perl/perl5/issues/12271.

Thank you very much.
Jim Keenan

### CODE REVIEW

**Comment by karenetheridge** [comment]
Can File::Temp be used to create the tempfiles + tempdirs, or does that module depend on this one? But since they're both in core (since 5.6.1), a circular dependency should still be fine - both will be available via core at some version and either one can be upgraded from cpan with a dependency on the original core version.

**Comment by jkeenan** [comment]
On 6/20/21 7:32 PM, Karen Etheridge wrote:
> Can File::Temp be used to create the tempfiles + tempdirs, or does that 
> module depend on this one? 

File::Temp does not depend on Pod::Html.

**Comment by jkeenan** [comment]
If there are no further comments I will merge this branch into blead within 48 hours, then submit the next pull request in this series.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
I squashed the two commits in this branch locally before merging to blead, testing, then pushing to origin as merge commit ddf86ab3dc887706544973328ece2259cc4f90bd and code commit 8433f82996ead276b305b5c8e4314d9295e08bbe.

Closing p.r.

Thank you very much.
Jim Keenan

**Pull request closed without merging**
