### PR TITLE
cpan/Archive-Tar - Update to version 3.02

### PR DESCRIPTION
**Pull request by jkeenan**
3.02  13/04/2023 (Manfred Stock)
- Test block sizes up to (2**31 - 1) bytes only (fix for 32bit perls)
- Don't match on message from exception in symlink test
- Improve formatting of $Archive::Tar::RESOLVE_SYMLINK documentation

### CODE REVIEW

**Comment by jkeenan** [comment]
Steve,

I see that in the process of preparing for 5.37.1, you synched Archive::Tar's version 3.02 into blead -- but then reverted it.

```
commit 602a11e9c8b4e2b8fdcbc4a94cbe7f5a0c3808b4
Author:     Steve Hay <steve.m.hay@googlemail.com>
AuthorDate: Wed Jul 19 17:32:04 2023
Commit:     Steve Hay <steve.m.hay@googlemail.com>
CommitDate: Wed Jul 19 17:32:04 2023

    Revert "Update Archive::Tar from 2.40 to 3.02"
    
    This reverts commit 591063c99f0757db88773c5d1ee03dbfbf334613.
    
    (cpan/Archive-Tar/t/90_symlink.t failed tests 6, 11, 16 and 20-21)
```
I was surprised at these failures.  So, starting from HEAD (923dde9b8ebe55ba73323ed675156712bc0062c9), I configured and ran:
```
$ perl Porting/sync-with-cpan Archive::Tar
```
... and built and ran all tests successfully.  I saved my work to a branch in my own repo.  If this pull request works for you, feel free to use it.

**Comment by steve-m-hay** [comment]
On Thu, 20 Jul 2023 at 03:38, James E Keenan ***@***.***> wrote:
>
> Steve,
>
> I see that in the process of preparing for 5.37.1, you synched Archive::Tar's version 3.02 into blead -- but then reverted it.
>
> commit 602a11e9c8b4e2b8fdcbc4a94cbe7f5a0c3808b4
> Author:     Steve Hay ***@***.***>
> AuthorDate: Wed Jul 19 17:32:04 2023
> Commit:     Steve Hay ***@***.***>
> CommitDate: Wed Jul 19 17:32:04 2023
>
>     Revert "Update Archive::Tar from 2.40 to 3.02"
>
>     This reverts commit 591063c99f0757db88773c5d1ee03dbfbf334613.
>
>     (cpan/Archive-Tar/t/90_symlink.t failed tests 6, 11, 16 and 20-21)
>
> I was surprised at these failures. So, starting from HEAD (923dde9), I configured and ran:
>
> $ perl Porting/sync-with-cpan Archive::Tar
>
> ... and built and ran all tests successfully. I saved my work to a branch in my own repo. If this pull request works for you, feel free to use it.

Thanks for looking, but I'm afraid your PR looks exactly the same as
what I tried.

I just gave a brief test of Archive-Tar-3.02 in my 5.38.0 installation
and I get the same failure there too:

D:\Dev\Temp\Archive-Tar-3.02>perl -Mblib t\90_symlink.t
ok 1 - use Archive::Tar;
ok 2 - Object created from src\linktest\linktest_with_dir.tar
ok 3 -    Extracting with insecure mode: 0
ok 4 -        No fatal error
ok 5 -        RV as expected
not ok 6 -        Error matches (?^:SECURE EXTRACT MODE)
#   Failed test '       Error matches (?^:SECURE EXTRACT MODE)'
#   at t\90_symlink.t line 54.
#                   'No such file in archive: 'linktest/orig' at
t\90_symlink.t line 51.
# Could not find file 'orig' in memory. at t\90_symlink.t line 51.
# Making symbolic link 'D:\Dev\Temp\Archive-Tar-3.02\t\linktest\link'
to 'orig' failed at t\90_symlink.t line 51.
# Could not extract 'linktest/link' at t\90_symlink.t line 51.
# '
#     doesn't match '(?^:SECURE EXTRACT MODE)'
ok 7 - Object created from src\linktest\linktest_with_dir.tar
ok 8 -    Extracting with insecure mode: 1
ok 9 -        No fatal error
not ok 10 -        RV as expected
#   Failed test '       RV as expected'
#   at t\90_symlink.t line 53.
#          got: ''
#     expected: '1'
not ok 11 -        Error matches (?^:^$)
#   Failed test '       Error matches (?^:^$)'
#   at t\90_symlink.t line 54.
#                   'No such file in archive: 'linktest/orig' at
t\90_symlink.t line 51.
# Could not find file 'orig' in memory. at t\90_symlink.t line 51.
# Making symbolic link 'D:\Dev\Temp\Archive-Tar-3.02\t\linktest\link'
to 'orig' failed at t\90_symlink.t line 51.
# Could not extract 'linktest/link' at t\90_symlink.t line 51.
# '
#     doesn't match '(?^:^$)'
ok 12 - Object created from src\linktest\linktest_missing_dir.tar
ok 13 -    Extracting with insecure mode: 0
ok 14 -        No fatal error
ok 15 -        RV as expected
not ok 16 -        Error matches (?^:SECURE EXTRACT MODE)
#   Failed test '       Error matches (?^:SECURE EXTRACT MODE)'
#   at t\90_symlink.t line 54.
#                   'No such file in archive: 'linktest/orig' at
t\90_symlink.t line 51.
# Could not find file 'orig' in memory. at t\90_symlink.t line 51.
# Making symbolic link 'D:\Dev\Temp\Archive-Tar-3.02\t\linktest\link'
to 'orig' failed at t\90_symlink.t line 51.
# Could not extract 'linktest/link' at t\90_symlink.t line 51.
# '
#     doesn't match '(?^:SECURE EXTRACT MODE)'
ok 17 - Object created from src\linktest\linktest_missing_dir.tar
ok 18 -    Extracting with insecure mode: 1
ok 19 -        No fatal error
ok 20 -        RV as expected
not ok 21 -        Error matches (?^:Could not create directory)
#   Failed test '       Error matches (?^:Could not create directory)'
#   at t\90_symlink.t line 54.
#                   'No such file in archive: 'linktest/orig' at
t\90_symlink.t line 51.
# Could not find file 'orig' in memory. at t\90_symlink.t line 51.
# Making symbolic link 'D:\Dev\Temp\Archive-Tar-3.02\t\linktest\link'
to 'orig' failed at t\90_symlink.t line 51.
# Could not extract 'linktest/link' at t\90_symlink.t line 51.
# '
#     doesn't match '(?^:Could not create directory)'
1..21
# Looks like you failed 5 tests of 21.

I will weave this for after 5.39.1 rather than trying to rush in a
last minute fix for a non-essential (as far as I know) module update.

I strongly suspect it's a Windows specific thing. Anything to do with
symbolic links on Windows makes me twitch, and I saw a couple of
changes in that area in the delta for 5.38.0:

    symlink() on Windows now replaces any / in the target with \,
since Windows does not recognise / in symbolic links. The reverse
translation is not done by readlink(). [GH #20506]

    symlink() where the target was an absolute path to a directory was
incorrectly created as a file symbolic link. [GH #20533]

Cc'ing Chris in case he's unaware of these failures on Windows.
although there are 2 Windows failures reported on CPAN Testers
already: http://matrix.cpantesters.org/?dist=Archive-Tar+3.02

**Comment by jkeenan** [comment]
> I will leave this for after 5.39.1 rather than trying to rush in a last minute fix for a non-essential (as far as I know) module update.

> I strongly suspect it's a Windows specific thing. Anything to do with symbolic links on Windows makes me twitch, and I saw a couple of changes in that area in the delta for 5.38.0: symlink() on Windows now replaces any / in the target with \, since Windows does not recognise / in symbolic links.

That sounds like a reasonable way to proceed.  Thanks for posting the test failures.

**Comment by jkeenan** [comment]
> > I will leave this for after 5.39.1 rather than trying to rush in a last minute fix for a non-essential (as far as I know) module update.
> 
> > I strongly suspect it's a Windows specific thing. Anything to do with symbolic links on Windows makes me twitch, and I saw a couple of changes in that area in the delta for 5.38.0: symlink() on Windows now replaces any / in the target with , since Windows does not recognise / in symbolic links.
> 
> That sounds like a reasonable way to proceed. Thanks for posting the test failures.

I have filed this ticket upstream, which quotes your test failures.

https://rt.cpan.org/Ticket/Display.html?id=149072

I'll mark *this* ticket Send to CPAN and close it.

**Pull request closed without merging**
