### PR TITLE
Preserve split " " behaviour when whitespace modifiers are present

### LINKED ISSUE #18032: use re '/aansx'; breaks split " ", ...
$ perldoc -f split
[...] As another special case, "split" emulates the default behavior of the command line tool awk when the PATTERN is either omitted or a string composed of a single space character
[...] In this case, any leading whitespace in EXPR is removed before splitting occurs, and the PATTERN is instead treated as if it were "/\s+/";
[...] in Perl 5.18.0 and later this special case is triggered by any expression which evaluates to the simple string " ".
[...] If omitted, PATTERN defaults to a single space, " ", triggering the previously described awk emulation.
[...]

```
$ perl -Mstrict -wE'

  my $s= "  foo  bar  ";

  say for split " ", $s;

  { use re qw( /aansx );
    say for split " ", $s;
  }
'
```
```
foo
bar
 
 
f
o
o
 
 
b
a
r 



```
```
---
Site configuration information for perl 5.24.3:

Configured by root at Tue Feb 13 14:35:15 CET 2018.
[...]
Locally applied patches:
    fix for #132063
    fix for #132227
[...]
```

### PR DESCRIPTION
**Pull request by richardleach**
Prior to this commit, the " " pattern would be collapsed into the empty "" pattern if the split was within scope of `use re` whitespace modifiers. Since this split pattern is documented as being a special case, that behaviour is undesirable.

Fixes #18032

### CODE REVIEW

**Review by demerphq — COMMENTED** [review]
Can you please hold off merging this, the change doesn't look right to me. I spent a fair bit of time removing logic very much like this in the past as it is very fragile and we really should have a special metapattern for this as well. I will post a more detailed review in a day or two.

**Comment by tonycoz** [comment]
I think it could use a behaviour test - ie. testing the results of `split " "` where it was broken rather than just testing the regexp compiler dump.

**Comment by richardleach** [comment]
I'll wait for @demerphq's review before making any changes.

**Comment by demerphq** [comment]
@richardleach I pushed https://github.com/Perl/perl5/pull/22069

I think we should just be exempting `split STRING` from `use re '/x'`. IMO it doesn't make sense to allow /x to apply to string arguments to split. We dont't apply the same metacharacter rules in split STRING and split PATTERN, and i feel like /x is about changing how a pattern is parsed, not how a string literal is parsed, an interpretation that means the special case of split " " is preserved. THis has the advantage that something like:

```
my $prefix = "";
my $infix= " ";
my $suffix = "";

my @parts= split $prefix . $Infix . $suffix;
```

triggers the expected awklike emulation under `use re "/x"`;

**Comment by richardleach** [comment]
Ok, I'll close this PR in favour of #22069.

**Pull request closed without merging**
