### PR TITLE
Provide richer explanation of the `unicode_strings` difference.

### PR DESCRIPTION
**Pull request by FGasper**
The output here kinda exemplifies bug #19063.

### CODE REVIEW

**Comment by Grinnz** [comment]
Heavy details are rather out of place for this document. Perhaps the section https://perldoc.perl.org/perlunicode#The-%22Unicode-Bug%22 could be enhanced with this information and the feature could be updated if it doesn't sufficiently point there?

**Comment by FGasper** [comment]
> Heavy details are rather out of place for this document. Perhaps the section https://perldoc.perl.org/perlunicode#The-%22Unicode-Bug%22 could be enhanced with this information and the feature could be updated if it doesn't sufficiently point there?

Ah, there’s more in that linked section than I’d realized.

I think the verbiage I was looking for—but didn’t find a bit earlier—was (something like) “this fixes a bug in Perl”.

I also think:
> … unless it is clear to Perl that Unicode is desired

… leaves something to be desired in terms of accuracy, since appending wide characters isn’t the only thing that upgrades a string.

**Comment by khwilliamson** [comment]
On 8/19/21 8:52 PM, Felipe Gasper wrote:
>     Heavy details are rather out of place for this document. Perhaps the
>     section https://perldoc.perl.org/perlunicode#The-%22Unicode-Bug%22
>     <https://perldoc.perl.org/perlunicode#The-%22Unicode-Bug%22> could
>     be enhanced with this information and the feature could be updated
>     if it doesn't sufficiently point there?
> 
> Ah, there’s more in that linked section than I’d realized.
> 
> I think the verbiage I was looking for—but didn’t find a bit earlier—was 
> “this fixes a bug in Perl”.
> 
> I also think:
> 
>     … unless it is clear to Perl that Unicode is desired
> 
> … leaves something to be desired in terms of accuracy, since appending 
> wide characters isn’t the only thing that upgrades a string.
> 

There's that word again 'upgrade' which I think clouds what is going on.

But "unless it is clear to Perl" doesn't seem wrong to me.  It doesn't 
say that a wide character is the only or even main way to make it clear 
to Perl.  There is a complete list in one of the pods.  Maybe just 
providing a link would be sufficient.

**Comment by khwilliamson** [comment]
@FGasper  @Grinnz 
where are we with this request

**Comment by jkeenan** [comment]
> @FGasper @Grinnz where are we with this request

There has been no further discussion of this p.r. in the past 6 months, so I propose that we close this ticket.

**Comment by jkeenan** [comment]
> > @FGasper @Grinnz where are we with this request
> 
> There has been no further discussion of this p.r. in the past 6 months, so I propose that we close this ticket.

No further discussion in 3-1/2 months; closing.

**Pull request closed without merging**
