### PR TITLE
autodoc.pl: fix typos

### PR DESCRIPTION
**Pull request by testwill**

### CODE REVIEW

**Comment by tonycoz** [comment]
All of the fixes are to `autodoc.pl`, which the commit title could mention, even as simple as `autodoc.pl: fix typos`.

**Review by tonycoz — APPROVED** [review]

**Comment by tonycoz** [comment]
This needs an AUTHORs update now or when merged.

**Comment by tonycoz** [comment]
It wasn't a sign-off, but the failing authors test:
```
#   Failed test 'Is authors_file 'AUTHORS' up to date?'
#   at Porting/updateAUTHORS.pl line 127.
#   File 'AUTHORS' changes:
#     would add: guangwu                        <guoguangwu@magic-shield.com>
# 
# Files need updating! You probably just need to run
# 
#    Porting/updateAUTHORS.pl
# 
# and commit the results.
# Looks like you failed 1 test of 5.
porting/authors.t ......... 
Dubious, test returned 1 (wstat 256, 0x100)
```

**Comment by demerphq** [comment]
Normally we only have one entry in AUTHORS per author. The AUTHORS file should contain your canonical name/email. The .mailmap file may add a mapping for other emails or names. This should be automatically done by the authors script when it is rung with the right args.

**Pull request merged**
