### PR TITLE
fix confusing configure question

### PR DESCRIPTION
**Pull request by cmburn**
Hi!
I feel odd over a pull request this small, but the question
`When you set your locale to something besides C.UTF8, does it do so, or just pretend to?`
is on the confusing side, since it's unclear if it's asking if it actually does, or if it pretends to. I'm aware this won't be committed, however the file itself says to submit pull requests anyway.

### CODE REVIEW

**Comment by jkeenan** [comment]
> Hi! I feel odd over a pull request this small, but the question `When you set your locale to something besides C.UTF8, does it do so, or just pretend to?` is on the confusing side, since it's unclear if it's asking if it actually does, or if it pretends to. I'm aware this won't be committed, however the file itself says to submit pull requests anyway.

We will try to summon `Configure` experts: @Tux @doughera88

**Comment by khwilliamson** [comment]
We'll absolutely make a clarification.   But I'm not sure your proposal is sufficiently helpful.   Here
are the salient points:

> Some` systems fake their locales, so that they pretend to accept a locale
     change, but they either do nothing, making everything the C locale, or
     on some systems there is a a second locale "C-UTF-8" that can be
     switched to.  Configure probes have been added to find such systems. 
 Anything running the current musl library has this characteristic, as does OpenBSD and its kin, as
they view locales as security risks. 

So how to boil that down to a comprehensible question to override the Configure probe?  One possibility, is to add something like

> Accept the default if this question doesn't make much sense to you

With this added information, do you have a different wording?

**Comment by cmburn** [comment]
Hmm... not quite, maybe something like
`Some systems do not actually change locales when told to do so, in particular OpenBSD and systems with a musl libc. Does your system fall in this category?

Accept the default if this question doesn't make much sense to you`

I use OpenBSD systems a good deal (including the system I'm building for), as well as musl systems if I'm running in Docker or something, I might not think of that. It might be good to define those systems! I'm not attached to anything here, so obviously feel free to do whatever works best :)

**Comment by khwilliamson** [comment]
reopening to track the progress of this

**Comment by khwilliamson** [comment]
woops, won't let me reopent

**Comment by doughera88** [comment]
On Mon, Apr 18, 2022 at 06:29:52AM -0700, cmburn wrote:
> Hmm... not quite, maybe something like
> `Some systems do not actually change locales when told to do so, in particular OpenBSD and systems with a musl libc. Does your system fall in this category?

I agree that a generic 'some systems' is often too vague to be helpful,
but more specific lists of systems are impractical to maintain, and we
have no real way to know if they will be useful or correct in a couple
of years.  Possibly including a specific version (e.g. OpenBSD X.Y)
would be helpful -- it would at least give a reader 5 years from now a
sense that the data in the question is old.

-- 
    Andy Dougherty		***@***.***
    Dept. of Physics
    Lafayette College, Easton PA 18042

**Comment by khwilliamson** [comment]
On 4/19/22 08:44, doughera88 wrote:
> On Mon, Apr 18, 2022 at 06:29:52AM -0700, cmburn wrote:
>  > Hmm... not quite, maybe something like
>  > `Some systems do not actually change locales when told to do so, in 
> particular OpenBSD and systems with a musl libc. Does your system fall 
> in this category?
> 
> I agree that a generic 'some systems' is often too vague to be helpful,
> but more specific lists of systems are impractical to maintain, and we
> have no real way to know if they will be useful or correct in a couple
> of years. Possibly including a specific version (e.g. OpenBSD X.Y)
> would be helpful -- it would at least give a reader 5 years from now a
> sense that the data in the question is old.

The text here is wrong.  musl on any box had this problem (and maybe 
still does; I don't know their philosophy on this).

So a version for that would be good.

It's unlikely OpenBSD will ever change, because they think locales are a 
security hole, and a major point of their OS is to be secure.

**Pull request closed without merging**
