### PR TITLE
Remove obsolete FCRYPT ifdefs and associated PL_cryptseen

### PR DESCRIPTION
**Pull request by richardleach**
Per #17623, this commit removes what seems to be obsolete functionality, the use of which would never have been enabled by Configure or platform-specific Makefiles.

This isn't necessarily intended for immediate merging, but it would be great if someone could push to a smoke-me branch...

### CODE REVIEW

**Comment by jkeenan** [comment]
> Per #17623, this commit removes what seems to be obsolete functionality, the use of which would never have been enabled by Configure or platform-specific Makefiles.
> 
> This isn't necessarily intended for immediate merging, but it would be great if someone could push to a smoke-me branch...

See: smoke-me/jkeenan/rleach/ghpr-17624-obsolete branch.

**Review by atoomic — APPROVED** [review]

**Comment by atoomic** [comment]
@tonycoz / @iabyn this looks good to me, any reason to do not merge this PR as it?

**Comment by iabyn** [comment]
On Thu, Mar 12, 2020 at 07:36:38PM -0700, Nicolas R. wrote:
> @tonycoz / @iabyn this looks good to me, any reason to do not merge this PR as it?

It looks good to me, but I think we should merge early in the 5.33.x
cycle.

-- 
"You're so sadly neglected, and often ignored.
A poor second to Belgium, When going abroad."
    -- Monty Python, "Finland"

**Review by tonycoz — APPROVED** [review]
I agree with Dave on delaying it.

**Comment by toddr** [comment]
@richardleach can you rebase please?

**Pull request merged**
