### PR TITLE
toke.c: Return to pre-existing gcb rules

### PR DESCRIPTION
**Pull request by khwilliamson**
As stated in the C comments added in this commit, it has always worked
to say s/mark1/mark2/ where the marks are literal characters.  This is
incorrect because the marks should be considered modifiers of the '/'
delimiters.  (The substitute should be changed to do something like
s/\x{foo/\x{bar}/.)  But that may not happen in time for 5.36.  So this
commit reverts to  the behavior prior to 32b8779 for the ASCII delimiters that
have always worked this way.  Non-ASCII delimiters will continue to work
the new way, which could break code expecting the old.  But use of
non-ASCII delimiters is pretty rare, and the users of that could be
expected to have more knowledge of Unicode and would be less likely to
do something contrary to the Unicode Standard than someone using the
typical ASCII delimiters.

### CODE REVIEW

**Comment by jkeenan** [comment]
Was there a specific commit at which we moved from the "pre-existing rules" to the existing rules?

**Comment by khwilliamson** [comment]
I revised the commit message to include the breaking commit number

**Comment by rjbs** [comment]
As I commented on #19554, I think we should leave blead as is and view this as as correction that does not need a long warning period.

**Comment by demerphq** [comment]
Just to be clear, @rjbs you are saying we should close this PR and not apply?

**Comment by rjbs** [comment]
That's my personal opinion.  I could certainly be outvoted, and possibly swayed.

**Comment by demerphq** [comment]
Its been a long time with no activity on this, so I am going to close the ticket. @khwilliamson if you object please reopen.

**Pull request closed without merging**
