### PR TITLE
Data-Dumper: dump booleans as booleans

### PR DESCRIPTION
**Pull request by haarg**
Use the support for tracking booleans to dump boolean values as !!1 and
!!0.

### CODE REVIEW

**Comment by rwp0** [comment]
Good idea, but  can't we name them more clearly simply as `true` and `false`?

`!!1` and `!!0` isn't nice even for dumping IMHO

**Comment by haarg** [comment]
An advantage of `!!1` and `!!0` is that they are compatible with older perl versions. Newer perls do include `builtin::true` and `builtin::false`. They currently trigger warnings, so if they were used it would probably require delaying making this change until the builtin features are marked stable.

**Comment by leonerd** [comment]
To be honest, even when `builtin::true` et.al. are considered stable, I'd still suggest dumping these as `!!0` and `!!1` by default, for compatibility with older perls, which will still be able to load this output. Maybe by an option users can request a more human-readable output at the expensive of that compat.

**Comment by khwilliamson** [comment]
Is there a reason to delay applying this?

**Review by tonycoz — APPROVED** [review]

**Comment by nicomen** [comment]
Given AFAIK Dumper produces a string, and you want to let it output !!0 and !!1 as false and true for eval-ing a new output in an older perl, would it make sense to output `!!0 # false` and `!!1 # true` when `$Data::Dumper::Indent` > 1 for readability?

**Comment by rwp0** [comment]
> Maybe by an option users can request a more human-readable output at the expensive of that compat.

Please let us have such an option, since there is already many Dumper options this could fit well.

**Pull request merged**
