### PR TITLE
Math-Complex: fix syntax error in example

### PR DESCRIPTION
**Pull request by pjacklam**
This fixes CPAN RT #131037

### CODE REVIEW

**Comment by jkeenan** [comment]
@pjacklam, thank you for your continued efforts in maintaining Math-Complex.

Since this library is "CPAN upstream," we usually expect the maintainer(s) of such libraries to do revisions upstream and make a new CPAN release.  After that point, someone who has a commit bit to the core distribution runs the program `Porting/sync-with-cpan`, which handles merging the updated CPAN library into core.

Hence, I'm a bit surprised to see this p.r., as well as https://github.com/Perl/perl5/pull/20120 and https://github.com/Perl/perl5/pull/20121, as it suggests you want to do revisions to Math-Complex in the core distribution *first*, rather than after a CPAN release (which, among other things, would generate valuable CPANtesters results).

Can you clarify?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> @pjacklam, thank you for your continued efforts in maintaining Math-Complex.
> 
> Since this library is "CPAN upstream," we usually expect the maintainer(s) of such libraries to do revisions upstream and make a new CPAN release. After that point, someone who has a commit bit to the core distribution runs the program `Porting/sync-with-cpan`, which handles merging the updated CPAN library into core.
> 

Hmm, I see that Math-Complex is indeed maintained [upstream on CPAN](https://metacpan.org/pod/Math::Complex), but that its last CPAN release was in 2012, done by someone who is no longer (to the best of my knowledge), and does not have a listed repository.  So how we should proceed in this is unclear.  @rjbs, @book, @leonerd, do you have thoughts about this?

**Comment by pjacklam** [comment]
I have contacted the maintainers of Math-Complex several times though the years asking for co-maint, so I can release new versions of the Math-Complex distribution, but have I never received any reply. I contacted a PAUSE admin to ask for co-maint, but was told to contact the maintainers, which, as I mentioned, I had already done several times without success. So I gave up.

I noticed that the Math-Complex version in core Perl is 1.59_02, newer than the one on CPAN, so I thought I might contribute though pull requests to core Perl. While I know this is not the right way to develop a module that has CPAN as upstream, I don't know how else to do it.

**Comment by jkeenan** [comment]
> I have contacted the maintainers of Math-Complex several times though the years asking for co-maint, so I can release new versions of the Math-Complex distribution, but have I never received any reply. I contacted a PAUSE admin to ask for co-maint, but was told to contact the maintainers, which, as I mentioned, I had already done several times without success. So I gave up.
> 
> I noticed that the Math-Complex version in core Perl is 1.59_02, newer than the one on CPAN, so I thought I might contribute though pull requests to core Perl. While I know this is not the right way to develop a module that has CPAN as upstream, I don't know how else to do it.

Thanks for taking the initiative on this.  I suspect the Perl Steering Council and PAUSE administrators will have to discuss this.  (That, however, should not keep you from continuing to work on these p.r.s.)

**Comment by jkeenan** [comment]
Math-Complex is now maintained in `dist/` rather than `cpan/`.  Handled manually in 17f4c42e6e.  Closing.

**Pull request closed without merging**
