### PR TITLE
study_chunk: avoid transforming ops while enframed

### PR DESCRIPTION
**Pull request by hvds**
gh16947: the outer frame may be in the middle of looking at the part
of the program we would rewrite. Let the outer frame deal with it.

### CODE REVIEW

**Review by khwilliamson — APPROVED** [review]

**Review by xsawyerx — APPROVED** [review]

**Comment by xsawyerx** [comment]
We can merge this.

**Comment by dur-randir** [comment]
This commit introduced the following regression:
```
./miniperl -e 'm$ss++$i for s0'
```
now panic()'s with 
```
regrepeat() called with unrecognized node type 53='EXACTFU_S_EDGE'
```
@xsawyerx @hvds @khwilliamson

**Comment by hvds** [comment]
Confirmed, looks like SUSPEND may use framing recursion inconsistently. Looking into it now.

**Comment by hvds** [comment]
I've reopened #16947 and put further information there.

**Pull request merged**
