### PR TITLE
Replace ssh with https

### PR DESCRIPTION
**Pull request by ghost**
Modify the `git remote add fork` argument in perlhack.pod.

### CODE REVIEW

**Comment by Grinnz** [comment]
Why?

This part of the documentation is describing your personal fork, which you need to set up with write access.

**Comment by ghost** [comment]
[SSH URLs](https://docs.github.com/en/free-pro-team@latest/github/using-git/which-remote-url-should-i-use#cloning-with-ssh-urls) are not mentioned in perlhack.pod.

https://github.com/Perl/perl5/commit/617d9ec40b6f4f34796deb5007320a135e402779#diff-fbf8c7e20f85f9aacf05c038ed8c687d
Update perlgit and perlhack to reference GitHub pull request workflow
khwilliamson committed Oct 24, 2019

perlhack.pod

```diff
-  % git format-patch -1
-  % ./perl -Ilib utils/perlbug -p 0001-*.patch
+  % git remote add fork git@github.com:MyUser/perl5.git
```

A git protocol clone was previously replaced with an https clone.

https://github.com/Perl/perl5/commit/47ef154c59e75e9351d27b3bd06d6ac57494193c#diff-fbf8c7e20f85f9aacf05c038ed8c687d
Update documentation, comments, metadata to reference GitHub as canon… 
toddr committed Oct 20, 2019

perlhack.pod

```diff
-  % git clone git://perl5.git.perl.org/perl.git perl
+  % git clone https://github.com/Perl/perl5.git perl
```

**Comment by Grinnz** [comment]
That does not answer the question.

**Comment by Leont** [comment]
Different people have different preferences. I can see the argument for mentioning both ways, but simply changing it to your preference seems like an unfortunate move.

**Comment by apparluk** [comment]
Create a GitHub fork of the perl5 repository and add it as a remote, if you haven't already, as described in the GitHub documentation at https://help.github.com/en/articles/working-with-forks.

```
% git remote add fork https://github.com/MyUser/perl5.git
```

If you'd rather use an SSH URL for your `git push` see ["Connecting to GitHub with SSH"](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh).

```
% git remote add fork git@github.com:MyUser/perl5.git
```
Then, push your new branch to your fork.

**Comment by Grinnz** [comment]
It is not a preference. The remote added for your personal fork must have write access.

**Comment by xenu** [comment]
You can have write access via https, github supports that.

**Comment by Grinnz** [comment]
Only via explicit credentials, but I suppose if you want to explain both that option and ssh keys.

**Comment by Grinnz** [comment]
If you want to mention both options, it would be best to link to https://docs.github.com/en/free-pro-team@latest/github/using-git/which-remote-url-should-i-use and indicate that authentication with either SSH keys or personal access token is required to push to your private fork.

**Comment by ghost** [comment]
Create a GitHub fork of the perl5 repository and add it as a remote, if you haven't already, as described in the GitHub documentation at https://help.github.com/en/articles/working-with-forks.

```
% git remote add fork git@github.com:MyUser/perl5.git
```

For more information, see ["Connecting to GitHub with SSH"](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh). 


If you'd rather use an HTTPS URL for your `git push` see ["Cloning with HTTPS URLs"](https://docs.github.com/en/free-pro-team@latest/github/using-git/which-remote-url-should-i-use#cloning-with-https-urls).

```
% git remote add fork https://github.com/MyUser/perl5.git
```
Then, push your new branch to your fork.

**Comment by apparluk** [comment]
Create a GitHub [fork](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/working-with-forks) of the perl5 repository and add it as a remote via [SSH](https://docs.github.com/en/free-pro-team@latest/github/using-git/which-remote-url-should-i-use#cloning-with-ssh-urls).

```
% git remote add fork git@github.com:MyUser/perl5.git
```

If you'd rather use an HTTPS URL for your `git push` see ["Cloning with HTTPS URLs"](https://docs.github.com/en/free-pro-team@latest/github/using-git/which-remote-url-should-i-use#cloning-with-https-urls).

```
% git remote add fork https://github.com/MyUser/perl5.git
```
Then, push your new branch to your fork.

<hr>

Finally, create a GitHub [Pull Request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) from your branch to blead.

**Comment by apparluk** [comment]
There could be some grammatical and typographical improvements.

I think also Gisle Aas no longer is the maintainer of _illguts_.

Seems like this nonsense is finally obsolete.

=head2 "The Road goes ever on and on, down from the door where it began."

to

=head1 AUTHOR

**Comment by apparluk** [comment]
> noting #18205 merge is pending I haven't added my name to this branch.

Implementing https://github.com/Perl/perl5/pull/18229#issuecomment-706638529 fails on porting/authors.t.

**Comment by Grinnz** [comment]
The current addition is reasonable.

**Comment by apparluk** [comment]
Absent more reviews, and noting the authors.t fail, the merge could be made and we could close.

**Review by atoomic — APPROVED** [review]
LGTM, at least this leaves the choice to the user to use ssh or https :-)

**Comment by ghost** [comment]
Opening this ticket was not a matter of personal preferences.

When creating a repository via GitHub's menu subsequent instructions use HTTPS URLs.

**Pull request merged**
