### PR TITLE
Add an extra smoke run

### PR DESCRIPTION
**Pull request by Tux**
We also need some variation that runs under UTF-8 environment involving
$PERL_UNICODE and $LC_ALL. Preferable with and without -DDEBUGGING

### CODE REVIEW

**Comment by toddr** [comment]
@Tux This commit is now in conflict. We reduced the number of permutations to 5 since that's how many will run simultaneously. Do you have  a suggestion of which of the existing ones we should replace?

**Comment by dur-randir** [comment]
WIll old smokers still be running on the new github repo? If so, then we can keep travis/etc at a bare minimum, just to detect obvious breakage, and get full report on p5p@.

**Comment by toddr** [comment]
@dur-randir This is probably a question for @tonycoz which we should discuss on the mailing list.

**Comment by tonycoz** [comment]
> 
> 
> @dur-randir This is probably a question for @tonycoz which we should discuss on the mailing list.

I don't run smokes (I used to), I just collate the results on perl.develop-help.com. Also this is updating travis, which beyond working on the original .travis.yml isn't anything I'm specifically responsible for (ie. why me?)

**Comment by Tux** [comment]
I changed my smokers to the new url's
I think that we should smoke at travis, that what brings most feedback, even if those are illogical combinations
1. -Uusethreads -DDEBUGGING
2. -Dusethreads -Duse64bitint -Duselongdouble
Those two under blank and PERL_UNICODE="" + LANG="en_US.UTF8"

**Comment by atoomic** [comment]
@Tux this branch is currently conflicting with blead, and should be rebased.
I'm not against adding new flavors to Travis, but note that they will slow down the smoker time.

Maybe we would like to add a note also in the travis file itself your comment `that what brings most feedback, even if those are illogical combinations`

**Comment by tonycoz** [comment]
I've created a new PR #17342 which I believe satisfies the needs this PR was trying to address.

- It doesn't add an extra job
- it tests a larger variety of useful Configure options that have tended to cause problems in the past

**Comment by tonycoz** [comment]
> 
> 
> I've created a new PR #17342 which I believe satisfies the needs this PR was trying to address.
> 
>     * It doesn't add an extra job
> 
>     * it tests a larger variety of useful Configure options that have tended to cause problems in the past

which I've merged, this PR hasn't been updated in a month and I believe the issues it tries to fix are now covered, so I'm closing it.

**Pull request closed without merging**
