### PR TITLE
Configure: Fix compilation error on some systems

### PR DESCRIPTION
**Pull request by khwilliamson**
See https://github.com/Perl/perl5/issues/22793

This typo in a printf format causes some C compilations to fail; others to just warn.  However stderr is redirected to /dev/null, so we weren't aware of this issue.

When it fails, other issues cause perl to not be usable on the system.

This commit should be added to maint 5.40 and 5.38

* This set of changes requires a perldelta entry, to be furnished

### CODE REVIEW

**Comment by jkeenan** [comment]
> See #22793
> 
> This typo in a printf format causes some C compilations to fail; others to just warn. However stderr is redirected to /dev/null, so we weren't aware of this issue.

Do you recall which platforms this was a problem on?

**Comment by tonycoz** [comment]
> Do you recall which platforms this was a problem on?

Any system that has the compiler enable `-Werror=format` by default, though I don't know any that do that.   Ubuntu was setting `-Werror=format-security` but that's different.

In any case it fixes a bug (one that produces undefined behaviour technically).

**Review by tonycoz — APPROVED** [review]

**Comment by jkeenan** [comment]
> 
> This commit should be added to maint 5.40 and 5.38
> 

If so, then before doing those 2 maintenance releases, we should line up some machines on which we can test this patch.  (Passes against blead for me.)

**Comment by khwilliamson** [comment]
The OP has tested on their machine running 5.38; and I have tested it on my machine running 5.38

**Pull request merged**
